### ISSUE TITLE
Hedera Node - Problem with starting a local single-node network

### ISSUE THREAD

**Issue by mwb-al** [hashgraph/hedera-services#10075]
### Description

I'm trying to run a local hedera node as per the documentation https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/docs/intellij-quickstart.md but I get an error message when starting the application:

```
Task :app:ServicesMain.main() FAILED
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module io.netty.common does not read a module that exports reactor.blockhound.integration

Execution failed for task ':app:ServicesMain.main()'.
Process 'command 'C:\Program Files\Java\jdk-17\bin\java.exe'' finished with non-zero exit value 1
```

### Steps to reproduce

1. git clone https://github.com/hashgraph/hedera-services.git
2. set OpenJDK17 for this project
3. run the Gradle assemble
4. set Run Configuration inside Intellij
![image](https://github.com/hashgraph/hedera-services/assets/151550037/88000b02-0ff8-4ab1-ad5e-590d55cd9548)
5. Run application

### Hedera network

other

### Version

v0.45.0-SNAPSHOT

### Operating system

Windows

**Comment by MichalQW** [comment]
Result of Gradle: hedera-services/Tasks/application/run

![image](https://github.com/hashgraph/hedera-services/assets/91373503/d562c5f4-baaa-490d-a297-ea9f87479673)

**Comment by mwblocky-al** [comment]
Result of Gradle: hedera-services/Tasks/application/run

![image](https://github.com/hashgraph/hedera-services/assets/151550037/8e050904-0ee9-4a77-b39c-daab7746d3f2)

**Comment by mmalik-al** [comment]
+1
The same issue on develop branch.


**Operating system**
Linux 6.3.7 KDE Plasma

------------------------
Quickstart guide linked in the README works on `9a5783c` commit.

**Comment by jamesnguyentech** [comment]
I'm also experiencing a similar issue on the develop branch. It seems that the Readme file is too outdated.

Operating system
MacOS Sonoma 14.1

**Comment by pathornteng** [comment]
Hi team, any update on this issue? Can we provide a way to run the node? I also have the same issue.

**Comment by poulok** [comment]
Closing as it is outdated. If this is still an issue, please re-open or create a new ticket and we will address it.
