### ISSUE TITLE
Fix broken ISS tests

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#10115]
Some ISS tests are broken because of the removal of the state dump feature. Discuss potential solutions for this.

**Comment by edward-swirldslabs** [comment]
Are these broken tests related to this issue?  

http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20231128-062346-GCP-Daily-ISS-4N/ISS-emergency-recovery-diff-hash-1k-10m/
http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20231128-062346-GCP-Daily-ISS-4N/ISS-emergency-recovery-reconnect-1k-10m/
http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20231128-062346-GCP-Daily-ISS-4N/ISS-emergency-recovery-1k-10m/

**Comment by lpetrovic05** [comment]
> Are these broken tests related to this issue?
> 
> http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20231128-062346-GCP-Daily-ISS-4N/ISS-emergency-recovery-diff-hash-1k-10m/ http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20231128-062346-GCP-Daily-ISS-4N/ISS-emergency-recovery-reconnect-1k-10m/ http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20231128-062346-GCP-Daily-ISS-4N/ISS-emergency-recovery-1k-10m/

yes
