### ISSUE TITLE
Fix and enable remaining contract mod-service `HapiSpec`s

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#10160]
### Problem

We have the following contract `HapiSpec`s not annotated with `@HapiTest`:
 - [x] [`ERCPrecompileSuite.someErc20ApproveAllowanceScenariosPass()`](https://github.com/hashgraph/hedera-services/pull/9995)
 - [x] #10465
 - [x] #10466
 - [x] #10467
 - [x] #10188
 - [x] [`ERCPrecompileSuite.someErc721SetApprovedForAllScenariosPass()`](https://github.com/hashgraph/hedera-services/pull/9995)
 - [x] [`ERCPrecompileSuite.someErc721NegativeTransferFromScenariosPass()`](https://github.com/hashgraph/hedera-services/pull/9995)
 - [x] #10468
 - [x] #10175
 - [x] #10177
 - [x] [`TokenAndTypeCheckSuite.checkTokenAndTypeNegativeCases()`](https://github.com/hashgraph/hedera-services/issues/10139)
 - [x] #10424
 - [x] #10431
 - [x] [`SigningReqsSuite.autoRenewAccountCanUseLegacySigActivationIfConfigured()`](https://github.com/hashgraph/hedera-services/issues/10162)
 - [x] [`ContractKeysStillWorkAsExpectedSuite.contractKeysStillHaveSpecificityNoMatterTopLevelSignatures()`](https://github.com/hashgraph/hedera-services/pull/10039/files)
 - [x] `ContractKeysStillWorkAsExpectedSuite.canStillTransferByVirtueOfContractIdInEOAThreshold()`
 - [x] [`ContractKeysStillWorkAsExpectedSuite.approvalFallbacksRequiredWithoutTopLevelSigAccess()`](https://github.com/hashgraph/hedera-services/pull/10039/files)
 - [x] [PrngPrecompileSuite.nonSupportedAbiCallGracefullyFails()](https://github.com/hashgraph/hedera-services/pull/10074)
 - [x] [PrngPrecompileSuite.prngPrecompileHappyPathWorks()](https://github.com/hashgraph/hedera-services/pull/10074)
 - [x] [PrngPrecompileSuite.multipleCallsHaveIndependentResults()](https://github.com/hashgraph/hedera-services/pull/10074)
 - [x] #10330
 - [x] #10331
 - [x] #10333
 - [x] #10220
 - [x] #10238
 - [x] #10520
 - [x] #10245
 - [x] #10246
 - [x] #10247
 - [x] #10248
 - [x] #10244
 - [x] #10242
 - [x] #10239
 - [x] #10243
 - [x] #10309
 - [x] #10313
 - [x] #10469
 - [x] #10470
 - [x] #10471
 - [x] #10473
 - [x] #10474
 - [x] #10475
 - [x] #10476
 - [x] #10477
 - [x] #10478
 - [x] #10350
 - [x] #10351
 - [x] #10352
     - https://github.com/hashgraph/hedera-services/pull/10327 check if EVM_ADDRESS is 20 bytes
 - [x]  [`Create2OperationSuite.canMergeCreate2MultipleCreatesWithHollowAccount()`](https://github.com/hashgraph/hedera-services/pull/10141)
 - [x] #10374
 -  [x] #10371

### Solution

Fix and enable them.

**Comment by MiroslavGatsanoga** [comment]
Closing as all of the tasks listed are done.
