### ISSUE TITLE
Rename test classes to follow one consistent scheme

### ISSUE THREAD

**Issue by mmalik-al** [hashgraph/hedera-services#10217]
### Problem

Currently we have many test classes that are named either `*Test.java` or `*Tests.java`. This introduces unnecessary inconsistencies across entire project. 

### Solution

* Rename all test classes to the same suffix. `*Test.java` OR `*Tests.java`

**Comment by poulok** [comment]
Closing as this is not important to fix and will cause lots of conflicts with priority PRs.
