### ISSUE TITLE
Create a `disconnect` HapiSpecOp that will disconnect a given node from communicating with the others

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#10224]
- [ ] Create a `disconnect` HapiSpecOp that will disconnect a given node by blocking its tcp ports from communicating with the others. 
- [ ] Submit some transactions while the node is blocked. 
- [ ] Then unblock its ports after sometime, and the node should reconnect.

**Comment by Neeharika-Sompalli** [comment]
Not successful to disable ports on a Mac os and test the disconnect locally.

**Comment by Neeharika-Sompalli** [comment]
Worked with @nathanklick , to enable blocking ports on Mac or in CI runs. Tried by enabling vlan and using several rules. But we were not successful to enable disconnect locally.

**Comment by nathanklick** [comment]
Linux and BSD (MacOS) treat all TCP/IP connections which have a source and destination of the local machine as loopback connections which pass across the `lo` or `lo0` interface. Even if the `lo`/`lo0` adapter has multiple IP address aliases or Linux `dummy` driver based virtual NICs are used, the kernel treats outbound client connections as originating from one of the "loopback" aliases randomly. This inhibits our ability to bastion or block a node.

**Comment by netopyr** [comment]
Will not implement
