### ISSUE TITLE
Use `dev` config with `modrun`

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#10227]
### Problem

It is difficult to understand what config is being used when using `modrun`, and in fact, on a fresh repo if you run `modrun` it fails to start due to some configuration value requiring `/opt/hgcaa` existing. This has been hit by several new contributors. In addition, we pollute the workspace with files as part of the local run (such as `hedera-node/output` and `hedera-node/data/saved`). These are ugly and require extensive ignores in .gitignore. It would be better to build a directory under `hedera-node/hedera-app/build` that will copy the required files into it and then execute from there, rather than having `hedera-node` be the current working directory. This way a simple clean is enough to clean up all this information.

### Solution

The build file that contains `modrun` is `hedera-node/hedera-app/build.gradle.kts`. This build file should be updated so that it creates a directory, let's say `hedera-node/hedera-app/build/node`. In this directory it copies everything from `hedera-node/data`, except`hedera-node/data/config`, which should be removed. Instead, the `hedera-node/configuration/dev` will be copied as `hedera-node/hedera-app/build/node/data/config`. This way the `dev` directory is used as config. The build script should be updated so that the libs and the built hedera app jar are copied into `hedera-node/hedera-app/build/node` in the right places _instead of_ being copied into the `hedera-node/data` places that it does today. And the `modrun` command should be modified to use `build/node` as the working directory instead of `..`.

**Comment by jamesnguyentech** [comment]
I'll update it. @rbair23
