### ISSUE TITLE
Support optional auto-renew accounts for all expiring entity types

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#103]
Users can create a contract, token, or topic with an "auto-renew account" to fund the entity's renewal fees.

In the modularized codebase we should thus,
 - [ ] Support auto-renew accounts for accounts.
 - [ ] Support auto-renew accounts for files.

**Comment by anighanta** [comment]
AutoRenew feature is implemented. This feature is not relevant anymore.

**Comment by tinker-michaelj** [comment]
Duplicate of https://github.com/hashgraph/hedera-services/issues/1194
