### ISSUE TITLE
Client log is flooded with status resolution error

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#1032]
https://app.circleci.com/pipelines/github/hashgraph/hedera-services/10280/workflows/a98db548-b8b5-48ab-a2cc-e4bb0d4d2d4b/jobs/53538

Some client log is flooded with the following error:
`2021-02-01 07:18:39.492 ERROR  427  HapiTxnOp -  [ accountID 2 validStart(1612163859, 119) ], status resolution failed with unrecognized exception, not getting txn response back`

This results in a very large slack message and the slack client fails to send the report of the test run

The following code floods the client log
https://github.com/hashgraph/hedera-services/blob/2e8bbe6f0b2f328ffd91cb1ae9ab644aeb91e41d/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java#L426-L432
because `statusResponse()` is called in a while loop trying to resolve the status of the submitted transaction
https://github.com/hashgraph/hedera-services/blob/2e8bbe6f0b2f328ffd91cb1ae9ab644aeb91e41d/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java#L383-L397

**Comment by tinker-michaelj** [comment]
Yes I deleted this in `schedule-develop` (where I've been spending most my time recently haha); it should simply be deleted in `master` as well imo.

**Comment by tinker-michaelj** [comment]
I'd also suggest we rethink a recent change in `HapiSpecOperation` that defaults to suppressing the stack trace of a failed operation [here](https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java#L197)...

I assume the reason has to do with keeping JRS Validators happy, but in practice this can make it **very** hard to tell what has gone wrong in a test!

**Comment by qnswirlds** [comment]
> I'd also suggest we rethink a recent change in `HapiSpecOperation` that defaults to suppressing the stack trace of a failed operation [here](https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java#L197)...
> 
> I assume the reason has to do with keeping JRS Validators happy, but in practice this can make it **very** hard to tell what has gone wrong in a test!

I agree, @tinker-michaelj. I don't like the idea of changing the clients to make the validators happy either. Sometimes we can do that. But most of the time, we should change the expectation in the validators.

**Comment by ljianghedera** [comment]
Yeah, the primary goal of the changes is to make the JRS validator happy. Now I would think we still need to cater the requirement of the JRS as it's a major user of the test-client. But meanwhile, I think we can also keep original stack trace in DEBUG level log simultaneously. So we can always turn on debug to get info we want.

**Comment by JeffreyDallas** [comment]
Maybe use a specific MARKER for such scenario, and JRS and Production version use a different log4j2.xml to turn it ON or OFF
