### ISSUE TITLE
HashListByteBuffer releases DirectByteBuffers lazily, adds memory pressure

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#10342]
### Problem

`HashListByteBuffer.close()` clears its collection of `ByteBuffers` (`data`). When those are `DirectByteBuffers` (`offHeap == true`), the native memory is not immediately released and will have to wait until the Java objects are garbage collected.
It would be good to apply the same technique here as in `LongListOffHeap`, i.e. call `UNSAFE.invokeCleaner(buffer)`.

### Solution

Call `UNSAFE.invokeCleaner(buffer)`.

**Comment by jamesnguyentech** [comment]
I'll update it.
