### ISSUE TITLE
Single shot Allowance removal [escape valve related to allserial NFT allowance risk]

### ISSUE THREAD

**Issue by Burstall** [hashgraph/hedera-services#10357]
### Problem

When using AccountAllowanceApproveTransaction().approveTokenNftAllowanceAllSerials(), you have no visibility on what approvals are in place. This is a problem as there appears to be a limit, and when you come to delete these approvals, you must have prior knowledge of the token/spender held off-chain.

The risk is a user wallet has too many approvals in place, and they do not know exactly which spenders have an allowance, rendering them unable to delete allowances [AccountAllowanceDeleteTransaction().deleteTokenNftAllowanceAllSerials() requires token/owner/spender]. In this case, the user's wallet is no longer usable for allowance-based work.

[I ran into this in testing, the user experience on mainnet would be horrible if it occurred]

### Solution

Create an SDK method to allow the revoking of all 'NftAllowanceAllSerials' in a single method. Not ideal as it could have impacts where other allowances were assumed to be in place but the nuclear option is better than rendering the account stuck.

The added benefit comes that if a user is worried their account could have signed an allowance to a bad actor then can revoke everything in a single shot for maximum safety. 

### Alternatives

Fixing mirror nodes to provide visibility on the "approveAll" state [ https://github.com/hashgraph/hedera-mirror-node/issues/7343 ]. Ideally, we would get both.

**Comment by Neeharika-Sompalli** [comment]
Mirror node shows the allowance details example API : https://mainnet.mirrornode.hedera.com/api/v1/accounts/<accountId>/allowances/tokens
Similarly allowances/crypto , allowances/nfts (for nfts, only approved for all allowances are displayed). NFTs data will be improved in 0.106 release of mirror node.
