### ISSUE TITLE
Add independent throttles for different types of queries - Answer only, answer state proof etc.

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#1036]
**Summary**

- [ ] Add independent throttles for different types of queries

- ANSWER_ONLY
- ANSWER_STATE_PROOF
- COST_ANSWER
- COST_ANSWER_STATE_PROOF

- [ ] Modify tools to use the added throttles

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
