### ISSUE TITLE
Define best practice regarding position of `@NonNull` annotations

### ISSUE THREAD

**Issue by mxtartaglia-sl** [hashgraph/hedera-services#10380]
Review comment on PR:

_Originally posted by @hendrikebbers in https://github.com/hashgraph/hedera-services/pull/10332#discussion_r1420057791_

**Comment by mxtartaglia-sl** [comment]
Google has it defined [as](https://google.github.io/styleguide/javaguide.html#s4.8.5-annotations):

4.8.5.1 Type-use annotations
Type-use annotations appear immediately before the annotated type. An annotation is a type-use annotation if it is meta-annotated with 

```
@Target(ElementType.TYPE_USE). Example:

final @Nullable String name;

public @Nullable Person getPersonByName(String name);
```


According to our codebase, Swirlds Labs ad-hoc convention is to use `@Annotation final Type name;` there are 10400+ occurrences of that convention.
![image](https://github.com/hashgraph/hedera-services/assets/152629744/6c779314-feb4-4ff3-a558-418ff1ab04ea)

While the opposite `final @Annotation Type name` is only present on less than 120 occurrences in our code base:
![image](https://github.com/hashgraph/hedera-services/assets/152629744/6d5513fb-fe49-43d8-9b22-714c33b599a9)

Consistency within a codebase is often more important than the specific style chosen. Since the project has a semi-established convention, it might be a good idea to formalize it and adhere to it.

**Comment by mxtartaglia-sl** [comment]
Besides defining we should also find a way to enforce if possible automatically.
code style page: https://www.notion.so/swirldslabs/007-Java-Code-Style-a0130a7059b044f68447b9ca3a5242b3#c4ff403bfdb7419f87d32c09d27cf667

**Comment by jsync-swirlds** [comment]
For what it's worth, the modular services code has been (informally at least) preferring `final @NonNull Type variable` style (that is, final always comes before the annotation, if both are present).  I don't think I've seen a PR with the order reversed in some months.

**Comment by mxtartaglia-sl** [comment]
After a conversation with @rbair23 the following was defined:
>  Both formats seem acceptable. If we want to pick one, we'll choose the most prevalent pattern and update Spotless accordingly so it will rearrange the text automatically to be the correct format.

There is no strong motivation to force only one pattern, so closing the ticket and leaving it for future reference.
