### ISSUE TITLE
No need to have state snapshots from every consensus nodes in the cloud

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/hedera-services#10398]
Every node saves a state snapshot to its local disk every 15 mins. Then all these snapshots are uploaded to AWS / GCP buckets, where they are stored forever. Note that despite all snapshots for the same round aren't 100% byte to byte identical, they are all logically identical, and any of them can be used to restore a node from, if needed.

The idea is to upload just a single snapshot for a round to the cloud, or upload them all but then delete redundant. For example, it can be a part of the validation tool CI pipeline:

1. The validation tool identifies the latest round available to validate
2. CI pipeline spawns N jobs (where N is the number of nodes in the network, e.g. 29 in mainnet)
3. Each job downloads a state for the corresponding consensus node for the identified round and verifies it

This pipeline can be enhanced further:

4. Once all states are validated, another job is created. This job will find the smallest (in size) state among all nodes and copy it to a dedicated folder. Then all uploaded states for the round are deleted from the bucket, leaving that dedicated folder only

Today mainnet states are uploaded to the following bucket / folder:

gs://mainnet-1m/<node name>/<round>/

The proposal is to have a slightly different path, which will not be specific to any node:

gs://mainnet-1m/states/<round>/

In the future, once #10353 is implemented, step 4 will be slightly different. There will be no need to find the smallest state, but a state for an arbitrary node can be downloaded, then compacted, then uploaded back to the cloud.

**Comment by poulok** [comment]
We also need to collect a super majority of signatures on the state before deleting copies
