### ISSUE TITLE
Create enum converter for simple enum types

### ISSUE THREAD

**Issue by mxtartaglia-sl** [hashgraph/hedera-services#10535]
We need an easy way to convert enums by name and we do not want to create a specific converter for each enum that can just be converted "by-name".

**History**:
We can use the ConverterService class to convert a value or ask for the converter  
This [recent change](https://github.com/hashgraph/hedera-services/pull/10411), enabled us to convert a value to an enum based on its name. But introduce an inconsistency between functionalities we would like to address.

**Related**:
[Original task] (https://github.com/hashgraph/hedera-services/pull/10411#discussion_r1425847293_)
[Abstract Converter] (https://github.com/hashgraph/hedera-services/pull/10321)

_Originally posted by @mxtartaglia-sl in https://github.com/hashgraph/hedera-services/pull/10411#discussion_r1425847293_

**Comment by hendrikebbers** [comment]
Please add a short documentation about enum usage to https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/docs/base/configuration/configuration.md#supported-datatypes
