### ISSUE TITLE
Fix INSUFFICIENT_PAYER_BALANCE error in nightly tests

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1054]
**Summary of the defect**
Most of the nightly regression tests are failing with `INSUFFICIENT_PAYER_BALANCE` error on Feb 3rd. 
Failing Crypto-Restart test link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1612420086307000

Possible Resolution:
This might be solved by using `long initialBalance = 5_000_000_000_000L;` in `CryptoCreateForSuiteRunner` and use different initialBalance for performance tests in LoadTest `public static OptionalLong initialBalance = OptionalLong.of(900_000_000_000L);`

**Comment by qnswirlds** [comment]
@Neeharika-Sompalli, I've been looking at the failed tests. Yeah, I was thinking to reuse the public static var when commenting on your PR yesterday. But I forgot that the account created by `CryptoCreateForSuiteRunner` will be the payer when creating sender and receiver accounts for loadtest. I would propose that we still share the public static var, make it (1 mil hbars) but give the account created by `CryptoCreateForSuiteRunner` 5 times (or 10 times) that balance.

**Comment by Neeharika-Sompalli** [comment]
I agree with you @qnswirlds. Thank you!
