### ISSUE TITLE
`not all nodes saved for round` validator error

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#10548]
Failing test: `VMerkle-Basic-2.5k-110m`

```
---- VirtualMerkleLeafValidator FAILED validation ----
<<ERROR>>
not all nodes saved for round 2496
```

- [data directory](http://35.247.76.217:8095/swirlds-automation/release/0.45/4N/VMerkleLong/20231215-094519-GCP-Daily-VMerkleLong-4N/VMerkle-Basic-2.5k-110m/summary.txt)

It appears that the validator is asserting that all nodes have the same states saved. I don't know what that should be a test assertion, there wasn't anything inherently wrong with the run. I think the assertion should simply be removed.

**Comment by poulok** [comment]
@alittley has this test failed since this ticket was written?

**Comment by alittley** [comment]
@poulok I've not seen any additional failures. Closing, to be reopened if this is observed again
