### ISSUE TITLE
Move NanoClock to Base

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#10593]
The NanoCl`o`ck class should be part of the time package of swirlds-base.

**Comment by hendrikebbers** [comment]
Maybe that can be done in combination with [#7163](https://github.com/hashgraph/hedera-services/issues/7163) since that needs a clock.

**Comment by mxtartaglia-sl** [comment]
PR:https://github.com/hashgraph/hedera-services/pull/10641
