### ISSUE TITLE
Fix failing Recovery tests

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1069]
**Summary of the defect**
Fix the following failing Recovery tests in nightly regression
- [x] Crypto-Recovery-300-7m      
- [x] Crypto-Recovery-EvSave15sTrunc-300-7m 
- [x] File-Recovery-EvSave15sTrunc-2-7m 

Link to Failing test : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1612776734035700

**Comment by JeffreyDallas** [comment]
There is merged PR should have fixed those issues.

https://github.com/swirlds/swirlds-platform/pull/2913

**Comment by Neeharika-Sompalli** [comment]
@JeffreyDallas These tests are still failing on nightly regression in services https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1612863307036500

**Comment by JeffreyDallas** [comment]
> @JeffreyDallas These tests are still failing on nightly regression in services https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1612863307036500

The change is in platform-core, so have to wait until new SDK drop to fix the issue

**Comment by Neeharika-Sompalli** [comment]
Passed tests:
 Crypto-Recovery-EvSave15sTrunc-300-7m: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612898286260100
Crypto-Recovery-300-7m: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612894851258000
