### ISSUE TITLE
Fix HapiClientValidator for the failing Random/Hotspot Performance tests

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1070]
**Summary of the defect**
HapiClientValidator fails for various errors while running Random Performance tests. Fix the validator to accommodate the errors.

Failing test link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1612774191035600
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1612778939035800

**Comment by ljianghedera** [comment]
Just a heads up. I am looking into this issue now. If someone is already working on this issue, please let us know so we don't duplicate our effort on the same issue.
