### ISSUE TITLE
Design: HIP-755 (Schedule Service System Contract)

### ISSUE THREAD

**Issue by bibitibooo1** [hashgraph/hedera-services#10730]
Create a design doc that lays out how [HIP 755](https://hips.hedera.com/hip/hip-755) can be implemented.
Calling out new components, interfaces and existing structures to add on to.

Open questions
- [ ] Does HAPI logic fully support dispatch logic to HSS
- [ ] Are there any unique authorization steps that needs to be added for SC
- [ ] Is a unique schema or representation of the transaction needed for this HIP e.g. solidity vs protobuf structs

Goal is to to take no longer than the A sprint of the milestone to create doc and get agreement.
Once a draft PR is created note this in services discussions for community

**Comment by bibitibooo1** [comment]
To design in Q1.

**Comment by Nana-EC** [comment]
Follow up
- create EPIC where this task is one item
- Update description
