### ISSUE TITLE
Proposal: Zombie event countermeasures

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#10748]
# Driving Goal

We want to change the definition of what it means for an event to be ancient. Currently, and event is considered ancient based on its generation. We instead want to start using birth rounds to determine what is ancient and what isn't ancient. This is a prerequisite change for dynamic rosters.

# Problem

At the migration boundary between a generation-defined ancient threshold and a round-defined ancient threshold, it is possible that some events that were once considered ancient will no longer be considered ancient. I refer to these events as "zombie events", since they were once dead and rise back up to terrorize the living.

Allowing ancient events to become non-ancient can cause a host of problems, up to and including the network halting or an ISS. We absolutely can not tolerate even a single zombie event.

# Proposed Solution

Let the following variables have the definitions below:

- `lastGenerationVersion`: the last software version that uses a generation-defined ancient threshold
- `firstRoundNonAncient`: the round number of the last state generated by `lastGenerationVersion`
- `lastMinimumGenerationNonAncient`: the minimum generation non-ancient for the last state generated by `lastGenerationVersion`

Add the following files to each `GossipEvent` class. These fields will not be serialized or included in the hash of each event. These fields will best for each event as it is inserted into the intake pipeline, but before the intake pipeline makes the decision if the event is ancient or not.

```
private SoftwareVersion lastGenerationVersion;
private long lastMinimumGenerationNonAncient;
private long firstRoundNonAncient;

// ...

public void setAncientThresholdMigrationData(
    SoftwareVersion lastGenerationVersion, 
    SoftwareVersion firstRoundVersion,
    long lastMinimumGenerationNonAncient,
    long firstRoundNonAncient) {

        this.lastGenerationVersion = lastGenerationVersion;
        // etc.
}
```

When an event is asked for its birth round, it will use the following decision tree:

- if the event has a software version that exceeds `lastGenerationVersion`, it returns the true birth round
- if the event has a software version that does not exceed `lastGenerationVersion`, then
    - if the generation of the event is less than `lastMinimumGenerationNonAncient`, it returns `-1`
    - if the generation of the event is greater than or equal to `lastMinimumGenerationNonAncient`, it returns `firstRoundNonAncient`

~After migration, when deciding which round number should be used as the current minimum round non-ancient, then use the following equation: `long minimumRoundNonAncient = max(firstRoundNonAncient, latestRound - 26);`~

Using this mechanism, all events created post migration will have their usual lifecycle. All events created before the migration will be non-ancient at the moment of migration if and only if they were non-ancient prior to the migration.

**Comment by edward-swirldslabs** [comment]
> **long minimumRoundNonAncient = max(firstRoundNonAncient, latestRound - 26);**

I've been using the definition **minRoundNonAncient := latestConsensusRound - 26 +1** since the latestRound counts as one of the 26 non-ancient rounds.  Let me know if I should change what I use or this definition you have here should change. 

That said, I don't think we need to play with the minimumRoundNonAncient definition since this is for an active network with no overlap on rounds near ROUND_FIRST.   The next update of the `NonAncientEventWindow` is going to slide the lowerbound in either case and the end result would behave the same as if the definition had not been modified.

**Comment by cody-littley** [comment]
> I've been using the definition minRoundNonAncient := latestConsensusRound - 26 +1 since the latestRound counts as one of the 26 non-ancient rounds. Let me know if I should change what I use or this definition you have here should change.

I probably have an off by one error here, super easy to do in this context 🙃 . Don't change the definition we've been currently running with based on what is in this ticket.

**Comment by cody-littley** [comment]
We discussed this on a call, and have reached consensus on moving forward with this proposal. Closing the proposal ticket as completed, will open later tickets for actual implementation tasks.
