### ISSUE TITLE
Gas calculation for precompiles incorrectly varies with HAPI exchange rate

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#10828]
### Description

Gas calculation appears to vary with hbar exchange rate, compromising Hedera's policy of fixed fee gas costs.

### Steps to reproduce

Run the following unit test in the build:

private static final long GAS_COST_IN_TINYCENT = 852;

    @Test
    void exchangeRateChangesCausesUnstableGasCost() {
        final var mintFeeTinycents = 10000123L;
        final var fixedHbarEquiv = 30000;
        final var pre0900CentEquiv = 269100;
        final var post0900CentEquiv = 269232;
        System.out.println("Pre-09:00 gas cost: " + gasCostGiven(mintFeeTinycents, fixedHbarEquiv, pre0900CentEquiv));
        System.out.println("Post-09:00 gas cost: " + gasCostGiven(mintFeeTinycents, fixedHbarEquiv, post0900CentEquiv));
    }

    private long gasCostGiven(final long tinycentFee, final int hbarEquiv, final int centEquiv) {
        final var rate = ExchangeRate.newBuilder().setHbarEquiv(hbarEquiv).setCentEquiv(centEquiv).build();
        final var gasPriceInTinybar = getTinybarsFromTinyCents(rate, GAS_COST_IN_TINYCENT);
        final var feeInTinbyar = getTinybarsFromTinyCents(rate, tinycentFee);
        final var baseGasCost = (feeInTinbyar + gasPriceInTinybar - 1L) / gasPriceInTinybar;
        return baseGasCost + (baseGasCost / 5L);
    }

with the following exchange rates:

```
At 08:59 CST
curl -X 'GET' \
  'https://mainnet-public.mirrornode.hedera.com/api/v1/network/exchangerate?timestamp=1703343540' \
  -H 'accept: application/json'
and
```

```
At 09:01 CST
curl -X 'GET' \
  'https://mainnet-public.mirrornode.hedera.com/api/v1/network/exchangerate?timestamp=1703343660' \
  -H 'accept: application/json'
```

### Additional context

Proof on mainnet for same function call at two different times (with two different exchange rates): fail https://hashscan.io/mainnet/transaction/1703343586.545013838 success https://hashscan.io/mainnet/transaction/1703344296.632845003
fail gas: 14,232 success gas: 14,226

**Impact**

dApps cannot be certain the gas consumed by a smart contract function call when the gas changes with HAPI exchange rate. This compromises Hedera's stated policy that fees are denominated in USD.

### Hedera network

mainnet

### Version

v0.45.0

### Operating system

None

**Comment by Nana-EC** [comment]
We should ensure documentation around this occurrence is clear for community

**Comment by MrValioBg** [comment]
Dis | ds
-- | --
ds | ds
