### ISSUE TITLE
Differential testing PBB: Figure out the "doctored" states

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#10880]
Currently to load a mono-state into the event playbook tool the state needs to be manually "doctored" (via a PCLI tool) to fix a problem w.r.t. missing preconsensus event files.  (This might be unnecessary for states post 0.44.)

But this impedes pulling down an arbitrary state and running events against it. 

Either make this "doctoring" scriptable, or eliminate the need for it.

**Comment by mhess-swl** [comment]
I was able to load a 0.44 mainnet state with minimal effort, so we shouldn’t need to doctor any states unless we want to run pre 0.44 states. 

How to do: after downloading the mainnet state (and putting it in the node's state directory),  copy all `.pces` files from the state `preconsensus-events` dir to `data/saved/preconsensus-events/<node id>`

**Comment by mhess-swl** [comment]
**Update**: We may still want to use pre 0.44 states; the mainnet events for the small piece of January 4th I've tested have very few user transactions...

**Comment by mhess-swl** [comment]
Few user transactions shouldn't be an issue going forward. Going to close this issue in the interests of spending time on higher priorities.
