### ISSUE TITLE
GetAccountInfo (on previewnet) returns null for ProxyAccountId

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-services#1090]
**Summary of the defect**
(raised by community developer)
`getAccountInfo` on the previewnet network returns a null value for `proxyAccountId`, this was not the case previously and may cause regression issues in existing code not expecting a null.

**Comment by tinker-michaelj** [comment]
Do we know what language they're working in? (In the Java library, objects representing proto messages return the default instance of a missing field's type, never `null` under any circumstances.)

**Comment by bugbytesinc** [comment]
in .net core gRPC, the default value of objects is null, so this has caused a regression in the .NET SDK.  IIRC a similar change in the past caused an issue with the JS sdk.  I will change the .NET sdk to account for this value possibly being null.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
