### ISSUE TITLE
Reconnect test failed due to recent change 

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#10927]
### Description

Reconnect test failed because reconnect did not happen as expected.

http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/3NReconnect/20240111-063730-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-Interrupted-2NReconnect-1k-41m/
http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/3NReconnect/20240111-063730-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-NI-3NReconnect-2k-30m/

The last good commit is `551a8ad917`

![image](https://github.com/hashgraph/hedera-services/assets/39912573/0ec9d44b-0b68-4c55-92ed-eb3474a083b9)

and the commit `e9a4d50918` caused reconnect test failed.

![image](https://github.com/hashgraph/hedera-services/assets/39912573/10f83e18-479b-44ac-8b45-3bf1bd951962)

I run the test on the above two commit fours times,
and the commit `e9a4d50918` consistently failed.

![image](https://github.com/hashgraph/hedera-services/assets/39912573/344de513-fff6-46bf-8da3-0a6f417d35ba)

### Steps to reproduce

Run nightly regression test panel `GCP-Daily-Comp-3NReconnect-15N-4C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by poulok** [comment]
This has been fixed
