### ISSUE TITLE
Figure out how to use protoc to render record files as readable text

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#10953]
In order to troubleshoot differences between record files, we'll need a standard and reliable way to read the exact content of a record file. The textual representation produced from the code snippet in #10571 doesn't seem to be sufficient. 

`protoc` (natively) dumps a protobuf into "proto text", which should be sufficient. The task for this ticket is to figure out how to use `protoc` to output proto text from a given record file, and troubleshoot any issues. Alternatively, we could write a small tool that utilizes code from the repo (e.g. `RecordStreamingUtils`) to output a record file. 

* @david-bakin-sl has done this in the past, but it is surprisingly tricky to get the correct command line arguments (and I've lost the script file I had used)

We may want to use this as part of our solution to #10955.

**Comment by mhess-swl** [comment]
`protoc` has proved _very_ difficult to work with. I've tried all sorts of variants of the following command with no success:
```bash
# Both commands (and all their variants) were executed in the `<repo root>/hedera-node/hapi/hedera-protobufs/` 

# Try decoding with proto.RecordStreamFile:
protoc --proto_path "$(pwd)/streams" --proto_path "$(pwd)/services" --proto_path "$(pwd)" --decode proto.RecordStreamFile streams/record_stream_file.proto < 2024-01-04T21_15_00.829207003Z.rcd

# Try decoding raw:
protoc --proto_path "$(pwd)/streams" --proto_path "$(pwd)/services" --proto_path "$(pwd)" --decode_raw < 2024-01-04T21_15_00.829207003Z.rcd
```

**Comment by jsync-swirlds** [comment]
PBJ has a JSON serialization format.  Have we considered reading with PBJ and writing back out in JSON format (Codec ModelObject.JSON)?

**Comment by mhess-swl** [comment]
> PBJ has a JSON serialization format. Have we considered reading with PBJ and writing back out in JSON format (Codec ModelObject.JSON)?

Oh I like this much better! I totally forgot about PBJ JSON. It works brilliantly! Thanks @jsync-swirlds !!

**Comment by mhess-swl** [comment]
Example implementation: 
[record-file-to-json_example_12jan24.patch](https://github.com/hashgraph/hedera-services/files/13924674/record-file-to-json_example_12jan24.patch)

**Comment by mhess-swl** [comment]
Patch file has an example. Good to close
