### ISSUE TITLE
Investigate binary diff tools to utilize in in the state saving

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#10962]
### Problem

Currently we save state for every node roughly every 15 minutes. The state files have massive amount of duplicated data, so instead of storing the whole state we can store diffs only. 

### Solution

There are following questions that need answer:

- What is best bin-diff tool?
- What is best pattern of files to bundle with diffs?
   -  One node a time period, 1h, 3h, 6h, 1 day?
   -  All nodes for one 15min time slot? 
   - All nodes for a time period, 1h, 3h, 6h, 1 day?
- What is best compression to apply?

**Comment by imalygin** [comment]
There are following candidates for the diff tool:
- rsync 
- xdelta

Both tools give promising results and both used for creation of incremental backups

**Comment by imalygin** [comment]
Experiment 1 - the same node, different timestamps

For this experiment I took 7 states: the current and the states that were created 15min, 1hr, 3hr, 6hr, 12hr and 24hr ago. Then created a `tar` file for each state
Then I calculated diffs using both tools
E.g., 

```
rsync -av --only-write-batch=12hr-rsync 12hr.tar latest.tar

xdelta3 -e -s 12hr.tar latest.tar 12hr-xdelta
```

For the reference, the latest state size is 6660 MB, the oldest state size is 6588 MB. 
| Timeframe | Tool name | Diff size |
| ---- |------- | ----- |
| 15 min |rsync || 119 MB |
| 15 min  | xdelta3  | 25 MB |
| 1 hr  |rsync |  380 MB |
| 1 hr    | xdelta3  | 28 MB |
| 3 hr | rsync |  420  MB |
| 3 hr  | xdelta3  | 29 MB |
| 6 hr |rsync |  1065 MB |
| 6 hr  | xdelta3  | 41 MB |
| 12 hr  |rsync |  1102 MB |
| 12 hr  | xdelta3  | 45 MB |
| 24 hr   |rsync |  1137 MB |
| 24 hr  | xdelta3  | 50 MB |

`xdelta3` demonstrated vastly better results on the data that we have.

**Comment by imalygin** [comment]
### Experiment for the same node

I took round `159555230` from the following set of hosts:
```
l-dell-01 - node01
ecstatic-bohr-hivelocitydns-com - node02
hgc-cherryserver-spare - node04
hedera-council-google-node - node05
hgc-ovhcloud-mainnet - node06
```

Here are the results:

**Comment by jasperpotts** [comment]
There are two options for diff styles. With trade offs between size and easy or restoring.<img width="781" alt="Diff-Options" src="https://github.com/hashgraph/hedera-services/assets/1466205/a8323974-32cd-4962-ac84-488a69b7049c">

**Comment by imalygin** [comment]
### Experiment 3 - sequence of diffs for one day

This experiment is the `Option 2` Jasper mentioned above. I took 24 hours worth of state files and created a set of diffs to be able to restore to any state within that day using sequence of diffs. 

I created two following scripts for the diff creation and state reconstruction:

`diff_creator,sh`
```
#!/bin/bash

# Check if the source directory is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <source_directory>"
    exit 1
fi

# The first argument is the source directory
source_directory="$1"

# Check if the provided directory exists
if [ ! -d "$source_directory" ]; then
    echo "Error: Directory '$source_directory' does not exist."
    exit 1
fi

# Change to the source directory
cd "$source_directory"

start_time=$(date +%s.%N) # Record the start time of the script

# List all tar files sorted alphanumerically in the source directory
tar_files=$(ls -1 *.tar)

# Check if tar files are found
if [ -z "$tar_files" ]; then
    echo "Error: No tar files found in directory '$source_directory'."
    exit 1
fi

# Create an array of tar files
readarray -t sorted_files <<< "$tar_files"

# Initialize the previous file variable
prev_file=""

# Loop through the array, starting from the first file
for current_file in "${sorted_files[@]}"; do
    # Skip the first iteration
    if [ -z "$prev_file" ]; then
        prev_file="$current_file"
        continue
    fi

    # Create delta file name
    delta_file="delta_${prev_file%.*}_to_${current_file%.*}.xdelta"

    # Start time for this operation
    start_op=$(date +%s.%N)

    # Create delta file using xdelta3
    echo "Creating delta: $delta_file"
    xdelta3 -W 16777216 -0 -B 2147483648 -e -s "$prev_file" "$current_file" "$delta_file"

    # End time for this operation
    end_op=$(date +%s.%N)

    # Calculate and print time taken for this operation
    op_time=$(echo "$end_op - $start_op" | bc)
    echo "Time taken for $delta_file: ${op_time}s"

    # Update previous file to current
    prev_file="$current_file"
done

end_time=$(date +%s.%N) # Record the end time of the script
total_time=$(echo "$end_time - $start_time" | bc) # Calculate total execution time

echo "All delta files created."
echo "Total time taken: ${total_time}s."
```

`reconstructor.sh`
```
#!/bin/bash

# Check if the initial tar file and directory are provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <initial_tar_file.tar> <xdelta_files_directory>"
    exit 1
fi

# The first argument is the initial tar file
initial_tar_file="$1"

# The second argument is the directory containing xdelta files
xdelta_dir="$2"

# Check if the provided directory exists
if [ ! -d "$xdelta_dir" ]; then
    echo "Error: Directory '$xdelta_dir' does not exist."
    exit 1
fi

# List and sort all xdelta files in the directory
xdelta_files=$(ls -1 "$xdelta_dir"/*.xdelta | sort)

# Check if xdelta files are found
if [ -z "$xdelta_files" ]; then
    echo "Error: No xdelta files found in directory '$xdelta_dir'."
    exit 1
fi

# The initial state is the initial tar file
current_state="$initial_tar_file"

start_time=$(date +%s) # Record the start time of the script

# Loop through sorted xdelta files and apply them to update the current state
for delta_file in $xdelta_files; do
    start_op=$(date +%s) # Start time for this operation

    # Temporary file for the next state
    next_state_temp="temp_next_state.tar"

    # Apply the delta to the current state and store in a temporary file
    xdelta3 -d -s "$current_state" "$delta_file" "$next_state_temp"
    echo "Applied delta: $delta_file"

    end_op=$(date +%s) # End time for this operation
    op_time=$((end_op - start_op)) # Time taken for this operation in whole seconds
    echo "Time taken to apply $delta_file: ${op_time} seconds"

    # Move the temporary file to be the new current state
    mv "$next_state_temp" "$current_state"
done

end_time=$(date +%s) # Record the end time of the script
total_time=$((end_time - start_time)) # Calculate total execution time in whole seconds

# Extract the timestamp from the last delta file
last_delta_file=$(basename "${xdelta_files##* }")
timestamp=${last_delta_file##*_to_}
timestamp=${timestamp%.xdelta}

# Name of the final state file
final_state="reconstructed_${timestamp}.tar"
mv "$current_state" "$final_state"

echo "Final state reconstructed: $final_state"
echo "Total time taken: ${total_time} seconds.

```

**Comment by imalygin** [comment]
Here are the results of `diff_creator.sh`:

Average diff size: 44.8 MB
Average time: 40 seconds
Total time taken: 3867 seconds

Total size of all diffs: 8486 MB
Average state size: 6875 ./reMB
Initial state size: 6863 MB

**Comment by imalygin** [comment]
### xdelta3 observations

1. Diffs are not compressible:
```
rsa-key-20230427@jasper-ssd:~/recent$ 7z a all_deltas.7z all_deltas.tar

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,48 CPUs Intel(R) Xeon(R) CPU @ 2.80GHz (50657),ASM,AES-NI)

Scanning the drive:
1 file, 8486912000 bytes (8094 MiB)

Creating archive: all_deltas.7z

Items to compress: 1


Files read from disk: 1
Archive size: 8486002900 bytes (8093 MiB)
Everything is Ok
```

2. The state compresses well:

```
rsa-key-20230427@jasper-ssd:~/recent$ 7z a state.7z 159644099.tar

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,48 CPUs Intel(R) Xeon(R) CPU @ 2.80GHz (50657),ASM,AES-NI)

Scanning the drive:
1 file, 6869964800 bytes (6552 MiB)

Creating archive: state.7z

Items to compress: 1


Files read from disk: 1
Archive size: 2527703014 bytes (2411 MiB)
Everything is Ok

```

3. `xdelta3` has to be used with the following set of settings ` -W 16777216 -0 -B 2147483648`, where
`-W` - The input window size. Determines how much of the input is compressed in a single VCDIFF window. Smaller windows have higher compression cost and take less memory to decode. Larger windows have better compression but only up to a point, because large-window addresses take more bits to encode. The maximum value is 16MB.
`-B` - The encoder uses a buffer for the source input (of size set by the command-line flag -B). To ensure the source input is read sequentially, with no backward seeks, the encoder maintains the source horizon at half the source buffer size ahead of the input position. A source copy will not be found if it lies more than half the source buffer size away from its absolute position in the input stream. For large files, -B may need to be raised. The maximum value is 2GB.
`-0` - The tool doesn't apply any compression.  I tried max level compression - `-9` and with this level the resulting diff size was only 10% smaller and it took 3 times longer to create it (120 seconds with compression, 40 seconds without it). It's just not worth it. 

**Without these settings `xdelta3` is not performing well with the state files**

[See here ](https://github.com/jmacd/xdelta/blob/wiki/TuningMemoryBudget.md)for more details.

4. `xdelta3` work is really calculation-heavy. So, performance of the script is mostly CPU-bound, not IO-bound.

**Comment by imalygin** [comment]
Here are the results of `reconstructor.sh` for the **recent state files**:

Average time per diff - 13.6 sec
Longest time per diff - 17 sec
Shorted time per diff - 12 sec

Total time: 1297 sec

**Comment by imalygin** [comment]
Here are the results of `diff_creator.sh` for the state files **before compaction improvement (08/15/2023)**:

Average diff size: 29.9 MB
Min diff size: 17 MB
Max diff size: 30.6 MB

Average time: 18 seconds
Total time taken: 1718 seconds

Total size of all diffs: 2840 MB
Average state size: 2523 MB
Initial state size: 2473 MB

Total state size: 242 GB

The size of the final archive that contains all diffs and initial state: 3104 MB

**Comment by imalygin** [comment]
Here are the results of `reconstructor.sh` for the state files **before compaction improvement (08/15/2023)**:

Average time per diff - 6.4 sec
Longest time per diff - 8 sec
Shortest time per diff - 6 sec

Total time: 611 sec

**Comment by imalygin** [comment]
Here are the results of `diff_creator.sh` for the state files before VirtualMap introduced (12/28/2021):

Average diff size: 20.2 MB
Min diff size: 18.7 MB
Max diff size: 22.5 MB

Average time: 6.6 sec
Total time taken: 632 sec

Total size of all diffs: 1922 MB
Average state size: 2149 MB
Initial state size: 2175 MB

Total state size: 206 GB

The size of the final archive that contains all diffs and initial state:1882 MB

**Comment by imalygin** [comment]
Here are the results of `reconstructor.sh` for the state files **before VirtualMap introduced (12/28/2021):**



Total time: 127 seconds

**Comment by imalygin** [comment]
To conclude: `xdelta3` works best with the later states with JasperDB/MerkleDB introduced. But even for the older state compression rate ~90% which is a big win.
