### ISSUE TITLE
Componentize Round Handler

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#10984]
- This issue represents the first step of componetizing the round handler, which is to use the framework for the round handler inputs, but leave the outputs as-is (outside the framework)
    - inputs are consensus rounds, and updates to the running hash 
- The [second step](https://github.com/hashgraph/hedera-services/issues/11280) will be done later, and involves using the framework to carry the output of the round handler
    - the output is a signed state

**Comment by lpetrovic05** [comment]
@alittley this ticker needs information
