### ISSUE TITLE
Design proposal: disentangle shadowgraph from consensus

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#10982]
Image of proposed wiring. Irrelevent parts of the system excluded. Coloring is funny because export of mermaid into draw.io doesn't preserve color and I had to apply it by hand. I find the best way to view this image is to zoom into the web page. It's an SVG, so it won't get pixelated. For some reason, if you click on the image the text gets mangled.

![shadowgraphRefactor](https://github.com/hashgraph/hedera-services/assets/56973212/20a70c73-459f-4b70-bb17-a8700198ffc9)

The idea is to make it so that consensus does not rely on the shadowgraph for anything. The shadow graph will only be used by gossip after these changes are completed.

There are currently the following dependencies between consensus and the shadowgraph:

- data is inserted into the shadowgraph on the consensus thread
- the shadowgraph uses the same links as consensus
- the shadowgraph is responsible for unlinking events
- the shadowgraph is used for stale event detection

To solve the issue of shared links, we need to create a new linker for the shadowgraph, and a stand alone unlinker for consensus. Pulling the shadowgraph into its own scheduler will resolve the issue where data can only be inserted into the shadowgraph on the consensus thread. Finally, we can write a stale event detector that does not require a shadowgraph to function.

**Comment by lpetrovic05** [comment]
needs single component wrapper: consensus, linking, unlinking, stale event detection

**Comment by cody-littley** [comment]
Closing this as we currently agree on the design.
