### ISSUE TITLE
Fix INSUFFICIENT_PAYER_BALANCE in HCS-Restart-Performance-Hotspot-10k-61m

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1100]
Though `HCS-Restart-Performance-Hotspot-10k-61m` with 6N_6C test is supposed to run for 60 minutes, the test stops within 10 minutes, as the client gets `INSUFFICIENT_PAYER_BALANCE` error.  Fix the error and check if the test runs for 60 minutes

**How to reproduce (if possible)**
https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1613725043061600

**Comment by anighanta** [comment]
Trying a run with auto renew period for account balance set to 2 mins instead of 3 mins.
In a 60 mins run, this would top up 30 times. Making to amount transfers to the test account to : 30 * 5 Mil HBAR. 
which should be fine.

**Comment by JeffreyDallas** [comment]
I tried with local launched test, even with 2 mins balance auto recharge window, after 10 minutes, the clients stop submitting new transactions. Need to continue to debug

![image](https://user-images.githubusercontent.com/39912573/108728825-8a3a1480-74ef-11eb-9e37-1341208dcc66.png)

**Comment by Neeharika-Sompalli** [comment]
15N test have  the same issue with `SubmitMessageLoadTest`, https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1613827283013000

**Comment by Neeharika-Sompalli** [comment]
This is caused because of using account that is in the state as PAYER, which should be done only for Random tests. For hotspot tests we use a payer we created from GENESIS with higher balance.

This should be solved by adding `totalTestAccounts=1` to `ciPropsMap`

```"hederaServicesConfig": {
	"ciPropsMap" : "messageSize=128,tps=42,totalTestAccounts=1,mins=60,threads=40",
	"testSuites": [
	  "SubmitMessageLoadTest"
	]
  },
```

Testing this change now.
