### ISSUE TITLE
Fix Reconnect tests that doesn't stop after test duration completes

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1101]
Due to a recent change in `swirlds-platform-regression` Reconnect tests that are running in CircleCI doesn't stop after the test duration is completed. Because of this the results are not posted to slack.
Investigate the reason for this issue and fix it.

**How to reproduce (if possible)**
CircleCI link for the test that did not finish https://app.circleci.com/pipelines/github/hashgraph/hedera-services/11066/workflows/4ade7a2a-7bf8-440e-adc2-9ec98569ebf9/jobs/56493

**Comment by Neeharika-Sompalli** [comment]
This is being fixed by Ron on JRS side in `swirlds-platform-regression` . Once that PR goes in, need to verify if that fixes the issue on services side as well.

**Comment by qnswirlds** [comment]
Reconnect test that passed after the fix in regression
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1613836622002100

**Comment by Neeharika-Sompalli** [comment]
This is fixed by a platform-regression change.
