### ISSUE TITLE
Direct call w/o value to system accounts [0.0.361-0.0.750] result in precompile error

### ISSUE THREAD

**Issue by yiliev0** [hashgraph/hedera-services#11033]
### Description

Executing a ContractCall w/o value to system account in the range[0.0.361-0.0.750) result in `PRECOMPILE_ERROR` 

### Steps to reproduce

1. Create an account
2. Execute ContractCall to 0.0.629 using the account from step1.

**Expected result**: The call should succeed with no-op. 
**Actual result**: The call fails with `PRECOMPILE_ERROR`

### Hedera network

other

### Version

0.46.0

### Operating system

None

**Comment by stefan-stefanooov** [comment]
This will be taken care of after 0.48 version.
