### ISSUE TITLE
Determine how much space is saved by removing hashes and indices

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#11088]

**Comment by imalygin** [comment]
This is a follow up for the set of experiments done in https://github.com/hashgraph/hedera-services/issues/10962 

The idea behind this experiment is the following. The indices are critical for MerkleDB performance, but they are not required for the data extraction. That is, one can get the data out of MerkleDB without indices but it's going to be _really_ slow. Also, indices can be reconstructed on demand. It takes significant amount of time but it can be done. 

For long term backups there is no demand of high performance or immediate availability and, therefore, we don't have to store indices for older backups. It will introduce significant inconveniences (much more time required to restore the state) but it will save storage. 

The goal of this ticket to access what percentage of space can be stored this way.

**Comment by imalygin** [comment]
For the experiment I took the data from [this experiment](https://github.com/hashgraph/hedera-services/issues/10962#issuecomment-1899399306): 

Initial data size of 96 states: 660 GB
Data size of 96 states without indices: 383 GB

**Comment by imalygin** [comment]
The size of the final archive that contains all diffs and initial state prior to index removal -  6476 MB
The size of the final archive without indices - 5124 MB

Prior index removal:
Average diff size: 44.8 MB
Min diff size:19 MB
Max diff size: 50.8 MB

After index removal:
Average diff size: 42.9 MB
Min diff size: 18.6 MB
Max diff size: 48.1 MB

**Comment by jasperpotts** [comment]
Did you test with hashes and indexes removed or just indexes?

**Comment by imalygin** [comment]
I removed both - indexes and hashes. That is, I removed `.ll`, `.hdhm`, and `.hl` files.
