### ISSUE TITLE
Split app transaction prehandle into separate class

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#11113]
App transaction prehandle is currently part of `SwirldStateManager`, but I don't think there is any reason that it needs to be. Prehandle isn't synchronized in any way with normal handling.

App transaction prehandle should be split into a separate class.

**Comment by poulok** [comment]
The reason it was originally put there was to consolidate all interactions with the `SwirldState` in a single class. The only threading relationship prehandle has with handle is that prehandle must always complete for a given event before that event is send to handle, but this is enforced other ways. Also, prehandle should always be invoked on the latest immutable state, and the latest immutable state is updated by the consensus handling thread in the `SwirldStateManager`. It is easier to ensure that the correct objects are being invoked when they are all in one class. Maybe there is a clean and easy way to do it differently, but these are things to consider.
