### ISSUE TITLE
Design(Blocked): Helper library in modularized hedera-services repo which will make possible externalisation of `hedera-smart-contract-service-impl`

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#11129]
Currently Mirror Archive Node utilizes a `hedera-evm` library from the `hedera-mono-service` code base, which will be deprecated soon. We need to substitute it with its replacement, which would be `hedera-smart-contract-service-impl`.

To do so, we need to define an additional helper library, which would keep interfaces for the new `State` that is used inside `hedera-smart-contract-service-impl`, as well as the default `HandleContext` implementation, that is the entry object which `hedera-smart-contract-service-impl` uses for performing a transaction.

**Comment by netopyr** [comment]
@IvanKavaldzhiev Can we close this issue? In my understanding, reusable services have been implemented.

**Comment by IvanKavaldzhiev** [comment]
Yes, I think it's a good moment to close the issue.
