### ISSUE TITLE
System accounts disambiguation: Create hapi tests for Call operations for system accounts

### ISSUE THREAD

**Issue by kselveliev** [hashgraph/hedera-services#11137]
### Problem

Calling operations on system accounts in hedera may differ from ethereum.
We need to add hapi tests for them and check and document the behaviour.

### Solution

Add tests for **Call** operations(**CallOp**, **DelegateCallOp**, **CallCodeOp**, **StaticCallOp**) involving the system accounts and ensure that these tests conform to the following expected behavior.
<img width="760" alt="image" src="https://github.com/hashgraph/hedera-services/assets/138600514/28f5d28e-39a5-4e36-aabc-f099206df773">

**Comment by bilyana-gospodinova** [comment]
The column for Ethereum was updated in the Notion page but the one for Hedera remains the same so no changes in the tests are necessary.
