### ISSUE TITLE
System accounts disambiguation: Create hapi tests for transfer and send operations for system accounts

### ISSUE THREAD

**Issue by kselveliev** [hashgraph/hedera-services#11138]
### Problem

Calling operations on system accounts in hedera may differ from ethereum.
We need to add hapi tests for them and check and document the behaviour.

### Solution

Add tests for **transfer** and **send** operations involving the system accounts and ensure that these tests conform to the following expected behavior.
<img width="1049" alt="image" src="https://github.com/hashgraph/hedera-services/assets/138600514/a880b1c6-d4bb-4e95-845b-f0626601d420">

**Comment by 0xivanov** [comment]
Opening because there is part 2 PR : https://github.com/hashgraph/hedera-services/pull/11490
