### ISSUE TITLE
Automation - Bind/Unbind SuiteRunner jar for a release

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#1114]
Right now, every time we release a new version of Services to Maven Central, we need to unbind `SuiteRunner` jar from Maven lifecycle. After that we have to rebind it so `SuiteRunner` jar could be generated for regression testings.
https://github.com/hashgraph/hedera-services/blob/93383a72c6298421cf7dd17a2904199fafd9426f/test-clients/pom.xml#L209-L227

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
