### ISSUE TITLE
Executing an internal call with amount against system accounts results in `PRECOMPILE_ERROR`

### ISSUE THREAD

**Issue by yiliev0** [hashgraph/hedera-services#11159]
### Description

Executing a call function with specifying an amount, directed at a contract that itself contains a call function, leads to a precompile error. This error specifically occurs when the target of the contract call is a system account within the range of 0.0.10 to 0.0.357.
EOA ---call---> Contract(call with amount) ---call[value]---> 0.0.357

This behaviour is observed in version 0.46, but also in previous versions.
https://hashscan.io/previewnet/transaction/1706173001.987222003 

### Steps to reproduce

1. Create an contract with the following function:
```
    function makeCallWithAmount(address _to, bytes memory _data) external payable returns (bool success, bytes memory returnData) {
        (success, returnData) = _to.call{value: msg.value}(_data);
    }
```
2. Deploy the contract and grab the contract address
3. Execute a ContractCall(with amount) against the contract address(step2) with the function name("makeCallWithAmount") with function parameter of the  system account address(0.0.357).

**Expected result**: The transaction should result with `INVALID_FEE_SUBMITTED`
**Actual result**: The transaction fails with `PRECOMPILE_ERROR`

### Hedera network

other

### Version

0.46.0

### Operating system

None

**Comment by 0xivanov** [comment]
Is the data parameter empty?
