### ISSUE TITLE
Executing an internal call without amount against system accounts results in `PRECOMPILE_ERROR`

### ISSUE THREAD

**Issue by yiliev0** [hashgraph/hedera-services#11158]
### Description

Executing a call function without specifying an amount, directed at a contract that itself contains a call function, leads to a precompile error. This error specifically occurs when the target of the contract call is a system account within the range of 0.0.10 to 0.0.357. 
EOA ---call---> Contract(call) ---call---> 0.0.357

This behaviour is observed in version 0.46, but also in previous versions. 
https://hashscan.io/previewnet/transaction/1706171808.147232330

### Steps to reproduce

1. Create an contract with the following function:
```
    function makeCallWithoutAmount(address _to, bytes memory _data) external returns (bool success, bytes memory returnData) {
        (success, returnData) = _to.call(_data);
    }
```
2. Deploy the contract and grab the contract address
3. Execute a ContractCall against the contract address(step2) with the function name("makeCallWithoutAmount") with function parameter of the  system account address(0.0.357)

**Expected result**: The transaction should be successful with no op
**Actual result**: The transaction fails with `PRECOMPILE_ERROR`

### Hedera network

other

### Version

0.46.0

### Operating system

None

**Comment by 0xivanov** [comment]
Is the data parameter empty?
