### ISSUE TITLE
EET test for HCS validation + system file capture

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#112]
Write EET tests to:

- Store protobuf versions of the six system files to disk.
- Run HCS operations using fee schedule + exchange rates loaded from disk.

**Comment by anighanta** [comment]
handled here [ProtectedFilesUpdateSuite](https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/java/com/hedera/services/bdd/suites/file/ProtectedFilesUpdateSuite.java)
