### ISSUE TITLE
Executing an internal call with value against PRNG/Exchange rate precompile addresses returns success

### ISSUE THREAD

**Issue by yiliev0** [hashgraph/hedera-services#11218]
### Description

Executing an internal call with value against PRNG/Exchange rate precompile addresses returns success. Only the contract that acts as middleman is credited with hbars.

### Steps to reproduce

1. Create a contract with the following function:
```
 function makeCallWithAmount(address _to, bytes memory _data) external payable returns (bool success, bytes memory returnData) {
        (success, returnData) = _to.call{value: msg.value}(_data);
    }
```
2. Deploy the contract
3. Execute a contract call against the contract from step1/2 using the function with parameters(address _to) using the PRNG/ExchangeRate precompile addresses 
```
var data = encodeDataToByteArray("getPseudorandomSeed()");
var parameters = new ContractFunctionParameters()
                .addAddress("0x0000000000000000000000000000000000000169")
                .addBytes(data);
```

**Expected result**: The secondary call against the precompile address should fail with `INVALID_FEE_SUBMITTED`
**Actual result**: The secondary call is successful. 

Note: This is also reproducible with ExchangeRate precompile address

### Hedera network

other

### Version

0.46.0

### Operating system

None

**Comment by 0xivanov** [comment]
Note: `testTransferToNonExistingSystemAccounts` in test-clients
