### ISSUE TITLE
Create platform-base example project for feature testing

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#11224]
Create a new project that uses platform-base modules like logging and metrics, that can be used to test platform-base module behavior without the production platform and services layers.

This new project should allow for testing of:

- logging
- metrics reporting
- configuration

**Comment by mxtartaglia-sl** [comment]
@hendrikebbers @timo0 
Before moving it to a broader code review, would you provide early feedback for https://github.com/hashgraph/hedera-services/pull/11408?
Thanks
