### ISSUE TITLE
Return TransactionID of scheduled txn in ScheduleCreate receipt

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1127]
**Summary**
A scheduled transaction `S` inherits the `TransactionID` of its parent `ScheduleCreate`.

If Alice, Bob, and Carol all schedule `S` in order via `C1`, `C2`, and `C3`, then the receipt for `S` is **only available** by querying with the `TransactionID` of `C1` (plus `scheduled=true`). 

Bob will know the `ScheduleID` of `S` from the receipt of `C2`; and if he is following the record stream, he can match this `ScheduleID` to the `scheduleRef` field in the record for `S`.

But without communicating with Alice or following the record stream, Bob has no easy way to query for the receipt of `S`.

**Possible resolution**
- In the receipt of a `ScheduleCreate` transaction that resolves to `SUCCESS`, include the `TransactionID` that should be used to query for the receipt of the scheduled transaction.
- At **minimum**, the scheduled transaction's inherited `TransactionValidStart` should be returned in [the `ScheduleGetInfoResponse`](https://hashgraph.github.io/hedera-protobufs/#proto.ScheduleGetInfoResponse).

**Comment by lbaird** [comment]
I agree. It should return the transactionID of the transaction that was first and that actually created it.

________________________________

**Comment by tinker-michaelj** [comment]
> I agree. It should return the transactionID of the transaction that was first and that actually created it.

Thanks @lbaird. 👍

**Comment by noshmody** [comment]
All but the first creator will have to poll queries the ScheduleID or the TransactionID. 
Is this an acceptable solution?

What is the anticipated throttle for Scheduled Transactions? 

**_Sample Calculation to help set the throttle_**
 500 byte Scheduled transaction size 
 1000 TPS
 
 Would add approximately 1 GB to state (in memory)

**Comment by lbaird** [comment]
I think after submitting a scheduled transaction, the user can simply ask for the receipt or record of the outer transaction. And if successful, the result will include the transaction ID of the inner transaction, which might or might not match the outer ID, depending on whether that user was first.

The throttle should be the same as for creating other entities, once we allow them to last more than a half hour.  Until then, a higher throttle limit would be ok, but it’s probably better to have the lower throttle from the beginning.


________________________________
