### ISSUE TITLE
Unit Test Failure: `VirtualMapHashingTest#fullLeavesRehash` fails intermittently 

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#11304]
### Description

[com.swirlds.virtualmap.VirtualMapHashingTest](https://scans.gradle.com/s/7ctqo3b42kwww/tests/task/:swirlds-virtualmap:test/details/com.swirlds.virtualmap.VirtualMapHashingTest.fullLeavesRehash(int)[3]) is failing intermittently. 

It looks like it happens under the load. I found this in the logs
```
18:34:18.747  59595 Test worker Flushed in 180 ms 
18:34:18.748  59596 Test worker Doing full rehash for the path range: 7775 - 15550  in the VirtualMap at [1]
```
Normally it takes 10-20 ms. 

See [this link ](https://scans.gradle.com/s/7ctqo3b42kwww/tests/task/:swirlds-virtualmap:test/details/com.swirlds.virtualmap.VirtualMapHashingTest/fullLeavesRehash(int)%5B3%5D?top-execution=1) for more details

### Steps to reproduce

1. Run make sure that CPU resources and disk I/O are limited
2. Run `VirtualMapHashingTest.fullLeavesRehash`

### Hedera network

other

### Version

v0.47

### Operating system

None

**Comment by artemananiev** [comment]
Another JRS failure with the same symptoms: http://35.247.76.217:8095/swirlds-automation/release/0.47/4N/Reconnect/20240220-094051-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/
