### ISSUE TITLE
Make event.softwareVersion @NonNull

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#11300]
Events did not have a software version before. When added, the version was marked as `@Nullable` to support migration. Since we no longer need to support events with no software version, `@NonNull` should be enforced for events. The same should be done for any code that uses that version, like `ScopedSystemTransaction`

**Comment by lpetrovic05** [comment]
maybe this makes more sense to do as part of the event refactor

**Comment by poulok** [comment]
This will be done as part of the event refactor work when the Event no longer has no-arg constructor.
