### ISSUE TITLE
Relying on ThreadLocal for performance is broken within ForkJoinPools

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#11309]
### Problem

I'm always frustrated when...

**InnocuousForkJoinWorkerThread.java:**
> A worker thread that has no permissions, is not a member of any user-defined ThreadGroup, uses the system class loader as thread context class loader, and clears all ThreadLocals after running each top-level task.

In several cases, we rely on `ThreadLocal` when we need a supporting object with high instantiation cost. Instead of creating a new object for each operation, we create them once per thread and store in `ThreadLocal` making them readily available for independent subsequent operations. Examples are `HASH_BUILDER_THREAD_LOCAL` in `VirtualHasher`, `CACHE` in `EcdsaSecp256k1Verifier`, `BUFFER_CACHE` and `BUFFEREDDATA_CACHE` in `DataFileReaderPbj`, etc.
When those `ThreadLocals` are used in `ForkJoinPools`, they are recreated for each top-level task diminishing the cost saving we used to enjoy.

### Solution

Apparently, it's totally safe to use `ThreadLocal` when we need to create context for an operation to bypass some third-party library we do not control that calls back into our code **within the same task**, i.e. for functional reasons.
It's also desirable to provide reusable supporting objects in dedicated pools for performance reason (`HASH_BUILDER_THREAD_LOCAL` in `VirtualHasher.HASHING_POOL` is a good example).
There are two approaches to solving it:
* create a `ConcurrentLinkedQueue` of resources from which needed objects can be obtained, creating new instances on demand, and to which they should be released. An example of this approach is `ReusableBucketPool`.
* extend `ForkJoinWorkerThread` for dedicated pools to provide effectively thread-local resources intended for the purpose of the pool. Such pools should be created with a fixed size to avoid frequent thread recreation.

**Comment by artemananiev** [comment]
Two major usages of `ThreadLocal` in platform data:

1. Data file readers (JDB and PBJ): cache bytes buffers / buffered data objects per thread, as allocating a new buffer is costly
2. Virtual hasher: caches `HashBuilder` objects

In case of data file readers, we sometimes need to update the buffers. In the new approach, there should be a way to release a different object than was leased from a pool.

**Comment by artemananiev** [comment]
I spent some more time on this topic. The implementation referenced in bug description, `InnocuousForkJoinWorkerThread`, is only used when there is a security manager in the JVM, and only for the common fork-join pool. Custom fork-join pools like what is used in `VirtualHasher` are not affected, they use regular worker threads, which do not clean thread locals.

@OlegMazurov Need some more information from you about where you noticed `InnocuousForkJoinWorkerThread` objects.

**Comment by artemananiev** [comment]
Besides that, I forced clearing thread locals using the API @hendrikebbers referenced above, but couldn't see any measurable difference (in performance) when running a local crypto transfer benchmark.

**Comment by OlegMazurov** [comment]
I don't see any manifestation of the issue in current code. We stopped using `ForkJoinPool.commonPool()` in platform, this is probably why. The ticket can be closed.
