### ISSUE TITLE
Validate proposed non-breaking protobuf changes vis-a-vis Services

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1131]
**Summary**
Validate that https://github.com/hashgraph/hedera-protobufs/pull/13, which standardizes and cleans up the Hedera protobufs, has no breaking impacts on Services code, Engineering clients, and doc generation.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
