### ISSUE TITLE
Unit test failure: `learnerAbortsReconnectHalfWayThrough`

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#11362]
Unit test is failing frequently on `develop`

https://scans.gradle.com/s/vniyewoi3y42w/tests/overview?outcome=FAILED

```
org.opentest4j.AssertionFailedError: reconnect should produce identical tree ==> expected: <true> but was: <false>
```

**Comment by poulok** [comment]
Waiting for further occurrences. This cannot be reproduced, even by running the test repeatedly on a GCP instance (mimicking CI pipeline setup)

**Comment by poulok** [comment]
No failures in the last few weeks, this was likely fixed by another merge.
