### ISSUE TITLE
Log claims state is incomplete, despite node having a supermajority of signatures

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#11422]
- FCM-Migration-NewNodesFromGenesis-2.5k-8m
- [data directory](http://35.247.76.217:8095/swirlds-automation/release/0.47/6N/Migration/20240207-125249-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/)
    - `node4` completes a reconnect as a teacher and writes the reconnect state to disk
    - An error is printed (see below) claiming that the state didn't have enough signatures, despite having a supermajority
    - This looks like a race condition with respect to how signatures are being added to a state 

```
State written to disk for round 4351 did not have enough signatures. Collected signatures representing 35169714123/50000000000 weight. Total unsigned disk states so far: 1. {} [com.swirlds.logging.legacy.payload.InsufficientSignaturesPayload]
```
Note: `35169714123/50000000000 = 0.703`

**Comment by lpetrovic05** [comment]
@alittley Why do you think this is a race condition?

**Comment by alittley** [comment]
> @alittley Why do you think this is a race condition?

Because it says it didn't have enough signatures, but then says that the signatures represent >70% of the weight, which should be enough

**Comment by poulok** [comment]
Waiting for a reproduction with the extra logging

**Comment by alittley** [comment]
After a lot of looking and testing, I can't find any mechanism that could explain the observed behavior.

**Comment by alittley** [comment]
Hasn't been observed in a long time.

**Comment by edward-swirldslabs** [comment]
New observation: http://35.247.76.217:8095/swirlds-automation/release/0.53/4N_2C/Ubuntu2204_Update/20240825-111009-GCP-Daily-Update-Ubuntu2204-4N-2C/Crypto-Update-Jar-1.5k-25m/swirlds-logs.html

**Comment by litt3** [comment]
> New observation: http://35.247.76.217:8095/swirlds-automation/release/0.53/4N_2C/Ubuntu2204_Update/20240825-111009-GCP-Daily-Update-Ubuntu2204-4N-2C/Crypto-Update-Jar-1.5k-25m

@edward-swirldslabs That test is not a reoccurrence.

This issue is for a log claiming there aren't enough signatures, but then logging values which _are_ enough. i.e. "Not enough signatures, only 70%" (but 67% is the completion threshold).

**Comment by edward-swirldslabs** [comment]
Agreed, after digging deeper, this is not a reoccurrence.

**Comment by alex-kuzmin-hg** [comment]
I see it on HashSphere:
```
2024-11-26 22:00:17.855 1995     ERROR EXCEPTION        <<scheduler StateSnapshotManager>> DefaultStateSnapshotManager: State written to disk for round 958 did not have enough signatures.
This log adds debug information for #11422.
Pre-check weight: 1500/3500 (0.000000%)  Post-check weight: 1500/3500 (0.000000%)
Pre-check threshold: false   Post-check threshold: false {} [com.swirlds.logging.legacy.payload.InsufficientSignaturesPayload]
```
