### ISSUE TITLE
HCS Message Size Limit

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-services#1145]
Hedera transactions are gossiped throughout the network, and while Hedera can process small HCS messages at the same high TPS rate as crypto transfers, larger HCS message can affect the latency for other transactions. The maximum size of Hedera transaction is currently limited to 6K bytes to accommodate a number of signatures as well as enabling updating the address book in a single transaction. To prevent many large messages from slowing down other transactions,  we limit the HCS message size to 1024 bytes. Applications can still use larger HCS messages using the fragmentation feature that is already implemented in HCS services as well as in the mirror nodes.

**Comment by ljianghedera** [comment]
I did some research and found checking of the , here are what we will do to address this issue: 

- [ ] Add a new property for hedera services `consensus.message.max.size` to let hedera services to limit the chunk or whole message size of HCS `submitMessage` request; 
- [ ] In hedera services precheck, add logic to check the size of HCS `submitMessage` request to make sure the size of the payload is less or equal to the value configured by the new property;
- [ ] Add a new ResponseCodeEnum, INVALID_MESSAGE_SIZE_TOO_LARGE, to denote the error condition if the message or chunk size is larger than the configured value;
- [ ] Create test scenarios for the new enhancement;

**Comment by abhishek-hedera** [comment]
I think it would be appropriate to have the **MESSAGE_SIZE_TOO_LARGE = 214** based on the open pull request for scheduled transactions.
https://github.com/hashgraph/hedera-protobufs/pull/15/files#diff-64b63e3c61d8f80c7f9ad9f2ac6180bd7f87af6a55a622d59b886714a9bb1acbR224

**Comment by abhishek-hedera** [comment]
> The changes needed:
> 
>     * [ ]  Follow hedera-protobufs changing procedure to add a new response code **MESAGE_SIZE_TOO_LARGE = 211;** to `ResponseCode.proto` file. The change needs for both `hedera-protobufs` and `hedera-protobufs-java` repo;
> 
>     * [ ]  Add a new property, `max.submitMessage.allowed.size = 1024` to hedera-node bootstrap.properties or application.properties;
> 
>     * [ ]  In TransactionHandler class's `validateTransactionPreConsensus(...)` method, before `basicPrecheck.validate(txn)` , add a section to check the message size against the value of `max.submitMessage.allowed.size` if the transaction is `ConsensusSubmitMessage`;
> 
>     * [ ]  In `SubmitMessageTransitionLogic` class's `doTransition()` method, add a section after message empty check section to check the message size;
> 
>     * [ ]  Testing:
>       
>       * [ ]  EET testing: review/modify existing EET test cases to make sure they still work given the new message size limits:
>         
>         * [ ]  AssortedHcsOps;
>         * [ ]   ChunkingSuite;
>         * [ ]  ConsensusThrottlesSuite;
>         * [ ]  SubmitMessageSuite;
>         * [ ]  ScheduleRecordSpecs
>       * [ ]  Regression testing: Review/modify existing JRS test cases to make sure they still work. These includes:
>         
>         * [ ]  MixedTransferCallAndSubmitLoadTest
>         * [ ]  SubmitMessageLoadTest;
> 
>     * [ ]  YAHCLI changes: no code change is needed here. Devops or any other users can use the `ychcli` command tools to add/modify the value of `max.submitMessage.allowed.size`. The link for how to use this command is: https://github.com/hashgraph/hedera-services/tree/01174-M-Yahcli-Documentation/test-clients/src/main/java/com/hedera/services/yahcli
> 
> 
> One question: do we allow the new `max.submitMessage.allowed.size` property to be changed dynamically?



> I think it would be appropriate to have the **MESSAGE_SIZE_TOO_LARGE = 214** for the new hedera-protobufs change PR. The current open pull request for scheduled transactions already references unique code 213.
> https://github.com/hashgraph/hedera-protobufs/pull/15/files#diff-64b63e3c61d8f80c7f9ad9f2ac6180bd7f87af6a55a622d59b886714a9bb1acbR224

**Comment by noshmody** [comment]
@abhishek-hedera Yes, many properties (e.g. throttles) can be set via transaction and are enforced as set, as should be the case for . **_submitMessage.maxAllowed_** should also be a property that can be configured dynamically

**Comment by ljianghedera** [comment]
@abhishek-hedera yes, changed to **214**. 
@noshmody Following the convention, I would put a `**_consensus._**` in front of the name **_submitMessage.maxAllowed_**. So it should either be **_consensus.submitMessage.maxAllowedSize_** or **_consensus.maxAllowedSize_**

**Comment by abhishek-hedera** [comment]
@donaldthibeau The check for consensus submit message size will be done by the transaction handler logic. The node can submit a consensus submit message with any size. For submitting this transaction a node + network fee would be charged. The service fee would be charged when the submit message size is limited to 1024 bytes else it would return **MESSAGE_SIZE_TOO_LARGE** error response code

**Comment by donaldthibeau** [comment]
Thanks @abhishek-hedera . Can we also create an issue in the protobuf repo to track that implementation and associated response code?
