### ISSUE TITLE
Signed state file writer attempts to resave reconnect state

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#11458]
- [logs](https://preproduction.grafana.hedera-ops.com/explore?schemaVersion=1&panes=%7B%22fl4%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Benvironment%3D%5C%22performance%5C%22,%20log_name%3D%5C%22swirlds%5C%22,%20node_id%3D%5C%220%5C%22%7D%22,%22queryType%22:%22range%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221707005579000%22,%22to%22:%221707091979000%22%7D%7D%7D&orgId=1)

In the perfnet run linked above:
- every reconnect that occurs is logged when the state is received
- about 2 minutes later, the `SignedStateFileWriter` declares that that same reconnect state is going to be written to disk
- then, the `SignedStateFileManager` logs the message:
```
SignedStateFileManager: Not saving signed state for round 271277 to disk because it has already been saved.
```

I'm not sure if this is having any performance effect or not, but it seems that there is a problem with the flow of data through the system.

**Comment by lpetrovic05** [comment]
@alittley the link you posted does not work for me. how can I get those logs?

**Comment by alittley** [comment]
@lpetrovic05 When you say "does not work", what do you mean?

This is the only source I have for these logs.

**Comment by lpetrovic05** [comment]
[link with log formatting](https://preproduction.grafana.hedera-ops.com/explore?schemaVersion=1&panes=%7B%22fl4%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Benvironment%3D%5C%22performance%5C%22,%20log_name%3D%5C%22swirlds%5C%22,%20node_id%3D%5C%220%5C%22%7D%20%7C%20json%20%7C%20line_format%20%60%7B%7B%20.body%20%7D%7D%60%22,%22queryType%22:%22range%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221707005579000%22,%22to%22:%221707091979000%22%7D%7D%7D&orgId=1)
