### ISSUE TITLE
JRS Failure: Large reconnect regression in JRS test `FCM-Migration-NewNodesFromGenesis-2.5k-8m`

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#11484]
- [data directory](http://35.247.76.217:8095/swirlds-automation/release/0.47/6N/Migration/20240209-125320-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/)

This test failed due to the `ReconnectPerformanceValidator`. Normally I've seen a "failure" of this sort be ~25 seconds, but this run shows ~50 seconds.

**Comment by edward-swirldslabs** [comment]
http://35.247.76.217:8095/swirlds-automation/release/0.46/4N/Reconnect/20240221-091256-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

This one took 21 seconds to transfer 5+GB http://35.247.76.217:8095/swirlds-automation/release/0.46/4N/Reconnect/20240221-091256-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

**Comment by poulok** [comment]
We will wait for more reproductions in order to have more data. Successive runs have nearly identical metrics to failed runs that take an order of magnitude longer. Hoping @OlegMazurov can take a look when he is available.

**Comment by poulok** [comment]
I will check with the hashgraph team to see if this has reproduced recently.

**Comment by artemananiev** [comment]
My guess at some point was that some JRS jobs, if run in parallel, may compete for compute/network/etc. resources, which results in slower reconnect times. However, this proved to be wrong:

* Concurrent JRS runs are not supported (at least, concurrent runs of the same github workflow). I don't know if they were allowed in the past, though
* Within a single run, one node may reconnect just fine (10-11 seconds), while another node reconnects 5 times slower (50 seconds. Both reconnects are running at about the same time in parallel
* In successful runs, the picture is similar: two nodes are reconnecting at the same time, and both take 10 seconds to complete

**Comment by artemananiev** [comment]
The latest failure so far: 03/08/2024, develop: http://35.247.76.217:8095/swirlds-automation/develop/6N/Migration/20240308-082228-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/ - reconnect wasn't insanely slow (50s), but still about 2 times slower than usual / expected (20s)

**Comment by poulok** [comment]
This test is covered by other, more stable tests so it is being deleted.
