### ISSUE TITLE
Investigate increased memory usage

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#11538]
In one of the latest longevity test runs, we observed an increased direct memory footprint. We need to investigate, the cause, if this is expected, and eventually fix it.

![Image](https://github.com/hashgraph/hedera-services/assets/3652866/00d1646d-bdb3-4d19-af3b-0983bd0ba193)

**Comment by tomzhenghedera** [comment]
See latest update in[ Test issue 438](https://github.com/hashgraph/hedera-testing/issues/438)

**Comment by netopyr** [comment]
The increased memory usage can be attributed to the increased maximum entity count.
