### ISSUE TITLE
nodeAccountID for scheduled transaction 

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1153]
Mirror node found the `nodeAccountID` is missing from scheduled transaction. Here is the slack link that captures this issue https://hedera-hashgraph.slack.com/archives/GAE009Y5D/p1615218753107300.

The scheduled transaction design document doesn't mention how to handle the `nodeAccountID` for scheduled transaction at all. So here are two options:

1. We add the `nodeAccountID` into the transaction record as normal transactions. This will need us to decide which node account to use to fill this field: the one submitted the outer `ScheduledCreate` transaction or something else;
2. Or in the documentation to mention that this field will be empty for scheduled transaction and for the downstream application to pick some default node accountID as its value;

We need quick action on this issue.

**Comment by lbaird** [comment]
The field should be empty. So do number 2.  This field is supposed to represent the node that the user chose to submit a transaction to, which then put it into an event and gossiped it out for consensus calculations.

But the inner transaction by itself was NOT given to a node, nor put into an event, nor gossiped out. All of that happened to the outer transaction, but never happened to the inner transaction. So it should remain empty for the inner transaction.

________________________________
