### ISSUE TITLE
State size of reconnected node differs

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#11539]
During one of our tests, we observed that the state size of a reconnected node differed substantially from the state size of other nodes. This needs to be fixed.

![Image](https://github.com/hashgraph/hedera-services/assets/3652866/852dd8d6-9294-4745-b772-34203336b232)

**Comment by tomzhenghedera** [comment]
See latest update in[ Test issue 438](https://github.com/hashgraph/hedera-testing/issues/438)
