### ISSUE TITLE
Reloading saved state failed to preserve accounts

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#11549]
Further details can be found in the test report: https://github.com/hashgraph/hedera-testing/issues/432

**Comment by tomzhenghedera** [comment]
see latest update in[ Test issue 432](https://github.com/hashgraph/hedera-testing/issues/432#issuecomment-1975807803)

**Comment by tomzhenghedera** [comment]
latest develop and release/0.48 builds don't have the issue any more, so this ticket could be closed.
