### ISSUE TITLE
Document the Gradle build configuration

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/hedera-services#11568]
## Description

The Gradle build logic needs to be documented including:

- The `build-logic` folder
- Project/module naming standards
- Use of the GradleX tooling
- Available custom tasks

**Comment by jjohannes** [comment]
As part of this (or split-out into separate issue): Use unified naming and structure in **all** repositories 
- https://github.com/hashgraph/hedera-services
- https://github.com/hashgraph/pbj
- https://github.com/hashgraph/hedera-sdk-java
- ...

For example:
- Use `gradle/plugins` as "build logic" folder everywhere
- Use `com.hedera.gradlebuild...` as namespace for all convention plugin
- Use similar naming for plugins that do similar things in the different repos
- Use the **exact** same names for convention plugins that do **exactly** the same in different repos (later we could think about sharing the logic between repos)

**Comment by jjohannes** [comment]
**Start with the _user_ documentation**

As part of this, move the following to `docs` folder in root, update where appropriate. Make sure we have a full "how and what to use Gradle for in daily development" guide.

- branch-naming-conventions
- docker-quickstart
- gradle-quickstart
- hedera-java-style-guide
- intellij-quickstart
- maintainers-guide

**Comment by jjohannes** [comment]
I plan to document the Gradle setup itself in the README of the new repository we'll create for the Gradle setup as part of #14255

**Comment by jjohannes** [comment]
Follow up work: https://github.com/hiero-ledger/hiero-gradle-conventions/issues/6
