### ISSUE TITLE
Remove support for Sonar and SonarCloud

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/hedera-services#11574]
## Description

Due to the single threaded nature of SonarScan and the size of our codebase, the sonar plugin takes more than 5 hours to perform a scan. This is untenable and as such SonarCloud has been deprecated and the CI pipelines have stopped executing SonarScan reports. 

We need to remove the SonarScan plugin and SonarCloud configuration from the Gradle build and clean up any residue present in the CI workflows.

**Comment by JeffreyDallas** [comment]
@jjohannes I am looking into this per Nathan's suggestion.
