### ISSUE TITLE
Self ISS during reconnect

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#11582]
While we performed a reconnect in one of our tests, the node encountered a self ISS. More details can be found here: https://github.com/hashgraph/hedera-testing/issues/434

**Comment by tomzhenghedera** [comment]
see latest update in [Test issue 438](https://github.com/hashgraph/hedera-testing/issues/438#issuecomment-1976065772)

**Comment by tomzhenghedera** [comment]
auto-reconnect regressed with latest build, see update in [test issue 434](https://github.com/hashgraph/hedera-testing/issues/434#issuecomment-1986951352)

**Comment by tomzhenghedera** [comment]
With the latest **fix-entityid-issue** branch build, the auto-reconnect Self-ISS and node restart Self-ISS didn't not show and can be considered the fix worked.  This ticket could be closed whence it's merged.
