### ISSUE TITLE
Add clients for performance test with Queries

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1158]
**Summary**
Create clients for different types of queries and ,measure the performance. Later after implementing #1036 test the performance with the throttles added.

1. ANSWER_ONLY
2. ANSWER_STATE_PROOF
3. COST_ANSWER
4. COST_ANSWER_STATE_PROOF

**Comment by ljianghedera** [comment]
Summary of what to do with this issue:

1. First phase for Query rate (QPS) only. Create one or multiple query mixes to pump to server and get the query response code, **NO** validation:

   - [ ] Current state file has 1M crypto account, 1M topic, 100 token and 1.2 M token association, 1000 scheduled transaction. Will use this state file to construct query mixes for accounts (GetAccountInfo, getAccountBalance, GetAccountRecords, etc.), consensus (getTopicInfo), tokens (getTokenInfo), schedule (getScheduleInfo). The query traffic will be created using UmbrellaRedux. With config property file, the ration of each query type can be controlled;
   - [ ] May need to add/enhance existing query operations if necessary;
   - [ ] Enhance the state file to have files, smart contracts; then add the queries for file (getFileContent, getFileInfo), contract (getContractIfno, contractCallLocal, getBySolidityID, getTxRecordByContractID);

2. Second phase : query + validate query results, such as validate account's hbar balance, token balances, file contents, topic's message sequence number, expirationTime, etc. 
The steps to do so:
   - [ ] 1. Restore the state file. The entities included in the state file are queryable, but not verifiable;
   - [ ] 2. Before running query mixes, run random transactions  to create reasonable amount of accounts, topics, tokens/token associations, files, smart contracts, scheduled transactions and save these information into client's registry. These information will be used to validate query results in next phase's query and validation;
   - [ ] 3. Create query mixes to query and verify the query results of entities created in previous step;

**Comment by abhishek-hedera** [comment]
With the current test regression results for queries, the stats displayed are for transactions and do not take into account the stats for queries. Some queries have fees while others could be free of charge and thus are not the accurate display of QPS. As query is processed only by a single node to which that query was submitted to, each node should be able to produce the stats for all the queries that it received which could later be assimilated to check the query stats for all nodes in the network.

**Comment by ljianghedera** [comment]
Some profiling results: https://hedera-hashgraph.slack.com/archives/D01TLKEPBT2/p1617769911000400

On server node side, 
1. Wwhen no traffic, memory usage reaches ~32 GB at initial loading. After that it reaches ~16GB. GC occurs ~2 1/2 minutes; CPU load is ~22%;
2. When the traffic is 2000 QPS (40x50, getAcctInfo), the memory usage is reaching 104GB. The GC triggered every ~2 minutes . CPU load is around 35%;
3. When traffic reach 3600 QPS (60x60, getAcctInfo), the memory usage is reaching 104GB. The GC triggered every ~ 70 seconds . CPU load is around 38%;

On client node side:
3. On client side, when no traffic, the memory usage reaches 0.21GB. GC no particular pattern. CPU load is ~ 1%;
4. When traffic is heavy (40 tps x 50 threads), memory usage is ~0.8GB; no particular GC pattern; CPU load is ~ 95 %;

**Comment by ljianghedera** [comment]
How to upload and present the jprofiler saved snapshot results ?

**Comment by abhishek-hedera** [comment]
For GetTokenInfo, the average live memory used for servers ranged between 5.3 GB - 6.7 GB for 15K QPS.
For clients with 8GB RAM and 4 CPU, the average memory usage remained ~0.5 GB

**Comment by Neeharika-Sompalli** [comment]
> How to upload and present the jprofiler saved snapshot results ?

@ljianghedera  You can take screenshot of the important results and post to the issue
