### ISSUE TITLE
State proof groundwork

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#117]
**Summary of the issue**
The Platform's technical roadmap includes _state proofs_. A state proof offers cryptographic certainty that one or more data elements belonged to the network state at a given point in consensus time. 

For example, I could receive a state proof that affirms, among other things, that account `0.0.1234` had a balance of `987_654_321`tℏ at consensus time `2021-04-14T20:57:22.242381Z`.

But there are conditions on **which** data elements may appear in a state proof. In particular, the data elements in a state proof are the union of the data in one or more leaves of the Merkle tree that forms Services state. 

Therefore Services must ensure the leaves of state "group" data at a granularity appropriate to the state proofs our users will  want.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
