### ISSUE TITLE
Peform profiling and performance tests on branch with some logging migrated to new framework

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#11740]
We need performance data for the new logging framework compared to the log4j framework used in the consensus node today. Create a branch and either migrate some existing logging to the new framework, or add new log statements, and compare the performance of the new framework vs. the existing framework using Oleg's benchmarks.

**Comment by timo0** [comment]
![Image](https://github.com/hashgraph/hedera-services/assets/1241026/fa09c406-9b22-4868-be4b-81ceb0cef5bb)
![Image](https://github.com/hashgraph/hedera-services/assets/1241026/8b66c785-cb98-457b-b59d-f238e39b779a)

Our performance is now on pair with the current slf4j logging
