### ISSUE TITLE
Add dependency from platform-core to protobufs

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#11764]
The module `com.swirlds.platform.core` needs to have a transitive dependency on `com.hedera.node.hapi` in order to start using protobufs for events and transactions. All apps should also get this dependency via the platform. The platform and apps should also be able to use PBJ via this dependency.

**Comment by poulok** [comment]
@lpetrovic05, @nathanklick merged a PR from @jjohannes that fixed the problem you ran into when you tried to add the dependency. You should be able to do it now.

**Comment by lpetrovic05** [comment]
> @lpetrovic05, @nathanklick merged a PR from @jjohannes that fixed the problem you ran into when you tried to add the dependency. You should be able to do it now.

Works now, thank you
