### ISSUE TITLE
Introduce PBJ schema for singletons, queues and KV storage

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#11774]
With the migration to PBJ (see #5592), all the data is represented by `protobuf objects. However, the Merkle tree itself is not serialized using the `protobuf` protocol.

This task is about changing that. After it's complete, the whole Hedera state can be considered as `protobuf` data.

**Comment by imalygin** [comment]
@artemananiev 

If you already have a ticket for this, feel free to close this one.

**Comment by poulok** [comment]
Closing, since it is not needed after the Virtual Mega Map effort.
