### ISSUE TITLE
Add NetworkService query to return the midnight rates set

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1179]
**Summary**
As a network operator, I want to know the bounds within which account `0.0.57` can adjust the exchange rate.

These bounds are determined by,
1. The "midnight rate set"; that is, the rate set that was active at midnight UTC of the current day.
2. A maximum percent change from the midnight rates that `0.0.57` is allowed to make.

But I don't have any easy way to compute these bounds. 

**Possible resolution**
Provide a new `getAllowedExchangeRateBounds` query under the `NetworkService` gRPC service to return the minimum and maximum rates that `0.0.57` is allowed to set.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
