### ISSUE TITLE
Inconsistent behavior when contract call is invoked via interface between long zero address and EVM address

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#11804]
### Description

The behavior when calling a function on a deployed contract via an interface which acts on the address of the contract is inconsistent when given the long zero address vs the EVM address.  If given the EVM address the call succeeds whereas it fails when given the long zero address.

Investigate whether this is intended behavior and if so then create documentation so that developers are not surprised.  If this is not intended behavior then fix the issue.

### Steps to reproduce

given these contracts
```
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24 <0.9.0;

import {IMission} from "./IMission.sol";

contract Mission is IMission {
    struct MissionParticipation {
        uint256 endOfMission;
    }

    mapping(address => MissionParticipation) private missionParticipants;

    function enterMission() external{
        missionParticipants[msg.sender] = MissionParticipation (
            100
        );
    }

    function isParticipant(
        address _wallet
    ) external view returns (bool _isParticipant) {
        return missionParticipants[_wallet].endOfMission != 0;
    }
}
```
and
```
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24 <0.9.0;

import {IMission} from "./IMission.sol";

contract BoostManager {
    modifier onlyActivemission(address _mission) {
        IMission mission = IMission(payable(_mission));
        require(mission.isParticipant(msg.sender), "Not active");
        _;
    }

    function boostWithGemCards(
        address _mission
    ) external onlyActivemission(_mission) returns (uint256) {
        return 500;
    }
}
```
with IMission interface defined as 

```
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.12 <0.9.0;

interface IMission {
    function isParticipant(
        address _wallet
    ) external view returns (bool _isParticipant);
}
```

- Deploy the boostmanager and mission contracts. 
- In the mission contract call EnterMission with the account that you are going to going to sign the next transaction. T
- Then in BoostManager you call boostWithGemCards and pass the Mission address 
- The call succeeds when given the EVM address but fails with the long zero address

### Hedera network

testnet

### Version

v0.47.1

### Operating system

None

**Comment by stoyanov-st** [comment]
> [@georgi-l95](https://github.com/georgi-l95) . I think this ticket came about as a result of the a conversation we had on slack [here](https://swirldslabs.slack.com/archives/C03EHC2H8CR/p1709046427793129). After looking at the contracts above, It appears to me that the contract is keeping track of the {msg.sender} address in its own storage map (`missionParticipants`). If this is the case, I can see no way that we could look up a long zero address in the ledger and convert that into an evm address from the alias (f there is one) and see if this value is in the participants map. Am I understanding the issue correctly. If not then please explain further.
> 
> If you agree that this is not expected behavior then let's close this issue.

Seems that it is indeed the {msg.sender} case that is preventing this from working with long zero addresses.
It could possibly be solved when [HIP-632](https://hips.hedera.com/hip/hip-632) is released, but cannot see a problem on our side.
