### ISSUE TITLE
Autorenew for Hedera entities

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#1180]
- [x] Create an autorenew document #1183
- https://github.com/hashgraph/hedera-services/blob/autorenew-document/docs/autorenew-feature.md
- [x] Create a HIP for entity auto renewal
- https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-16.md
- [ ] Implement the autorenew feature for accounts #1215
- [ ] Implement the autorenew feature for other entity types

**Comment by tinker-michaelj** [comment]
Auto-renew/removal for non-account entities will be done in dedicated issues.
