### ISSUE TITLE
Expected '4717234', got '4717235' - Matching field 'accountNum' Matching field 'accountID'

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#11860]
### Description

---- CryptoCreate DIFFERED (TRANSACTION_RECORD_MISMATCH) ----
Mismatched values, expected '4717234', got '4717235' - Matching field 'accountNum' Matching field 'accountID' Matching field 'receipt'  ==> expected: <4717234> but was: <4717235>

Hashscan transaction [here](https://hashscan.io/mainnet/transaction/1708336639.867840003)

Transaction Body:
```
transactionID {
  transactionValidStart {
    seconds: 1708336627
    nanos: 5137017
  }
  accountID {
    accountNum: 484746
  }
}
nodeAccountID {
  accountNum: 17
}
transactionFee: 200000000
transactionValidDuration {
  seconds: 120
}
cryptoCreateAccount {
  key {
    ed25519: "\364K\361Ms\017H\031\021\300np\371\330\225\333\211\220\227p\210\333\025\037\350b\203bh\274F5"
  }
  sendRecordThreshold: 9223372036854775807
  receiveRecordThreshold: 9223372036854775807
  autoRenewPeriod {
    seconds: 7776000
  }
}
```

### Steps to reproduce

Re-run events from round 162917799

### Hedera network

other

### Version

11805-diff-testing branch (with reverted commit 6954892)

### Operating system

macOS

**Comment by tinker-michaelj** [comment]
Fixed in `12267-neg-allow-amount-is-invalid-op`, probably earlier.
