### ISSUE TITLE
Determine if date time formatting is required

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#11869]
We need to determine how important it is to have readable date-time values in the raw log so we can invest time in improving the parser's performance.

Logging the raw long value is faster (by 10 to 12%). The drawback is that a parser is needed to examine log files.
Loki adds a timestamp to all parsed log messages, but we doubt its precision.

**Comment by mxtartaglia-sl** [comment]
We defined that the framework will provide the formatted version of the dates:
* People on the team frequently consume raw logs, it would be an operational cost to run them through a parser + some logs might be very lengthy on size to be able to do it quick.
* Jmh test needs them in human-readable format
* It would be difficult to match GC logs with app logs without running them through other tools.
* HTML viewer doesn't support large files in its current version

**Comment by mxtartaglia-sl** [comment]
Changes addressed on: [#11925](https://github.com/hashgraph/hedera-services/issues/11925)
