### ISSUE TITLE
New config annotation with "value" as default value

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#11866]
The majority of uses of the `@ConfigProperty` annotation in platform code only supply a default value and do not override the default name of the config property. As a quality of life improvement, it would be nice if we had an annotation that allows us to use the special `value` argument to instead specify the default value, which would allow us to avoid having to use the `defaultValue = ` keyword each time. For example, `@ConfigDefault("true")`.

**Comment by mxtartaglia-sl** [comment]
Duplicated of https://github.com/hashgraph/hedera-services/issues/12902
