### ISSUE TITLE
Use recommended max size hints in mod-service `VirtualMap`s

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#11867]
### Problem

We need to choose the max size hints of `VirtualMap`s to both support future growth and keep direct memory usage in a reasonable window.

### Solution

Use these max size hints:

<img width="456" alt="Screenshot 2024-03-04 at 9 02 30 AM" src="https://github.com/hashgraph/hedera-services/assets/52669800/8143747e-88de-41a7-8301-e81d89748dba">

**Comment by netopyr** [comment]
Implemented the changes as part of the branch that enables modularization
