### ISSUE TITLE
Expected 'TOKEN_NOT_ASSOCIATED_TO_ACCOUNT', got 'SPENDER_DOES_NOT_HAVE_ALLOWANCE'

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#11876]
### Description

Hashscan transaction [here](https://hashscan.io/mainnet/transaction/1708329881.355363003)

Transaction body:
```
transactionID {
  transactionValidStart {
    seconds: 1708329870
    nanos: 360112695
  }
  accountID {
    accountNum: 1104922
  }
}
nodeAccountID {
  accountNum: 29
}
transactionFee: 100000000
transactionValidDuration {
  seconds: 120
}
memo: "Swapping NFTs 0 / 1 - Altlantis"
cryptoTransfer {
  transfers {
  }
  tokenTransfers {
    token {
      tokenNum: 4110805
    }
    nftTransfers {
      senderAccountID {
        accountNum: 692756
      }
      receiverAccountID {
        accountNum: 995022
      }
      serialNumber: 359
      is_approval: true
    }
  }
}
```

### Steps to reproduce

Re-run events from round 162910486

### Additional context

Probably related to #11849 

### Hedera network

other

### Version

11852-pay-rewards-in-triggered-txn

### Operating system

macOS

**Comment by mhess-swl** [comment]
Fixed in 11852-pay-rewards-in-triggered-txn (commit f63e35)

**Comment by mhess-swl** [comment]
This bug is occurring again for the exact same transaction, as of commit `d46699da7` on the release/0.48 branch

**Comment by tinker-michaelj** [comment]
Identical streams for this interval in `12267-neg-allow-amount-is-invalid-op`
