### ISSUE TITLE
expected 'INVALID_ALLOWANCE_SPENDER_ID', got 'INVALID_ACCOUNT_ID' (round 162926130)

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#11885]
### Description

Hashscan transaction [here](https://hashscan.io/mainnet/transaction/1708343833.983966003)

Transaction Body:
```
transactionID {
  transactionValidStart {
    seconds: 1708343811
    nanos: 75933899
  }
  accountID {
    accountNum: 2189934
  }
}
nodeAccountID {
  accountNum: 24
}
transactionFee: 10000000000
transactionValidDuration {
  seconds: 120
}
cryptoApproveAllowance {
  tokenAllowances {
    tokenId {
      tokenNum: 4381245
    }
    owner {
      accountNum: 2189934
    }
    amount: 1000000
  }
}
```

### Steps to reproduce

Re-run events from round 162926130

### Additional context

Possibly related to #11876 

### Hedera network

other

### Version

11852-pay-rewards-in-triggered-txn

### Operating system

macOS

**Comment by iwsimon** [comment]
Fixing PR has been merged.
