### ISSUE TITLE
Entries at position 298596 had different transactions (round 162951120)

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#11909]
### Description

Hashscan transaction [here](https://hashscan.io/mainnet/transaction/1708364922.004758003)

Transaction Body:
```
transactionID {
  transactionValidStart {
    seconds: 1708364908
    nanos: 128293662
  }
  accountID {
    accountNum: 4367947
  }
  nonce: 1
}
contractCreateInstance {
  autoRenewPeriod {
    seconds: 7776000
  }
  auto_renew_account_id {
    accountNum: 0
  }
}
```

### Steps to reproduce

Re-run events from round 162951120

### Hedera network

other

### Version

11852-pay-rewards-in-triggered-txn (commit b94f07)

### Operating system

macOS

**Comment by tinker-michaelj** [comment]
Fixed in `release/0.48`.
