### ISSUE TITLE
Too much overhead from warming up

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#11915]
### Problem

Warming up of `VirtualMap` entries is currently implemented with multiple levels of parallelism that use uncontrollable number of threads and create too much overhead.

* CacheWarmer.warm() is called at the start of each round. It submit an asynchronous task to `ForkJoinPool.commonPool` from which all warming up unfolds.
* For each event in a round and each transaction in an event a new task (`warm()` lambda) is submitted to the same `commonPool`.
* `accountStore.warm()` is called for the transaction payer account; the rest is delegated to `TransactionDispatcher.dispatchWarmup()` -> `CryptoTransferHandler.warm()`
* `CryptoTransferHandler.warm()` creates one parallel stream for all crypto transfers to warm up accounts and another parallel stream for all token transfers to warm up NFTs, participating accounts, token relations, etc. All newly created tasks are implicitly submitted to `commonPool`.
* All `accountStore.getAccountById()` and `nftStore.get()` calls are executed by the calling `commonPool` thread. Those calls are likely to read their values from disk.
* All `warm()` calls end up in `OnDiskReadableKVState.warm()` where a new `VirtualThread` is created for each entity being warmed up.
* Under the hood, `VirtualThreads` submit continuations (tasks) to a dedicated `ForkJoinPool` of `CarrierThreads` (thread group name). There may be hundreds of those threads.

Overhead associated with doing warmups is multifaceted: 
* excessive allocation and initialization of various objects (lambdas, tasks, `VirtualThreads`,...)
* excessive creation of OS threads
* excessive thread communication (passing tasks, parking and unparking threads)

### Solution

A dedicated fixed size thread pool should be used for all warming calls. `ForkJoinPool.commonPool` should be avoided at any stage (including implicit `parallelStreams`).
We need increased disk read parallelism. Dedicated threads doing blocked reads with minimal overhead is the solution. `VirtualThreads` are of little help in this scenario. They may provide more parallelism (because it's uncontrollable) and be perceived as a faster implementation but we'll be better off, all things considered, with a firm control of resources (threads) we allocate for this subsystem.

**Comment by poulok** [comment]
Can this ticket be closed? @OlegMazurov @netopyr
