### ISSUE TITLE
Update Freeze transaction to use instant in time 

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#1192]
**Summary**
Update Freeze transaction to use instant in time

**Change Areas**

- [x] Replace Freeze Transaction Protobuf from start, end, hours and minutes with **_Timestamp_**
- [x] Update EET client to send new Instant Freeze transaction
- [x] Update YAHCLI client to use new Instant Freeze
- [x] Update tests to use Instant Freeze

**Comment by ljianghedera** [comment]
Here is the new protobuf message using *Timestamp*  for Freeze transaction bod:

```
message FreezeTransactionBody {
    Timestamp startTime = 1; // the freeze start Timestamp
    Timestamp endTime = 2; // the freeze end Timestamp
    FileID updateFile = 3; // The ID of the file needs to be updated during a freeze transaction
    bytes fileHash = 4; // The hash value of the file, used to verify file content before performing freeze and update
}
```
