### ISSUE TITLE
scheduleOpsEnablement() seems not working in customHapiSpec(...)

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1193]
(This may not be an issue. But just want to mention here to see if this needs or can be improved.)

In following code snippet:
```
		return defaultHapiSpec("RunMixedOps")
				.given(
					...
					scheduleOpsEnablement(),
					cryptoCreate("treasury")
								.hasRetryPrecheckFrom(permissiblePrechecks)
								.key(GENESIS)
				).when(...)
```
The `scheduleOpsEnablement()` works.

But in the code snippet:
```
	private HapiApiSpec jrsRestartTemplate() {
		return customHapiSpec("JrsRestartTemplate")
				.withProperties(Map.of(
						"persistentEntities.dir.path", ENTITIES_DIR
				)).given(
						scheduleOpsEnablement(),
						expectedEntitiesExist()
				).when(...)
```
The `scheduleOpsEnablement()` operation is not executed. Even wrapping it inside `withOpContext` or directly using the fileUpdate(...) doesn't help either.

Not sure whether this is caused `cusomHapiSpec` or not, but it would be nice to have consistent behaviors in similar contexts.

(Please refer to issue #1189 as well)

**Comment by tinker-michaelj** [comment]
Obsolete.
