### ISSUE TITLE
Add autoRenewAccount and autoRenewPeriod to all entities other than scheduled transactions

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#1194]
- Currently, a file is not associated with an `autoRenewAccount` (nor `autoRenewPeriod`) so a file can only be renewed by a fileUpdate transaction.
- Accounts and contracts are entities that already own/self-own an account to be able to automatically renew themselves. Would we allow another account to be responsible for an account/contract autorenew fees, i.e. also adding `autoRenewAccount` and `autoRenewPeriod` for account and contract entities? https://github.com/hashgraph/hedera-services/pull/1190#discussion_r599657540

**Comment by qnswirlds** [comment]
Please discuss and vote for also adding `autoRenewAccount` for account and contract entities. @lbaird, @donaldthibeau, @noshmody, @steven-sheehy, @tinker-michaelj. Thanks!

**Comment by steven-sheehy** [comment]
In my opinion, it should. Both to be consistent and also for use cases like custodial wallets. I mentioned to @atul-hedera and he also agreed.

**Comment by noshmody** [comment]
The Admin account for all entities (other than files) should be used to renew the entity.
For the scope of the current feature, files will remain non-renewal.
In a future release we can add Admin accounts to files which can be used for auto renewal.

**Comment by tinker-michaelj** [comment]
Duplicate of #103
