### ISSUE TITLE
Consolidate all entities expiration time

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#1197]
Most entities are using the field `expirationTime`, some (token) entities are using the field `expiry`. Consolidate all entities to use `expirationTime`.

**Comment by steven-sheehy** [comment]
I think it should be the other way around. Consolidate all to `expirationTime`. Especially since there's only one entity with `expiry`. That would be less of a breaking change.

**Comment by qnswirlds** [comment]
> I think it should be the other way around. Consolidate all to `expirationTime`. It also matches what the mirror node database is modeled as. Especially since there's only one entity with `expiry`.That would be less of a breaking change.

Thanks @steven-sheehy. I fixed the description.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
