### ISSUE TITLE
SCHEDULES_BY_EQUALITY_KEY should not be string key

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/hedera-services#11971]
### Description

The map in state for `SCHEDULES_BY_EQUALITY_KEY` should not by keyed by String. String just seems odd. Talking with Joseph it should be a hash, in which case it should be Bytes not String.

Also the migration code seems wrong as it is converting Long to String and storing that in there which will never work.
```
                schedulesByEquality.put(
                        ProtoString.newBuilder()
                                .value(String.valueOf(scheduleEqualityVirtualKey.getKeyAsLong()))
                                .build(),
                        ScheduleList.newBuilder().schedules(schedules).build());
```

### Steps to reproduce

Problem in code

### Hedera network

other

### Version

0.0.48

### Operating system

None

**Comment by kimbor** [comment]
Closed in error. This should not be closed until relevant changes are merged to develop.
