### ISSUE TITLE
Special file (fee, exchange, app prop, api perm, address books) large file handling

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#120]
Fee and exchange rates can handle file updates where the file contents span more than 1 HAPI transaction (create/update + append transactions being required to store the entire fee/exchange rate file), whereby after the last file append the fee schedule and exchange rates are loaded on the running node.

Other special files (api properties, api permissions, etc) don't handle large files that can't be sent in a single update transaction.

All of the "special" files should handle the case where append transactions are required.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
