### ISSUE TITLE
Design: MATs initiative

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#12013]

**Comment by Nana-EC** [comment]
@attest08 still working on this?
If so should sync up with @nathanklick and @rbarkerSL for latest on pipeline details and see what work is needed here by the team

**Comment by attest08** [comment]
The analysis from QA perspective is done -> https://www.notion.so/limechain/MATs-Optimization-Proposal-Shared-7b1a9a43659e45419d424c5e5a96d511?pvs=4
