### ISSUE TITLE
HIP-540: Update protobufs

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#12157]
We should introduce a boolean flag in TokenUpdateTransaction about whether the system should check the validity of the updated key.

**Comment by petreze** [comment]
An [issue](https://github.com/hashgraph/hedera-protobufs/issues/332) was created in hedera-protobufs repo and the [PR](https://github.com/hashgraph/hedera-protobufs/pull/334) with the new field for the HIP was merged
