### ISSUE TITLE
Remove duplication : FeeScheduleDeJson

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1217]
**Summary**
Class `FeeScheduleDeJson` in `test-clients` is just a duplicate of `JsonToProtoSerde` in `hedera-node`.
Move it to `hapi-utils` or other utilities package so that it can be used in both `test-clients` and `hedera-node`

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
