### ISSUE TITLE
Use Persistent entities for ValidationScenarios

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1218]
**Summary**
Currently if during validation of network upgrades, we run `ValidationScenarios`. 
If the test fails/stops before deleting the created entities their keys will be lost and we can't delete them. 

Use persistent entities in `ValidationScenarios` test. 
These should be used in Yahcli's `CostOfEverything` suit as well.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
