### ISSUE TITLE
[re] migrate nightly perf test workflow to new network

### ISSUE THREAD

**Issue by tomzhenghedera** [hashgraph/hedera-services#12193]
The nightly workflow needs to be updated moving to new network.

**Comment by rbarkerSL** [comment]
@tomzhenghedera is this still a required ticket? If so can we get a little more information behind the story?

**Comment by tomzhenghedera** [comment]
this I believe was the task set up the workflow to run nightly on engnet1 which had been completed and currently active.  We could close this ticket.
