### ISSUE TITLE
SignatureVerifierImpl.verify() should not call verifyAsync()

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#12237]
### Problem

`SignatureVerifierImpl.verify()` is invoked in threads handling client API calls to verify the payer signature (IngestChecker.verifyPayerSignature()). The actual verification is delegated to a separate thread pool via `Cryptography.verifyAsync()`. The overhead of passing the call from a larger pool to a smaller pool and then waiting for the result in `SignatureVerificationFutureImpl.get()` is not justified. Client thread throughput drops significantly.
A similar case can be made for `PreHandleWorkflowImpl.verifySignatures()`.

### Solution

Verify signatures synchronously in the calling thread.

**Comment by poulok** [comment]
Related to https://github.com/hashgraph/hedera-services/issues/11313?

**Comment by OlegMazurov** [comment]
@poulok Yes, though this ticket covers both initial verification in client threads and pre-handle.

**Comment by OlegMazurov** [comment]
This issue is very likely to be responsible for slow nodes during longevity tests against v0.49 in `perf1`.
High contention is observed in pre-handle threads (in a `ForkJoinPool`) when trying to submit tasks via `Cryptography.verifyAsync()`. The `preHandleMicros` metric is an order of magnitude higher for slow nodes. 
Comparing a healthy node (`node12` 🔴) to a slow node (`node23` 🟣)
![Screenshot 2024-04-17 at 5 22 18 PM](https://github.com/hashgraph/hedera-services/assets/23125269/0fc7e7f6-c00b-4d1b-9c81-748308e6221a)
