### ISSUE TITLE
Standardized properties cannot override non-standardized properties

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#1224]
https://github.com/hashgraph/hedera-services/blob/2ff1e352b4e42fbbabb8edff42ad5de60e8d3518/hedera-node/src/main/java/com/hedera/services/context/properties/ScreenedSysFileProps.java#L54-L74

How to reproduce:
- Start a genesis network with a non-standardized property, for example with `minimumAutoRenewDuration=20`
- Update the special file `APP_PROPERTIES` with the corresponding standardized property, which is `ledger.autoRenewPeriod.minDuration=10`
- Create an account with `autoRenewSecs(10)`, which satisfies the updated settings
- Receive `failed Wrong precheck status! Expected OK, actual AUTORENEW_DURATION_NOT_IN_RANGE!`

**Comment by tinker-michaelj** [comment]
In your `FileUpdate` of `0.0.121`, did you also _remove_ the legacy `minimumAutoRenewDuration=20` setting?

If both the legacy and the standardized properties are present, there's no guarantee which will end up being applied.

**Comment by qnswirlds** [comment]
It's not worth fixing this issue. Just follow @tinker-michaelj's suggestion to also remove the legacy property when updating file `0.0.121`. Closing this issue.
