### ISSUE TITLE
Minting 0.25 Token Value Its Throwing Error

### ISSUE THREAD

**Issue by devnasim** [hashgraph/hedera-services#1226]
**Environment:**
- OS: [e.g. Macos]
- JavaScript SDK
- Token Id - 0.0.478419  TESTNET

`err PrecheckStatusError: transaction 0.0.130962@1617398334.770918947 failed precheck with status INVALID_TOKEN_MINT_AMOUNT
    at new PrecheckStatusError (/Users/nasimakhtar/Projects/kravein-pay/kravein-pay-js/node_modules/@hashgraph/sdk/lib/PrecheckStatusError.cjs:23:5)
    at TokenMintTransaction.execute (/Users/nasimakhtar/Projects/kravein-pay/kravein-pay-js/node_modules/@hashgraph/sdk/lib/Executable.cjs:267:15)`

**Comment by tinker-michaelj** [comment]
Hi @devnasim, the only precheck enforced on a `TokenMint` amount is that it must be greater than 0.

If you are trying to mint a decimal (i.e. `0.25`) amount of tokens, it's possible the SDK is casting this to an integral type and rounding down to zero.

**Comment by donaldthibeau** [comment]
@devnasim you need to specify the lowest denominated form without decimals for interaction with the Hedera Token service.

**Comment by donaldthibeau** [comment]
Closing out given this is expected behavior.
