### ISSUE TITLE
Expected '-9280411', got '-18567739' - Matching field 'amount' Matching field 'transferList' (round 165085473)

### ISSUE THREAD

**Issue by povolev15** [hashgraph/hedera-services#12283]
Description
Hashscan transaction [here](https://hashscan.io/mainnet/transaction/1710280092.503043203)

For body,
transactionID {
  transactionValidStart {
    seconds: 1710280092
    nanos: 503043203
  }
  accountID {
    accountNum: 1122349
  }
  scheduled: true
}
transactionFee: 50000000
memo: "Sent via HashPack Secure Trade"
cryptoTransfer {
  transfers {
    accountAmounts {
      accountID {
        accountNum: 819585
      }
      amount: -100000
    }
    accountAmounts {
      accountID {
        accountNum: 1122349
      }
      amount: 100000
    }
  }
  tokenTransfers {
    token {
      tokenNum: 1350444
    }
    nftTransfers {
      senderAccountID {
        accountNum: 1122349
      }
      receiverAccountID {
        accountNum: 819585
      }
      serialNumber: 1131
    }
  }
}
➡️  Expected Record receipt {
  status: SUCCESS
  exchangeRate {
    currentRate {
      hbarEquiv: 30000
      centEquiv: 396303
      expirationTime {
        seconds: 1710280800
      }
    }
    nextRate {
      hbarEquiv: 30000
      centEquiv: 390818
      expirationTime {
        seconds: 1710284400
      }
    }
  }
}
transactionHash: "\276\226\225ay\316\225BP\230o\346\notC\016\226\352\250o\341\252\357x\262\250\373G\367\b\274\377\313\336\372\340\360C\317\2618\363\"\300\017\240l"
consensusTimestamp {
  seconds: 1710280136
  nanos: 572337007
}
transactionID {
  transactionValidStart {
    seconds: 1710280092
    nanos: 503043203
  }
  accountID {
    accountNum: 1122349
  }
  scheduled: true
}
memo: "Sent via HashPack Secure Trade"
transactionFee: 69175
transferList {
  accountAmounts {
    accountID {
      accountNum: 98
    }
    amount: 62258
  }
  accountAmounts {
    accountID {
      accountNum: 800
    }
    amount: -9280411
  }
  accountAmounts {
    accountID {
      accountNum: 819585
    }
    amount: -169175
  }
  accountAmounts {
    accountID {
      accountNum: 999404
    }
    amount: 1000
  }
  accountAmounts {
    accountID {
      accountNum: 1122349
    }
    amount: 93000
  }
  accountAmounts {
    accountID {
      accountNum: 1332229
    }
    amount: 9293328
  }
}
tokenTransferLists {
  token {
    tokenNum: 1350444
  }
  nftTransfers {
    senderAccountID {
      accountNum: 1122349
    }
    receiverAccountID {
      accountNum: 819585
    }
    serialNumber: 1131
  }
}
scheduleRef {
  scheduleNum: 4957167
}
assessed_custom_fees {
  amount: 6000
  fee_collector_account_id {
    accountNum: 1332229
  }
  effective_payer_account_id {
    accountNum: 1122349
  }
}
assessed_custom_fees {
  amount: 1000
  fee_collector_account_id {
    accountNum: 999404
  }
  effective_payer_account_id {
    accountNum: 1122349
  }
}
paid_staking_rewards {
  accountID {
    accountNum: 1332229
  }
  amount: 9287328
}
 but was receipt {
  status: SUCCESS
  exchangeRate {
    currentRate {
      hbarEquiv: 30000
      centEquiv: 396303
      expirationTime {
        seconds: 1710280800
      }
    }
    nextRate {
      hbarEquiv: 30000
      centEquiv: 390818
      expirationTime {
        seconds: 1710284400
      }
    }
  }
}
transactionHash: "\276\226\225ay\316\225BP\230o\346\notC\016\226\352\250o\341\252\357x\262\250\373G\367\b\274\377\313\336\372\340\360C\317\2618\363\"\300\017\240l"
consensusTimestamp {
  seconds: 1710280136
  nanos: 572337007
}
transactionID {
  transactionValidStart {
    seconds: 1710280092
    nanos: 503043203
  }
  accountID {
    accountNum: 1122349
  }
  scheduled: true
}
memo: "Sent via HashPack Secure Trade"
transactionFee: 69175
transferList {
  accountAmounts {
    accountID {
      accountNum: 98
    }
    amount: 62258
  }
  accountAmounts {
    accountID {
      accountNum: 800
    }
    amount: -18567739
  }
  accountAmounts {
    accountID {
      accountNum: 819585
    }
    amount: -169175
  }
  accountAmounts {
    accountID {
      accountNum: 999404
    }
    amount: 1000
  }
  accountAmounts {
    accountID {
      accountNum: 1122349
    }
    amount: 93000
  }
  accountAmounts {
    accountID {
      accountNum: 1332229
    }
    amount: 18580656
  }
}
tokenTransferLists {
  token {
    tokenNum: 1350444
  }
  nftTransfers {
    senderAccountID {
      accountNum: 1122349
    }
    receiverAccountID {
      accountNum: 819585
    }
    serialNumber: 1131
  }
}
scheduleRef {
  scheduleNum: 4957167
}
assessed_custom_fees {
  amount: 6000
  fee_collector_account_id {
    accountNum: 1332229
  }
  effective_payer_account_id {
    accountNum: 1122349
  }
}
assessed_custom_fees {
  amount: 1000
  fee_collector_account_id {
    accountNum: 999404
  }
  effective_payer_account_id {
    accountNum: 1122349
  }
}
paid_staking_rewards {
  accountID {
    accountNum: 1332229
  }
  amount: 9287328
}

Steps to reproduce
Rerun events from round 165085473

Additional context
No response

Hedera network
other

Version
release/0.48 (commit https://github.com/hashgraph/hedera-services/commit/a393e249728e749aab3c1f0ab791e96d7066ed41)

Operating system
macOS

**Comment by kimbor** [comment]
Also occurring on round 162902128

**Comment by povolev15** [comment]
no issue anymore
