### ISSUE TITLE
Investigate memory leak after migration

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#12281]
Our tests show that we keep the old data after migration. This needs to be investigated and fixed.

**Comment by mhess-swl** [comment]
The most likely suspect identified is `MerkleHederaState#copyAndReleaseVirtualMap`:

```
        public void copyAndReleaseVirtualMap(@NonNull final String stateKey) {
            final var md = stateMetadata.get(stateKey);
            final VirtualMap<?, ?> virtualMap = (VirtualMap<?, ?>) findNode(md);
            final var mutableCopy = virtualMap.copy();
            setChild(findNodeIndex(serviceName, stateKey), mutableCopy);
            kvInstances.put(stateKey, createReadableKVState(md, mutableCopy));
        }
```

The virtual map is copied, but not released.

**Comment by mhess-swl** [comment]
Looking at the number of virtual maps in memory prior to and following the "big-bang migration" of services from mono -> modular format, there is a significant increase of unreleased virtual maps (from 5 -> 90+). I'm currently working through all the places that these maps need to be released.

**Comment by mhess-swl** [comment]
PR to develop [here](https://github.com/hashgraph/hedera-services/pull/12429)
