### ISSUE TITLE
Investigate if a new server socket needs to be created when adding/removing nodes

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#12299]

**Comment by kfa-aguda** [comment]
Notes:

Ultimately, it appears the JSSE is designed to make the truststore and keystore static repositories but it *appears* we do not need to create new server socket(s). 

In other to update the truststore with the dynamically updating peer signing certificates, the following must happen, in that order:
- the trust manager factory will need to be re-initialized with the updated keystore
- the ssl context will need to be re-initialized with the updated trust manager factory
- the JVM's default context be re-set to this re-initialized SSL context 
- existing server socket(previously obtained from this SSLContext) should now be ready to handshake with the updated peers (as they will re-use the re-initialized context)

These are gathered from just reading the related classes. Needs verification and testing.

**Comment by lpetrovic05** [comment]
> Notes:
> 
> Ultimately, it appears the JSSE is designed to make the truststore and keystore static repositories but it _appears_ we do not need to create new server socket(s).
> 
> In other to update the truststore with the dynamically updating peer signing certificates, the following must happen, in that order:
> 
> * the trust manager factory will need to be re-initialized with the updated keystore
> * the ssl context will need to be re-initialized with the updated trust manager factory
> * the JVM's default context be re-set to this re-initialized SSL context
> * existing server socket(previously obtained from this SSLContext) should now be ready to handshake with the updated peers (as they will re-use the re-initialized context)
> 
> These are gathered from just reading the related classes. Needs verification and testing.

Nice! The next step for this then will be to create a unit test that does it.
