### ISSUE TITLE
(3/18 13:15) Expected 'ACCOUNT_AMOUNT_TRANSFERS_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON', got 'TOKEN_NOT_ASSOCIATED_TO_ACCOUNT'

### ISSUE THREAD

**Issue by kimbor** [hashgraph/hedera-services#12319]
### Description

[Tx in hashscan](https://hashscan.io/mainnet/transaction/1710767832.323640257)

---- CryptoTransfer DIFFERED (TRANSACTION_RECORD_MISMATCH) ----
Mismatched values, expected 'ACCOUNT_AMOUNT_TRANSFERS_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON', got 'TOKEN_NOT_ASSOCIATED_TO_ACCOUNT' - Matching field 'status' Matching field 'receipt'  ==> expected: <ACCOUNT_AMOUNT_TRANSFERS_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON> but was: <TOKEN_NOT_ASSOCIATED_TO_ACCOUNT>

For body,
transactionID {
  transactionValidStart {
    seconds: 1710767822
    nanos: 215117509
  }
  accountID {
    accountNum: 5026534
  }
}
nodeAccountID {
  accountNum: 4
}
transactionFee: 200000000
transactionValidDuration {
  seconds: 120
}
cryptoTransfer {
  transfers {
  }
  tokenTransfers {
    token {
      tokenNum: 2021338
    }
    transfers {
      accountID {
        accountNum: 3925906
      }
      amount: 1
    }
    transfers {
      accountID {
        accountNum: 5026534
      }
      amount: -1
    }
  }
}
➡️  Expected Receipt status: ACCOUNT_AMOUNT_TRANSFERS_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON
exchangeRate {
  currentRate {
    hbarEquiv: 30000
    centEquiv: 340485
    expirationTime {
      seconds: 1710770400
    }
  }
  nextRate {
    hbarEquiv: 30000
    centEquiv: 339682
    expirationTime {
      seconds: 1710774000
    }
  }
}
 but was status: TOKEN_NOT_ASSOCIATED_TO_ACCOUNT
exchangeRate {
  currentRate {
    hbarEquiv: 30000
    centEquiv: 340485
    expirationTime {
      seconds: 1710770400
    }
  }
  nextRate {
    hbarEquiv: 30000
    centEquiv: 339682
    expirationTime {
      seconds: 1710774000
    }
  }
}

### Steps to reproduce

Run 15 minutes of diff testing starting with round 165629090

### Hedera network

other

### Version

0.48

### Operating system

None

**Comment by kimbor** [comment]
Similar difference exists for round 165627070

**Comment by netopyr** [comment]
Error check ordering issue

**Comment by kimbor** [comment]
Will not fix
