### ISSUE TITLE
Add MerkleLeaf test helper for automating serialize/deserialize unit tests w/ all combinations of fields set

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1235]
**Summary**
As a Hedera Services developer, I want to automatically do "live-fire" serialization/deserialization tests for each new `MerkleLeaf` implementation; in particular, I want a helper to instantiate my new `MerkleLeaf` with all combinations of fields being either (A) unset or (B) set to default values.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
