### ISSUE TITLE
remove `contracts.evm.version.dynamic` property

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#12462]
### Problem

The `contracts.evm.version.dynamic` is not implemented in the modularized code.

### Solution

Implement a way to have dagger provided the correct EVM version update configuration update.

**Comment by lukelee-sl** [comment]
After examining how this configuration is used in mono service, it seems that this is used _only_ by the evm module to allow for loading different versions of the evm for eth_call and eth_estimateGas.  We should keep this config around until it is clear that when mirror node consume the smart contract module, it is no longer needed.

**Comment by david-bakin-sl** [comment]
Maybe it could always be `true` - why not?  What does `false` protect us from?  What does `true` cost us in, say, performance?  Then if always true: we don't need it.

**Comment by lukelee-sl** [comment]
Verified with Ivan that this seems to be no longer needed from an evm module perspective.
