### ISSUE TITLE
TPS Mismatch for Misc-Basic-1-20m, Misc-Update-1-5m

### ISSUE THREAD

**Issue by abhishek-hedera** [hashgraph/hedera-services#1249]
**Summary of the defect**
Max TPS inside `Misc-Basic-1-20m` is 14 but the name says it is 1, similar for Misc-Update-1-5m, TPS is 4 but the name has 1 TPS.
Slack Link - https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618206775268900
https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618290745277400
Summary Link - https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618206815021100

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by abhishek-hedera** [comment]
Today `Misc-Baisc-1-20m `it had a TPS of 12 instead of 14
Slack Link - https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618465991297800
Summary Link - https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618466029024600

**Comment by anighanta** [comment]
This is the test config for `Misc-Basic-1-20m`

```
{
  "name": "Misc-Basic-1-20m",
  "description": "SuiteRunner-AllSuites-JRS",
  "parentList": [
	"configs/services/default/standard-services-configs.json",
	"configs/services/default/standard-services-settings.json",
	"configs/services/default/standard-services-validators.json"
  ],
  "duration": 1200,
  "hederaServicesConfig": {
	"testSuites": [
	  "ControlAccountsExemptForUpdates",
	  "UmbrellaRedux",
	  "TopicCreateSpecs",
	  "SubmitMessageSpecs",
	  "TopicUpdateSpecs",
	  "HCSTopicFragmentationSuite",
	  "TopicGetInfoSpecs",
	  "CryptoCreateSuite",
	  "CryptoRecordSanityChecks",
	  "SignedTransactionBytesRecordsSuite",
	  "SuperusersAreNeverThrottled",
	  "FileRecordSanityChecks",
	  "VersionInfoSpec"
	],
	"fixedNode": true,
	"payerId" : 2
  }
}
```

Just renaming the test to `Misc-Basic-12-20m` would be sufficient I think. and similarly `Misc-Update-1-5m` to `Misc-Update-5-5m` by looking at the results as we cannot control the TPS on these tests
