### ISSUE TITLE
 Crypto-Restart-RecordStreamV5-1.5k-10m : Exception in swirlds.log

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1254]
**Summary of the defect**
ErrorValidator failed on Node 2.
Exception in swirlds.log : 
```
2021-04-13 06:33:42.872 56       INFO  EXCEPTION        <jvm-pause-detector-thread> Browser: JVMPauseDetectorThread detected JVM paused for 1313 ms
```

Slack Link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618296218279900
Summary Link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618297081021900

**Comment by Neeharika-Sompalli** [comment]
This issue with `JVMPauseDetectorThread` is being profiled by Cesar in platform. Once there is a solution in platform we could adapt it to the existing tests

**Comment by anighanta** [comment]
Closing this issue, tracking it here https://github.com/hashgraph/hedera-services/issues/1264
