### ISSUE TITLE
File-Recovery-EvSave15sTrunc-2-7m : Exception in swirlds.log

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1256]
**Summary of the defect**
ErrorValidator failed on Node 0.
Exception in swirlds.log :

```
2021-04-13 09:27:53.685 82       INFO  EXCEPTION        <jvm-pause-detector-thread> Browser: JVMPauseDetectorThread detected JVM paused for 2839 ms
```

Slack Link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618306135284100
Summary Link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618306173022100

**Comment by Neeharika-Sompalli** [comment]
This issue related to JVMPauseDetectorThread is being profiled by Cesar in platform. Once there is a solution in platform we could adapt it to the existing tests

**Comment by anighanta** [comment]
Closing this issue, tracking it here https://github.com/hashgraph/hedera-services/issues/1264
