### ISSUE TITLE
Upgrade to JDK 16

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#1258]
**Summary**
Until the next LTS release of Java, we need to keep pace with the interim releases. The latest interim release is JDK 16. The next LTS should be JDK 17 due later this year.

**Comment by nathanklick** [comment]
@rbair23 Technically this is dictated by the Swirlds Platform SDK requirements. 

As I mentioned to @tinker-michaelj earlier, we plan on upgrading the Platform SDK to OpenJDK 16 however that timeline has yet to be determined. Until the Platform SDK has been tested against OpenJDK 16, Hedera should continue deploying and testing against OpenJDK 12.0.2 which is the currently the only supported JDK.
