### ISSUE TITLE
MixedOps-Restart-Performance-10k-31m : Exception in Swirlds Log

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1262]
**Summary of the defect**
ErrorValidator failed on Node 16.
Exception in swirlds.log :
```
2021-04-14 02:55:09.358 39       INFO  EXCEPTION        <jvm-pause-detector-thread> Browser: JVMPauseDetectorThread detected JVM paused for 2128 ms
```

Slack Link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618369394285600
Summary Link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618369446023200

**Comment by Neeharika-Sompalli** [comment]
@anighanta  Issue with `JVMPauseDetectorThread` can occur on many tests. This will be resolved once Cesar has an idea in platform. In my opinion, It should be one single issue and is not related to the test itself.

**Comment by anighanta** [comment]
Closing this issue, tracking it here https://github.com/hashgraph/hedera-services/issues/1264
