### ISSUE TITLE
Analyze and improve performance of pull / leaves to root reconnect policy

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/hedera-services#12649]
This is a follow-up for https://github.com/hashgraph/hedera-services/issues/11889 and a pre-requisite for https://github.com/hashgraph/hedera-services/issues/12648.

The new pull-based leaves to root reconnect policy is sometimes faster than the existing push-based algorithm, but sometimes slower. To make it default, these cases when it's slower should be analyzed and fixed.

**Comment by poulok** [comment]
Covered by #12108
