### ISSUE TITLE
Create a wiring component for computing the running event hash

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#12656]
In order to run turtle tests, we need to have all things running in the wiring framework.

We are deleting the consensus event stream soon-ish, so don't want to spend effort rewriting the CES so that it's compatible with the wiring framework.

Most of what the CES does is not super important, but it currently fills the critical role of computing the running event hash. Even when the CES is gone, we still want to compute a running event hash.

Create a platform component whose job it is to compute the running event hash. The running event hash computed by the CES can be ignored. Then, when we do turtle tests, we can simply turn off the CES.

**Comment by lpetrovic05** [comment]
I really feel like the running hash should be removed together with the CES
