### ISSUE TITLE
`updateContract` can fail with `NullPointer`

### ISSUE THREAD

**Issue by 0xivanov** [hashgraph/hedera-services#12673]
### Description

There are cases where `updateContract` transaction can fail with `NullPointerException`

### Steps to reproduce

-

### Hedera network

other

### Version

0.48

### Operating system

None

**Comment by stefan-stefanooov** [comment]
Fixed in this PR.
https://github.com/hashgraph/hedera-services/pull/12578/files#diff-4c5d05b4ce327332a72500c4e5c415783a91af0b9b10563ed2cc0bbcc5bda8ee
