### ISSUE TITLE
AllProtectedFilesUpdate-Reconnect-1-12m Failures

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1267]
**Summary of the defect**
AllProtectedFilesUpdate-Reconnect-1-12m test fails with the following errors:

- [ ] ReconnectStreamValidator failed:
```java.lang.IndexOutOfBoundsException: index should be within [0, -1]
    at com.swirlds.regression.validators.StreamSigsInANode.getSigFileName(StreamSigsInANode.java:50)
```

- [ ] StatsValidator failed
```
java.io.FileNotFoundException: results/4N_1C/Reconnect/20210414-071354-GCP-Daily-Comp-Reconnect-4N-1C/AllProtectedFilesUpdate-Reconnect-1-12m/node0003/ServicesStats3.csv (No such file or directory)
```
- [ ] HAPIClientValidator FAILED
```
2021-04-14 07:16:47.722 ERROR  242  HapiApiSpec - Fees failed to initialize! Please check if server is down...
java.lang.IllegalStateException: Could not download '0.0.112' final status PLATFORM_NOT_ACTIVE
```

The main reason would be `PLATFORM_NOT_ACTIVE` as it triggers the other 2 errors to occur.

Slack Link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618385489291800
Summary Link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618388436023800

**Comment by Neeharika-Sompalli** [comment]
This is fixed and merged today morning. Passed test https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1618360190343900
