### ISSUE TITLE
HCS-Restart-Performance-Random-10k-61m : Platform Not Active error

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1268]
**Summary of the defect**
HapiClientValidator failed on Node 5 with error.
```
PLATFORM_NOT_ACTIVE
```

This further triggers :
 StreamSimpleValidator FAILED asserting that Node 0 produced different no of record steam files than other nodes.

**Comment by ljianghedera** [comment]
Was not able to reproduce the issue in local GCP run. Will keep an eye on the weekend's running and see if the problem re-appear.

**Comment by ljianghedera** [comment]
The root cause seems to be that server can't handle the TPS and one random server node may get killed prematurely.

**Comment by Neeharika-Sompalli** [comment]
If it is because server could not handle the TPS, we were able to do 10K TPS in the past. Need to investigate what has changed the performance.

**Comment by ljianghedera** [comment]
Agree, I will open another issue to track what causes the TPS to go down. For now, per Nosh's suggestion, I will lower the TPSs  (but will still keep highest possible TPSs for Crypto, HCS, HTS so to track any future possible performance deteriorations)  to let these failed perf tests to pass for monitoring purpose.
