### ISSUE TITLE
Validate and Update pureChecks(): CryptoCreateHandler

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#12714]
This handler could have the following additional pure checks:
* autoRenewPeriod: if not null, check for > -1
* shardID: if not null, check for > 0
* realmID: if not null, check for > 0
* newRealmAdminKey: if not null, check for empty list??
* memo:  verify not null (but empty string is allowed)
* maxAutomaticTokenAssociations: check for > -1
* stakedId: verify not null
        - if type is stakedAccountID, verify stakedAccountID is valid
        - if type is stakedNodeId, verify stakedNodeId is valid
* alias: verify not null   

Lastly, there may be a mismatch between the handler logic and the protobuf object. `autoRenewPeriod` is a `@Nullable` field, but the handler requires this field to be present [here](https://github.com/hashgraph/hedera-services/blob/7056eeacde38b686114b7bf253baf0a7a5c9bf7a/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java#L115). Which is correct?

**Comment by jsync-swirlds** [comment]
This goes a bit too far in pure checks.
Clarifications:
<dl><dt>autoRenewPeriod</dt><dd>This _may_ check for null (in future it should allow null). The transaction spec allows not setting this value to get the "default".</dd></dl>
<dl><dt>shardID</dt><dd>do not validate in pure checks</dd></dl>
<dl><dt>realmID</dt><dd>do not validate in pure checks</dd></dl>
<dl><dt>newRealmAdminKey</dt><dd>This _may_ check for null, but should be checked in handle if possible. This should not be used at all and is obsolete as we don't automatically create realms (the whole concept of what realm means is different from when this was introduced).</dd></dl>
<dl><dt>memo</dt><dd>This absolutely should allow null; memo is an optional field.</dd></dl>
<dl><dt>maxAutomaticTokenAssociations</dt><dd>`-1` is allowed here with the most recent HIP, even if we don't allow less than zero temporarily, it should be checked in handle.</dd></dl>
<dl><dt>stakedId</dt><dd>This is allowed to be null.  Not all accounts stake their HBAR.<br/>
These two should also be in Handle.
<ol><li>if type is stakedAccountID, verify stakedAccountID is valid</li>
<li>if type is stakedNodeId, verify stakedNodeId is valid</li></ol></dd></dl>
<dl><dt>alias</dt><dd>Alias is not always set, in fact it _usually_ shouldn't be set in this transaction. Alias is a contract ID, the result of an ethereum CREATE2 call, results from a pre-create HBAR transfer, or is generated by the system.  In the last case it's supposed to be _unset_ in state.</dd></dl>
