### ISSUE TITLE
Validations intermittently fail due to 100% CPU consumption 

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#12712]
### Description

The state validation is a time consuming procedure. To speed it up, it's was parallelized as much as possible. The downside of this parallelization is that it's not uncommon for it to consume 100% of the GitHub runner. This has unfortunate side effects - the validations may:
```
Validate State of Mainnet / Main Net node15-Dentons-167820068
The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
Validate State of Mainnet / Main Net node15-Dentons-167820068
The self-hosted runner: hedera-state-validator-linux-large-rtsjc-wzb5m lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
Validate State of Mainnet / Main Net node15-Dentons-167820068
The operation was canceled.
Validate State of Mainnet / Main Net node13-UCL-167820068
The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
Validate State of Mainnet / Main Net node13-UCL-167820068
The self-hosted runner: hedera-state-validator-linux-large-rtsjc-glnv5 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
Validate State of Mainnet / Main Net node13-UCL-167820068
The operation was canceled.
```

See an example here - https://github.com/hashgraph/hedera-state-validator/actions/runs/8628172550

@nathanklick confirmed that 100% is the reason for the failure:

<img width="966" alt="image" src="https://github.com/hashgraph/hedera-services/assets/1595361/df915a16-238e-4bcd-a1a1-f4e9ba5616ca">

The root cause of the failure is that with 100% CPU consumption the runner is not able to report that it's still alive. 

### Steps to reproduce

Run [Mainnet validation](https://github.com/hashgraph/hedera-state-validator/actions/workflows/flow-validate-states-mainnet.yaml)

### Hedera network

mainnet

### Version

v0.49

### Operating system

None

**Comment by poulok** [comment]
@Nathan, your help is needed on this ticket

**Comment by imalygin** [comment]
I had a meeting with @nathanklick , and he helped me to debug the `cgroup` configuration

**Comment by poulok** [comment]
Runners have been upgraded so that this is no longer a problem.
