### ISSUE TITLE
Crypto-Migration-Restart-Testnet-100-6m Named Incorrectly

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1273]
**Summary of the defect**
Crypto-Migration-Restart-Testnet-100-6m  test is configured to run for 10 mins but named as 6m.

**Comment by Neeharika-Sompalli** [comment]
The name is correct, but JRS should be fixed to not exceed the timing. Because of which we have warning in the test. It is related to https://github.com/hashgraph/hedera-services/issues/1222

**Comment by anighanta** [comment]
```
{
  "name":"Crypto-Migration-Restart-Testnet-100-6m",
  "description" : "Services-MigrationTest-With-Restart-Testnet-JRS",
  "parentList": [
    "configs/services/default/standard-services-configs.json",
    "configs/services/default/standard-services-settings.json",
    "configs/services/default/migration-services-settings.json",
    "configs/services/default/standard-services-validators.json",
    "configs/validators/restart-validators.json"
  ],
  "duration": 600,
  "hederaServicesConfig": {
    "ciPropsMap" : "tps=10,mins=1,threads=10",
    "testSuites": [
      "CryptoTransferLoadTest"
    ],
    "payerId": "50"
  },
...
...
```

This is the test config. Duration = 600 is 10 mins.

**Comment by Neeharika-Sompalli** [comment]
> ```
> {
>   "name":"Crypto-Migration-Restart-Testnet-100-6m",
>   "description" : "Services-MigrationTest-With-Restart-Testnet-JRS",
>   "parentList": [
>     "configs/services/default/standard-services-configs.json",
>     "configs/services/default/standard-services-settings.json",
>     "configs/services/default/migration-services-settings.json",
>     "configs/services/default/standard-services-validators.json",
>     "configs/validators/restart-validators.json"
>   ],
>   "duration": 600,
>   "hederaServicesConfig": {
>     "ciPropsMap" : "tps=10,mins=1,threads=10",
>     "testSuites": [
>       "CryptoTransferLoadTest"
>     ],
>     "payerId": "50"
>   },
> ...
> ...
> ```
> 
> This is the test config. Duration = 600 is 10 mins.

Thanks @anighanta . You are correct , I was confused with two issues
