### ISSUE TITLE
(4/9 07:45) TokenBurn ---- Mismatched values, expected '3', got '2' - Matching field 'serialNumber'  ==> expected: <3> but was: <2>

### ISSUE THREAD

**Issue by thomas-swirlds-labs** [hashgraph/hedera-services#12738]
### Description

Similar to #12600 but in Token Burn 

Hashscan transaction [here](https://hashscan.io/mainnet/transaction/1712648525.276413003)

Transaction Body:

```
transactionID {
  transactionValidStart {
    seconds: 1712648507
    nanos: 181908443
  }
  accountID {
    accountNum: 4553969
  }
}
nodeAccountID {
  accountNum: 3
}
transactionFee: 3500000000
transactionValidDuration {
  seconds: 180
}
memo: "NFTs burned via Kabila Tools"
tokenBurn {
  token {
    tokenNum: 5351322
  }
  serialNumbers: 1
  serialNumbers: 3
  serialNumbers: 5
  serialNumbers: 4
  serialNumbers: 2
}
```

### Steps to reproduce
Re-run events from round 167719758 - April 9th (07:30am)

### Additional context
Hedera network

### Version
release/0.48

### Operating system
macOS

**Comment by iwsimon** [comment]
At daily meeting today, the sequence of serialNumbers was not important if the all of serialNumbers were in the receipt which is this case.
