### ISSUE TITLE
Type 0x2 transactions missing gas params in the response

### ISSUE THREAD

**Issue by simsonraj** [hashgraph/hedera-services#12782]
### Description

the transactions response for type 0x2 transactions doesnt include maxFeePerGas & maxPriorityFeePerGas fields,  There are some inherent validations that look for `maxFeePerGas  when the transaction is Type 0x2

### Steps to reproduce

curl --location 'https://webproxy-scale-int-hedera-rpc.public.main.sand.cldev.sh/' \
--header 'Content-Type: application/json' \
--data '{
	"jsonrpc":"2.0",
	"method":"eth_getBlockByNumber",
	"params":[
		"0x2A68A8", 
		true
	],
	"id":1
}'

### Hedera network

testnet

### Version

relay/0.45.0-SNAPSHOT

### Operating system

None

**Comment by Nana-EC** [comment]
Should have been opened on the relay side given our architecture.
Will connect a ticket on that end to track the work

**Comment by quiet-node** [comment]
fixed in https://github.com/hashgraph/hedera-json-rpc-relay/issues/2404
