### ISSUE TITLE
HCS autorenew accounts should be allowed without adminKey (Should be extended to files also)

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#128]
Current functionality in 0.4 disallows setting an adminKey on a topic without there existing an adminKey on the topic.

The desired functionality is to allow there to be an autoRenewAccount on a topic whether the topic has an adminKey or not.

This change DOES NOT affect the signing requirements for create/update topic, as any change to a topic involving the autorenewAccount must have:
- the signature of the initial/postUpdate autoRenewAccount (if any; none if the update results in the autoRenew account being removed)
- the signatures of the adminKey (if there is one). For updates where the adminKey is changed this still includes both the before and after version of the adminKey.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
