### ISSUE TITLE
`CurrencyAdjustments` class has incorrect `MAX_NUM_ADJUSTMENTS` limit

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#12825]
### Description

This ticket is the investigation result of https://github.com/hashgraph/hedera-services/issues/12824

`CurrencyAdjustments` fails to deserialize due to hitting this limit. 
Here is the [transaction information](https://hashscan.io/mainnet/transaction/1713189452.039489664), and it has 73 adjustments.

This issue can be potentially dangerous as it may cause the reconnect failure. 

### Steps to reproduce

1. Download the state files
```
gsutil -m cp -r "gs://mainnet-1m/hgc-teraswitch-spare-2/168343348" .
```

2. Download the validator 
```
gsutil -m cp  "gs://hedera-ci-ephemeral-artifacts/hedera/hedera-state-validator/validator-0.47.jar"
```
3. Run `java -jar validator-0.47.jar /path/to/round/168343348 totalSupply`

### Hedera network

mainnet

### Version

v0.47

### Operating system

None

**Comment by tinker-michaelj** [comment]
Fixed on relevant branches.
