### ISSUE TITLE
Remove dependency on javafx.util.Pair

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#1288]
**Summary**
Remove the dependency in ExpiryManager and TxnAwareRecordsHistorian and ConfigDrivenNettyFactory on the javafx.util.Pair class. While it is nice to reuse logic, pulling in the entire JavaFX module for this one class simply isn't worth it.

**Comment by anighanta** [comment]
@rbair23 I think someone wrongly imported `Pair` from javafx instead if importing from `org.apache.commons`. 
I think replacing the import `javafx.util.Pair` with `org.apache.commons.lang3.tuple.Pair` will address this
