### ISSUE TITLE
Refactor BalancesExporter

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#129]
To supplement #2057

`BalancesExporter` should internally check if it’s time to export. It doesn’t need to expose another method `boolean isTimeToExport(Instant now)`. The only method to be exposed could be `toCsvFileWhenItIsTimeToExport`

Also add `DefaultBalancesExporterTest` to test calls to delegate.

**Comment by qnswirlds** [comment]
This issue is now obsolete. `BalancesExporter` has become an interface and a new `SignedStateBalancesExporter` has been implemented.
