### ISSUE TITLE
ConfigDefault annotation

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#12902]
For the configuration engine, we currently specify the default values of configurations using the syntax `@ConfigProperty(defaultValue = "1000")`. This is a bit on the verbose side. It would be nice if we had a shorter way of doing this.

Add a new annotation `@ConfigDefault` that uses the `value` argument as the default value. This will allow us to use the following syntax: `@ConfigDefault("1000")`.

**Comment by mxtartaglia-sl** [comment]
Depends on: https://github.com/hashgraph/hedera-services/issues/12902

**Comment by poulok** [comment]
Before this moves forward, there needs to be a design proposal.
