### ISSUE TITLE
Migration tests (Crypto-Migration-Restart-Testnet-100-10m,Crypto-Migration-Testnet-100-5m) failed due to fee initialization failure

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1292]
**Summary of the defect**

All migration tests (for both `master` and `release/0.13`) failed for similar reason: Could not download '0.0.112' final status INVALID_SIGNATURE. 

Similar error occurred to `Crypto-Restart-Testnet-200-16m` as well.

Seems like the state file update has missed something.

**How to reproduce (if possible)**
summary link for master: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618986450031900
summary link for release/0.13: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618987435032000

slack link for master `Crypto-Migration-Testnet-100-5m`: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618984537371400
slack link for master  `Crypto-Migration-Restart-Testnet-100-10m`: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618985215372200
slack link for master  `Crypto-Restart-Testnet-200-16m`: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618986404373900

**Service logs (if applicable)**
```
...
---- HAPIClientValidator FAILED validation ----
2021-04-21 06:05:53.193 ERROR  242  HapiApiSpec - Fees failed to initialize! Please check if server is down...
java.lang.IllegalStateException: Could not download '0.0.112' final status INVALID_SIGNATURE
2021-04-21 06:05:55.393 ERROR  242  HapiApiSpec - Fees failed to initialize! Please check if server is down...
java.lang.IllegalStateException: Could not download '0.0.112' final status INVALID_SIGNATURE
ClientNode - Suite                    Result   Failures
Node 0 - CryptoCreateForSuiteRunner   FAILED   CreatePayerAccountForEachClient
Exceptions:2
Node 0 - CryptoTransferLoadTest       FAILED   RunCryptoTransfers
Exceptions:2

```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by Neeharika-Sompalli** [comment]
@anighanta  Is the modified state and modified pem file updated in the tests ?

**Comment by anighanta** [comment]
We have to update the circleCI key right ?

**Comment by ljianghedera** [comment]
Yeah

**Comment by Neeharika-Sompalli** [comment]
> We have to update the circleCI key right ?

`KEY_DevTestNetTreasury` in Environment variables of CircleCI is being used for StartUpAccount.txt. If the key is present in repo , it could be modified in `config.yml` to use that key

**Comment by anighanta** [comment]
I updated `KEY_DevTestNetTreasury` env variable in CircleCI. we are not going to save the keys in the repo from now on right ?

**Comment by ljianghedera** [comment]
No, we don't save it in repo any more.

**Comment by ljianghedera** [comment]
The issue is fixed after Anirudh updated the `KEY_DevTestNetTreasury` env variable in CircleCI.
