### ISSUE TITLE
HTS-Basic-AccountBalances-Client-2k-15m: failed for AccountBalancesValidator failure

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1295]
**Summary of the defect**
The root cause is some account balances file was not scheduled on epoch boundary

**How to reproduce (if possible)**
Refer to the slack report links:

slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618988292376700
summry link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618991510032600

**Service logs (if applicable)**
```
...

---- AccountBalancesValidator FAILED validation ----
<<ERROR>>
First account balances file wasn't scheduled to be exported at epoch export boundary.
exportPeriod is 300 seconds. The file's export time is: 2021-04-21T06:44:00.005Z. First file name: 2021-04-21T06_44_00.005437Z_Balances.pb
All client side account balances should be covered by server side's account balances

```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
Closed by 01229 Fix the occasional failure account balances file is on epoch export period boundary and others #1341

**Comment by Neeharika-Sompalli** [comment]
This issue is repeated in today's regression https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1620026125196100
