### ISSUE TITLE
Standardize system initialization (i.e. during genesis startup)

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#130]
Current system initialization logic is both confusing (scattered across several components in a surprising way) and creates an unnecessary risk of user error (e.g. is partially but not entirely controlled by the `initializeHederaLedgerFlag`).

This issue is to standardize the system initialization phase by consolidating all logic to create missing system files/accounts from the configuration on disk exactly when these files/accounts are missing.

Reference #2260

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
