### ISSUE TITLE
fix: Rewrite grpc's "possibly CATASTROPHIC failure" which actually isn't possibly catastrophic, so it is appropriately less scary

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#13004]
If we get a gRPC message or something that's too large (I guess larger than we've configured gRPC for) it throws a `RuntimeException` with a really scary message which then shows up in our logs and frightens innocent developers, like me.

![image](https://github.com/hashgraph/hedera-services/assets/117694041/1a3fff6d-aa7b-43f9-a6ea-319fad5b090c)

I'm given to understand that it isn't actually possibly catastrophic at all, nor even an error.  It's just a warning.  (Or so I've been told.)

It would be nice to catch that exception and rewrite it to be more temperate.

**Comment by netopyr** [comment]
@david-bakin-sl Thanks for reporting the issue. Can you please attach the whole stack trace? Otherwise, it will be hard to catch the `Exception`. 😉
