### ISSUE TITLE
Refactor `Service` and move it to `platform-sdk`

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#13084]
The goal of this ticket is to make it possible for `PlatformState` to utilize schema framework that allows a service to have a protobuf definition and provides a way to migrate from one version to the other. 

To make it work, several things have to happen: 

1. Current service `Service` interface needs to be split in two parts:

`Service`: 
```
public interface Service {
    String getServiceName();
    void registerSchemas(@NonNull SchemaRegistry registry, @NonNull SemanticVersion version);
}
```
amd
`RpcService`:
```
public interface RpcService extends Service {   
    Set<RpcServiceDefinition> rpcDefinitions();
}
```
2. `RpcService` remains in `hedera-app-spi` while `Service` and a set of related classes such as:
```
MigrationContext
GenesisRecordsBuilder
NodeInfo
NetworkInfo
SelfNodeInfo
SchemaRegistry
StateDefinition
```
should migrate to `platform-sdk`. 

Here is how the class dependencies look like:

![image](https://github.com/hashgraph/hedera-services/assets/1595361/e8723ded-6aae-43db-a405-cc97ca44469a)

This refactoring will unblock the next refactoring https://github.com/hashgraph/hedera-services/issues/11771

**Comment by netopyr** [comment]
I think it is wrong to move `GenesisRecordsBuilder`, `NodeInfo`, `NetworkInfo`, and `SelfNodeInfo` to platform.

If platform wants to reuse the migration functionality, we need to find a different design to provide additional data.
