### ISSUE TITLE
Add more descriptive response code than NOT_SUPPORTED

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#131]
Response code NOT_SUPPORTED is used widely in service hedera code.
user often get NOT_SUPPORTED, sometime hard to debug and figure out 
exact cause.

For example, if API permission was not configured probably, it also return
NOT_SUPPORTED

Literally, "NOT_SUPPORTED" means a feature not implemented or supported yet.

But in current code base it's used (abused) in many places, where some times
is not due to a feature not implemented.

We should add more response code to give a specific and descriptive
cause of error code.

**Comment by JeffreyDallas** [comment]
Close obsolete issue
