### ISSUE TITLE
Create the `PlatformState` protobuf

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#13124]
Create a protobuf definition for the `PlatformState` to include with one of the proposals for the Public Merkle API project.

There is an open [PR](https://github.com/hashgraph/hedera-protobufs/pull/349) in the protobuf repo to use as a starting point.

This effort needs to be coordinated with the TSS project because it will be affected. There are two options:
1. Do not wait for any changes to the `PlatformState` required by TSS. Include any changes later when they are known.
2. Delay this proposal until the TSS design is done and include any changes when they are ready.

The team has decided to follow option 1.

**Comment by imalygin** [comment]
https://github.com/hashgraph/hedera-protobufs/pull/349
