### ISSUE TITLE
AllProtectedFilesUpdate-NIReconnect-1-12m: failed,  node 3 did not reconnect even once

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1318]
**Summary of the defect**
The major failure is the ReconnectValidator reported that node 3 didn't finish required reconnect for at least once. This is for master branch.

release/0.13 is fine. 

```
---- ReconnectValidator FAILED validation ----
Node 3 was expected to reconnect at least 1 time. (reconnect count: 0)

```

**How to reproduce (if possible)**

Please checkout the slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1619254391456500
and summary link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1619258520038700

**Service logs (if applicable)**
```
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by Neeharika-Sompalli** [comment]
This issue is resolved with other reconnect tests and fixed. Test passes now https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1620026843197400
