### ISSUE TITLE
Support new "Istanbul" opcodes

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#132]
The scVM currently supports opcodes from the Constantinople version of Solidity.  Istanbul introduced two new opcodes, SELFBALANCE and CHAINID.  This limits compatibility to compilers up to solc version 0.5.12.

Add the two new opcodes to the VM for compatibility with Istanbul.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
