### ISSUE TITLE
Test flake in consensus unit test

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#13201]
https://scans.gradle.com/s/vxxar7mbfa4m2/tests/task/:swirlds-platform-test:test/details/com.swirlds.platform.test.consensus.ConsensusTests/nodeRemoveTest(ConsensusTestParams)%5B1%5D?top-execution=1

**Comment by cody-littley** [comment]
Another flake (different test): https://scans.gradle.com/s/vxxar7mbfa4m2/tests/task/:swirlds-platform-test:test/details/com.swirlds.platform.test.consensus.ConsensusTests/nodeRemoveTest(ConsensusTestParams)%5B1%5D?top-execution=1

**Comment by edward-swirldslabs** [comment]
both links are the same.
