### ISSUE TITLE
MixedOps-NDReconnect-1.5k-25m has HAPIClientValidator validation failure

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1320]
**Summary of the defect**

The client log reports SubmitMessageForReconnect didn't finish: 

```
---- HAPIClientValidator FAILED validation ----
<<ERROR>>
Suite SubmitMessagesForReconnect started, but did not finish in node 0 file hapi-client-combined.log!
```

Same error also happened to MixedOps-NIReconnect-1.5k-25m  test.

**How to reproduce (if possible)**

slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1619340211002700
summary link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1619340251042700

**Service logs (if applicable)**
```
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by Neeharika-Sompalli** [comment]
This issue is fixed with other failing reconnect tests
