### ISSUE TITLE
Decide which library will be used for BLS bilinear pairings

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#13236]
Based on which elliptic curve @rsinha decides we should use, determine the library that needs to be wrapped and used by the Cryptography Module.

@AlfredoG87 needs to verify that the selection will work for smart contracts.

**Comment by rsinha** [comment]
Given the precompiles that are available, we can go with the BN254 curve. The interface for pairings is generic, so we can later swap this for a different curve as well, giving us crypto agility.

Some of the popular libraries implementing this curve are listed here: https://hackmd.io/@gnark/eccbench
Choosing arkworks crate (https://docs.rs/ark-bn254/latest/ark_bn254/) allows for supporting a large number of curves with the same generic interface, allowing for crypto agility.

**Comment by rsinha** [comment]
Ah, BN254 is the other name for `alt_bn128`. All good here :)
