### ISSUE TITLE
Add in-memory mode to `VirtualMap` for smaller number of entries

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#13246]
It would be very useful to be able to store very small virtual maps totally in memory. Roster maps would use this, and any current structures that are queues. Queues are not efficient for hashing, so it would be better to store them as in memory maps.

A new configuration is required to indicate that a particular map should be kept in memory. The VirtualNodeCache also needs to be updated to eliminate a memory leak that would happen if there are no flushes, which would be the case for in-memory virtual maps.

**Comment by poulok** [comment]
This ticket is no longer relevant due to the decision to organize the state a single large virtual map.
