### ISSUE TITLE
Nightly Canonical Token Transfer tests are failing

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#13249]
Nightly canonical token tests are failing because 1 or 3 nodes cannot keep up with transaction handling, causing the secC2C to increase above the acceptable maximum.

[Failing test histories](https://preproduction.grafana.hedera-ops.com/d/ec9413c6-6f17-49fc-951b-51cbc21a1eef/network-health?orgId=1&from=1715415640064&to=1715419264586&var-network=engnet1&var-NodeID=All)

**Comment by OlegMazurov** [comment]
Running the same benchmark with 100% CPU utilization (all available CPUs) simultaneously on every node in `engnet1`:
![engnet1](https://github.com/hashgraph/hedera-services/assets/23125269/315e0685-3a91-4756-afbc-542c4486aada)
Node 1 is twice as slow as node 0. The assumption that the network is more or less homogeneous is not valid. The reason for the difference may be poor isolation of VMs in GCP, CPU thermal throttling or something else.
The observed behavior - high secC2C on a slow node - is expected under the circumstances (the extent may be questioned, though). From that perspective, the network is not suitable for nightly performance testing.
