### ISSUE TITLE
Reconnect test for Auto renew feature

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1325]
**Summary**
Once Autorenew feature is implemented the following reconnect test should be implemented. 

Create a test in which a few accounts will be auto renewed while the node is down and test if reconnect is successful with the state.

**Comment by anighanta** [comment]
@Neeharika-Sompalli this scenario looks very similar to the last point in this issue https://github.com/hashgraph/hedera-services/issues/1225 . if it is can we close this ?

**Comment by Neeharika-Sompalli** [comment]
@anighanta  you are right. The issue has the same test described in it. Closing this issue
