### ISSUE TITLE
Back out protobuf-changes related to dynamic address book

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#13265]
As we postponed the dynamic address book to release 0.52, we need to back out all changes that were already committed to the protobuf repository.

Modified this for hedera-services code back out. Created issue #357 for hedera-protobufs back out.

**Comment by jsync-swirlds** [comment]
What is the value of removing the protobufs?
I can see removing (or setting aside) implementation from the services repository, but what is the harm of having API definitions in place before the implementation is written; that's very nearly a necessity in many situations, as API definition may well need to be completed and settled well before implementation can be scheduled.
