### ISSUE TITLE
Hedera Native Library

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#13317]
### Overview

The `Hedera Native Library` will contain necessary code to wrap native libraries, so that they can be leveraged by java applications. It will be in a separate repository from `hedera-services`.

```[tasklist]
- [ ] https://github.com/hashgraph/hedera-services/issues/13319

```

### Sibling Epics

- https://github.com/hashgraph/hedera-services/issues/13315
- https://github.com/hashgraph/hedera-services/issues/13316

**Comment by poulok** [comment]
This will be covered by the #13316 epic
