### ISSUE TITLE
HTS precompiled contract (0x167) updateTokenInfo method fails

### ISSUE THREAD

**Issue by AlbertoMolinaIoBuilders** [hashgraph/hedera-services#13341]
### Description

We are trying to update the info of an Hedera Token through the HTS precompiled contract (0x167) invoking the "**updateTokenInfo**" method. We simply need to update the token's name, so we provide a new token name string and all other input arguments are set as 0 (default). Please check the [transaction](https://hashscan.io/testnet/transaction/1715604700.363997005) .

We get a "**INVALID_TREASURY_ACCOUNT_FOR_TOKEN**" error. My feeling is that for some reason, the contract is trying to set the treasury account to address(0), but we are passing address(0) as the treasury account simply because we do not want to update it at all..... If I remember correctly it used to work fine (all "0" arguments were ignored) but now it returns this unexpected error....

### Steps to reproduce

- Create a Token with a treasury account
- Try to update the Token's name using the HTS precompiled (0x167)

### Hedera network

testnet

### Version

latest

### Operating system

None

**Comment by Nana-EC** [comment]
Thanks @AlbertoMolinaIoBuilders 
We'll take a look and get back to you.

In the mean time can you share more details around the specific method and params you're passing in by highlighting the solidity and js code you're executing?

This will help us to better understand your flow and speed up investigation.

Thanks

**Comment by AlbertoMolinaIoBuilders** [comment]
Hello @Nana-EC , If you check [this](https://hashscan.io/testnet/transaction/1715604700.363997005) transaction you can see that the "treasury account" provided is address(0) and we get an error : INVALID_TREASURY_ACCOUNT_FOR_TOKEN. However the reason why the treasury account is 0 is because we do not want to change. If you check [this](https://hashscan.io/testnet/transaction/1719325682.034882585) second transaction you will see that everything was ok (and the treasury account was still 0)

**transaction in error**
![image](https://github.com/hashgraph/hedera-services/assets/114951681/21e7aef3-2b7b-4e41-943b-10c250bd50be)

**successful transaction**
![image](https://github.com/hashgraph/hedera-services/assets/114951681/402a84c1-beb2-4043-833c-b3c085412afc)

**Comment by AlbertoMolinaIoBuilders** [comment]
thank you it seems to work now!
