### ISSUE TITLE
Maintain each PendingRecord changes per SavePointStack

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#13447]
After https://github.com/hashgraph/hedera-services/issues/13559 each SavePoint maintains its own records instead of the recordListBuilder. Move them to be used as `BlockItems` 

- [ ] Create a new `SavePoint` type that includes the wrapped state and its pending block items
- [ ] Add a `PendingRecord` object that includes all the information needed for a `BlockItem`. It should include 
      - `Transaction`
      -  `TransactionOutput`
      - `List<StateChanges>` `TransactionResult`
      - `RecordType` thats ays it is a `PRECEDING`, `CHILD`
      - Enum that respresents what should happen to this record if there is a rollback (should it be removed or reverted)
- [ ] Add `List<PendingRecord>` to `SavePoint`. When a child save point stack is committed its List<PendingRecord> will be flushed to its parent save point stack
- [ ] Add a utility method that takes `List<PendingRecord>` and return `List<BlockItems>`
- [ ] At the end of HandleWorkflow, we go through all the List<PendingRecord> in the same order and assign `consensusTimestamp` according to platform's consensusTimestamp

**Comment by Neeharika-Sompalli** [comment]
Existing System: 
<img width="893" alt="image" src="https://github.com/hashgraph/hedera-services/assets/52669918/4885ffb9-a093-4638-a897-a5fbf7140c9f">


Proposed Change: 
<img width="827" alt="image" src="https://github.com/hashgraph/hedera-services/assets/52669918/a84f45d5-5cb0-48e3-8cc6-edcf7271e167">

**Comment by derektriley** [comment]
Done.
