### ISSUE TITLE
Warm up fungible token transfers

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#13452]
### Problem

Validating fungible token relations is expensive during transaction handling (lots of disk I/O).

### Solution

Warm up fungible token relations similarly to NFTs.

**Comment by poulok** [comment]
Is this unique to `develop` or is it also present in `release-50`?

**Comment by OlegMazurov** [comment]
> Is this unique to `develop` or is it also present in `release-50`?

It could help `release-50` as well.
