### ISSUE TITLE
VMerkleDual-NDReconnect-500-60m - reconnect node was stuck in REPLAYING_EVENTS for ~43 minutes

### ISSUE THREAD

**Issue by kfa-aguda** [hashgraph/hedera-services#13490]
Before that, CPU was already pegged at 100% which eventually affected replay. 

Started checking around 15 mins mark, active 19 mins. 

Also noticed # of live threads doubled during checking? This needs further investigation.
[multipage_pdf.pdf](https://github.com/hashgraph/hedera-services/files/15420687/multipage_pdf.pdf)

http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20240523-053638-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m

**Comment by OlegMazurov** [comment]
Possibly related to #13486

**Comment by kfa-aguda** [comment]
Closing this as a performance regression as per @OlegMazurov's comment.
If we do see this again in this cycle, we can reopen this ticket.
