### ISSUE TITLE
Remove dead code in synthetic record generation 

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#13536]
### Problem

At present we only support streaming synthetic records at genesis (for system account creations). This is obscured by the dead code [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java#L438), which reads as if `state.getReadableStates(BlockRecordService.NAME)` will sometimes be non-empty; but it will not be, since no `Schema`s are applied at this point in the startup lifecycle.

### Solution

Delete this dead code.

**Comment by HarshSawarkar** [comment]
Hi, I have a question. Does removing this code affect the RESTART state? Could you please guide me?![image](https://github.com/user-attachments/assets/97b83c06-64a4-4a70-b3b2-060a98914978)

**Comment by tinker-michaelj** [comment]
Fixed.
