### ISSUE TITLE
Initial system files should be externalized via synthetic `FileCreate` at network genesis

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#13594]
### Description

Operators for test environments are forced to manually upload system file contents to externalize the initial exchange rates, fee schedules, throttles, etc. to mirror nodes in the environment.

### Steps to reproduce

Start a network from genesis, observe mirror nodes don't have active fee schedules.

### Hedera network

other

### Version

develop

### Operating system

None

**Comment by ElijahLynn** [comment]
When this issue is complete, can you please notify `#devops` with the message: 

> You can deprecate the upload-default-configs.yml playbook now that this PR is complete, see playbook notes for context.
