### ISSUE TITLE
refactor util.sh DB functions

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#136]
qnswirlds:
"We could use a helper function to return the ssh command on the argument HOST. Then we can use eval to execute the command. This will help avoid duplicate codes that could be tricky to maintain/modify later."

function get_binary_object_count() {
  for HOST in ${TF_HOSTS[@]}; do
    **ssh -o StrictHostKeyChecking=no ubuntu@$HOST \
      "sudo -u postgres psql -d fcfs -c 'SELECT COUNT(*) FROM binary_objects' | egrep -o '[^(]+[0-9]+' | egrep -o '[^ ]*[0-9]+'" > binaryObject_$HOST.count**
    num=$(cat binaryObject_$HOST.count)
    ci_echo "Number of binary objects on $HOST: $num"
  done
}

function verify_binary_object_count() {
  local diff=$1
  for HOST in ${TF_HOSTS[@]}; do
    actual=$(**ssh -o StrictHostKeyChecking=no ubuntu@$HOST \
         "sudo -u postgres psql -d fcfs -c 'SELECT COUNT(*) FROM binary_objects' | egrep -o '[^(]+[0-9]+' | egrep -o '[^ ]*[0-9]+'"**)

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
