### ISSUE TITLE
Dashboard for handle times

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#13618]
With modularization we introduced metrics to track how long the execution of the handle workflow takes for each transaction type (e.g., `app_cryptoTransferDurationAvg_ns` and `app_cryptoTransferDurationMax_ns`). We should create a dashboard that visualizes these numbers.

The graphs should be combined because there are so many transaction types. Maybe a graph per service? By default, it should show the duration during the last 24h.

**Comment by mhess-swl** [comment]
I've created a dashboard for all transaction types [here](https://production.grafana.hedera-ops.com/d/bdop10nktvmdce/handle-transaction-times?orgId=1). Feedback would be great!

**Comment by mhess-swl** [comment]
@netopyr what's the best way to verify these times are presented accurately?
