### ISSUE TITLE
Precheck only verifies user pays node, network fees

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#13633]
According to @lbaird, our goal for precheck handling is this: 

> GOAL: precheck only verifies that the user will pay the node and network fee.

We want to evaluate all of the handler precheck methods to ensure this goal is met.

**Comment by netopyr** [comment]
@mhess-swl `TransactionHandler` does not have precheck methods. During the ingest workflow, we only call `calculateFees()` (and temporarily `pureChecks()`). Do you want us to review the `calculateFees()` implementations? Did you notice anything suspicious?
