### ISSUE TITLE
Nodes get stuck in `REPLAYING_EVENTS`

### ISSUE THREAD

**Issue by litt3** [hashgraph/hedera-services#13669]
## Examples

- [VMerkleDual-NDReconnect-500-60m](http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20240604-053751-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/)
    - The `ConsensusEngine_busy_fraction` metric flatlines at `1.0` for `node3` (which is the one with the problem)
    - Some potentially relevant warnings are logged:
        - `Value for key SmartContractByteCodeMapKey{contractId=30000} was not found inside smart contract bytecode map.` 
        - `Value for key SmartContractByteCodeMapKey{contractId=0} was not found inside smart contract bytecode map.`
- [MixedOps-Interrupted-2NReconnect-1k-41m](http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/3NReconnect/20240604-063903-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-Interrupted-2NReconnect-1k-41m/)
    - `node14` (the one with the problem) doesn't display any of the "suspicious" behavior seen on the previous test. For this reason, I assume that the "suspicious" behavior is coincidental, not the root cause. 

## Behavior

1. A node is stopped
2. The node is restarted
3. It never advances past `REPLAYING_EVENTS`

**Comment by alittley** [comment]
It is currently suspected that this is just another expression of the presently existing performance issues
