### ISSUE TITLE
HIP-904: Enhance test-clients to include all new verbs from the HIP

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#13660]
### Problem

Following HIP-904, we define 4 new transaction types in Hedera - `TokenReject`, `TokenAirdrop`, `TokenClaim` and `TokenCancel`. In order to provide bdd integration tests, covering these functionalities we need to define these new types in test-clients and provide verbs for them. These verbs then will be used to send HAPI transactions with these new types against a running consensus node. 

### Solution

Define the missing new operations in `test-clients` and provide verb and helper methods if needed, for using them in bdd test implementations.

```[tasklist]
### Tasks & Definition of done
- [ ] Define HapiTokenClaim operation and expose it in `TxnVerbs`
```

**Comment by MiroslavGatsanoga** [comment]
Closing as the only task left here will be done as part of https://github.com/hashgraph/hedera-services/issues/13737.
