### ISSUE TITLE
`MixedOps-Interrupted-2NReconnect-1k-41m` failed due to `InboundConnectionManager` trying to create new connection

### ISSUE THREAD

**Issue by litt3** [hashgraph/hedera-services#13689]
- [data folder](http://35.247.76.217:8095/swirlds-automation/release/0.51/15N_4C/3NReconnect/20240605-120839-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-Interrupted-2NReconnect-1k-41m/)

## Failure Description

1. The node (`node14`) falls behind and stops gossip
2. There are numerous occurrences of the following warning
3. It seems like `node14` is not able to reconnect for several minutes, and then the entire network is restarted

```
InboundConnectionManager: 14 got new connection from 7, disconnecting old one
```

**Comment by poulok** [comment]
Old issue, closing
