### ISSUE TITLE
FileOps-NIReconnect-12-21m: ReconnectPerformanceValidator failed validation 

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1368]
**Summary of the defect**
Not much error information in results log files. 

**How to reproduce (if possible)**

slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1620298331275900
summary link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1620298373066200

**Service logs (if applicable)**
```
---- ReconnectPerformanceValidator FAILED validation ----
<<ERROR>>
Reconnect took 10.821 seconds to transmit 3.4561967849731445 mb.
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by Neeharika-Sompalli** [comment]
This can be resolved by modifying the expectation in the JSON file. Currently it expects sync should happen within 10 seconds, but it took 10.8 secs
