### ISSUE TITLE
Define HapiTokenAirdrop operation and expose it in `TxnVerbs`

### ISSUE THREAD

**Issue by yosiftouma** [hashgraph/hedera-services#13697]
- Define the `HapiTokenAirdrop` in `TxnVerbs` so that the QAs can start writing tests and the devs can debug
- Similar implementation: https://github.com/hashgraph/hedera-services/pull/13685/files#diff-cbfe07161e6f5fa283bd5d0b7fd5002c426efa58e486c602c496f4a201f50eb0
- Create the new `TokenAirdropHandler` that implements `TransactionHandler` and override the `preHandler`, `pureChecks` and `handle` methods(add TODO: implement in them)

**Comment by vtronkov** [comment]
Completed in https://github.com/hashgraph/hedera-services/pull/14279
