### ISSUE TITLE
Use the new Statistics class in LearnerThread/LearningSynchronizer

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#13748]
The `ReconnectMapStats` class already exists which tracks the necessary metrics, but it is not invoked yet so it does not do anything. This ticket is for adding code that need to determine which nodes, and how many, need to be sent to `ReconnectMapStats` so that the metrics are accurate.

The metrics must be reset at the end of the reconnect so that a subsequent reconnect starts from zero.

**Comment by anthony-swirldslabs** [comment]
1st part: https://github.com/hashgraph/hedera-services/pull/14071

**Comment by anthony-swirldslabs** [comment]
The second part is migrated to https://github.com/hashgraph/hedera-services/issues/14198
