### ISSUE TITLE
Use the per-map metrics functionality of the Statistics class

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#13750]
The `ReconnectMapStats` implementation already supports per-map metrics if it is provided a label (indicating which map the metrics are for). This ticket is to create one instance of the stats class per map, provide each to the aggregate stats class, then update the individual map stats instances instead of incrementing the stats on the aggregate instance directly. The aggregation should still be useful because not all data that is synchronized is in a map.

**Comment by anthony-swirldslabs** [comment]
Since we're moving towards a single huge map for storing all the logical virtual maps, we decided not to implement this story.
