### ISSUE TITLE
Package modularized smart contracts service to be consumable  

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#13767]
### Problem

The smart contracts service module is not currently in a state where it can be easily consumed by other applications (e.g the mirror node).  One consequence of this is that new functionality in system contracts is not currently available when calling the mirror node.

### Solution

Refactor the codebase to enable easy consumption of the smart contracts module by other applications.

**Comment by Nana-EC** [comment]
Services is in process here.
Anything remaining in the HSCS areas?

**Comment by Nana-EC** [comment]
@tinker-michaelj and @IvanKavaldzhiev is there any remaining work here that HSCS needs to carry out as part of reusable services?
