### ISSUE TITLE
Document the design for the Roster Proposal in support of the Consensus Node TSS project

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#13775]
Document everything needed for the design proposal for the consensus roster in order to support TSS block signing. What data will be included in the roster, what is the lifecycle of that data, etc.

The design proposal will be created and gotten through acceptance in another ticket.

Questions to answer by this proposal as follows. Kore and Anthony each assigned parts to flesh out the drafts.

- [ ] 		Roster Proposal - no keying for shares, just adoption of roster with target life-cycle. - Kore
- [ ] 		What is the new Roster API and Fields? (TSS compatible) - Kore
- [ ] 		How is a new network bootstrapped from genesis? (TSS Compatible) - Anthony
- [ ] 		How does the App tell the Platform about setting a new roster? (CAB Life-cycle) - Kore
- [ ] 		How can we do upgrades without using config.txt any more, save CAB in the state? (TSS Compatible). - Anthony
- [ ] 		What is the roster adoption process on upgrade? (TSS Compatible) - Anthony
- [ ] 		On startup, need a place where we can check whether or not to adopt the new roster based on some criteria. - Anthony
- [ ] 		 What does the state look like storing CAB roster, current roster, and ?previous roster? - Kore
- [ ] 		Is there any impact to replay of PCES? - Kore
- [ ] 		What components are affected by switching to Roster from Address Book? - Anthony
- [ ] 		How do we implement this change over in an incremental fashion? - TBD???
- [ ] 		What kinds of tests need to be created to test the new roster life-cycle? - Kore
- [ ] 		What work does Services need to do?  What impacts DevOps? - Kore
- [ ] 		Are there any phased or staged deliveries of the capability? - TBD ???

**Comment by anthony-swirldslabs** [comment]
I've created a private page in Notion and tried to provide answers to the questions assigned above. I need to polish the page a bit, and then I'll share it with the team for review.

**Comment by anthony-swirldslabs** [comment]
I got a first round of early reviews from subject matter experts and addressed some feedback. I'll discuss the doc with Ed tomorrow, and also will still try to get Jasper to take a peek before I request a formal review from the team.

**Comment by anthony-swirldslabs** [comment]
The answers to questions assigned to me are open for review at https://www.notion.so/swirldslabs/TSS-CAB-adoption-genesis-startup-3e73fde015224793bf45245a73c2e699

Only the last question about other components affected by the switch to the Roster is left out as I believe this is a low-level task of performing a usage search and code replacements that will probably boil down to simple renaming of types and methods used. So I don't believe that question requires any design decisions.
