### ISSUE TITLE
Include check of inner scheduled transaction in check of outer schedule transaction

### ISSUE THREAD

**Issue by derdis14** [hashgraph/hedera-services#1377]
**Summary**
Currently, the inner scheduled transaction is not validated, only the outer schedule transaction. 

It is therefore possible, for example, to create a scheduled crypto transfer with transfers that do not sum to zero. The network responds with an INVALID_ACCOUNT_AMOUNTS error only when the scheduled transaction is triggered, rather than when the schedule transaction is executed. It would be better to prevent the creation of a schedule for a semantically incorrect transaction that will end up failing.

**Possible resolution**
Extend function `validate` of class `ScheduleCreateTransitionLogic `

**Comment by tinker-michaelj** [comment]
Hi @derdis14, thanks for the issue!

Leemon has guided that [precheck](https://github.com/hashgraph/hedera-services/blob/master/docs/transaction-prechecks.md) _only_ be used to ensure a transaction has a valid payer account that will be able to afford to pay node and network fees at consensus.

It is definitely important to protect clients from scheduling transactions that will certainly fail at consensus! But we would prefer such enhancements be made to client libraries like the [Java SDK](https://github.com/hashgraph/hedera-sdk-java).

**Comment by tinker-michaelj** [comment]
Hi @derdis14, very good idea! I initially misread your idea as an enhancement to precheck (in case you saw that!)

But I think I understand now. When we handle a `ScheduleCreate`, we could take that opportunity to do "sanity checks" on the transaction being scheduled.

If, as in your example, there is no hope of the transaction being `SUCCESS`ful at consensus, we could fail the `ScheduleCreate` right away and resolve to the status that the scheduled transaction _would_ end with; `INVALID_ACCOUNT_AMOUNTS` in your example.

Got it.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
