### ISSUE TITLE
Analyze account property "inheritance" when finalizing a hollow account

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#13848]
When finalizing a hollow account by doing a contract create from an EOA the question arises:  What are the newly-finalized account's properties?  Things like auto renew account, staking, etc., but especially the presence/absence of an admin key, and if present, what is it to be?

Need to review this as the answers aren't clear at this point.

Consider:
a) who's doing it?  e.g., what's the POV of an ethereum developer?
b) what did we do in mono, and was it correct anyway?
c) what flexibility (or lack of it) do various settings mean for the contract account going forward?  (is there lock in to things that can't be changed?)

**Comment by david-bakin-sl** [comment]
More discussion on internal slack: https://swirldslabs.slack.com/archives/C056T02B6UT/p1718327321632719

**Comment by stoyanov-st** [comment]
We are not setting staking data or auto renew account. The admin key is zeroed which makes the contract immutable, so no flexibility whatsoever.
