### ISSUE TITLE
Migrate expiration times w/ mercy extension when auto-renew enabled

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1388]
**Summary**
When [auto-renewal](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-16.md) is first enabled, every entity in the network will receive a free extension of its expiration time.

The extension will be to _either_...
1. 90 days after the entity's current expiration; or,
2. A consensus timestamp ~90 days after auto-renew is enabled.

...whichever is larger. 

**Possible resolution**
During the first upgrade that enables auto-renew, as a migration step in `ServicesMain.init()`, scan all entities (accounts, contracts, files, topics, tokens) and update their expiration by this rule.

---

To avoid making a huge number of entities expire at the same second, **if** an entity prefers option (2), give it an additional, pseudorandom number of seconds in the range of 0-168 hours.

This number might be based on e.g. a prefix of the SHA-384 hash of the entity's id.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
