### ISSUE TITLE
Work around PBJ issues so protobufs compile in services repo (e.g. not having nested proto definitions)

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#13897]
Currently the block stream protos don't compile in the services codebase. We need to get them compiling, even if we use some temporary workarounds.  

Related, but possibly not the cause, there are a number of issues filed in the PBJ repo that _may_ be impacting said compile-ability:
* https://github.com/hashgraph/pbj/issues/262
* https://github.com/hashgraph/pbj/issues/263

Of course, there may be other issues as well. These issues may be a good starting point, though.

**Comment by derektriley** [comment]
After speaking with Joseph created a PR to address compilation issues with PBJ.
Confirmed I could compile the block stream protobufs with PBJ from hedera-services.

https://github.com/hashgraph/hedera-protobufs/pull/382
