### ISSUE TITLE
Determine the proposals and scopes for the Mega Map project

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#13891]
Determine which proposals are needed for migrating the state to a single large virtual map accessed with complex keys, and define the scope of each. This is required for _concise_ merkle proofs.

Considerations

- Do we want to carry forward merkle routes?
- How will iteration work? Should we still have iteration?
- What operations will be used internally but not exposed externally?
- Complex keys
- Add linked list to queue data to maintain the structure and iteration
- How to change on disk storage to keep items of the same logical map close to each other
- How to update ISS detection tools (i.e. which part of the state today diverged)

This ticket can be closed when there are tickets for creating the proposals needed for the Mega Map projects. It may be one proposal or several. Each should include the scope for the proposal.

**Comment by artemananiev** [comment]
The following areas are identified to require design proposals:

* VirtualMap / MerkleDb changes: https://github.com/hashgraph/hedera-services/issues/14802
* State API changes: https://github.com/hashgraph/hedera-services/issues/14803
* Data migration: https://github.com/hashgraph/hedera-services/issues/14804

Complex keys, ISS detection tools, state validator changes - all these will be minor features with no impact on APIs, external users, data formats, and so on, so they don't require design proposals.
