### ISSUE TITLE
Reconnect - Node resilience : Scenario when a Node fails when writing state to disk

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1390]
**Summary**
This issue occurs only if the Node's java process crashes/stops or node fails for any other reason.

If a node fails while it is writing a saved state to disk, we might have a corrupt/empty postgres back up file that cannot be restored when the node comes back online. 
When the node is restarted from the latest saved state, that has corrupt/empty postgres backup file we might encounter an error like below as observed in #1293 

```
...
2021-04-21 08:54:36.278 24       INFO  SNAPSHOT_MANAGER << SnapshotManager >> SnapshotManager: SnapshotManager: Completed task [taskType='RESTORE', applicationName='com.hedera.services.ServicesMain', worldId='123', nodeId=3, roundNumber=706, snapshotId=restore, timeStarted=2021-04-21T08:54:36.266080Z, timeCompleted=2021-04-21T08:54:36.278842Z, complete=true, error=true ]
2021-04-21 08:54:36.279 25       ERROR EXCEPTION        <main> Browser: Saved state not loaded:
com.swirlds.platform.internal.SignedStateLoadingException: Failed to restore postgres sql snapshot: /home/services_nightly_regression/remoteExperiment/data/saved/com.hedera.services.ServicesMain/3/123/706/SignedState.swh
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:472) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:699) [swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:942) [swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:343) [swirlds-platform-core-0.9.0.jar:?]
2021-04-21 08:54:36.286 26       DEBUG STARTUP          <main> BinaryObjectStore: Recovery Starting
```

**Possible resolution**
If there is a previous round which is successfully written on the reconnecting node that can be used to restore at startup. For this manual intervention from devops is needed to clean up the bad last round on the disk.

One way to test if the saved state for that round is successfully written to disk is to try and load that state in a dev environment before restarting node from the last saved state on reconnecting node.

**Comment by jsindy** [comment]
We need a way to determine if the state and db backup is successful. I think we can write a file once the state and database backup is finished writing to disk. For example `round_number.finished`.

If a node goes to reconnect or even just is started back up is should use the last backup that has the associated file.

**Comment by lbaird** [comment]
If the state is written with its signature, then the signature could be checked when it is loaded. That would catch accidental corruption. And also catch malicious intentional corruption.

________________________________

**Comment by jsindy** [comment]
Could we do something similar for the database as well? Solving this bug is required for fully autonomous reconnect. As it stands if the java process dies within 7~ second of the every 15 minute mark the node is unrecoverable without intervention.

**Comment by nathanklick** [comment]
Also, please note that the above failure can manifest for many reasons such as missing PSQL command line tools, insufficient permissions to execute the commands against PostgreSQL, or the PSQL commands returned a non zero exit code.

**Comment by nathanklick** [comment]
The in-memory signed state already is verified against the on disk version at startup but right now it simply logs an error if the verification fails. Additionally it is a weak check that will fail during an application state migration. Also I believe it is only checking the hash of both and not actually ensuring integrity of the signed state on disk before it is loaded.

**Comment by nathanklick** [comment]
The node should probably sign both the database and signed state after they are written. The signatures should be stored in a signature file beside each and be verified before the files are loaded by the system.

**Comment by lbaird** [comment]
If we wait for confirmation that the database is done before writing the signature for the state file, then it should (theoretically) prevent problems with the database being corrupted by being shut down during the writing.

But it won’t help with malicious corruption or corruption by bugs in the database software itself.

To avoid that, we would need to have a way to ask the database for a hash of all its data for a particular snapshot. I don’t know if it has that ability. It would almost certainly be too slow if we tried to implement that ourselves.

________________________________

**Comment by lbaird** [comment]
We should probably refuse to start, if we detect the state is corrupted.  And we should be checking a signature, rather than just a hash.

________________________________

**Comment by lbaird** [comment]
Does signing the database involve reading every byte of it at the time of signing? That might be slow. Or does the database itself give us a way to sign quickly and verify quickly?

________________________________

**Comment by nathanklick** [comment]
@lbaird Since the database backup is handled by a shell script, my thoughts were that we could simply run `sha384sum` against the gzipped TAR file that is produced by the script and then we can return the SHA-384 of the TAR GZ file back to the platform to be signed with the node key.

**Comment by jsindy** [comment]
That sounds good to me, along with this we will want logic that if it fails the signature check it tries a previous state/database. currently, mainnet keeps the last 5.

**Comment by lbaird** [comment]
That would be great. Keep checking all 5, until it finds one that’s valid.

From: Joshua Sindy ***@***.***>
Reply-To: hashgraph/hedera-services ***@***.***>
Date: Thursday, May 13, 2021 at 1:14 PM
To: hashgraph/hedera-services ***@***.***>
Cc: Leemon Baird ***@***.***>, Mention ***@***.***>
Subject: Re: [hashgraph/hedera-services] Reconnect - Node resilience : Scenario when a Node fails when writing state to disk (#1390)


That sounds good to me, along with this we will want logic that if it fails the signature check it tries a previous state/database. currently, mainnet keeps the last 5.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
