### ISSUE TITLE
Implement new state structure and register it in InitialModServiceTokenSchema

### ISSUE THREAD

**Issue by yosiftouma** [hashgraph/hedera-services#13939]
- Understand how InitialModServiceTokenSchema works
- Add StateDefinition.*onDisk*(*AIRDROPS_KEY*, PendingAirdropId.PROTOBUF, PendingAirdropValue.PROTOBUF, MAX__AIRDROPS); to statesToCreate
- MAX__AIRDROPS - put it to 10_000_000_000 for now and ask in the airdrop slack channel about the correct value
- It's possible that this change will be enough for the implementation but make sure that this is the case. It's possible that adding the state definition to statesToCreate automatically handles everything but we need to double-check that.

**Note**: in order to use the new protobufs use the changes from hip-904-proto-updates branch

For more context read: https://github.com/hashgraph/hedera-services/pull/12792

**Comment by vtronkov** [comment]
Approved and merged into the feature branch: https://github.com/hashgraph/hedera-services/pull/13566
