### ISSUE TITLE
Replace Service JRS CI tests with `@HapiTest`s

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#13953]
### Problem

JRS tests, although closer to production environments, are much slower, more opaque, and brittle than `@HapiTest`s that can be run locally against a subprocess network.

### Solution

Replace all tests that run in the "Hedera Node JRS Panel" test with equivalent `@HapiTest`s.

- [ ] Upgrade Software Version - https://github.com/hashgraph/hedera-services/issues/13993
- [ ]  Create @HapiTest that adds and removes Nodes in same upgrade Test
- [x] #14051

**Comment by Neeharika-Sompalli** [comment]
Done
