### ISSUE TITLE
ACL Feature Improved Key Management

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#140]
[Design of ACL Feature](https://hederatest.sharepoint.com/:w:/s/Engineering/ETCCJ_9ZOchHmaJnwtPGrT8BITbg5bbrFlXiMScTAJ_Rhg?e=7TDFAm)

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
