### ISSUE TITLE
Gossip & PCES protobuf serialization

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#14012]
A placeholder ticket for all the work that needs to be done in order to migration PCES and Gossip to protobuf. Before this can be done, the event hashing needs to be migrated first because of the reliance on the legacy `SoftwareVersion` class.

Some thoughts on this:
- we will probably need a protobuf schema for both of these. since gossip is something that will likely change in the future, is it worth developing the schema now?

**Comment by poulok** [comment]
Closing, as this ticket is subsumed by:

- https://github.com/hashgraph/hedera-services/issues/15202
- https://github.com/hashgraph/hedera-services/issues/15208
- https://github.com/hashgraph/hedera-services/issues/15205
