### ISSUE TITLE
Performance regression from debug logging

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#14018]
### Description

The regression is caused by the following stack trace fragment:
```
DefaultHandleWorkflow.logUserTxn()
  DaggerHederaInjectionComponent$UserTransactionComponentImpl.txnInfo()
    PreHandleResultModule_ProvideTransactionInfoFactory.get()
      PreHandleResultModule_ProvidePreHandleResultFactory.get()
        PreHandleResultModule_ProvidePreHandleResultFactory.providePreHandleResult()
          PreHandleResultManager.getCurrentPreHandleResult()
            PreHandleWorkflowImpl.preHandleTransaction()
```
Although the actual logging is guarded by checking if `logger.isDebugEnabled()`, parameter evaluation happens outside the check. As the stack trace shows, that evaluation invokes transaction pre-handling, which is an expensive operation.

This is the only context [in a particular profile] where the `txnInfo()` method is invoked. It should be evaluated whether its [derived] implementation justifies such high cost.

### Steps to reproduce

From performance testing of the `develop` branch in `perf1`.

### Additional context

Introduced by #13804 or some relevant work.

### Hedera network

other

### Version

v0.52.0-SNAPSHOT

### Operating system

Linux

**Comment by Neeharika-Sompalli** [comment]
Should be resolved by https://github.com/hashgraph/hedera-services/pull/13996.

**Comment by Neeharika-Sompalli** [comment]
Fixed by this PR https://github.com/hashgraph/hedera-services/pull/13996.
