### ISSUE TITLE
Implement e2e tests for airdropTransaction

### ISSUE THREAD

**Issue by nickeynikolovv** [hashgraph/hedera-services#14024]
Implement e2e tests related to airdrop transaction.
Test plan: https://www.notion.so/limechain/TokenAirdropTransaction-Test-Plan-919ed1800ee845378c5c625648d05ebc?pvs=4

**Comment by Neeharika-Sompalli** [comment]
@Nana-EC  yes this can be closed.

**Comment by Neeharika-Sompalli** [comment]
Completed with the implementation of Airdrop HIP.
