### ISSUE TITLE
Handle 0x0 address for treasury during UpdateTokenInfo call

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#14040]
### Problem

The HTS `UpdateTokenInfo` call fails when the treasury is passed in as the 0x0 address.  It should not fail the treasury address should be null when creating the child transaction body for token service processing.

### Solution

If the treasury address is 0x0 then do not set a treasury address in the child transaction body when dispatching to the token service.

**Comment by Nana-EC** [comment]
Resolved as part of https://github.com/hashgraph/hedera-services/issues/13341
