### ISSUE TITLE
Always use (oldExpiration + effectiveRenewalPeriod) for newExpiration in auto-renew

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1405]
**Summary of the defect**
The `RenewalProcess` is using (consensusTime + effectiveRenewalPeriod) as the new expiration in the record for an auto-renewed account. 

This is a mismatch with the actual new expiration that uses the (oldExpiration + effectiveRenewalPeriod).

**Suggested fix**
Just use (oldExpiration + effectiveRenewalPeriod) for both.

**Comment by anighanta** [comment]
(oldExpiration + renewalPeriod) for the new expiration -> this is what we are doing currently on the entities. But when writing the operation to record stream, the memo is set as (consensusTime + renewalPeriod)
