### ISSUE TITLE
Update memo for "lazy-created account" to "auto-created account" 

### ISSUE THREAD

**Issue by Ashe-Oro** [hashgraph/hedera-services#14064]
### Problem

Memos appended to auto created accounts, per the [HIP-583](https://hips.hedera.com/hip/hip-583) spec, are incorrectly labeled as "lazy-created" whereas the spec calls this "auto-created". 

Here's an example: https://hashscan.io/mainnet/account/0.0.6271006?ph=1&pt=1&p1=1&k1=1719413387.478646003

### Solution

Update memo on transactions which auto-create an account. 

from: `lazy-created account`
to: `auto-created account`

**Comment by netopyr** [comment]
We discussed this and agreed that the memo field can be left empty instead of setting `lazy-created account` or `auto-created account`.
