### ISSUE TITLE
AddressBookService should be in package `proto` for SDK consistency

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-services#14087]
While it is not necessary to place every new service in the same package as every existing service; the team would prefer to keep the services in the SDK grouped in the `proto` namespace for the time being to minimize confusion or mistakes on the part of SDK developers.

To that end, we need to change the `package` value [on line 3](https://github.com/hashgraph/hedera-protobufs/blob/main/services/address_book_service.proto#L3) of the `address_book_service.proto` file to `package proto;`.
We _may_ also remove the `proto` prefix from `Transaction` and `TransactionResponse` on lines 134, 145, and 157 (see image below), but this is not strictly necessary.
![image](https://github.com/hashgraph/hedera-services/assets/121976561/740e0741-a5fe-4273-95dd-eaa61cf26ebd)

This change should not affect any other protobuf files, but will have small effects in the Address Book service definition that must be coordinated.

**Comment by iwsimon** [comment]
hedera-protobufs pr 386 fixed this.
