### ISSUE TITLE
Reconnect Failure Flapping Network Connection when teacher has lower node id. 

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#14094]
This issues is to do root cause analysis and determine what the correct fix is for the bug filed. 

### Description

*What Happens*

A new node to the network is attempting to perform a reconnect.  The teacher node experiences multiple socket exceptions for failing to read from the new node. The teacher node re-establishes connection with the new node since its node id is lower than the new node.  Repeat this pattern multiple times. 

*What Should Happen* 

The lower ID node teaches the new node and no socket exception occurs. 

### Steps to reproduce

This is unverified, but the pattern happens frequently. 

1. Add a new node to the network with a high ID. 
2. Wait for it to reconnect with a lower id node as teacher. 
3. Watch the logs indicate a flapping network connection.  

### Additional context

<img width="1547" alt="Screenshot 2024-07-01 at 8 06 53 AM" src="https://github.com/hashgraph/hedera-services/assets/123979964/b410cfff-eb5b-45c2-950b-e63e0b26de8d">

### Hedera network

other

### Version

develop

### Operating system

None

**Comment by edward-swirldslabs** [comment]
http://35.247.76.217:8095/swirlds-automation/develop/10N/MultiSBReconnect/20240627-060037-GCP-Daily-MultiSBReconnect-3R-10N/FCM-MultiSBReconnect-3R-1k-20m/swirlds-logs.html

Same pattern of failure in reconnect but not due to a new node being added to the network.

**Comment by edward-swirldslabs** [comment]
http://35.247.76.217:8095/swirlds-automation/release/0.52/5N/MinStake/20240629-103320-GCP-RestartWithNewNodes-MinStake-5N/NFT-Restart-Stake-2.5k-10m/swirlds-logs.html

Node for flaps trying to learn from node 3 long enough to cause a old signed state exception.

**Comment by litt3** [comment]
Another occurrence:

http://35.247.76.217:8095/swirlds-automation/release/0.51/4N/Reconnect/20240717-091408-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

**Comment by lpetrovic05** [comment]
> http://35.247.76.217:8095/swirlds-automation/develop/10N/MultiSBReconnect/20240627-060037-GCP-Daily-MultiSBReconnect-3R-10N/FCM-MultiSBReconnect-3R-1k-20m/swirlds-logs.html
> 
> Same pattern of failure in reconnect but not due to a new node being added to the network. Node 2 trying to reconnect with node 1, node 1 can't read and has socket exceptions.

The test failed with the following message:
```
<<ERROR>>
Node 2 was expected to reconnect at least 2 times.  (reconnect count: 1)
```
The only issue I see here is that the test expects the node to fall behind and reconnect twice, but it seems to only happen once

**Comment by lpetrovic05** [comment]
> http://35.247.76.217:8095/swirlds-automation/develop/10N/MultiSBReconnect/20240627-060037-GCP-Daily-MultiSBReconnect-3R-10N/FCM-MultiSBReconnect-3R-1k-20m/swirlds-logs.html

This was referring to this test: http://35.247.76.217:8095/swirlds-automation/develop/10N/MultiSBReconnect/20240627-060037-GCP-Daily-MultiSBReconnect-3R-10N/FCM-MultiSBReconnect-3R-1k-20m/swirlds-logs.html

**Comment by lpetrovic05** [comment]
Also, connections seem to be breaking while we are trying to pause gossip

**Comment by anthony-swirldslabs** [comment]
I'm going to be adding extra logging per https://github.com/hashgraph/hedera-services/issues/14304 which may (or may not) help get better diagnostics for this issue.

**Comment by lpetrovic05** [comment]
I think I know what the issue might be. The class `SyncPermitProvider` has these methods:
```
    /**
     * Release a permit. Should be called exactly once for each call to {@link #acquire()} that returns true.
     */
    public synchronized void release() {
        if (usedPermits == 0) {
            throw new IllegalStateException("No permits to release");
        }
        usedPermits--;
        updateMetrics();
    }

    /**
     * Blocks until all permits have been released.
     */
    public void waitForAllPermitsToBeReleased() {
        while (true) {
            synchronized (this) {
                if (usedPermits == 0) {
                    return;
                }
                try {
                    MILLISECONDS.sleep(10);
                } catch (final InterruptedException e) {
                    Thread.currentThread().interrupt();
                    throw new RuntimeException("interrupted while waiting for all permits to be released", e);
                }
            }
        }
    }
```

The method `waitForAllPermitsToBeReleased()` sleeps inside the `synchronized` block. When it wakes up, it most likely acquires the lock again immediately. This means that gossip threads are blocked on calling `release()`. This makes them unresponsive, so connections break due to timeouts. It would also cause the wait for take really long potentially.

Simply moving the sleep out of the lock should fix the issue.

**Comment by edward-swirldslabs** [comment]
The notify/wait on a lock is also an option.

https://howtodoinjava.com/java/multi-threading/wait-notify-and-notifyall-methods/
