### ISSUE TITLE
Drive decision on single VirtualMap or binary tree

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#14099]
This ticket is complete when there is a decision by the system architects. The work for the assignee is to drive the conversation, setup meetings, participate in performance test, etc - anything required to get a decision made.

A decision matrix would be helpful. There are some pros and cons apart from performance. This ticket includes documenting these pros and cons. Some are listed below.

Cons to a single Virtual Map:
1. Lose the ability to have small state proofs that are local to a small virtual map
2. It's cheaper to rehash a smaller, specific virtual map when changes are made

Pros to a single Virtual Map:
1. Average depth goes down

**Comment by litt3** [comment]
Decision has been made to proceed with the large virtual map strategy.
