### ISSUE TITLE
Scheduled Transactions

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#141]
[Design of Scheduled Transactions](https://hederatest.sharepoint.com/:w:/s/Engineering/ERWJhHEFy3tJlvRsaKNBw5kBTKsP9nW7zdgQN9sWnlXvVg?e=wK3P9m)

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
