### ISSUE TITLE
CI: create a manually triggered workflow to promote an existing alpha or ad-hoc artifact to the builds.hedera.com bucket

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/hedera-services#14120]
### Problem

currently we need to manually promote an existing ad-hoc or alpha artifact to builds.hedera.com bucket.

### Solution

provide a manual workflow that can be ran that will promote an existing ad-hoc or alpha artifact to builds.hedera.com bucket.

relates to: https://github.com/hashgraph/solo/issues/415

**Comment by rbarkerSL** [comment]
@jeromy-cannon is this still needed?

**Comment by jeromy-cannon** [comment]
closing, I don't think we want to proceed with this at this time
