### ISSUE TITLE
Make StakingValidator static

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#14127]
The class `StakingValidator` has no internal state, and all methods can be turned into static methods. With this change, we would also not have to inject an instance.

**Comment by HarshSawarkar** [comment]
Hi, I would like to work on this issue. Could you assign it to me?

**Comment by HarshSawarkar** [comment]
Hi, I have raised a PR for this issue. Could you please review it? Here's the link https://github.com/hashgraph/hedera-services/pull/14159

**Comment by netopyr** [comment]
@HarshSawarkar, thanks again for your contribution. If you are interested, I will review our open issues and mark more with `Good First Issue` shortly.

**Comment by HarshSawarkar** [comment]
Hi @netopyr , 
Thank you for the opportunity! I would love to work on the issues and contribute. Looking forward to seeing the list!
