### ISSUE TITLE
Create Test Plan for DAB

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#14172]
### Problem

We need to have a test plan for the tests, covering the testing activities for HIP-869.
- HIP: https://hips.hedera.com/hip/hip-869
- Test Plan Document: https://www.notion.so/limechain/HIP-869-Test-Plan-Dynamic-Address-Book-a96e0052092c4cb8adafd8e18eea3b06?pvs=4

### Solution

Write a document listing all necessary tests to be implemented.

**Comment by iwsimon** [comment]
Closed as the Test Plan is completed.
