### ISSUE TITLE
Add a query to get (return) Smart Contract state

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#142]
- Create a query to get the state of a smart contract. 

- Add an optional "state" parameter (which is a file ID) to contract create that will read the initial state from a file

- Add a “frozen” boolean to smart contracts, which can optionally be set to true or false in update (if signed by admin key) or in create, and reject any contract function call that occurs while it is frozen. This would allow an admin to freeze it, then get the state, then transfer that state to HCS, and be assured that no transactions will be lost.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
