### ISSUE TITLE
Skip Codacy Checks on Forked PRs

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/hedera-services#14293]
## Background

On forked PRs codacy fails

## Request(s) and Intent

Some of the checks like the Codacy reporter need an additional if condition added in order to be skipped on forked PRs (this will need to be done for any step which requires access to secrets)

## Acceptance Criteria

- [ ] Codacy is skipped on forked PRs

**Comment by san-est** [comment]
I've reviewed the repository and the task and I believe Codacy is setup via GUI only for this repo. What this means is that we may still skip Codacy checks on forked PRs but we would have to make the configuration through the GUI itself and we cant use the if statement in a workflow.
I don't believe I have access to the configuration through: [Codacy GUI](https://app.codacy.com/gh/hashgraph/hedera-services/coverage/commits)

Maybe something we can review together.
