### ISSUE TITLE
Invalid required transaction fee returned by precheck with INSUFFICIENT_TX_FEE status code

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-services#1430]
**Summary of the defect**

The current open-review master branch of hedera-services has manifested a regression where the required cost of a transaction returned by precheck when the transaction fee is insufficient is now incorrect.

**How to reproduce (if possible)**
Submit a transaction with a small fee such as one tb, retrieve the cost returned by the INSUFFICIENT_TX_FEE error and use it as the transaction fee value to resubmit the same transaction.  Expectation would be the transaction succeeds, however it still fails with INSUFFICIENT_TX_FEE -- but this time it is not a precheck failure - a failure on transactionGetReceipt instead - perhaps that is a hint to the problem.

**Log**
```
5/17/2021 11:47:48 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1621295268", "nanos": 741394600 }, "accountID": { "accountNum": "2300" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "1", "transactionValidDuration": { "seconds": "120" }, "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "4885" }, "amount": "-9" }, { "accountID": { "accountNum": "2300" }, "amount": "9" } ] } } }
5/17/2021 11:47:48 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "3UFI6d1HVxpYI3HMTKnHu4jvDE+VIx1ogxpwozcHpRob4CZHySKj2Ebd8hXxr5SHfTPkTrxELvfr7Pr+UxUBAw==" }, { "pubKeyPrefix": "6A==", "ed25519": "VnHmoBHgqqW9lzCDI6nsQ38+KYDuk+H7o6GvO7W3ngtmD79MckD86xE/GrsjkLJL7x3uRA4soJSoUWZe0wZoCQ==" } ] }
5/17/2021 11:47:48 PM  RX:(00)  { "nodeTransactionPrecheckCode": "INSUFFICIENT_TX_FEE", "cost": "122510" }
5/17/2021 11:47:48 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1621295268", "nanos": 775090800 }, "accountID": { "accountNum": "2300" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "122510", "transactionValidDuration": { "seconds": "120" }, "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "4885" }, "amount": "-9" }, { "accountID": { "accountNum": "2300" }, "amount": "9" } ] } } }
5/17/2021 11:47:48 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "nTTVD+kYcTEwfcVPVnNyFNwehaAzrL4/sQ2U+hE0YIRVt/rQiVV2tYqMMoVwRLXSG38xxLt4MSiB7x5GDqITAA==" }, { "pubKeyPrefix": "6A==", "ed25519": "RGSt2/ipUyYN6nCusQCLCpasknBF0EqhRtaagGyRKnIMVu5YrNVo8hoaZgodEue3poU0Rgpx+9ExCV4oXbBqCQ==" } ] }
5/17/2021 11:47:48 PM  RX:(00)  { }
5/17/2021 11:47:48 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1621295268", "nanos": 775090800 }, "accountID": { "accountNum": "2300" } } } }
5/17/2021 11:47:48 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
5/17/2021 11:47:49 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
5/17/2021 11:47:49 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
5/17/2021 11:47:50 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "INSUFFICIENT_TX_FEE", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
...
```
**Environment:**
Docker on Ubuntu 20.04
HAPI/Services TAG=v0.11.0-1607-g618a8b16d-dirty

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by bugbytesinc** [comment]
This also manifests in **preivewnet**

**Comment by bugbytesinc** [comment]
V 14 on **testnet** manifests this bug as well.

**Comment by tinker-michaelj** [comment]
Hi @bugbytesinc, this is a result of changing precheck to validate only that the given `transactionFee` will cover the [network and node fees](https://github.com/hashgraph/hedera-services/blob/master/docs/transaction-prechecks.md); but not necessarily the service fee.

(A node's only responsibility in precheck is to verify it can submit a transaction without _itself_ being charged any fees at consensus. And as long as it submits a transaction that will cover the network and node fees, this condition is met.)

So the semantics of this scenario are essentially:
1. Client: "Please submit this transaction, I will pay 1tb."
2. Node: "No way, I'll be charged the network fee if I submit that! I need at least 122510tb to even consider it."
3. Client: "Ok, please submit at that price."
4. Node: "<shrug> Don't mind if I do, at least I'll get paid."
5. Network at consensus: "Ok, but where's the service fee?"

**Comment by qnswirlds** [comment]
Thanks @tinker-michaelj for the explanation! @bugbytesinc, if you think our answer is satisfiable, please close the issue. Thanks!

**Comment by bugbytesinc** [comment]
This is a regression from previous behavior.  The documentation states this value as:
```
uint64 cost = 2; // If the response code was INSUFFICIENT_TX_FEE, the actual transaction fee that would be required to execute the transaction.
```

If the value of "cost" does not include all the necessary fees to execute the transaction as indicated in the doc, than what value does it have at all?  How is a system expected to self-heal from having too low of a xfer limit without this information?

**Comment by tinker-michaelj** [comment]
@bugbytesinc There is some divergence between,

1. The self-interest of a node operator, which is just to receive node fees for submitting transactions with payers that can be charged network and node fees; and,
2. The ease-of-use for a network client.

Especially in a future with permissionless nodes and high network utilization, this divergence could be material; and the plan is to only **require** node operators to do enough work in precheck to protect their self-interest. (Of course, some node operators might voluntarily do more work in a proxy service layer, maybe to attract more traffic.) 

So this is just a step in that direction...service fees may become significantly harder to estimate accurately pre-consensus, and we wouldn't expect nodes to do that work.

All that said, if we are concerned this will break clients in the present, I can definitely escalate to Product and re-evaluate the timing/staging of these kinds of changes.

**Comment by bugbytesinc** [comment]
From a client/consumer point of view: if the value returned in `cost` does not reflect a number that I must use in order to have a successful outcome, then it has little utility, and would appear to cause confusion (this conversation is an example).  So if as you point out, the cost of computing the value may become problematic in the future to compute at precheck; then perhaps, to simplify matters, I'd ask that you consider to remove it from the spec.  It will save on transmission and computational fees.

Also, I'm not sure if the documentation points it out, if so I've missed it, it should be noted that indeed one can submit a transaction with a fee limit high enough to be accepted but not enough to execute fully **AND** the act of sending the transaction will result in at least the submission fees being deducted from the payer account, even if the transaction execution fails.
