### ISSUE TITLE
Include hash of payload in payloadWrapper

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#14385]
Since Hedera will need to hash payloads/transaction, and the platform does this when hashing events, we should include the hash of the payload in the payload wrapper. This way, Hedera can avoid hashing it again, thus saving CPU time.

Must be done after [this task](https://github.com/hashgraph/hedera-services/issues/14426), because the payload wrapper does not currently store the `EventPayload`, just a `OneOf`.

**Comment by poulok** [comment]
Blocked by #14426
