### ISSUE TITLE
TSS-Roster: project breakdown

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/hedera-services#14494]
Breakdown the TSS-Roster project into tickets such that each can be implemented within a sprint, and point the stories with the team. These stories should be part of a single epic.

**Comment by anthony-swirldslabs** [comment]
First revision is out for review: https://docs.google.com/spreadsheets/d/1SkYn8_I3uVQLkZwktOTFk2ZBldf9dYXw05meUwgdiNs/edit?gid=0#gid=0

**Comment by kfa-aguda** [comment]
do you want to break these down into actual tasks? The entries in the excel sheet seem broad. Are each expected to be epics? Happy to sync up tomorrow to draft them as concrete tasks

**Comment by anthony-swirldslabs** [comment]
@kfa-aguda : I've updated the document and replied to your comments in the doc. Please have a look.

**Comment by anthony-swirldslabs** [comment]
Tasks from https://docs.google.com/spreadsheets/d/1SkYn8_I3uVQLkZwktOTFk2ZBldf9dYXw05meUwgdiNs/edit?pli=1&gid=0#gid=0

have been translated into GitHub stories under a new epic at https://github.com/hashgraph/hedera-services/issues/14706
