### ISSUE TITLE
Regression test result validation and analysis

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#145]
- [ ] Criteria to validate the regression test results;
- [ ] Reporting, if any, for each regression test run;
- [ ] Reporting and diagrams for historic  regression test runs; 
- [ ] Overview of all log download + analysis currently done by Hedera testrunners, especially CircleCI workflows.

**Comment by anighanta** [comment]
doc [here](https://github.com/swirlds/swirlds-platform-regression/blob/develop/docs/regression-validation-checklist.md)
