### ISSUE TITLE
Add a flag to ServiceEndpoint to indicate if port is plaintext or TLS

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-services#1452]
**Summary**
As a client to HAPI, I want to be able to pull the address book and use its list of endpoints to start a gRPC channel and send transactions. The nodes have both insecure (50211) and secure (50212) ports. When setting up the gRPC channel I need to know whether the channel should be plaintext or use transport security (TLS). I can make an assumption that the well known port 50212 is TLS and vice versa, but this assumption might not hold true when we have community nodes.

```java
ManagedChannelBuilder.forTarget(address).usePlaintext().build();
```

vs

```java
ManagedChannelBuilder.forTarget(address).useTransportSecurity().build();
```

**Possible resolution**
Add a flag to the `ServiceEndpoint` proto to indicate if that endpoint is secured or not:

```proto
message ServiceEndpoint {
    bytes ipAddressV4 = 1;
    int32 port = 2;
    bool secure = 3;
}
```

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
