### ISSUE TITLE
Many VirtualMap / MerkleDb metrics are missing in grafana

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/hedera-services#14520]
A few examples of missing / zero metrics:

* virtual_map_vmap_size_TokenService_ACCOUNTS
* virtual_map_vmap_lifecycle_flushDurationMs_TokenService_ACCOUNTS
* merkle_db_ds_files_totalSizeMb_TokenService_ACCOUNTS
* merkle_db_ds_flushes_hashesStoreFileSizeMb_TokenService_ACCOUNTS

These metrics are not available, or not set (or sometimes set to zero) in both production and pre-production grafana instances, for all networks. The only exception is `engnet1`, which was started to run my branch about an hour ago. It shows all metrics just fine. It means, there are no issues with VirtualMap / MerkleDb, the metrics are produced correctly, but there are issues with exporting them from the process or importing to prometheus / grafana.

The branch was synchronized with develop a few hours ago, but there are no metrics specific changes in the branch. The test was started from a genesis state. When the same branch was running in the same network two days ago (but from an existing state), the metriss were not available.

**Comment by artemananiev** [comment]
This is not a recent regression, the metrics haven't been available for months now.

**Comment by poulok** [comment]
This ticket probably needs to be worked with someone from @dalvizu's team, and maybe even someone from @netopyr's team
