### ISSUE TITLE
Unable to connect to local network

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-services#1453]
Hey, I'm working on testing the `master` branches of the Hedera SDK against Hedera Services. I've been following the docker guide closely since this will be run inside GitHub Actions, and so far I've been able to start up the network against the latest commit on `master` by tagging the latest commit as `MASTER` and updated `.env` to contain `TAG=MASTER`. However, I am unable to connect to this local network with the SDK. I noticed that `*/config.txt` declares the nodes and their relevant ports and I tried to connect to those ports with no luck.

My `./hedera-node/configuration/compose/config.txt`
```
###############################################################################################
# Configuration file, for automatically running multiple instances
###############################################################################################
swirld, hedera
app, HederaNode.jar
address, A, Alice, 1, node_0, 50204, node_0, 50204, 0.0.3
address, B, Bob, 1, node_1, 50205, node_1, 50205, 0.0.4
address, C, Carol, 1, node_2, 50206, node_2, 50206, 0.0.5
#address, D, Dave, 1, 172.20.0.0, 50207, 70.240.247.13, 50207, 0.0.6
#TLS, on

```

To be specific I've been trying to connect to `127.0.0.1:50204`, but I am unable to. I could be doing something wrong that I'm unaware of.

**Comment by tinker-michaelj** [comment]
Hi @danielakhterov, the ports listed in the _config.txt_ are the gossip ports for the Swirlds platform.

The gRPC ports for Services, if using Docker Compose with the [default _docker-compose.yml_](https://github.com/hashgraph/hedera-services/blob/master/docker-compose.yml#L13), will be `50213` for node account `0.0.3`; `50214` for node account `0.0.4`; and `50215` for node account `0.0.5`.

Feel free to ping me out-of-band if you are blocked. 👍

**Comment by danielakhterov** [comment]
Ah, I definitely missed that. Thanks for the quick explanation.
