### ISSUE TITLE
Create Epics for the implementation of the TSS-Ledger-ID platform proposal

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#14539]
[Conditional TSS Candidate Roster Adoption](https://github.com/hashgraph/hedera-services/issues/14540)
[Manual Bootstrapping for Existing Networks](https://github.com/hashgraph/hedera-services/issues/14542)

**Comment by anthony-swirldslabs** [comment]
Both look good to me.

**Comment by edward-swirldslabs** [comment]
complete
