### ISSUE TITLE
Reduce size of transaction receipt cache

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#14541]
### Problem

We currently use a `QueueState<TransactionRecordEntry>` in state; but this is significantly more information than is required to classify and handle duplicate transactions deterministically. 

### Solution

Define two new messages,
```
message TransactionReceiptEntry {
     /**
     * The ID of the node that submitted the transaction to consensus. The ID is the ID of the node as known by the
     * address book. Valid node IDs are in the range 0..2^63-1, inclusive.
     */
    int64 node_id = 1;

    /**
     * The id of the submitted transaction.
     */
    TransactionID transaction_id = 2;

    /**
     * The resulting status of handling the transaction.
     */
    ResponseCodeEnum status = 3;
}
```

And,
```
message TransactionReceiptEntries {
    repeated TransactionReceiptEntry entries;     
}
```

Use instead an `QueueState<TransactionReceiptEntries>` where each round accumulates changes for one new `TransactionReceiptEntries`; and we purge entire rounds of receipts at the point the youngest receipt (the latest consensus time) in the round is expired.

**Comment by jasperpotts** [comment]
The new queue should be built using the States API not using FCQueue directly any more.

**Comment by tinker-michaelj** [comment]
> The new queue should be built using the States API not using FCQueue directly any more.

Ah yes I just typed `FCQ` out of long habit 😅, will be a `QueueState`.
