### ISSUE TITLE
Modifying existing workflows

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/hedera-services#14571]
look at all workflows currently running on push to develop

Runs minimal acceptable test suite
  - MATS runs do not use tags since they execute on every PR/commit merged to main

Look at breaking the unit test flows into independent parts
- MATS
- Hammer
- Long Running
- Performance
- Smoke
- Fuzz

look at how/where jacoco/codecov tasks are called?

look at how/where adhoc release is called
- ensure adhoc release runs after all testing iff all pre-tests are passing
- ensure publishing jacoco/codecov results as build artifact in github actions

Closes with #14570

**Comment by jjohannes** [comment]
Once #5009 is merged, we'll have a consistent (and minimal) _test set_ setup for the tests we have right now. My suggestion as next step would be to get a minimal first version of this CI stage implemented:

> - Execute once every 3 hours
> - Grab the latest untested commit from develop

And then setup:

- PR builds runs:
  - `test`
- New  "3 hours" stage runs:
  - `timeSensitive` 
  - `hammer` 
  - `iTest` 

After this solution is implemented, we already are in a state where:
- PR builds are quicker than now (no more _timeSensitive_ tests)
- ALL tests are executed at some point (including _hammer_ and _itest_)

Splitting the test buckets differently can then be discussed and done in the next step. This is more a conceptual question then (what test sets do we want and how are they named? How and who moves tests around? Etc).
