### ISSUE TITLE
Address mono service fidelity future/todo comments

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#14661]
Address the following todo/future comments

| app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersCall.java | 235 | // (FUTURE) Remove this divisor special case, done only for mono-service fidelity        |
|---------------------------------------------------------------------------------------|-----|------------------------------------------------------------------------------------------|
| app/service/contract/impl/exec/systemcontracts/hts/create/ClassicCreatesCall.java     | 126 | // (FUTURE) remove after differential testing, mono-service used the entire              |
| app/service/contract/impl/exec/scope/HandleHederaNativeOperations.java                | 140 | // FUTURE: For temporary backward-compatibility with mono-service, consume an entity id  |
| app/service/contract/impl/handlers/ContractCallHandler.java                           | 75  | // (FUTURE) Remove ExternalizeAbortResult.NO, this is only                               |
| app/service/contract/impl/utils/SynthTxnUtils.java                                    | 158 | // TODO - for mono-service equivalence, need to set the initial balance here             |

**Comment by david-bakin-sl** [comment]
Does [`ContextTransactionProcessor.call()` @L129](https://github.com/hashgraph/hedera-services/blob/b050024dcb781a8718cad351a282f1b45aa8959a/hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/ContextTransactionProcessor.java#L129) belong in this issue or some other?

> `// For mono-service fidelity, externalize an initcode-only sidecar when a top-level creation fails`
