### ISSUE TITLE
Create RosterMap map and RosterState singleton for States API (java code + register new named entities in States API)

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/hedera-services#14707]
Unsure about the States API-related process to create new named entities, so the estimate may be unclear.

**Comment by lpetrovic05** [comment]
This ticket does not provide much information

**Comment by kfa-aguda** [comment]
@lpetrovic05 i added some more description to the PR (https://github.com/hashgraph/hedera-services/pull/14861)
