### ISSUE TITLE
Work with Release Eng: research needed updates in JRS not to read config.txt on upgrades

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/hedera-services#14719]
This story assumes that the code to write a config.txt in preparation for an upgrade (added in Dynamic Address Book Phase 2) has been removed. Therefore any code that expects to copy a config.txt written by services to the startup location must be updated to NOT expect it.

This task is an investigation task to figure out what needs to happen in JRS and Solo given that the config.txt is no longer written in preparation for upgrade. There may be address book testing tool tests that need to be updated or deleted if they are obsolete.

Should be worked in conjunction with #14718 and #14721

**Comment by edward-swirldslabs** [comment]
This issue is subsumed by https://github.com/hashgraph/hedera-services/issues/16373 in the replanned work.
