### ISSUE TITLE
Implement unconditional adoption of the candidate roster at software upgrade (in addition to the existing config.txt logic for now)

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/hedera-services#14712]
If CR is present, adopt and use it as a new active roster, otherwise follow the existing config.txt-based logic.

Need to consider the scenario where the config.txt on disk has changed to ensure we can still upgrade and modify the address book according to the current process until everything is ready to switch to the new paradigm.

Edit
There has been a slight change in the design of the feature this issue was originally intended to address. The introduction of Consensus vs Execution brings some responsibility changes as it relates to which component(?s) will determine the active roster. 

A new logic will be introduced as part of the implementation of this issue that will arrive at the active Roster for the platform based on the genesisRoster, overrideRoster, active roster stored in state, or in-state candidate roster getting adopted. The details of exactly how to implement this will need to be discussed.

**Comment by kfa-aguda** [comment]
moving this back to backlog as it's now going to be implemented in future. Whether this is now going to be done by Spacetime or other team is yet to be determined.

**Comment by poulok** [comment]
The plan is for Team Spacetime to do this work.

**Comment by edward-swirldslabs** [comment]
This ticket is subsumed by https://github.com/hashgraph/hedera-services/issues/16355 in the replanned work.
