### ISSUE TITLE
Work with Services: create a task for services to use the API for installing the candidate roster and assign it to a Services engineer

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/hedera-services#14717]
This ticket is complete when there is a ticket in the services backlog for using the API. This also includes removing code that writes a config.txt in preparation for an upgrade.

This heavily depends on how and when Services want to abandon config.txt

**Comment by edward-swirldslabs** [comment]
This task is subsumed by https://github.com/hashgraph/hedera-services/issues/16371 in the replanned work.
