### ISSUE TITLE
Research the best testing framework for Roster integration tests (HAPI, JRS, ???)

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/hedera-services#14715]
Needs to be lightweight and long-term, and easy to use/run tests locally. HAPI tests seem to fit the bill. JRS seems too heavy.

HAPI tests should be able to cover the functionality. There are already HAPI test that perform a pseudo-upgrade and there are tests that exercise the new Dynamic Address Book feature using transactions to modify the address book. We should be able to combine these types of tests and inspect the resulting address book written to disk in the saved state directories.

**Comment by edward-swirldslabs** [comment]
This work is subsumed by the replanned integration testing description.
