### ISSUE TITLE
Refactor Services code to call the new IOC-enabled entry point to start the Platform

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/hedera-services#14714]
Follow on task to https://github.com/hashgraph/hedera-services/issues/14713

Move all the logic from the old entry point (that old buildComponentBuilder() method that now only reads state/config.txt/keys) to Services, so that this code is gone from Platform, and Services only ever call the new IOC-enabled newPlatformStartup() method introduced in the previous task.

After this task, the Platform deals with Rosters only. It doesn't know about AB at all.

**Comment by edward-swirldslabs** [comment]
This issue may be superceded by this code change: https://github.com/hashgraph/hedera-services/pull/15325

**Comment by edward-swirldslabs** [comment]
this issue is subsumed by https://github.com/hashgraph/hedera-services/issues/16357  in the replanned work.
