### ISSUE TITLE
Work with Services: discuss, agree, and document an approach for config.txt (on when and how to deprecate it)

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/hedera-services#14718]
When this ticket is complete, there should be agreement between services and platform on the approach.

**Comment by edward-swirldslabs** [comment]
Once https://github.com/hashgraph/hedera-services/issues/16371 is implemented and the feature flag is turned on, `config.txt` will never be written or used read from on subsequent software upgrades.   `genesis-config.txt` and `override-config.txt` will have the same file format for the near future.   Modification of the file format for these files should come in the proposal for importing/exporting TSS network configuration and hedera address book. 

This ticket is closeable.
