### ISSUE TITLE
Refactor PlatformBuilder for IOC by extracting config.txt/AB-related logic that will call a new IOC-enabled entry point

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/hedera-services#14713]
Updated Ticket Description: 

Services has already performed part of the Inversion of Control work.  See the issue linked in the comment down below. 

What's left to do is to finish the IoC work after the platform is using Roster, translate the Address Book from config.txt to Roster and only use roster in the platform startup.    This will have to wait until the platform is refactored to not use the address book format. 

----------------
Everything below here is part of the original ticket description.  
----------------

Current logic:
```
void buildComponentBuilder() {
    doEverything();
}
```

After this task:
```
// that old method from above
void buildComponentBuilder() {
    readConfigTxt();
    readState();
    readKeys();
    newPlatformStartup(state, genesisRoster, overrideRoster, keys);
}

// New, IOC-enabled entry point
void newPlatformStartup(state, genesisRoster, overrideRoster, keys) {
    doThatEverythingStuffUsingTheNewInputArgs();
}
```

This code will remain in the platform but will be refactored so that it is easy to move to services in a follow up ticket.

**Comment by edward-swirldslabs** [comment]
I'll need to take into account these code changes: https://github.com/hashgraph/hedera-services/pull/15325

**Comment by edward-swirldslabs** [comment]
This ticket is subsumed by https://github.com/hashgraph/hedera-services/issues/16357 in the replanned work.
