### ISSUE TITLE
Work with DevOps: to not move config.txt on upgrade

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/hedera-services#14721]
Create some informal documentation that describes the impact on DevOps (no more config.txt to copy on upgrade), and ensure this is effectively communicated to the devops team. They should understand and create tickets in their KanBan board for accomplishing the work, which should be reviewed by our team for accuracy.

**Comment by edward-swirldslabs** [comment]
This issue is subsumed by https://github.com/hashgraph/hedera-services/issues/16372 in the replanned work which creates more robust documentation to be consumed by DevOps and SOLO developers.
