### ISSUE TITLE
Convert all legacy tests to EET

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#1472]
- [x] Smart contracts (#1469)
- [x] Files (#1470)
- [x] Crypto (#1471)

**Comment by qnswirlds** [comment]
@anighanta, @ljianghedera, @tinker-michaelj, @Neeharika-Sompalli, I believe we have already converted almost all legacy tests to EET. Could you please go through this (nested) list to see what we have converted and close the corresponding issue? Thank you!

**Comment by ljianghedera** [comment]
Yeah, I am about to close this one as well. Anirudh and I have converted almost all of them except one or two.

**Comment by qnswirlds** [comment]
Thanks @ljianghedera for confirming! Please go through the list carefully and close out those issues that are done. Please leave those that are undone open. Thanks!

**Comment by qnswirlds** [comment]
There are some left-over work from #604 that are tracked by #661.

**Comment by ljianghedera** [comment]
@qnswirlds yes, I was thinking if we should still keep this issue (#1472) open and need to address #661 before we completely close #1472. For other sub-issues, I guess we don't need to keep them all open.

**Comment by qnswirlds** [comment]
I prefer to just keep them both open for now.
