### ISSUE TITLE
TSS Service Startup Implementation

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#14751]
Add startup logic for 
* testing conditions of adopting candidate roster that has been keyed and TSS-Ledger-ID feature flag on.
* state changes for adopting candidate roster, ledger id,  and cleaning up state 

- [x] #16823
- [x] #16845
- [x] https://github.com/hashgraph/hedera-services/issues/16553

**Comment by MiroslavGatsanoga** [comment]
Blocking since we need `TSS-Roster` [epic](https://github.com/hashgraph/hedera-services/issues/14706) of work to be completed before this issue can be worked on.
