### ISSUE TITLE
Validate account balances in StateValidationTool

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#14793]
It will be nice to have , if the StateValidationTool can check if 
1. any account has negative balance
2. sum of balances of all accounts is equal to `ledger.totalTinyBarFloat=5000000000000000000`

**Comment by imalygin** [comment]
Currently we have `TotalHbarSupplyIs_50B` which already calculates the total amount on all account. We should rename this class to `AccountValidator`  and rename its tag from `totalSupply` to `account` as well) and add one more assert that checks that there are no negative balances.
