### ISSUE TITLE
Avoid use of Stream.sorted() in perf-critical path

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1498]
**Summary**
Instead of using `Stream.sorted()` in `TransactionalLedger.commit()`, it will be more efficient to simply keep an `ArrayList` of changed keys and sort that.

**Comment by qnswirlds** [comment]
We should change the title of this issue, because the refactoring also includes replacing `stream().map...`. Anyway, this is a good one! I personally think stream is convenient and short in writing code, but a for loop is faster for performance.
