### ISSUE TITLE
EventDescriptor variables order reversed

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#15013]
### Issue

In release `0.53`, the `EventDescriptor` PBJ object is being wrongly populated. The variables `birthRound` and `generation` have been switched. This is happening in this [line of code](https://github.com/hashgraph/hedera-services/blob/3747e61503c22d5424d7cd3ff3d0d04c5909f5f7/platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/UnsignedEvent.java#L156).

In this release, this data is not used for anything else but hashing. So the impact of this only on the hash of the event. This is not compatible with current develop where the order hash been fixed, so the hash of an event is calculated differrently.

### Solutions

There are 2 possible solutions:
- Make a tiny code change in release `0.53` to reverse the order of these variables
- Change the order of the variables in subsequent releases, so that the protobuf remains the same, but the variables are mapped correctly. EDIT: upon further inspection, `generation` has an ordinal of `17` because there is an intent to remove it. changing the order would mess up this plan.

**Comment by anthony-swirldslabs** [comment]
It would be best to never use model constructors to prevent bugs like this. The builder available in every PBJ model could help ensure proper values are assigned to proper fields.

**Comment by lpetrovic05** [comment]
> It would be best to never use model constructors to prevent bugs like this. The builder available in every PBJ model could help ensure proper values are assigned to proper fields.

makes sense
