### ISSUE TITLE
Fix remaining Bugs and Security issues in SonarCloud

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1507]
On `master` SonarCloud shows there are 12 bugs and 7 security hotspots remaining. Resolve the errors.

NOTE: While creating the branch to address the issue, start branch name with branch so that sonar cloud compares the issues on master are resolved.

![image.png](https://images.zenhubusercontent.com/5e444a92cb1e040013d0dad5/13453cd5-5acd-46fe-a481-26dbfbc7b51d)

**Comment by anighanta** [comment]
Went through the list and I think that all of these remaining bugs can be ignored.
