### ISSUE TITLE
Record to indicate what contracts were deleted or created

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#151]
Currently if contract creates or deletes another contract executing solidity the contract id of newly created or deleted contract is not reflected anywhere , so there is no way to find out which transaction is responsible . Proposal add 2 new repeated fields  to ContractFunctionResult  
1 for contracts created , second one for contracts deleted

**Comment by qnswirlds** [comment]
A list of contracts that were created by the function call, namely `createdContractIDs`, was added in the `ContractFunctionResult` already.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
