### ISSUE TITLE
RCA for new(?) SleepCheckExceptions on master

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1514]
**Summary of the defect**
In e.g. https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1622540260034000 we see failures (under the umbrella `SleepCheckException`) that did not occur previously.

Prioritize diagnosis of these failures, esp to see if related to the `SleepCheckException`s on `master-plus-0.15.0-alpha.1`.

**Current understanding**
@ljianghedera cannot reproduce this error, suggesting a transient error that is not related to the `SleepCheckException`s that are happening on `master-plus-0.15.0-alpha.1`.

**Comment by ljianghedera** [comment]
In `master` branch, this failure can't be reproduced. Here are the slack summary that I've run several times with a branch from `master`. 

https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1622592252180400

So close it as it is not a high priority issue as of now.
