### ISSUE TITLE
Remove the nextNodeId line from the config.txt 

### ISSUE THREAD

**Issue by iwsimon** [hashgraph/hedera-services#15215]
The last line, nextNodeId, # in config.txt is not used by services. 
Since the next node id is now kept in the application state, there is no need to keep it in config.txt. 
Platform code checks this line. This line should be removed.

**Comment by poulok** [comment]
@edward-swirldslabs was this completed?

**Comment by edward-swirldslabs** [comment]
@poulok  I think it was discussed, but I didn't make a ticket for it or work it. Apologies if I was the one to drop the ball.
