### ISSUE TITLE
Support client determination of fees via a fee calculation module

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#153]
To enable clients to calculate fees based on the characteristics of transactions (& some queries) , we would like to make the fee calculation classes reuseable between services & the SDK . (and other clients)

Premise is that this module would take as input

a) a tx or query proto 
b) fee schedule
c) exchange rate

and output a dynamic fee in tinybars that reflected all the above

Clients could choose this model as an alternative to the current static high transactionFees.

We would like to open source this specific component to support 3rd party clients leveraging its functions

Does not replace COST_ANSWER

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
