### ISSUE TITLE
Eliminate busy loop in HalfDiskHashMap.endWriting()

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/hedera-services#15438]
`HDHM.endWriting()` has a busy loop. It was originally introduce to maximize thread throughput, while it was handling multiple HDHM buckets in parallel. However, it can be implemented more efficiently using tasks.

**Comment by alex-kuzmin-hg** [comment]
It's how endWriting() looks at ENGNET2 Tom's test (15 mins) in v0.53.4:
![image](https://github.com/user-attachments/assets/693f4186-5c28-44eb-b330-a1f64c724adf)

**Comment by alex-kuzmin-hg** [comment]
Now on performance Eng site: https://perf.analytics.eng.hashgraph.io/engnet2-20240906_175600/reports/com.swirlds.merkledb.files.hashmap.HalfDiskHashMap.html#448
