### ISSUE TITLE
Update workflows to publish and tag protobufs

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/hedera-services#15453]
We have the `hedera-protobufs-automation` service account in place in `hedera-protobufs` repo. 

Need to update the `node-flow-deploy-release-artifact.yaml` to checkout the main branch of github.com/hashgraph/protobufs in the following subdirectories
- platform
- services
- streams
- block

For each tag vA.B.C in hedera-services deployed to previewnet, this subset of protobufs will be automatically copied to the hedera-protobufs repo and the same tag vA.B.C created there on the main branch

Update the node-flow-deploy-release-artifact.yaml pipeline to include a step that checks out protobufs main, updates the folders owned by Services with (e.g. `rm -rf services/*`   and `cp -R ${SERVICES_ROOT}/hapi/hedera-protobufs/services/* services/`; then creates the target Services tag in the protobufs repo.

**Comment by mishomihov00** [comment]
@rbarkerSL @nathanklick Please check this comment - https://github.com/hashgraph/hedera-protobufs/pull/447#issuecomment-2462457251
