### ISSUE TITLE
`tss-library` `TssMessage` instances should be able to serialize/deserialize themselves

### ISSUE THREAD

**Issue by mxtartaglia-sl** [hashgraph/hedera-services#15506]
Implement these methods or equivalent:

`byte[] serialize(final TssMessage msg)`
`TssMessage deserialize(final byte[])`

Whether we will use protobuf on an internal serialization method depends on whats decided in: #15555.
We also discussed how the keys are serialized and the fact that using a custom serialization there provides a complication and no additional gain to incorporating protobuf only for messages.

**Comment by lpetrovic05** [comment]
Whatever the serialization ends up being, it must support version migration.
