### ISSUE TITLE
Check all usages of `getReadablePlatformState()` for thread safety

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#15620]
There is one known usage of `getReadablePlatformState()` on the mutable state that is not thread safe (Consensus Event Stream thread). An example of such unsafe usage is reading a value that could simultaneously be modified by another thread. The known unsafe usage causes no real problem. All other usages of `getReadablePlatformState()` on the mutable state should be evaluated for safety. We do not expect any, but we should be sure.

The mutable state is currently accessed via `SwirldStateManager.getConsensusState()`.

**Comment by thenswan** [comment]
I validated this by checking the logs for the following:  
1. **JRS**:  
   - `configs/suites/GCP-PRCheck-Abbrev-4N.json`  
   - `configs/suites/daily/4N/GCP-Daily-Reconnect-4N.json`  
2. **HAPI Tests**  

I can confirm that the Consensus Event Stream thread is the only known usage of `getReadablePlatformState()` on the **mutable** state.
