### ISSUE TITLE
Include some extremely long-lived entities in CI testing

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1565]
**Summary**
On mainnet some of the system accounts have expiration times of a billion years. 

This means that any incorrectly assessed `rbs` usage in a `CryptoUpdate` will result in astronomical fees.

**Suggested resolution**
Add a CI suite with some extremely long-lived entities and verify that `*Update` operations which don't increase `rbs` can be performed with a modest `transactionFee` of e.g. 1ℏ.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
