### ISSUE TITLE
TOPIC_FEE_008	TopicCreate with a fixedFee of 1 HBAR Sign with the transaction Payer.

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15663]
### Problem

TopicCreate with a fixedFee of 1 HBAR
Sign with the transaction Payer.

### Solution

Successful TopicCreate transaction.
A topic with a fixed fee of 1 HBAR should be created.

**Comment by ibankov** [comment]
Done.
