### ISSUE TITLE
TOPIC_FEE_017	TopicCreate with a custom fee and a fee collector account - a hollow account.

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15672]
### Problem

TopicCreate with a custom fee and a fee collector account - a hollow account.

### Solution

Successful TopicCreate transaction.
A topic with a fixed fee should be created.
The hollow account set as a fee collector account should not be finalised.

**Comment by ibankov** [comment]
Done.
