### ISSUE TITLE
TOPIC_FEE_018	TopicCreate with a custom fee and a fee collector account - an empty address.

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15673]
### Problem

TopicCreate with a custom fee and a fee collector account - an empty address.

### Solution

Successful TopicCreate transaction.
A topic with a fixed fee should be created.
The address set as a fee collector account should not have an account created on it.

**Comment by ibankov** [comment]
Not applicable
