### ISSUE TITLE
TOPIC_FEE_108	MessageSubmit to a topic with 10 different custom fees and each of them with 3 layers of custom fees. Each fee should be a different token. Each token should have a different fee collector account.

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15757]
### Problem

MessageSubmit to a topic with 10 different custom fees and each of them with 3 layers of custom fees. Each fee should be a different token. Each token should have a different fee collector account.

### Solution

Successful submitMessage transaction.
EOA should pay the specified fees to the specified fee collector accounts.

**Comment by JivkoKelchev** [comment]
This test is covered in issue #15516 and PR #15603.
