### ISSUE TITLE
TOPIC_FEE_109	MessageSubmit from token treasury to a topic with 3 layers of fees when the account is treasury for the 1st fee layer.

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15758]
### Problem

MessageSubmit from token treasury to a topic with 3 layers of fees when the account is treasury for the 1st fee layer.

### Solution

Successful submitMessage transaction.
The treasury should pay no fees.

**Comment by JivkoKelchev** [comment]
This test is covered in issue #15516 and PR #15603.
