### ISSUE TITLE
TOPIC_FEE_110	MessageSubmit from token treasury to a topic with 2 layers of fees when the account is treasury for the 2nd fee layer.

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15759]
### Problem

MessageSubmit from token treasury to a topic with 2 layers of fees when the account is treasury for the 2nd fee layer.

### Solution

Successful submitMessage transaction.
The treasury should pay the 1st fee layer.

**Comment by JivkoKelchev** [comment]
This test is covered in issue #15516 and PR #15603.
