### ISSUE TITLE
TOPIC_FEE_111	MessageSubmit from a fee collector account to a topic with 2 layers of fees when the account collects the tokens of the first layer

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15760]
### Problem

MessageSubmit from a fee collector account to a topic with 2 layers of fees when the account collects the tokens of the first layer

### Solution

Successful submitMessage transaction.
The fee collector should pay no fees.

**Comment by JivkoKelchev** [comment]
This test is covered in issue #15516 and PR #15603.
