### ISSUE TITLE
TOPIC_FEE_112	MessageSubmit from a fee collector account  to a topic with 2 layers of fees when the account collects the tokens of the second layer.

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15761]
### Problem

MessageSubmit from a fee collector account  to a topic with 2 layers of fees when the account collects the tokens of the second layer.

### Solution

Successful submitMessage transaction.
The fee collector should pay the 1st fee layer.

**Comment by JivkoKelchev** [comment]
This test is covered in issue #15516 and PR #15603.
