### ISSUE TITLE
Decouple jenkins from Release Branch Build Artifact workflow

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/hedera-services#15773]
Description:

The github actions workflow `Release Branch / Build Artifact [Branch]` is failing to complete because the jenkins communications are not working correctly. Need to move the jenkins portion into a new workflow that runs when the workflows complete

**Comment by nathanklick** [comment]
@rbarkerSL I would suggest disabling the integration handoff until the Jenkins issues are resolved. Additionally, we should move it into a entirely new workflow which is triggered on a `workflow_run` based trigger. Moving it to another job in the workflow will still cause issues with the new CITR changes.
