### ISSUE TITLE
Need a new specific Response Code for API permission other than NOT_SUPPORTED

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#158]
During testing file creation, I encounter error such as NOT_SUPPORTED.
From protocol file definition, it shows as "The API is not currently supported".

But actually is not due to that creation is a not supported API function,
but because only certain account number is allowed to use file creation API.

We should have a more developer friendly, straightforward error code
for such error condition instead of a vague NOT_SUPPORTED.

Something like API_NOT_ALLOWE (The called API is not allowed for the 
account number used in the transaction).

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
