### ISSUE TITLE
TOPIC_FEE_113	MessageSubmit from the fee collector of token A  to a topic with a custom fee of FT B when allCollectorsExcepmt=false

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15801]
### Problem

MessageSubmit from the fee collector of token A  to a topic with a custom fee of FT B when allCollectorsExcepmt=false

### Solution

Successful submitMessage transaction.
Token fee collector account should pay the specified topic custom fee.

**Comment by JivkoKelchev** [comment]
This test is covered in issue #15516 and PR #15603.
