### ISSUE TITLE
TOPIC_FEE_116	MessageSubmit to a topic with a fixed fee that has a fee collector account to be a hollow account

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15804]
### Problem

MessageSubmit to a topic with a fixed fee that has a fee collector account to be a hollow account

### Solution

Successful MessageSubmit transaction.
When submitting a message and paying the fee - the hollow account should remain unfinalised.

**Comment by JivkoKelchev** [comment]
This test is covered in issue #15516 and PR #15603.
