### ISSUE TITLE
TOPIC_FEE_126	Fee collector account submits a message to a topic with a fixed fee of 1 HBAR.

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15815]
### Problem

Fee collector account submits a message to a topic with a fixed fee of 1 HBAR.

### Solution

Successful submitMessage transaction.
Token fee collector account should not pay any topic custom fees.

**Comment by JivkoKelchev** [comment]
This test is covered in issue #15516 and PR #15603.
