### ISSUE TITLE
TOPIC_FEE_124	EOA submits a message to a topic with a custom fee and signs with the topic’s feeScheduleKey which is listed in the FMKL list

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15813]
### Problem

EOA submits a message to a topic with a custom fee and signs with the topic’s feeScheduleKey which is listed in the FMKL list

### Solution

Successful submitMessage transaction.
EOA shout NOT pay any custom topic fees.

**Comment by JivkoKelchev** [comment]
This test is covered in issue #15516 and PR #15603.
