### ISSUE TITLE
Update HederaLedger atomic transfers API to use non-GRPC type 

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1589]
**Summary**
The use of gRPC types in the `HederaLedger.zeroSumTransfers()` method is inefficient and makes it awkward to provide additional metadata about the adjustments involved.

For HIP-18, we would like a transfer attempt that fails due to an account being unable to pay a custom fee to resolve to  e.g. `INSUFFICIENT_BALANCE_FOR_CUSTOM_FEE` or `INSUFFICIENT_TOKEN_BALANCE_FOR_CUSTOM_FEE` instead of  the generic `INSUFFICIENT_ACCOUNT_BALANCE` response code.

This is easy to manage if `HederaLedger.zeroSumTransfers()` accepts a type that can customize the response code used to abort on insufficient balance for each of its adjustments.

**Comment by abhishek-hedera** [comment]
`INSUFFICIENT_TOKEN_BALANCE_FOR_CUSTOM_FEE` is repeated twice in the above summary.
