### ISSUE TITLE
Performance experiment without prehandle

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#15962]
We call the preHandle functionality right when an event arrives to check all signatures upfront. Then, we call it again before we execute the handle workflow to ensure the keys have not changed between the two calls. The second call happens on the handle Thread and eats away valuable resources (~10%). It is unclear though, if the preHandle functionality is so expensive or if the costs are so high because we use most objects for the first time and have to load them from disk. In the former case, we can gain significant performance improvements by avoiding calling the preHandle functionality while in the latter case, the performance improvements would be minor because we would just move loading the objects from disk to a later stage in the handle workflow.

We decided to run a small experiment to learn with which of the two cases we are dealing with.

1. Run our performance tests with a regular build and note the current performance. This is the base line.
2. Create a version of the handle workflow that does not call preHandle upfront. This means we are assuming the keys have not changed between preHandle and handle. This is most likely the case during our stress tests and even if not, we run the tests on a single node network and will not cause an ISS.
3. Run the performance tests from 1. again and compare the results.

If the numbers become a lot better, we know which area can be improved. If not, we can ignore preHandle for now.

**Comment by kimbor** [comment]
Regular build (develop/11b8218a):
NftTransferLoadTest - Finished NftTransferLoadTest: 677459190 transferred in 72000 sec, TPS: 9409
Build with preHandle removed from handle workflow (15962-performance-test/ebf18475):
NftTransferLoadTest - Finished NftTransferLoadTest: 673734564 transferred in 72000 sec, TPS: 9357

Performance is essentially the same.
