### ISSUE TITLE
Extend auto renewal function to files, topics and Smart contracts by associating with a crypto account.

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#161]
Extend auto renewal function to files, topics and Smart contracts  by associating with a crypto account.

HCS portion of this ticket (associate crypto account with HCS topic) moved to #1836 

Issue Coupled with #163

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
