### ISSUE TITLE
Investigate Java 21.0.5 issues

### ISSUE THREAD

**Issue by mishomihov00** [hashgraph/hedera-services#16181]
### Description

Since the last update of the windows-2019 (and possibly windows-2022, since it's readme was updated 5 days ago) GH runner image the Java version was bumped from 21.0.4 to 21.0.5, which caused the Gradle Determinism / Verify Artifacts (windows-2019) check to fail.

A quick fix was implemented - #16176, but a further investigation is need in order to determine if this problem was caused by the differences in the java versions or if it's an issue introduced in Java 21.0.5

### Steps to reproduce

Run the "Gradle Determinism" job from the "Node: PR Checks" workflow and specify "java-version: 21", instead of the current "java-version: 21.0.4", which will lead to Java 21.0.5 being used.

### Version

v0.54.2

### Operating system

Windows

**Comment by mishomihov00** [comment]
@rbarkerSL @nathanklick There is no obvious reason why different versions of Java caused such checksum issue.
The obvious thing is that the problem comes from the fact that in the `zxc-verify-gradle-build-determinism.yaml` workflow the `generate-baseline` job is running only on Linux with Java 21.0.4, but the `verify-artifacts` job is running also on Windows which was recently upgraded with Java 21.0.5

After hardcoding all Java versions to 21.0.5, everything with the builds seems to be working just fine - #16189 

Now I see 3 possible options:

1. Hardcode all versions to 21.0.**4**
2. Hardcode all versions to 21.0.**5**
3. Keep the `java-version` variable from the `node-flow-pull-request-checks.yaml` workflow as it was originally - `21`, and update the java on the self-hosted Linux runners (Definitely NOT a preferred choice for me as we will eventually end up in the same situation)

Please tell your opinion if we should stick with the old Java version or switch to the new one.

**Comment by rbarkerSL** [comment]
@mishomihov00 as part of PR #16175 we hard coded the java version to 21.0.4
