### ISSUE TITLE
Create a design doc outlining all the neccesary changes required for this module

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#16193]
The design doc can be in notion since we do not expect it to be long living. It should include:

1. Descriptions of all Jasper's wishes and use cases for it
2. A clear list of all changes that are necessary to achieve 1 including which packages need to move
3. State machine diagram, or similar, showing the lifecycle of a state and what methods transition them
4. Decide and document if there should be two modules or one (impl & api)

[Working diagram for context](https://drive.google.com/file/d/10N4V4Jr61B4OhbdSIMk5_futD8b8HlqL/view?usp=drive_link)

Jasper should review this document and approve before this ticket is closed.

**Comment by imalygin** [comment]
Here is the document https://www.notion.so/swirldslabs/Self-contained-State-module-12d7c9ab2591808399d2c0ff46b226d3
