### ISSUE TITLE
Change create & update HAPI APIs to add checkAllKeys flag, set by the client to require ALL new primitive keys sign the transaction.

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#162]
Change create & update HAPI APIs to add checkAllKeys flag, set by the client to require ALL new primitive keys sign the transaction.
Change HAPI API documentation to explicitly call out this requirement  

> **_ALL new primitive keys_** must sign as a safeguard to avoid accidentally changing to an invalid key, and then having no way to recover.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
