### ISSUE TITLE
Troubleshoot performance failures from Oct 23

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#16222]
Our nightly performance tests experienced an error in the `hts8k-tls` test on the night of October 23rd (and were posted the next morning, October 24th): 
<img width="611" alt="Screenshot 2024-10-29 at 15 45 44" src="https://github.com/user-attachments/assets/11adcd69-6b73-49cb-afa0-81f63f8218c4">

We need to figure out what caused the performance regression. There's strong evidence indicating that one of the commits to `develop` on Oct 23 is causing the issue, because the tests from the night before (and for many days prior) passed without issue:

<img width="769" alt="October 22 results" src="https://github.com/user-attachments/assets/c2d287a4-171f-4ae7-9c64-186d8f96c18d">

These are the commits that went in on October 23:
![image](https://github.com/user-attachments/assets/e4f18d8c-f773-4826-9817-836a91331eac)

Work with @tomzhenghedera and @OlegMazurov to run the performance tests.

**Comment by OlegMazurov** [comment]
The culprit is likely #16167, which set `streamMode = BOTH`, enabled block streams and caused `Hedera.manageBlockEndRound()` to be invoked from `onSealConsensusRound()`. That cost 15% of transaction handling time.

**Comment by tomzhenghedera** [comment]
#16167 was checked in after the failed run by commit `b4471468`, and after that run the nightly paused waiting for nmt being updated to support `pem` keys.   Thus there may still be a chance the failed run was a fluke(given the clear under performant from `node03` for the run), as was no 2nd run before #16167 to reproduce the failure.  Thus something to keep in mind with the reproducing effort.

**Comment by mhess-swl** [comment]
@tomzhenghedera reported that neither `hts8k-tls_commit-f5d3e52` nor `build-develop-b4471468` (a re-run of the 1st failed build) reproduced the issue. 

While the original failure can't be attributed to turning on block and record streams by default, producing both streams is still  a significant performance concern. We'll continue looking at how we can improve that performance.

**Comment by mhess-swl** [comment]
We haven't been able to find another source of performance concerns. Since https://github.com/hashgraph/hedera-services/issues/16365 ticket already exists to address the block stream performance, we'll put further info in that ticket.
