### ISSUE TITLE
Re-enable jenkins integration flow

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/hedera-services#16319]
The brand. new. jenkins integration workflow is in place to take over the jenkins notify steps in release flow. [This is the workflow](https://github.com/hashgraph/hedera-services/blob/develop/.github/workflows/node-zxf-deploy-integration.yaml)

Basically, what's happening is the jenkins service needs to be notified of a new build being available. And then it should respond back when the jenkins job is all happy and done 👍 

However, the job currently fails to start. This is because the input to the integration workflow `"event": "${{ inputs.event }}` is receiving extra '"' characters which makes the json being passed in invalid. Many a sad moment has been had.

Need to do one of the following:
- Update the input to use valid json (probably the easiest quickest path forward)
- Determine what inputs need to be passed from the github workflow to the jenkins files: (slower probably more correct path forward)
  - [build-upgrade-integration.Jenkinsfile](https://github.com/swirlds/infrastructure/blob/master/pipelines/build-upgrade-integration.Jenkinsfile)
  - [build-upgrade-integration-docker.Jenkinsfile](https://github.com/swirlds/infrastructure/blob/master/pipelines/build-upgrade-integration-docker.Jenkinsfile)
  - Pass the appropriate limited json to the jenkinsfiles

**Comment by andrewb1269hg** [comment]
`gh help run list`
```
JSON FIELDS
  attempt, conclusion, createdAt, databaseId, displayTitle, event, headBranch,
  headSha, name, number, startedAt, status, updatedAt, url, workflowDatabaseId,
  workflowName
```

`gh help run view`
```
JSON FIELDS
  attempt, conclusion, createdAt, databaseId, displayTitle, event, headBranch,
  headSha, jobs, name, number, startedAt, status, updatedAt, url,
  workflowDatabaseId, workflowName
```

We can probably pull the URL for the job from the JSON reply, then get additional information about the job through the Github API
`ref` =
`author`  =
`msg` =
`sha` = headSha (included in the JSON response)
