### ISSUE TITLE
Refactor `ServicesMain.main()` so that a single test of the new feature flag toggles between old behavior and new startup process

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#16357]
**Background**

In order to preserve legacy startup behavior until the whole system can switch over to the new roster lifecycle, we need to support both startup behaviors.  

This issue is to re-organize ServicesMain startup in the following way: 

1. Common bootstrapping code prior to determining roster history. 
1. If `AddressBook.useRosterLifecycle` is `false`
   1. The existing behavior with `AddressBook` and initialization is preserved.
   1. a `new RosterHistory(currentRoster, state.round+1, previousRoster, 0)` is created from current and previous AddressBooks after initialization.
1. If `AddressBook.useRosterLifecycle` is `true`
   1. parse `genesis-config.txt` into an `AddressBook` if it exists. 
   1. create a genesis roster from the genesis address book. 
   1. Load the state from disk, providing the genesis address book for use in creating a genesis state. 
   1. parse `config.txt` into an `AddressBook` if it exists
   1. create a config.txt roster from the address book. 
   1. parse `override-config.txt` into an `AddressBook` if it exists. 
   1. create an override roster from the address book.
   1. Call `determineRosterHistgory(loaded state, genesis roster, config.txt roster, override roster) 
1. Initialize and start Platform with the RosterHistory from either path. 

**Acceptance Criteria**

* That all existing unit tests and integration tests work with `AddressBook.useRosterLifecycle` set to `false`. 
* Manual testing of startup scenarios with `AddressBook.useRosterLifecycle` set to `true`. 
   * The Platform does not need to work correctly with this code path yet, just accept the `RosterHistory`. 

**Dependencies**
* https://github.com/hashgraph/hedera-services/issues/16351
* https://github.com/hashgraph/hedera-services/issues/16355

**Comment by petreze** [comment]
Closing in favor of [the following PR](https://github.com/hashgraph/hedera-services/pull/16594). The work is a duplicate
