### ISSUE TITLE
Cherry pick `isAuthorizedRaw` bug fix into 0.56 (PR #15920)

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#16404]
Cherry pick #16218 into 0.56

> Fix bug where isAuthorizedRaw fails when given an auto-created account with EC… key

Issue: #15920
PR: #16218

**Comment by Nana-EC** [comment]
@david-bakin-sl please confirm this if fixed and kindly close it if so

**Comment by david-bakin-sl** [comment]
Fixed.  Not sure why it didn't close automatically.
