### ISSUE TITLE
Add JRS test configurations to ignore non critical platform message INVALID_EVENT_ERROR to certain threshold values

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1657]
Recently, we are seeing this error message in lots of hedera services regression tests. As this is not a critical error in term of services regression, we can change the config to ignore this error message (make them as warning or info) to certain level.

**Comment by Neeharika-Sompalli** [comment]
Closed by https://github.com/swirlds/swirlds-platform-regression/pull/1246
