### ISSUE TITLE
TransactionReceipt nodeId property doesn't appear to be set properly for DAB transactions

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-services#16595]
### Problem

I ran a NodeDelete transaction. I submitted the transaction to node 6 (with account ID 0.0.9). I deleted node 2. The receipt had the nodeId set to 0. After testing a few different times, submitted to different nodes and deleting different nodes, it appears that the nodeId never gets set for the NodeDelete.

### Solution

- NodeDelete and NodeUpdate both need to set the nodeId of the affected node.

**Comment by SvetBorislavov** [comment]
+1

**Comment by jsync-swirlds** [comment]
HIP update is already in process; proto file update in both repositories will follow soon.
