### ISSUE TITLE
HCS: spec/decide/sign-off-on topic lifetime requirements (expiry/deletion)

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#166]
The current HCS topic lifetime works as follows:

- topics have an expirationTimestamp and deleted flag
- expirationTimestamp affects when submitMessages on that topic will receive an error.
- deleteTopic sets the deleted flag and no transactions or queries will succeed after that.
- some (internally decided) time after expiry or deletion - the topic will be removed from system state (not currently implemented).
- after expiration; getTopicInfo updateTopic and deleteTopic will still succeed.
- nothing can undelete a topic, but after expiration (and before removal from system state) - updateTopic can change the expiry (and memo/keys) and getInfo will return the topic's definition/state.

Should getTopicInfo and updateTopic still work while deleted (before removal from system)?

Should there be a way for topics to be undeleted (before removal from system)?

The protobuf comment on cryptoGetInfo (relating to crypto accounts) says:
        `bool deleted = 3; // If true, then this account has been deleted, it will disappear when it expires, and all transactions for it will fail except the transaction to extend its expiration date` 

Although I'm not sure the "except..." part is implemented or the "and all transactions" part refers to when it is deleted or after it disappears.

Note: This does not affect OA.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
