### ISSUE TITLE
Fix logging

### ISSUE THREAD

**Issue by thenswan** [hashgraph/hedera-services#16618]
**The Problem**
Logging is not working.

**The Solution**
Configure logging to:
1. Output logs to stdout/stderr, so logs are visible in GH jobs.
2. Save logs and in the event of a state validation error, upload logs to the GCP Bucket. Log file should be ~1mb.

**Comment by poulok** [comment]
@thenswan please remember to add the `Platform` label to any platform tickets

**Comment by thenswan** [comment]
@poulok got it
