### ISSUE TITLE
Non-zero fee for returning a state proof on a free query

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#167]
The fee for the CryptoGetAccountBalanceQuery has been set as 0. But, should the client request a state proof for the returned balance, the fee **should not** be 0 (due to the extra bandwidth required to return the state proof + competitive pressure doesnt force us to be free). 

The fee schedule does not allow us to set the default 'no state proof returned' option as free and the 'state proof returned' option as non-free so a hack in the code may be necessary. 

@lbaird  proposed hack (only relevant for when state proofs are turned on)

"calculate the entire fee, then add an if statement saying if it’s a balance query with no state proof, then set it to zero. "

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
