### ISSUE TITLE
Master branch MixedOps-NDReconnect-1.5k-25m ErrorValidator failed for TESTING_EXCEPTION multiple times

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1670]
**Summary of the defect**
This error message seems like INVALID_EVENT_ERROR, should be able to be ignored.

Check with platform people and probably change the validatorConfigs to hide it.

**How to reproduce (if possible)**
Run such-and-such `HapiApiSpec`.

Slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1624522082008400
Results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210624-072249-GCP-Daily-Comp-Reconnect-6N-1C/MixedOps-NDReconnect-1.5k-25m?authuser=3

**Service logs (if applicable)**
```
...
---- ErrorValidator FAILED validation ----
(Node 5) Marker TESTING_EXCEPTIONS appeared 596 time.
(Node 5) Marker EXCEPTION appeared 252 time.
(Node 5) Exception java.io.IOException appeared 32 time.

```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by tinker-michaelj** [comment]
Could be eliminated by increasing the JRS-configured threshold for Marker `TESTING_EXCEPTIONS`
