### ISSUE TITLE
update workflow to function with major slack version roll

### ISSUE THREAD

**Issue by andrewb1269hg** [hashgraph/hedera-services#16749]
New major version: https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0

Rolling from version 1.25.0 to 2.0.0 broke slack's functions. This needs to be resolved.

Here's the originating PR:
https://github.com/hashgraph/hedera-services/pull/16611

Here's the revert PR:
https://github.com/hashgraph/hedera-services/pull/16747

And here's an example of the workflow failing:
https://github.com/hashgraph/hedera-services/actions/runs/11965768181/job/33361748643
Step: `Report XTS execution failure` > `Report failure (slack`

**Comment by rbarkerSL** [comment]
i think this is the [culprit](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0#only-one-payload-input-can-be-provided:~:text=Recommended%20change%3A%20To%20continue%20replacing%20templated%20variables%20provided%20from%20the%20step%20env%20or%20default%20GitHub%20event%20context%20and%20payload%2C%20set%20the%20payload%2Dtemplated%20variable%20to%20true.)
