### ISSUE TITLE
Make the Hedera JRS Test on PRs required

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#16801]
Make the Hedera JRS Test (`hedera-node-jrs-panel`) in [this file](https://github.com/hashgraph/hedera-services/blob/df149d744b4256bc29d53fff96678f63eb1e47b9/.github/workflows/node-flow-pull-request-checks.yaml) a required check. This check can be removed once proper reporting and infrastructure is setup to ensure that XTS failures do not get ignored.

**Comment by rbarkerSL** [comment]
Complete.
