### ISSUE TITLE
Add max_custom_fees and accept_all_custom_fees field to ConsensusSubmitMessageTransactionBody and update the handler to delete allowances

### ISSUE THREAD

**Issue by povolev15** [hashgraph/hedera-services#16854]
* Delete the existing allowance code from `ConsensusSubmitMessageHandler`
* Add the new `max_custom_fees` and `accept_all_custom_fees` fields to `ConsensusSubmitMessageTransactionBody`
* Add the additional logic in `ConsensusSubmitMessageHandler` to support the newly added fields

**Comment by JivkoKelchev** [comment]
The changes are done and ready for review in this PR #15603.
All following changes will be tracked by issue [#15516](https://github.com/hashgraph/hedera-services/issues/15516)
