### ISSUE TITLE
Unexpected exception: "DefaultStateSnapshotManager: State written to disk for round NNN did not have enough signatures.", supplied with wrong percentage example

### ISSUE THREAD

**Issue by alex-kuzmin-hg** [hashgraph/hedera-services#16879]
### Description

current "develop" (hash f8e912a3fff6e9b1366400a4a009318165936c36 ) reproduces old bug https://github.com/hashgraph/hedera-services/issues/11422

I'm creating new one because the Reopening action is not enabled.

I see it on HashSphere:

```
2024-11-26 22:00:17.855 1995     ERROR EXCEPTION        <<scheduler StateSnapshotManager>> DefaultStateSnapshotManager: State written to disk for round 958 did not have enough signatures.
This log adds debug information for #11422.
Pre-check weight: 1500/3500 (0.000000%)  Post-check weight: 1500/3500 (0.000000%)
Pre-check threshold: false   Post-check threshold: false {} [com.swirlds.logging.legacy.payload.InsufficientSignaturesPayload]
```

that has 2 sides of a problem, 
1) according to evaluation of https://github.com/hashgraph/hedera-services/issues/11422  it should not be thrown,as we have sufficient signatures
2) its percentage output is wrong

### Steps to reproduce

To run NFT transfer test on low-profile node, e.g. xsmall GoogleCloud

### Hedera network

other

### Version

v0.56

### Operating system

Linux

**Comment by poulok** [comment]
One correction to the description. In the snippet above, the error should indeed be logged because less than a majority weight was collected. In the case of #11422, enough weight was collected and the error was logged when it should not have been. But the percentage calculated is still wrong.

**Comment by poulok** [comment]
@timfn-hg, this one might be a good ticket for you to work on.
