### ISSUE TITLE
Record file streaming - long delays for signatures

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#172]
@QianSwirlds @JeffreyDallas @lbaird @noshmody 

Looking at record files being generated by a testnet, the corresponding signature files are sometimes instantly created, sometimes several hours later.

good (instant)
```
-rw-r--r-- 1 exporter exporter  739 Jun 30 18:40 2019-06-30T18:40:04.942604001Z.rcd
-rw-r--r-- 1 exporter exporter  438 Jun 30 18:41 2019-06-30T18:40:04.942604001Z.rcd_sig
```

bad (2h20 minutes later)
```
-rw-r--r-- 1 exporter exporter 1.1K Jun 30 18:41 2019-06-30T18:41:47.790801001Z.rcd
-rw-r--r-- 1 exporter exporter  438 Jun 30 21:02 2019-06-30T18:41:47.790801001Z.rcd_sig
```

Following a discussion with Nosh and Qian, it would appear this is working as per the design, however the design assumes there is continued network activity by way of client transactions being issues.
If for some reason, a transaction is issued just before a period of inactivity on the network, that transaction will not show in the record files until the network becomes busy again.

I suggest enhancing the design such that the writing of the files is more deterministic and not dependent on network activity.

Note: this issue was raised by an exchange which is testing the record streaming facility via a mirror node and aren't finding their transactions in the records if the testnet is quiet.

**Comment by JeffreyDallas** [comment]
Close obsolete issue
