### ISSUE TITLE
Add generic HAPI to update setting in platform

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#1725]
Add generic HAPI to update setting in platform
This HAPI API will call the UpdateSetting API in the platform during handleTransaction

https://github.com/swirlds/swirlds-platform/issues/3560

**Summary**
As a Hedera Services client, I need _X_ so that I can accomplish _Y_.

**Possible resolution**
Lorem ipsum dolor sit amet.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
