### ISSUE TITLE
Add missing code coverage in hapi-fees/ from refactored-nfts branch merge

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1728]
Add missing code coverage in `hapi-fees/` module in `refactored-nfts` branch merge. The difference in code coverage is here[](https://github.com/hashgraph/hedera-services/pull/1615/files)

**Comment by ljianghedera** [comment]
This now is a smaller scope of issue #1766. Will follow up with #1766 and close this one.
