### ISSUE TITLE
Hedera services port

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#174]
Hackathon and community testing highlighted that port 50211 is not allowed through some firewalls (corporate and university).
Would it be worth considering lowering the port number to within a "usually allowed range" and maybe registering that port officially with IANA (https://en.wikipedia.org/wiki/Internet_Assigned_Numbers_Authority) ?

Using an unusual port could be a soft barrier to adoption.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
