### ISSUE TITLE
Implement the TokenFeeScheduleUpdate transition logic and others

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1750]
### Problem

This part of work is blocking testing of others, so I will go ahead to implement it and anything blocking the EET tests.

### Solution

- [x] Add a (validated) `Token.updateFeeSchedule()` method to the `Token` model object.
- [x] Return `CUSTOM_FEE_DENOMINATION_MUST_BE_FUNGIBLE_COMMON` if a NFT is used as the denomination for a fixed fee.
- [x] Return `CUSTOM_FRACTIONAL_FEE_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON` if a fractional fee is used in the fee schedule for a non-fungible token type.
- [x] Add a `TransitionLogic` implementation for `TokenFeeScheduleUpdate` plus lookup entry.
- [x] Update `TokenCreate` transition logic for `feeScheduleKey`.

**Comment by tinker-michaelj** [comment]
Closed by https://github.com/hashgraph/hedera-services/pull/1760
