### ISSUE TITLE
Simplify running CI suites locally

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1796]
### Problem

It is inconvenient, especially for outside collaborators, to need a CircleCI job in order run our CI pipeline.

### Solution

Provide an easy way (e.g. an extra flag to `SuiteRunner`?) that allows anyone to reproduce the CircleCI `run-continuous-integration-gcp` EET suites locally.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
