### ISSUE TITLE
Enable a query option for node signature on records

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#181]
**Motivation:**
Until state-proofs are an option, trusting persisted records is a weakness. Even after state-proofs are implemented, there should be a lower threshold for building a similar portable trust.

**Solution:**
As a user of Hedera, I should be able to ask a node to sign the record response so I can always prove that the record hasn't been changed to a third party. If I want to add more trust, I can submit to one node and request a signed record from one or more other (maybe even random) nodes. This should have a lower cost because it doesn't require merkle tree and explicit multi-node signing. It's strictly asking the individual node to sign that the record is true as far as they know.

In addition to:
```
ANSWER_ONLY
ANSWER_STATE_PROOF
COST_ANSWER
COST_ANSWER_STATE_PROOF
```
add
```
ANSWER_SIGNATURE
COST_ANSWER_SIGNATURE
```

**Comment by publu** [comment]
+1

I think that simple portable signatures for specific records are vital to the creation of trustless applications

**Comment by tinker-michaelj** [comment]
> I think that simple portable signatures for specific records are vital to the creation of trustless applications

Appreciate the comment, Pablo. 👍

**Comment by christianholman** [comment]
This would be a good addition

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
