### ISSUE TITLE
Transaction Involving Deleted Payer Account Should Charge Submitting Node

### ISSUE THREAD

**Issue by amckay7777** [hashgraph/hedera-services#1811]
### Description

When a payer account has been deleted and then a transaction is requested that involves that payer immediately after, then neither the node nor the payer account are charged for the transaction. Expected behavior is that if the payer account has already been deleted and then a transaction involves that same deleted payer, that the submitting node should be charged the fees associated with that transaction.

### Steps to reproduce

1. Run 3 nodes
2. Add the attached test to CryptoDeleteSuite and run it against the running nodes
[DeletedAccountCannotBePayerTest.txt](https://github.com/hashgraph/hedera-services/files/6812474/DeletedAccountCannotBePayerTest.txt)

### Additional context

<img width="1298" alt="SubmittingNodeNotCharged" src="https://user-images.githubusercontent.com/10032034/125537052-d1b44d01-b260-4dc9-b94b-19f0951b4372.png">

Notice that even after the final account balance print the balance of the submitting node did not decrease. The screenshot attached can be seen when running the test provided.

### Hedera network

testnet

### Version

0.16.0-SNAPSHOT

### Operating system

macOS

**Comment by tinker-michaelj** [comment]
Closed by #1820
