### ISSUE TITLE
HAPI: Move ResponseHeader into the Response message

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#182]
Currently, ResponseHeader is included in the individual Response type variation, but the ResponseHeader is not unique and it is annoying to have to dig into the type to unwrap the response header info (precheck, response type, etc).

Can we move the ResponseHeader into the Response message as a property in addition to the `response` property of the Response message?

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
