### ISSUE TITLE
HAPI: access by Solidity names 

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#184]
In the future (not yet), update the API so that everywhere an account or smart contract instance is referenced in a transaction or query, the user can access it by its Solidity name, not just by its Hedera name (AccountID or ContractID). So the AccountID or ContractID in the current API would be replaced with a oneof{} that has two options. This saves the user an extra query sometimes. At the cost of adding a byte or two to every transaction.

We should consider this carefully before doing it.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
