### ISSUE TITLE
Missing proto for CryptoUpdateClaim or CryptoExtendClaim

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#185]
Since the addition of claimDuration to Claims, it could be useful to add a means to extend that duration in order to lengthen the lifespan of the Claim. If the file/data that was hashed originally (or the accounts signing the claim) have changed, a new Claim should be created. However, if the hash and signatories are unchanged, it may be more efficient to extend the life of the existing claim.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
