### ISSUE TITLE
Add CI tests that update "hot" entities many times to simulate longevity testing

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1859]
### Problem

We don't have tests that simulate the fast-copy profile of a long-lived, frequently updated entity. (E.g. a token whose fee schedules change on a regular basis.)

### Solution

Add EET specs that, for each entity type, 
1. Create an instance; and, 
2. Update this instance for 10k+ rounds; and,
3. Use it in some way throughout.

📝 &nbsp; Some experimentation will be needed to determine how long a test must run in regression to pass 10k rounds.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
