### ISSUE TITLE
CryptoGetAccountRecords - add 2 timestamps to get records between 

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#186]
Developers have asked if there is a way to ask just for records that have timestamps between two timestamps. The concern is if they run that query once every 5 minutes or so, they will get a lot of overlap.

That would be a useful HAPI extension: an optional start time and optional end time (where a missing start counts as negative infinity, and a missing end counts as positive infinity).

That should be added to the issue for HAPI modifications.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
