### ISSUE TITLE
Fix Major SonarCloud CodeSmells

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1865]
### Description

Summary
Fix Major CodeSmells  in SonarCloud

Parent issue : #1491

First clean up those fake issues, like the following:

- [ ]  commented out line in license header to be removed;
- [ ]  The class with *Test.java needs to have @test scenarios;

### Steps to reproduce

https://sonarcloud.io/project/issues?branch=branch-01493-SonarCloud-Critical&id=com.hedera.hashgraph%3Ahedera-services&resolved=false&severities=MAJOR

### Hedera network

other

### Version

v0.17.0

### Operating system

Linux

**Comment by steven-sheehy** [comment]
You can just [search](https://sonarcloud.io/project/issues?branch=branch-01493-SonarCloud-Critical&id=com.hedera.hashgraph%3Ahedera-services&resolved=false&rules=java%3AS125&severities=MAJOR) for the bad rule and bulk mark those as false positive. Then you can add an [ignore criteria](https://www.baeldung.com/sonar-exclude-violations) to your pom.xml, to a sonar-project.properties, or via the UI so it doesn't come back. The mirror node has that [config](https://github.com/hashgraph/hedera-mirror-node/blob/87f0501a023652f4b9d59e6d51d972e5f465f12f/pom.xml#L88) already for that same rule.

**Comment by ljianghedera** [comment]
@steven-sheehy Nice! I did a little googling, but didn't find an easy way to prevent Sonar from future reporting this, but I believe Sonar must have some feature to let user to tell it to ignore certain patterns during scan or report. This's really going to help. I will try it out today. Thanks!

**Comment by tinker-michaelj** [comment]
Warnings on commented-out code no longer appear in Sonar.
