### ISSUE TITLE
SmartContractOps-NIReconnect-14-21m fails due to reconnected outside of allowed time window

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1895]
### Description

The reconnect occurs too late. 

Solution might be to adjust reconnect time, but it may worth to find out why this is happening

### Steps to reproduce

The slack report link for this failure: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1627461765309800

The slack summary report link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1627463994025400

### Additional context

---- ReconnectValidator FAILED validation ----
<<ERROR>>
Node 5 reconnected outside of its allowed time window
<<INFO>>
Node 5 reconnected 1 time.

### Hedera network

other

### Version

v0.17.0

### Operating system

Linux

**Comment by tinker-michaelj** [comment]
Passing in `master`.
