### ISSUE TITLE
MixedOps-Global-NI-3NReconnect-6k-30m and MixedOps-Global-ND-3NReconnect-6k-30m not run

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1897]
### Description

This seems happen a lot. No slack report sent to `hedera-regression` channel, no test results, only slack summary link.

### Steps to reproduce

Only Slack summary report link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1627464674025700

### Additional context

Slack summary report link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1627464674025700

### Hedera network

other

### Version

v0.17.0

### Operating system

Linux

**Comment by tinker-michaelj** [comment]
These tests appear in current regression summary.
