### ISSUE TITLE
Fixed fees cannot be assessed in the units of an owning token

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1925]
### Description

Suppose `0.0.T` is a token with a custom fee schedule, and includes a fixed fee of `5T` units.

Say we then submit a `CryptoTransfer` that sends `100T` from account `A` to account `B`.

This will trigger a custom fee of `5T`. **Because** custom fees must be charged recursively, this `-5T` balance change will itself trigger another `-5T` fee, and so on...

Thus the result of any such `CryptoTransfer` will be `CUSTOM_FEE_CHARGING_EXCEEDED_MAX_RECURSION_DEPTH`

‼️ Note there _is_ a work-around using `FractionalFee`. To achieve the fixed `5T` as above, we can create a fractional fee with:

1. `fractional_amount=1/9223372036854775807`
2. `minimum_amount=5`

Even if `T` has the maximum supply, the fraction is so tiny that the minimum fee of `5T` will always be assessed instead.

### Steps to reproduce

Create a token with a custom fee schedule that includes a fixed fee denominated by the `0.0.0` token (meaning units of the newly created token).

### Hedera network

testnet

### Version

v0.16.1

**Comment by bugbytesinc** [comment]
I thought `0.0.0` represented hBars?

**Comment by bugbytesinc** [comment]
It might be reasonable to disallow fixed fees of the same token.  A variable fee with a tight enough min/max would accomplish the same thing (except it that it would be skimmed from the transfer value instead of applied as an additional transfer).

**Comment by tinker-michaelj** [comment]
@bugbytesinc Leaving the `denominating_token_id` field unset/`null` means ℏ; setting to the "sentinel" `0.0.0` means units of the newly created token...But v good point, there is an existing work-around using `FractionalFee`, updating the issue with that!

**Comment by bugbytesinc** [comment]
But that's not the way protobuf works across platforms.  Null == 0.0.0 on some platforms.  Typescript/JavaScript/.NET all have different ways of filling in the blanks of "missing" protobuf values.

**Comment by bugbytesinc** [comment]
I'm just recalling, that in the past, we've had bugs manifest where client libraries where absence of values were interpreted as defaults 0's or empty sets.  Perhaps I may be remembering issues more with returned values than sent values, but there were issues.  Just trying to be cautious.

**Comment by tinker-michaelj** [comment]
> I'm just recalling, that in the past, we've had bugs manifest where client libraries where absence of values were interpreted as defaults 0's or empty sets. Perhaps I may be remembering issues more with returned values than sent values, but there were issues. Just trying to be cautious.

Agreed, we should use a sentinel of e.g. `-1.-1.-1` or something very obvious!

**Comment by steven-sheehy** [comment]
Sentinel values should be avoided if at all possible. An enum value would make more sense.

**Comment by tinker-michaelj** [comment]
> Sentinel values should be avoided if at all possible. An enum value would make more sense.

Even better. 👍
