### ISSUE TITLE
Automate Rekeying testNet states with Dev key

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1932]
### Problem

Currently its a manual process to re-key a testNet state with the Engineering Key 
`hedera-node/data/onboard/devGenesisKeypair.pem`. 

This requires the dev who is rekeying to have the genesis key of TestNet. 

### Solution

We can remove this dependency by Devops automating the rekeying process when sharing the testnet state
to the dev team for migration testing.

**Comment by tinker-michaelj** [comment]
Automation has been increased to a ~tolerable level.
