### ISSUE TITLE
Automate upload to GCP bucket upon `MAINTENANCE`

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1958]
### Problem

Uploading a new saved state into a GCP bucket is currently a manual process. 

### Solution

On the `state-creation-main` branch, update the `ServicesMain.platformStatusChange()` method to, **when** it enters `MAINTENANCE`, to sleep for a while and then upload the latest _data/saved/..._ folder to a GCP bucket given a new property like,
```
automation.sleepMinsBeforeGcpUpload=10
automation.gcpUploadBucket=<bucket-name>
```

This automation could be accomplished by either triggering a shell script calling `gsutil`, or by directly using the GCP Java client library.

⛔ &nbsp;We do need a way to get an appropriate credential onto the node in this case.

🅰️ &nbsp;For extra credit, enhance JRS to automatically extract a _*.tar.gz_ file when setting a saved state.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
