### ISSUE TITLE
HAPI to update the byte code of a SmartContract instance & call a method atomically - requires admin key

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#200]
Add HAPI transaction to replace existing byte code of a smart contract instance with new byte code.
A file with the updated byte code for a smart contract instance is provided as input.

This API must be signed by the admin key of the smart contract.
If the smart contract does not have an admin key then this functionality is NOT available for the given smart contract instance.  

The new transaction should replace the bytecode then call one function. Atomically, as a single transaction.
This is not urgent.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
