### ISSUE TITLE
AutoFunctionalTest:Smart Contract ERC-721 Token Functions

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#202]
Create automated tests for ERC-721 contract functions:
- ownerOf
- safeTransferFrom
- safeTransferFrom
- transferFrom
- approve
- setApprovalForAll
- getApproved
- isApprovedForAll
- supportsInterface

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
