### ISSUE TITLE
Finalize how auto-association affects `TokenCreate` signing requirements

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2046]
### Problem

At present, the following accounts must sign a `TokenCreate` **because** they are automatically associated to the newly created token:
1. The treasury account.
2. The fee collector for a fractional fee.
3. The fee collector for a self-denominated fixed fee.

If any of these accounts have open "auto-association slots", it is unclear if they should still be required to sign such a `TokenCreate`.

### Solution

Ask Product to confirm/deny whether these signing requirements should still hold.

**Comment by anighanta** [comment]
Confirmed with Atul, these requirements still hold. These associations will not be considered as implicit.
