### ISSUE TITLE
Clarify function and variable names

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2097]
### Problem

Some function names can be improved for greater readability and maintainability. For example,
- hapi-fees/src/main/java/com/hedera/services/usage/token/meta/ExtantFeeScheduleContext.java
    * line 35, 39
- hapi-fees/src/main/java/com/hedera/services/usage/token/meta/FeeScheduleUpdateMeta.java
    * line 42, 46, 50
- hedera-node/src/main/java/com/hedera/services/ServicesState.java
    * line 401 to end 
- hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
    * line 129 
- hedera-node/src/main/java/com/hedera/services/context/properties/NodeLocalProperties.java
    * line 96 to end 
- hedera-node/src/main/java/com/hedera/services/fees/calculation/AwareFcfsUsagePrices.java
    * functions `defaultActivePrices`/`activePrices` and `pricesGiven`/`defaultPricesGiven`
- ./hedera-node/src/main/java/com/hedera/services/queries/token/TokenAnswers.java
    * function `getTokenInfo` is different from others
- hedera-node/src/test/java/com/hedera/services/grpc/marshalling/ImpliedTransfersMarshalTest.java
    * line 240, `twoChanges` actually means "changes No 2"
    * line 270, `handlesEasyCase` does not reflect what the function does.
    * line 95, `a`, `b`, `c` Avoid single letter variable names.
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleAccount.java, hedera-node/src/main/java/com/hedera/services/store/models/Account.java
    * `getOwnedNfts` and `getNftsOwned`, named similarly but function very differently.
- In tests, some `@beforeEach` functions are named `setUp`, but others are `setup`.

### Solution

Improve names as suggested above.

**Comment by AayushSaini101** [comment]
Can I work on this issue
