### ISSUE TITLE
Remove hash field from BasicTransactionContext

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#2106]
Because we save the whole `accessor`, we don't need to save its `hash`.

https://github.com/hashgraph/hedera-services/blob/542a3ece54113e714d52c28eab603c43a35d46ff/hedera-node/src/main/java/com/hedera/services/context/BasicTransactionContext.java#L129-L137

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
