### ISSUE TITLE
Add ledger ID to entity infos

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-services#2136]
### Problem

When you request an account info from the network, there is not a mechanism to validate which network the request came from in the response. This is true for any of the entity info responses from tokens, topics, files, and smart contracts. There needs to be a programmatic to verify the network the response came from. This would be used in the Transaction Tool application to populate the corresponding network field for accounts users store in their application. 

If you import an account info file to the application there is not a deterministic way to identify what network the account info was pulled from. The account info response could be from previewnet, testnet, or mainnet. 

### Solution

Add a field called  `ledger_Id ` to the info responses. The following IDs can be used to identify different networks:

00 = MAINNET
01 = TESTNET
02 = PREVIEWNET

Crypto get info example:

   ```diff
message CryptoGetInfoResponse {
    ResponseHeader header = 1; //Standard response from node to client, including the requested fields: cost, or state proof, or both, or neither

 message AccountInfo {
        AccountID accountID = 1; // The account ID for which this information applies
        string contractAccountID = 2; // The Contract Account ID comprising of both the contract instance and the cryptocurrency account owned by the contract instance, in the format used by Solidity
        bool deleted = 3; // If true, then this account has been deleted, it will disappear when it expires, and all transactions for it will fail except the transaction to extend its expiration date
        AccountID proxyAccountID = 4; // The Account ID of the account to which this is proxy staked. If proxyAccountID is null, or is an invalid account, or is an account that isn't a node, then this account is automatically proxy staked to a node chosen by the network, but without earning payments. If the proxyAccountID account refuses to accept proxy staking , or if it is not currently running a node, then it will behave as if proxyAccountID was null.
        int64 proxyReceived = 6; // The total number of tinybars proxy staked to this account
        Key key = 7; // The key for the account, which must sign in order to transfer out, or to modify the account in any way other than extending its expiration date.
        uint64 balance = 8; // The current balance of account in tinybars
        // [Deprecated]. The threshold amount, in tinybars, at which a record is created of any transaction that decreases the balance of this account by more than the threshold
        uint64 generateSendRecordThreshold = 9 [deprecated=true];
        // [Deprecated]. The threshold amount, in tinybars, at which a record is created of any transaction that increases the balance of this account by more than the threshold
        uint64 generateReceiveRecordThreshold = 10 [deprecated=true];
        bool receiverSigRequired = 11; // If true, no transaction can transfer to this account unless signed by this account's key
        Timestamp expirationTime = 12; // The TimeStamp time at which this account is set to expire
        Duration autoRenewPeriod = 13; // The duration for expiration time will extend every this many seconds. If there are insufficient funds, then it extends as long as possible. If it is empty when it expires, then it is deleted.
        repeated LiveHash liveHashes = 14; // All of the livehashes attached to the account (each of which is a hash along with the keys that authorized it and can delete it)
        repeated TokenRelationship tokenRelationships = 15; // All tokens related to this account
        string memo = 16; // The memo associated with the account
        int64 ownedNfts = 17; // The number of NFTs owned by this account
   +    bytes ledger_id = 18; // The network ID of the network the response was returned from 
    }
    AccountInfo accountInfo = 2; // Info about the account (a state proof can be generated for this)
}
```

**Comment by SimiHunjan** [comment]
cc: @lbaird @mark-hedera @popowycz @DSMatusevich

**Comment by bugbytesinc** [comment]
Practically speaking, in order to retrieve AccountInfo from the network, one has to already have a valid network address and account on that network, so any tool querying for account info should already know which network it is talking to.  Same goes for mirror nodes, the tool consuming data from the mirror node should already know what network this mirror node belongs too.

**Comment by DSMatusevich** [comment]
The issue is that, in isolation, an account info does not tell us the network it was requested from. In other words, if I get an account or file info from Testnet or Mainnet, store as a file and email it to somebody else, without any other context, the other person would not know where this info comes from. 

In our application, we allow users to share account infos that have been obtained from all three networks, as well as some custom networks that the user may stand. Without the field indicating the provenance, this is not practical.

**Comment by bugbytesinc** [comment]
Which HIP is this?

**Comment by SimiHunjan** [comment]
There is not a HIP for this. This is a feature is requested for the Transaction Tool application Hedera council and staff members use to sign transactions managed by Hedera. https://github.com/hashgraph/hedera-transaction-tool-demo
