### ISSUE TITLE
assertThrows to expect only the exception from the method under test

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#2144]
https://sonarcloud.io/project/issues?id=com.hedera.hashgraph%3Ahedera-services&open=AXhLDHQLtNIsxbrzJwOx&resolved=false&rules=java%3AS5778&types=CODE_SMELL

Extract other methods into given statements.

**Comment by Neeharika-Sompalli** [comment]
Will be resolved with #2685
