### ISSUE TITLE
Standardize fee calculations for TokenGetInfo, TokenGetAccountNftInfos, TokenGetNftInfo, TokenGetNftInfos,

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#2183]
### Problem

Following example of `TokenCreate` example, refactor resource usage calculations of `TokenGetInfo`, `TokenGetAccountNftInfos`,  `TokenGetNftInfo`, `TokenGetNftInfos` to be based on AccessorBasedUsages and UsageAccumulator.

### Solution

- [ ] Change the incremental resource usage as calculated  into a calculation supported AccessorBasedUsages and UsageAccumulator;
- [ ] Add a `FeeSchedulesTest` method to generate the prices for _feeSchedules.json_, **given** a base operation defined by `BaseOperationUsage` (and the target price in _hapi-fees/src/main/resources/canonical-prices.json_);

Reference to issue #2071.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
