### ISSUE TITLE
Revise and relax netty settings for prod

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#2198]
Because the throttling mechanism has been improved in Services, netty settings for prod could be relaxed to be less restrictive to avoid warnings like the following:
```
Sep 14, 2021 5:22:12 PM io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:172)
```

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
