### ISSUE TITLE
Deprecate getAccountNftInfos and getTokenNftInfos queries 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-services#2207]
### Problem

These queries are better served by mirror nodes because the query responses will be enriched with historical context that only mirror nodes have
(e.g. list of previous owners of each NFT)

### Solution

Deprecate `getAccountNftInfos` and `getTokenNftInfos` queries.

Reference #2065

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
