### ISSUE TITLE
Use markers for log entries

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#2209]
Suggested list of markers:
- SERVICES_INIT
- SERVICES_MIGRATION
- SERVICES_PLATFORM_STATUS (or use the same `PLATFORM_STATUS` marker from swirlds platform)
- SERVICES_API_PERMISSIONS
- SERVICES_PROPERTIES
- SERVICES_STATE_VIEW
- SERVICES_FEES
- SERVICES_GRPC
- SERVICES_RECORDS
- SERVICES_FREEZE (or use the same `FREEZE` marker from swirlds platform)
- SERVICES_RECONNECT (or use the same `RECONNECT` marker from swirlds platform)

// May remove the `OPS` part

// Specific types of services
- SERVICES_CRYPTO_OPS
- SERVICES_FILE_OPS
- SERVICES_SMART_CONTRACT_OPS
- SERVICES_CONSENSUS_OPS
- SERVICES_TOKEN_OPS
- SERVICES_SCHEDULE_OPS

// Generic
- SERVICES_HANDLE_TRANSACTION
- SERVICES_ANSWER_QUERY

**Comment by lpetrovic05** [comment]
outdated
