### ISSUE TITLE
Restore `ScheduleCreate` idempotency w/ payer safety check

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2269]
### Problem

Suppose Alice and Bob are **both** trying to schedule transaction `X`, where `X` requires both of their keys to sign.

Say Alice's `ScheduleCreate` is handled first. Then Bob's `ScheduleCreate` will resolve to `IDENTICAL_SCHEDULE_ALREADY_CREATED`, and they will need to re-submit a `ScheduleSign` to include their signature.

This is inconvenient, since Bob and Alice shared a mutual intent to have `X` execute.

### Solution

Add a new `merge_with_identical_schedule` flag to the `ScheduleCreate` transaction,
```
message ScheduleCreateTransactionBody {
  SchedulableTransactionBody scheduledTransactionBody = 1;
  string memo = 2;
  Key adminKey = 3;
  AccountID payerAccountID = 4;

  /** 
   * Controls how the network will behave when there is an identical transaction already scheduled (but not yet executed).
   * 
   * If true, this ScheduleCreate will resolve to SUCCESS, and the existing schedule entity will receives any signatures from this transaction.
   * 
   * If false, this ScheduleCreate will resolve to IDENTICAL_SCHEDULE_ALREADY_CREATED, and the receipt will contain the id of the existing schedule entity.
   */
  bool merge_with_identical_schedule = 5;
}
```

That is, with `merge_with_identical_schedule=true`, treat Bob's `ScheduleCreate` as a `ScheduleSign` for the existing scheduled transaction resulting from Alice's `ScheduleCreate`.

⚠️ &nbsp;Do check that the `payerAccountId` field for the `ScheduleCreate` is "compatible" with the existing scheduled transaction. That is, if Bob's `ScheduleCreate` gave Alice as the payer; and Alice's gave anyone _other_ than Alice as the payer, then resolve to `IDENTICAL_SCHEDULE_ALREADY_EXISTS_WITH_DIFFERENT_PAYER`.

**Comment by steven-sheehy** [comment]
To be clear, the duplicate schedule create cannot modify any fields within the `ScheduleCreateTransactionBody` like `memo` or `payerAccountID`, right? Once created by the first schedule create the schedule is immutable.

**Comment by tinker-michaelj** [comment]
> To be clear, the duplicate schedule create cannot modify any fields within the `ScheduleCreateTransactionBody` like `memo` or `payerAccountID`, right? Once created by the first schedule create the schedule is immutable.

Correct...note that `memo` is part of the schedule's "identity", so a `ScheduleCreate` with different memo would not "collide".

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
