### ISSUE TITLE
Write + execute testing plan for HIP-23

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2289]
### Problem

It is a stylized empirical fact that a bug found after release is **30x more expensive** than a bug found in the design phase.

A HIP-23 bug that triggered late-night testnet problems suggest this is an understatement.

### Solution

- [ ] Create a test plan for HIP-23 in markdown format (i.e., something that could be easily copied and used in other PRs).
- [ ] Execute this test plan.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
