### ISSUE TITLE
Redundant signature duplication in Rationalization.execute()

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#2291]
### Problem

The issue can be reproduced with the `HelloWorldSpec` test and the following change at [line 65](https://github.com/hashgraph/hedera-services/blob/b81fb2c009545f59e6c72e32936ee92359c8b7f9/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HelloWorldSpec.java#L65):
```
	.payingWith("sponsor")
```

Although `txnSigs` initially contains only 1 signature, it is duplicated in `execute()` as both `realPayerSigs` and `realOtherPartySigs` contain a copy. Note that `allVaryingMaterialEquals()` does not prevent duplication due to failed check `requestedSubListEnd <= maxSubListEnd`.
Eliminating redundancy will ease pressure on signature verification.

### Solution

Avoid signature duplication in `txnSigs`.

**Comment by tinker-michaelj** [comment]
Fixed in `master`.
