### ISSUE TITLE
Redundant signature duplication in Expansion.execute()

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#2292]
### Problem

The issue can be reproduced with the `HelloWorldSpec` test and the following change at [line 65](https://github.com/hashgraph/hedera-services/blob/b81fb2c009545f59e6c72e32936ee92359c8b7f9/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HelloWorldSpec.java#L65):
```
	.payingWith("sponsor")
```
In `Expansion.execute()` the following two lines add the same signature twice increasing the overhead of signature verification:
```
63		final var payerStatus = expand(pkToSigFn, keyOrderer::keysForPayer);
...
73		final var otherStatus = expand(pkToSigFn, keyOrderer::keysForOtherParties);
```

### Solution

Avoid redundant duplication.

**Comment by tinker-michaelj** [comment]
Fixed in `master`.
