### ISSUE TITLE
Migrate non-storage blobs to a `VirtualMap`

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2319]
### Problem

HFS "paths" matching,
- `/0/f{num}` for file data; and,
- `/0/k{num}` for file metadata; and,
- `/0/s{num}` for contract bytecode; and,
- `/0/e{num}` for system-deleted files

...are all stored in `PostgreSQL` as `BinaryObject`s and suffer from poor performance.

### Solution

At startup, migrate all such `BinaryObject`s from the "storage" `MerkleMap` into a new top-level `VirtualMap` with fixed-size key type containing just the `num` and storage "type"; and variable-size value type wrapping a `byte[]`.

**Comment by Neeharika-Sompalli** [comment]
Already completed
