### ISSUE TITLE
Add pre-fetching of contract bytecode to expandSignatures

### ISSUE THREAD

**Issue by superboo** [hashgraph/hedera-services#2330]
### Problem

Performance impact for loading EVM bytecode for contract call transactions is felt in handleTransaction(). The loading action is currently accessing postgres for the data, while the newer virtual merkle storage layer will hit the disk. Both approach will incur an I/O call. The goal is to move the contract bytecode loading into an earlier stage, ideally in a parallel/asynchronous manner so the data is immediately available during handleTransaction().

### Solution

The `expandSignatures()` call on `ServicesState` will be used as the point where a pre-fetch can occur. Transaction logic for a request can implement an interface (`PreFetchable`) that will be called by the pre-fetch disruptor handler. The contract code will be stored in a 

[ ] Introduce an interface `PreFetchable` that the `ContractCallTransitionLogic` class will implement and pass back loaded bytecode for the target address.
[ ] Introduce disruptor that will contain a pre-fetch handler that will call transactions that have a `PreFetchable` transition class
[ ] Create a weak reference cache to hold loaded bytecode, keyed by target address
[ ] Change `ContractCallTransitionLogic` execution to use cache to fetch bytecode, if not present load synchronously
[ ] Change `ServicesState.expandSignatures` to submit transaction event to disruptor AFTER signature expansion has completed

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
