### ISSUE TITLE
Automatic Association of Token with a Pause key or Custom Fee

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#2331]
### Problem

As pointed out by @gakz  and @gregscullard, we have potential problem of an Account with automatic association slots getting spammed by Tokens with customFee and Tokens that can be paused which will cause the targeted account to either pay large amounts in customFee when transferring back those spammed tokens or leave the targeted account helpless by pausing the spam Token type.

### Solution

Following the discussion these are the suggestion by @lbaird :

```
1. Allow auto association with custom-fee tokens, and make a user’s returnToken transaction (return to treasury with no payment in return) free from custom fees. Allow returns during pause, freeze, and without KYC.
2.Do one of the following two, according to feedback from our users

- 2a: don't allow auto association with tokens that allow pause

- 2b: allow auto association with tokens that allow pause. And allow user returns and token dissociate during a pause

```

**Comment by tinker-michaelj** [comment]
Obsolete.
