### ISSUE TITLE
Prefetch queue not draining

### ISSUE THREAD

**Issue by superboo** [hashgraph/hedera-services#2427]
### Description

After enabling logging, noticed that the prefetch queue is not draining properly. The bug does not impact the caching of the EVM bytecode but it basically makes the prefetch stage useless.

### Steps to reproduce

Found issue by adding logging inside the prefetch Runnable lambda. Enabled global logging by editing the log4j.xml top-level logging setting. Noticed that enqueuing of the Runnable is happening but the execution of the Runnable is not being triggered.

### Hedera network

other

### Version

v0.20

### Operating system

macOS

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
