### ISSUE TITLE
HSCS-PREC-002 Non-nested happy TokenMint of fungible token units

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#2462]
### Problem

We need sample Solidity contract(s) and EETs to exercise the new HTS precompiles when used in a single top-level EVM transaction.
Validate that a valid TokenMint of fungible token units:

- [ ]  Results in the expected child TransactionRecord; and,
- [ ]  Increases the total supply by the expected amount; and,
- [ ]  Increases the treasury balance by the expected amount; and,
- [ ]  Uses both the caller's ContractID and a sigMap cryptographic sig to activate the token's supplyKey.

### Solution

Write EETs for the above items, extending the [recordWith() DSL](https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java#L47) as necessary to make expressing each type of assertion as simple as possible.

**Comment by tinker-michaelj** [comment]
Believed done in `master`.
