### ISSUE TITLE
HSCS-PREC-005 Non-nested happy TokenBurn of NFTs by serial no

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#2465]
### Problem

We need sample Solidity contract(s) and EETs to exercise the new HTS precompiles when used in a single top-level EVM transaction.
Validate that a valid TokenBurn of NFTs by serial no,

- [ ]  Results in the expected child TransactionRecord; and,
- [ ]  Removes the expected NFTs with treasury ownership; and,
- [ ]  Decreases the total supply by the expected amount.

### Solution

Write EETs for the above items, extending the [recordWith() DSL](https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java#L47) as necessary to make expressing each type of assertion as simple as possible.

**Comment by tinker-michaelj** [comment]
Done.
