### ISSUE TITLE
HSCS-PREC-006 Non-nested happy TokenAssociate

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#2466]
### Problem

We need sample Solidity contract(s) and EETs to exercise the new HTS precompiles when used in a single top-level EVM transaction.
Validate that a valid TokenAssociate,

- [ ]  Results in the expected child TransactionRecord; and,
- [ ]  Creates the new association with expected freeze and KYC statuses.
- [ ]  Uses both the caller's ContractID and a sigMap cryptographic sig to activate the account's key.

### Solution

Write EETs for the above items, extending the [recordWith() DSL](https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java#L47) as necessary to make expressing each type of assertion as simple as possible.

**Comment by tinker-michaelj** [comment]
Done via `hts-contracts` merge.
