### ISSUE TITLE
HSCS-PREC-024 [EVM-triggered Rollback] Successful precompile of NFT Mint does not affect state after top-level frame revert

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#2484]
### Problem

We need sample Solidity contract(s) and EETs to validate rollback works when an HTS precompile succeeds; but its parent MessageFrame reverts. There are a few scenarios to consider.

Verify when a top-level message frame makes two message calls, where the first does a successful precompile NFT mint; and the second fails, causing the top-level frame to revert; then the NFT minted by the first nested precompile does not exist (and there is no corresponding TransactionRecord).

### Solution

Write EETs for the above items, extending the recordWith() DSL as necessary to make expressing each type of assertion as simple as possible.

**Comment by tinker-michaelj** [comment]
Believed done in `master`.
