### ISSUE TITLE
HSCS-PREC-025 [EVM-triggered Rollback] successful dissociate precompile does not affect state after revert

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#2485]
### Problem

We need sample Solidity contract(s) and EETs to validate rollback works when an HTS precompile succeeds; but its parent MessageFrame reverts. There are a few scenarios to consider.

Verify a successful dissociate precompile in a nested frame which then creates a child frame that reverts due to OOG has no effects on state (and no TransactionRecord).

### Solution

Write EETs for the above items, extending the recordWith() DSL as necessary to make expressing each type of assertion as simple as possible.

**Comment by tinker-michaelj** [comment]
Believed done in `master`.
