### ISSUE TITLE
Test upgrade feature on perfnet

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#2489]
Happy path:
- Change `settings.txt` with `state.saveStatePeriod, 901` for the least impact
- Change `config.txt` to add a fake node
- Change `VERSION` to 0.50.0

Some abort scenarios:

**Comment by Neeharika-Sompalli** [comment]
Change in settings and version are tested on perfnet.

**Comment by qnswirlds** [comment]
Done. Closing.
