### ISSUE TITLE
Add metrics for percent full on each bucket

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-services#2565]
### Problem

There needs to be more visibility into network throttles to diagnose network related issues. 

### Solution

Add metrics for percent full of each bucket.

**Comment by tinker-michaelj** [comment]
[Done](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleMetrics.java#L59).
