### ISSUE TITLE
Ensure all gRPC message are logged exclusively using `TextFormat` encoding

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2634]
### Problem

To reduce our risk from yet-to-be-found vulnerabilities in log4j2, we should only log gRPC messages in octal-encoded format.

That is, before logging any gRPC message, we should:
1. Internally convert it to a `ByteString`.
2. Log it via `TextFormat.escapeBytes()`.

### Solution

1. Add a helper function that accepts a `logger and log level` or a `consumer`, `message` string and `gRPC` message, and performs the logging with an octal-encoded message.
2. Ensure all gRPC messages logged in _hedera-node/_ go through this helper.

**Comment by rbair23** [comment]
When logging, we should think:
Only INFO and above will be logged by default.
INFO should not include stack traces
INFO is used for informational messages. It could be an exception was the genesis of the message, but it doesn't mean we should print the exception.
WARN is used for warnings. They mean something is wrong, but not fatal. An exception message may be useful, and there may sometimes be a reason to print a stack trace.
FATAL/ERROR is used for fatal errors that are unrecoverable.
Neither INFO, WARN, or FATAL/ERROR should be logged more frequently as a consequence of higher load. This means we do not log at INFO, WARN, FATAL/ERROR for each request.
INFO, WARN, and FATAL/ERROR will be processed by all of the machinery (filebeat, elastic search, etc.). We don't want this volume to be huge, but we do want it to be extremely useful for observing the behavior of the system. These should be useful logs for engineering and devops.
DEBUG and TRACE should be useful for engineering. You can log whatever seems useful at this level EXCEPT for user data. That must remain a very rare case that is approved by principal engineers or higher. But it can be incredibly verbose, print logs per transaction, etc.
