### ISSUE TITLE
EET for crypto transfers with invalid accounts

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#2663]

**Comment by Neeharika-Sompalli** [comment]
@qnswirlds  There is one EET test `CryptoTransferLoadTestWithAutoAccounts` . Not sure if this issue means the same.

**Comment by qnswirlds** [comment]
Yes, @Neeharika-Sompalli. I saw that and was running some tests with it. But it seems we need something else. I will modify this issue later to match the need. Thanks!
