### ISSUE TITLE
Null TransactionContext.consensusTime() in TokenCreateTransitionLogic

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#2801]
### Description

Creating a new token on genesis (without any other transactions yet) seems to consistently reproduce the null TransactionContext.consensusTime() in TokenCreateTransitionLogic

### Steps to reproduce

- Start a new network without saved state, i.e. genesis without any transactions yet
- Use a client to send a token create transaction

### Hedera network

other

### Version

0.21.0

### Operating system

macOS

**Comment by netopyr** [comment]
Obsolete. Does not apply to modular code.
