### ISSUE TITLE
Node must stop accepting transactions and queries if the platform notifies of an ISS 

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#284]
Node must stop accepting transactions and queries if the platform notifies of an ISS 

Will not be part of 0.7.0 release.
New platform functionality issue [#2244](https://github.com/swirlds/swirlds-platform/issues/2244)  required for implementation.

**Comment by qnswirlds** [comment]
@lbaird, @lpetrovic05, @nathanklick, could you please confirm that we can close this issue?

**Comment by lpetrovic05** [comment]
This has not been implemented as far as I know

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
