### ISSUE TITLE
Ledger ID should return 00, 01, 02 for networks

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-services#2841]
### Description

- For testnet, the ledger ID returns `30783031` when it should return `01`
- `30783031`is the UTF-8 encoding of the Unicode string "0x01" instead of the big-endian representation of the number whose hex encoding is 0x01

Related HIPs: [33](https://hips.hedera.com/hip/hip-33), [198](https://hips.hedera.com/hip/hip-198)

0x00  Hedera mainnet
0x01  Hedera stable testnet
0x02  Hedera preview net

### Steps to reproduce

Get the ledger ID from an info response. 

### Hedera network

testnet

### Version

0.22.3

**Comment by anighanta** [comment]
SDK currently converts the ByteString directly to a byte array [here](https://github.com/hashgraph/hedera-sdk-java/blob/660985f14b28d33047e310d1343e929402e6b0de/sdk/src/main/java/com/hedera/hashgraph/sdk/LedgerId.java#L38) when using the ByteString from the info protobufs. Instead they should covert to string using `toStringUtf8()` and then use it accordingly.

**Comment by SimiHunjan** [comment]
@Daniel-K-Ivanov ^^

**Comment by danielakhterov** [comment]
@anighanta Per messages in Slack, we did realize the value is the bytes for a the hex encoding of the string `0x01`, but the question is why go through all that effort? Should this value not be simply the byte array `new byte[]{0x01}`?

**Comment by anighanta** [comment]
Java 17 has `HexFormat.of().parseHex(s)` that I can use.... will test using this and we should probably be good with sending out `new byte[]{0x01}`

**Comment by anighanta** [comment]
Created a [pr](https://github.com/hashgraph/hedera-services/pull/2858) with the changes.
