### ISSUE TITLE
Adding test reports for all current hedera services regression workflows 

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#290]
**Summary**
Add a summary report for all existing hedera services regression workflows.

**Possible resolution**

1. Understand the success/failure points for each job in all regression workflows;
2. Add the .json files for each workflow;
3. Mostly not need to touch the framework except to add the pattern entries for missing job;
4. If required to go deeper validation, extend the existing summary framework;

**Comment by alittley** [comment]
stale
