### ISSUE TITLE
Review benchmarks from Gradle JMH project and add relevant to `benchmarks` module

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2912]
### Problem

It is unclear which benchmarks in [the Gradle _benchmarks/_ directory](https://github.com/hashgraph/hedera-services/tree/release/0.23/benchmarks) still apply to current code.

### Solution

Review the benchmarks and move all applicable into the `benchmarks` module.

**Comment by netopyr** [comment]
Obsolete. Does not apply to modular code.
