### ISSUE TITLE
Congestion pricing multiplier can be out-of-sync on reconnected node

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2936]
### Description

The reconnected node in a run of the [`ValidateCongestionPricingAfterReconnect`](https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateCongestionPricingAfterReconnect.java#L83) EET accepted a transaction that other nodes rejected with `INSUFFICIENT_TX_FEE`.

### Steps to reproduce

Perform a reconnect while congestion pricing is active, where the reconnect is a "node death" or a "network interrupt" with the interrupt beginning before congestion started.

### Additional context

The root cause is that during a refactor for gas throttling, the [update to the pricing multiplier](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/state/logic/ThrottleScreen.java#L53) was accidentally moved **after** [fee charging](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/state/logic/TopLevelTransition.java#L68).

Since the reconnected node does not update its active multiplier immediately on reconnect (instead just at the next `handleTransaction()`), this meant it computed fees with a different multiplier in the first transaction it saw after reconnect.

### Hedera network

other

### Version

v0.24.0

**Comment by Neeharika-Sompalli** [comment]
@tinker-michaelj The ISS failure [here](https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1646329197803209) is related to this issue?
