### ISSUE TITLE
HIP-16 Performance validation of renew/expiry for smart contracts

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-services#2953]
### Problem

Currently, this feature is not enabled for any entity. This feature needs to be enabled for smart contracts.

HIP

- [x] https://hips.hedera.com/hip/hip-16
- [x] https://hips.hedera.com/hip/hip-372

### Solution

Enable auto-renew and expiry for smart contracts

**Comment by nickpoorman** [comment]
Here is some of the ongoing work related to this https://github.com/hashgraph/hedera-services/issues?q=is%3Aissue+is%3Aopen+label%3Aauto-renewal

- [ ] #3815 
- [ ] #3743 
- [ ] #3742 
- [ ] #3741 
- [ ] #3740 
- [ ] #2223

**Comment by nickpoorman** [comment]
In order to test we will need to update the `autoRenew.targetTypes` property on the performance network to include the `CONTRACT` type.

Followed up with Michael offline:
> The current state is prior testing has shown that our current approach for controlling time spent in auto-renew/expiry (vs. time spent handling user transactions) is not robust. The open issues above will give us more fine-grained control over how much time is spent in auto-renew / expiry.
