### ISSUE TITLE
RecordQuery for old transaction Id returns DUPLICATE_TRANSACTION

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-services#2955]
### Description

Querying for an old transaction id's record returns DUPLICATE_TRANSACTION when it likely should be UKNOWN.

### Steps to reproduce

In Javascript

```
   let transaction = new TransactionRecordQuery()
    .setTransactionId(TransactionId.fromString("0.0.635859@1641397075.463599894"))
    .setIncludeDuplicates(true);

    let record = await transaction.execute(client);
```

### Hedera network

testnet

### Version

v0.23.x

**Comment by tinker-michaelj** [comment]
@gregscullard Is this reproducible?

It's most likely that the `CryptoTransfer` query payment used for the `GetRecord` query happened to have a duplicate `TransactionID`, so **the `GetRecord` query itself** was rejected in precheck.

**Comment by tinker-michaelj** [comment]
Will close by Occam's, since it's easy to see why the `CryptoTransfer` payment in the `QueryHeader` could be rejected with `DUPLICATE_TRANSACTION`; and extremely hard to see how a `TransactionID` from months earlier would still be in the system. 😁
