### ISSUE TITLE
EntityNum should be long not int

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/hedera-services#2960]
### Problem

We can not optimize a EntityNum down to a single int as we will run out of 2 billion entities in no time if usage picks up.

com.hedera.services.utils.EntityNum currently drops shard and relm and down sizes num to a single integer to save RAM. 

### Solution

This is going to far and we need to go back to a long for num. This will effect other areas which will need to be fixed.

**Comment by lbaird** [comment]
I agree. We can afford to drop the shard and realm, but we can’t afford to
shrink the 3rd component from long to int.

**Comment by rjuang** [comment]
I can probably assign this to myself. Looks like this is closely related to what I'm doing.

**Comment by rjuang** [comment]
Note to self: BinPackUtils.MAX_NUM_ALLOWED also needs to be modified.

**Comment by netopyr** [comment]
Obsolete. Does not apply to modular code.
