### ISSUE TITLE
Add the original TransferLists to the TransactionRecord

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#2965]
Because of introduction of allowance transfers, we currently aggregate the balance changes by accumulating the actual balance changes and accumulating the allowance changes separately. 

Doing this we loose the actual TransferList we get from the TransactionBody and the final TransferLists we add to the TransactionRecord loose the `is_Approval` flag from the TransferLists as the final TransferLists we add to the record are aggregated fully.

One might want to have the original transferLists in the record to have a clear view on what part of the total transfer use the allowance.

**Comment by netopyr** [comment]
Closed due to inactivity
