### ISSUE TITLE
Construct the `StateView` for a query using `StateChildren` of the latest signed state

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2970]
### Problem

Right now the singleton [`AnswerFlow`](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/queries/QueriesModule.java#L49) is constructed with [a `Supplier<StateView>`](https://github.com/hashgraph/hedera-services/blob/02968-M-BackAliasMgrWithFCHashMap/hedera-node/src/main/java/com/hedera/services/state/StateModule.java#L199) that returns `StateView`s using a `StateChildren` that references the working state.

Instead, we want each supplied `StateView` to be constructed with a new `StateChildren` instances that is backed by the children of the most recent signed state. 

### Solution

After merging https://github.com/hashgraph/hedera-services/pull/2969, 
- [ ] Create an `ImmutableStateChildren` implementation of the `StateChildren` interface (can be identical to [`MutableStateChildren`](https://github.com/hashgraph/hedera-services/pull/2969) except no setters and a constructor that takes a `ServicesState`.)
- [ ] Create a `SignedStateViewFactory` that like the [`SigReqsManager`](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/sigs/order/SigReqsManager.java#L89), is injected with the `Platform`; and when asked for a `StateView` instance, creates a `ImmutableStateChildren` in much the same way that the `SigReqsManager` updates its `MutableStateChildren` [here](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/sigs/order/SigReqsManager.java#L143); and then constructs the requested `StateView` using this `ImmutableStateChildren`. (Note this factory will also need the `ScheduleStore` and `NetworkInfo` to be injected.)
- [ ] Because it is possible that an appropriate `StateChildren` cannot always be constructed (e.g., if the `Platform` has no signed state), update the `AnswerFlow` implementations to instead use a `Supplier<Optional<StateView>>`; and update [the `StakedAnswerFlow`](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/queries/answering/StakedAnswerFlow.java#L96) and [`ZeroStakeAnswerFlow`](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/queries/answering/ZeroStakeAnswerFlow.java#L52) to return `NOT_SUPPORTED` if the `Supplier` returns `Optional.empty()`.

**Comment by netopyr** [comment]
Obsolete. Does not apply to modular code.
