### ISSUE TITLE
Answer all applicable queries from the latest durable/signed state

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2971]
### Problem

We answer a handful of queries, most notably [`getTransactionReceipts` and `getTxRecordByTxID`](https://hashgraph.github.io/hedera-protobufs/#proto.CryptoService) and [the `NetworkService` queries](https://hashgraph.github.io/hedera-protobufs/#proto.NetworkService), using only data structures that don't include any Merkle types.

But all queries that **do** return information from a Merkle data structure should be answered:
  1. _If_ a state proof is requested, from the latest fully signed state (that is, a state for which Platform has collected a strong minority of signatures: at least 1/3 of the stake).
  2. If a state proof is not requested, from the latest durable state.

_Ideally_, the gRPC thread answering such a query would not touch the working state at all---not even to perform precheck on the `CryptoTransfer` payment submitted in the `QueryHeader`. However, the task of weaning precheck off the working state deserves its own issue(s), not a checkbox on this one. 😁 

So here we only want to ensure that all of the applicable [`AnswerService` implementations](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/queries/AnswerService.java#L39) use Merkle data structures exclusively from the latest durable or signed state.

### Solution

After merging https://github.com/hashgraph/hedera-services/pull/2969, there are three tasks to be done:

- [x] https://github.com/hashgraph/hedera-services/issues/2970
- [x] https://github.com/hashgraph/hedera-services/issues/2972
- [x] https://github.com/hashgraph/hedera-services/issues/2973

**Comment by netopyr** [comment]
Obsolete. Does not apply to modular code.
