### ISSUE TITLE
Refactor `StateView` to get schedule info from `StateChildren.schedules()`, not `ScheduleStore`

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2972]
### Problem

After merging #2969, the `StateView` component will still use a `ScheduleStore` to look up information to answer queries about scheduled transactions.

But [the `HederaScheduleStore`](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java#L77) always uses the `MerkleMap<EntityNum, MerkleSchedule> schedules` from the working state.

### Solution

Switch all `StateView` query answering to use the `schedules` returned from the injected `StateChildren`; remove the dependency on `ScheduleStore`.

**Comment by netopyr** [comment]
Obsolete. Does not apply to modular code.
