### ISSUE TITLE
Refactor `ContractCallLocalAnswer` to use only infrastructure from its given `StateView`

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2973]
### Problem

Both the [`AnswerService` implementation](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/queries/contract/ContractCallLocalAnswer.java#L69)  for the `contractCallLocal` query and its [usage estimator](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsage.java#L70) are currently injected with the singleton `AliasManager` that (post-https://github.com/hashgraph/hedera-services/pull/2969 merge) will exclusively use the mutable copy of the aliases `FCHashMap`.

Even more annoying, both are injected with the singleton `AccountStore` that exclusively uses the mutable copy of the accounts `MerkleMap`. :ton

### Solution

- [ ] Update `StateView` with a new method `AliasManager aliases()` that returns an `AliasManager` constructed with the `StateView`'s `stateChildren::aliases` as supplier.
- [ ] Replace all use of the singleton `AliasManager` with the new `StateView` option; stop injecting the singleton `AliasManager` in both components listed above.
- [ ] Refactor the [`CallLocalExecutor.execute()`](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/contracts/execution/CallLocalExecutor.java#L66) method to take a `MerkleMap<EntityNum, MerkleAccount> accounts` instead of an `AccountStore`; directly look up and validate the needed accounts from this map instead of the store.

**Comment by netopyr** [comment]
Obsolete. Does not apply to modular code.
