### ISSUE TITLE
(HIP-376) "Token redirect support" for ERC20/ERC721 `approve` and `transferFrom` methods

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#3011]
### Problem

HIP-218 did not support all approval/allowance and transfer-from idioms in ERC-20 and ERC-721.

### Solution

Extend the `HTSPrecompileContract` to support these idioms via the token-redirect mechanism.

**Comment by ljkrause** [comment]
Many thanks for the speed here! :-) Much appreciate 🥇
