### ISSUE TITLE
Specially handle ethereum transaction calls to token accounts

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#3020]
### Problem

Some Defi calls go directly to token contracts. For these calls, we would like to avoid spinning up the EVM just to make a call to a precompiled contract.

### Solution

Recognize the ethereum call is to a token account and work with HTS directly through a precompile function call that we support rather than going through the EVM.

We need to handle:
- [ ] Gas charging without spinning up an EVM 
- [ ] EVM context values used by the precompile (like `msg.sender`) to be replaced by hedera contract call transaction context values
- [ ] Returning of result - precompile returns Bytes; we need to create records

**Comment by shemnon** [comment]
This is a maybe for 0.26.0, we will first implement direct through the EVM layer and then revisit to see the tradeoffs between complexity and performance.

**Comment by stoqnkpL** [comment]
Worked on this in PR #3502.
Closed the PR after discussions with the Hedera team - performance improvements were not big enough to justify the change.
