### ISSUE TITLE
Need ability use mainnet state on a local network without mainnet keys

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#3026]
### Problem

For testing, we'd like to use mainnet state. However, we do not have mainnet council keys for obvious reasons. We need a way to be able to load up a mainnet state and run a network with it, but without they council keys. Obviously this separate network would not participate with mainnet in any way or communicate with it in any way.

### Solution

We could implement a feature whereby on startup of a network with a special command line flag, we can re-key special accounts, such that while deserializing the state we replace the public key with a different public key. Perhaps we have a key-file where each line of the file has `accountNum=publicKey` and then during deserialization if we are working on that accountNum then we replace with the given public key.

**Comment by poulok** [comment]
FYI @Nana-EC for local node consideration
