### ISSUE TITLE
client receives receives grpc error 13 while the transaction data is processed by the network

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-services#304]
**Summary of the defect**
Occasionally, client application will receive grpc error 13 (rpc error: code = Internal desc = server closed the stream without sending trailers), however, the transaction is received and successfully processed by the network.

**How to reproduce (if possible)**
Please refer to #303 

The grpc code 13 error happens more frequently than DUPLICATE_TRANSACTION, in one 1600 TPS 4K run, it happened 16 times out of 2880825 total HCS messages.

**Environment:**
- OS: Ubuntu 18.04
- Go: 1.13.8
- SDK: hedera-sdk-go@master
- Hedera Services Version: in both perfnet and testnet

**Comment by ElijahLynn** [comment]
crosslinking: relevant issue https://github.com/hashgraph/hedera-sdk-js/issues/1560

**Comment by ElijahLynn** [comment]
crosslinking https://github.com/hashgraph/hedera-services/issues/5012 as it is related with `DUPLICATE_TRANSACTION`.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
