### ISSUE TITLE
Refine `INVALID_SIGNATURE` codes for SC precompile signing requirements

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#3076]
### Problem

A `ContractCall` that uses HTS precompiles can fail because of missing or invalid signatures; but every type of failure resolves to the same `INVALID_SIGNATURE` status.

Furthermore, such a failure can occur **only** because a [public key's full prefix](https://hashgraph.github.io/hedera-protobufs/#proto.SignaturePair) was not included in the `SignatureMap`; and this full-prefix requirement needs to be better publicized. 

### Solution

- Resolve to a different response code depending on what precompile failed its signature check.
- Emphasize the full-prefix requirement in the code, e.g. `INVALID_FULL_PREFIX_SIGNATURE_FOR_TRANSFER_PRECOMPILE`

**Comment by stoqnkpL** [comment]
Fixed with https://github.com/hashgraph/hedera-services/pull/3590
