### ISSUE TITLE
Updated throttle values on public testnet and mainnet

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-services#308]
The public testnet and mainnet will be updated to the following values:

- 13 tps (crypto create, contract and file operations) 
- 8,000 tps (crypto operations (excluding crypto create), and queries)
- 3,000 tps (all consensus operations aside from createTopic)
- 5 tps (createTopic)
- Receipts will not have a throttle

**Comment by tinker-michaelj** [comment]
Here is a [a candidate file `0.0.121`](https://github.com/hashgraph/hedera-services/files/5271446/new-testnet-file121.txt) to use when updating preview- and stable-testnet throttles.

**Comment by tinker-michaelj** [comment]
The [candidate file `0.0.121`](https://github.com/hashgraph/hedera-services/files/5279304/new-testnet-file121.txt) to use when updating preview- and stable-testnet throttles; changed to reflect 8k crypto/6k HCS throttles.

**Comment by jsindy** [comment]
@tinker-michaelj DevOps is just getting this file into testing today cc @tannerjfco.

@tinker-michaelj can you provide the 4 or 5 lines I need to adjust in the currently version of the application.prop on testnet. Keeping in mind this is a 4 node network. I would like to make that change today and then adjust to using the buckets once we finish testing.

**Comment by jsindy** [comment]
Completed on testnet.

**Comment by jsindy** [comment]
@tinker-michaelj we have been requested to make the following adjustment
6,000 tps (all consensus operations aside from createTopic) to 3,000

Can you confirm this line needs to be changed to 3000? hapi.throttling.buckets.slowOpBucket.capacity=


For those following along the new settings would be

13 tps (contract and file operations) 
8,000 tps (crypto operations, and queries)
3,000 tps (all consensus operations aside from createTopic)
5 tps (createTopic)
Receipts will not have a throttle

**Comment by tinker-michaelj** [comment]
To reduce the max TPS for `{ ConsensusDeleteTopic, ConsensusUpdateTopic, ConsensusSubmitMessage }` to 3k, we can **add** these three lines to the existing file `0.0.121`:
```
hapi.throttling.ops.consensusUpdateTopic.capacityRequired=2.67
hapi.throttling.ops.consensusDeleteTopic.capacityRequired=2.67
hapi.throttling.ops.consensusSubmitMessage.capacityRequired=2.67
```

**Comment by jsindy** [comment]
Update completed on Testnet.

**Comment by jsindy** [comment]
Testnet and mainnet were updated.

We also added 

```
hapi.throttling.ops.cryptoCreate.bucket=slowOpBucket
hapi.throttling.ops.cryptoCreate.capacityRequired=461.0
```

To keep account creation at 13TPS

**Comment by tinker-michaelj** [comment]
Obsolete.
