### ISSUE TITLE
Add new functions to the safe HTS library + E2E tests

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#3132]
This issue is implemented with [PR2866](https://github.com/hashgraph/hedera-services/pull/2866), however, we need to resolve Danno's comment and move the code to another repo.

**Comment by Kalina-Todorova** [comment]
https://github.com/hashgraph/hedera-smart-contracts/pull/4

**Comment by stoqnkpL** [comment]
I just noticed Danno also said
> a testing app/framework should be set up that can test local or public networks (ideally only testnet and previewnet) should be added to verify the safe variants work as expected"

**Comment by Kalina-Todorova** [comment]
Tracked in https://github.com/hashgraph/hedera-smart-contracts/issues/43 
Closing this issue.
