### ISSUE TITLE
ContractGetByteCode should return deployed bytecode, not initcode

### ISSUE THREAD

**Issue by shemnon** [hashgraph/hedera-services#3140]
### Problem

When I try and query the bytecode of a contract via HAPI I get the initcode, or constructor code, of the smart contract.  What I need is the deployed bytecode for an address

### Solution

Update ContractGetBytecode to return the code from the CodeCache, like a smart contract call would query from.

**Comment by tinker-michaelj** [comment]
@shemnon [here](https://github.com/hashgraph/hedera-services/blob/03017-getBytecodeAnswer-not-initcode/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java#L616) is an EET that fails trying to assert `getContractBytecode` returns the initcode.

From code inspection I also don't see how the `getContractBytecode` answer for `0.0.X` could differ from what is in the `CodeCache` for `0.0.X`. 🤔

**Comment by shemnon** [comment]
The EET is explicitly checking that the result is the initcode, which is the bug.  The initcode execution results in deploying different code than the init code, which for most cases is all but the first 32 bytes of the init code.   The code cache does not have the initcode but this runtime code.

**Comment by shemnon** [comment]
This can be closed.  I found a [better test](https://github.com/hashgraph/hedera-services/blob/972c4bd6d05e93a887c1984ae346a9a87028c1c1/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractGetBytecodeSuite.java#L89) that shows we are returning the correct result.
