### ISSUE TITLE
Newly created token through the precompile not accessible through ERC20/721 redirect functions

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#3150]
### Description

I tried using a newly created token through the precompile not accessible through ERC20/721 redirect functions. Unfortunately loading the token through the Stacked World Updaters results in `INVALID_SOLIDITY_ADDRESS`. 
Need to move logic recognizing token accounts and returning the redirect bytecode to Stacked updaters as well (currently it's only applied to HederaWorldState.Udater)

### Steps to reproduce

- I created a token through the smart contract service using the new Token Create Precompile function.
- I tried using the address of the newly created token for a ERC721 call
- I got a `INVALID_SOLIDITY_ADDRESS` when loading the account

### Hedera network

other

### Version

local build latest master

**Comment by littletarzan** [comment]
Also testing this and getting response code 21. I had also gotten a revert for insufficient gas, was the gas limit raised high enough to afford the $1 fee?
