### ISSUE TITLE
Convert legacy test com.hedera.services.legacy.CI.MultipleCryptoTransfers to EET

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#317]
**Summary**
Part of Moving all legacy tests to EET suits

test to convert `com.hedera.services.legacy.CI.MultipleCryptoTransfers`

**Comment by qnswirlds** [comment]
@anighanta, @tinker-michaelj, could you please confirm that this issue is resolved?

**Comment by ljianghedera** [comment]
Closed by issue #604
