### ISSUE TITLE
Allow max supply for fungible tokens

### ISSUE THREAD

**Issue by KilianB** [hashgraph/hedera-services#3179]
### Description

Creating a fungible token with a max supply will always fails with a INVALID_TOKEN_MAX_SUPPLY pre check due to the following code:

https://github.com/hashgraph/hedera-services/blob/bd49d0a5f7e0f3ca319a344c96c2e4d636c701e3/hedera-node/src/main/java/com/hedera/services/txns/validation/TokenListChecks.java#L94-L103

The docs state that the maxSupply parameter should be viable for fungible tokens

> IWA Compatibility. Depends on TokenSupplyType. For tokens of type FUNGIBLE_COMMON - the maximum number of tokens that can be in circulation. For tokens of type NON_FUNGIBLE_UNIQUE - the maximum number of NFTs (serial numbers) that can be minted. This field can never be changed

https://docs.hedera.com/guides/docs/hedera-api/token-service/tokencreate

Ref: https://github.com/hashgraph/hedera-sdk-js/issues/1071

### Steps to reproduce

1. Try to run a token create transaction with any sdk.

```typescript
const createTx = new TokenCreateTransaction({
  tokenName: tokenName,
  tokenSymbol: tokenSymbol,
  supplyKey: privateKey,
  decimals: 8,

  initialSupply: 10_000_000,
  maxSupply: 10_000_000,
  treasuryAccountId: operatorAcc,
  tokenMemo: tokenMemo,
});
````

2. a pre check error will be returned.

### Hedera network

testnet

### Version

v0.24.2

**Comment by tinker-michaelj** [comment]
Hey @KilianB, thanks for the issue! You are getting the `INVALID_TOKEN_MAX_SUPPLY` response because the [default supply type](https://hashgraph.github.io/hedera-protobufs/#proto.TokenSupplyType) is **infinite**. So we need to specify finite in the `TokenCreate` operation, e.g.
```
const createTx = new TokenCreateTransaction({
  tokenName: tokenName,
  tokenSymbol: tokenSymbol,
  supplyKey: privateKey,
  decimals: 8,
  supplyType: TokenSupplyType.Finite,
  initialSupply: 10_000_000,
  maxSupply: 10_000_000,
  treasuryAccountId: operatorAcc,
  tokenMemo: tokenMemo,
});
```
