### ISSUE TITLE
Convert legacy test com.hedera.services.legacy.CI.TxRecordTest to EET suite

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#318]
**Summary**
part of moving all legacy tests to EET to suits.

class to move : `com.hedera.services.legacy.CI.TxRecordTest`

**Comment by qnswirlds** [comment]
@anighanta, @tinker-michaelj, could you please confirm that this issue is resolved?

**Comment by ljianghedera** [comment]
Closed by #604
