### ISSUE TITLE
Convert legacy test com.hedera.services.legacy.CI.NegativeAccountCreateTest to EET suite

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#319]
**Summary**
Part of moving all legacy test to EET suits

class to move : `com.hedera.services.legacy.CI.NegativeAccountCreateTest`

**Comment by qnswirlds** [comment]
@anighanta, @tinker-michaelj, could you please confirm that this issue is resolved?

**Comment by ljianghedera** [comment]
Closed by #604
