### ISSUE TITLE
HIP-372: Entity Auto-Renewals and Expiry Window

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-services#3192]
### Problem

HIP: https://hips.hedera.com/hip/hip-372

The original HIP-16 mentions the auto renewal duration between ~81 days and ~92 days. The rationale was to provide a wider window for the auto-renew duration period for better flexibility.

### Solution

The minimum auto-renew period will be equal to ~30 days (2,592,000 seconds), and the max auto-renew duration will remain equal to ~92 days (8,000,001 seconds).

**Comment by tinker-michaelj** [comment]
The values in this issue are the [active defaults](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/LedgerConfig.java#L37).
