### ISSUE TITLE
Convert legacy test com.hedera.services.legacy.file.FileServiceIT to EET suite

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#325]
**Summary**
part of moving all legacy tests to EET suits.

class to move : `com.hedera.services.legacy.file.FileServiceIT`

**Comment by ljianghedera** [comment]
While I am working on the issue #470, which is also file service related, I will pick up these related issues and move them to EET suites.

**Comment by ljianghedera** [comment]
All of these are moved.

**Comment by ljianghedera** [comment]
Closed by #604.
