### ISSUE TITLE
Convert legacy test com.hedera.services.legacy.file.SystemDeleteIT to EET suite

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#326]
**Summary**
part of moving all legacy tests to EET suits.

class to move : `com.hedera.services.legacy.file.SystemDeleteIT`

**Comment by ljianghedera** [comment]
The test scenarios need to move to EET :
1.  Contract deletions
2. Add negative test cases to System file deletions;

**Comment by ljianghedera** [comment]
Closed by issue #604
