### ISSUE TITLE
Queries: Additional validation on transfer transactions that pay for queries.

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#332]
**Summary**
Current clients can submit queries which are paid for by transfer transactions.
Currently we validate the payer signature and balance on the transfer transactions.
However a client could submit a query with a transfer transaction that could pay the network fees but NOT cover the node's fee to satisfy the query.

**Possible resolution**
We can protect against this by adding the following validations to query payments 

- [x] Validate each payer in transferList has balance to cover the transfer amount.

- [x] If the transaction payerID also exists in transferList for query payment transfer transaction, validate that payer has balance to cover transaction fee and the transfer amount

- [x] Number of beneficiaries in transfer need not be one. 

- [x] But node should be getting required `queryFee` amount which is positive number

Unit tests to be done :

- [x]  multiple payers pay amount to node 

- [x] multiple payers pay amount to node as well as one more beneficiary. But node gets correct query payment fee

- [x] multiple payers pay amount to node as well as one more beneficiary. But node gets less query payment fee

- [x] TransactionPayer will pay for query payment to node and payer has enough balance

- [x] TransactionPayer will pay for query payment to node and payer has less balance

- [x] Transaction payer is not involved in transfers for query payment to node and all payers have enough balance

- [x] Transaction payer is not involved in transfers for query payment to node and one or more have less balance

**Comment by Neeharika-Sompalli** [comment]
@lbaird  @donaldthibeau 

As per discussion with @noshmody, the following checks will be added in addition for the transfer transaction that pay for queries:
1.  Transfer list `transfers` should have only two account amounts in which payer account is transferring to node account.
2.  PayerAccountID  `transactionID.accountID` in transaction should be the same as the sending account in transfers list.
3. `nodeAccountID` should be the same as amount receiving account in transfers list.

Is that okay?

```
body=transactionID { 
       transactionValidStart { seconds: 1600185196 nanos: -978 } 
       accountID { accountNum: 2 } 
} 
nodeAccountID { accountNum: 3 } 
transactionFee: 84163 
transactionValidDuration { seconds: 120 } 
 memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" 
cryptoTransfer { 
    transfers { 
        accountAmounts { 
            accountID { 
                accountNum: 2 
                } 
                amount: -8 
            } 
            accountAmounts { 
                accountID { 
                    accountNum: 3 
                    } amount: 8 
            }
      }
}

**Comment by donaldthibeau** [comment]
@kenthejr @atul-hedera could you both please review?

**Comment by Neeharika-Sompalli** [comment]
Updated validations after discussion with @lbaird @noshmody 

1. Transfer transaction can be paid by more than one payer. So, number of account amounts in transfer list of query payment transfer transaction is not limited to two. 
2. Validate each payer in transferList has balance to cover the transfer amount.
3. If the transaction payerID also exists in transferList for query payment transfer transaction, validate that payer has balance to cover `transaction fee` and the `transfer amount`

**Comment by atul-hedera** [comment]
Do we need to also validate that each payer in the transferList has signed on the transaction?

**Comment by lbaird** [comment]
Yes, that should be part of the precheck.

________________________________

**Comment by Neeharika-Sompalli** [comment]
Yes that validation is currently done
