### ISSUE TITLE
Block does not contain child records from previous block parent tx

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#3340]
- Write an E2E test which verifies that block does not contain child records from previous block parent tx
- From: https://www.notion.so/swirldslabs/c306bbf842264eb391a9ee4cc92e1639?v=94195c43eba64dc2a39d79fc93c838de

**Comment by poulok** [comment]
This will be implemented as part of the block stream. It should already be done for the record stream.
