### ISSUE TITLE
Prepare a mono-repo for platform and services

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#3345]
### Problem

Hashgraph platform is currently built in a separate repo from services. Conceptually this works because the platform is intended to be useful for a variety of applications and not just Hedera DLT. However, now that Hedera has purchased the rights to the code and patents, we want to bring development of the Hashgraph platform into the hashgraph org on github. Today, the platform has to be developed a release in advance of the rest of the services code, and changes to the platform APIs have to be done in two steps: once in platform, then once in services. This friction makes it very difficult to coordinate work-in-progress builds across both code bases.

### Solution

Use a mono-repo for platform and services, and possibly eventually include mirror node and other projects.

There are multiple ways to design a loosely coupled component-oriented design. You can break components over different repos. Or you can have a mono-repo with a build system that builds the components individually. The key decision between having separate repos or a mono-repo is about the team organization and/or the release model.

In our case, since the platform APIs are in serious flux and we release to production the combination of platform and services together, it makes a lot of sense to combine the two into the same repo. We will still build and publish maven modules separately, but by putting them into the same repo we can more easily modify platform APIs and update services at the same time and test the entire end result on Hedera at the same time. We can also align the release schedules for platform and services.

Building a mono repo will require reorganization of the existing repo. We are also going to move to Gradle which has very strong support for mono-repo builds.

- [x] #3365
- [x] #3366
- [x] #3367
- [x] #3368

**Comment by tinker-michaelj** [comment]
Done.
