### ISSUE TITLE
Migrate hedera-services to Gradle

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#3365]
In preparation for the mono-repo (platform + services), migrate the build system from Maven to Gradle. Both Maven and Gradle have widespread industry acceptance and are able to build complex projects. Gradle is faster and more flexible and tends to have smaller and more succinct build files. The only problem with Gradle is that it gives so much power to the build system author that if not careful, like any other code, it can become messy, so the build should have a code owner and go through code review like any other code.

Must have:
- [x] #3369
- [x] #3370
- [x] #3371
- [x] #3380
- [x] #3378 
- [x] #3374
- [x] #3372
- [x] #3463
- [x] #3373
- [x] #3694

Can be added after initial cutover:
- [ ] #3376
- [x] #3379
- [ ] #3361 
- [x] #3433 
- [ ] #3377
- [ ] #3412
- [ ] #3457
- [ ] Use custom JRS Github action to automate setup of EET environments

**Comment by david-bakin-sl** [comment]
Actual _unit tests_ in `test-clients` don't work.  You can put an `@Test` annotated class in `test-clients/src/test/java/com/hedera/services/yahcli/commands` and it won't get found, won't get run.  In fact, the test running in IntelliJ reports "Test events were not received" and running `./gradlew test -tests <testclassname> -i` at the command line reports no such test found.

(There are currently _no_ unit tests there but it should be possible - as `yahcli` gets more features, for example, there might be a need for unit testing in there.)

**Comment by tinker-michaelj** [comment]
Done.
