### ISSUE TITLE
Change running hash calculation of record stream files to enable individual transaction and record removal without impacting running hash of record stream.

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#337]
**Summary**
Add a running hash to record stream files to enable removal of individual records without impacting this new running hash of record stream.

**Possible resolution**
A new running hash of the record stream will be calculated using the hash of transactions & records.
This will allow the removal of individual records from the record stream without impacting the running hash of the record stream.

**Comment by steven-sheehy** [comment]
No longer applicable
