### ISSUE TITLE
Move end to end tests to src/eet/java

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#3412]
The end to end tests are in `test-clients/src/test/java`. By default Gradle will execute these as part of `./gradlew test`, thinking they are unit tests. But they should be in `test-clients/src/eet/java`. This cannot be done until after we remove support for Maven because maven expects them to be where they are today. So after we remove maven, we should move the tests to their new home. We can then remove some extra build logic in the test-client's `build.gradle.kts`.

**Comment by netopyr** [comment]
Obsolete. The build system changed substantially since this issue was filed.
