### ISSUE TITLE
Build EVM component separately to allow simulations of eth calls

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#3415]
Research on building the EVM component separately with stores, etc.. and injecting it in the Mirror-node in order to make simulations of Eth calls.

The modularisation of the EVM can happen in 3 stages:

- Stage 1: Extract the EVM in a new module, without precompiles; Make the EVM module work with interfaces defined [here](https://limechain.notion.site/EVM-module-379313f2818949039bf9eaa2640c0470). Services implements the interfaces from the EVM module.
- Stage 2: The EVM Module interfaces have default implementations and Mirror-node implementations
- Stage 3: Add the precompile logic

**Comment by IvanKavaldzhiev** [comment]
Replaced with new more detailed epics.
