### ISSUE TITLE
Add Spotless/GoogleJavaFormat step to gradle build

### ISSUE THREAD

**Issue by shemnon** [hashgraph/hedera-services#3433]
Add the spotless plugin with the GoogleJava Format.

For now this will not be build breaking or blocking due to issue with the google java plugin in IntelliJ (we need version 2022.2.0 to ship, which changes the java baseline to 17).

To run spotless `./gradlew spotlessApply`
To run a check that will fail the build on formatting violations but no brea the build `./gradlew spotlessCheck`

**Comment by nathanklick** [comment]
Closed via #3374
