### ISSUE TITLE
Enable a HCS transaction to carry a crypto transfer

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-services#345]
**Summary**
This request came from Pablo via Discord. He would like to be able to include a crypto transfer as part of a HCS transaction.

We (Developer Advocates) have internally thought this would be a good idea which would enable hBAR settlements to take place as part of a HCS driven business process. 

An alternative could be that upon receipt of a given HCS message, only one of the participants sends payment, but this assumes the participant isn't being malicious. All participants could send payment from the payer's account which would result in N-1 failures (invalid signatures) and would require specific processing within the application to handle the failure as a false positive.

**Comment by publu** [comment]
What's the status?

**Comment by donaldthibeau** [comment]
Our team has been evaluating designs for enabling tokenization in line with Hedera differentiators. Will close out this issue as updated issues will be created once we have prioritized into the roadmap.
