### ISSUE TITLE
Extend test-clients to support reading of record files and assertions

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#3467]
### Problem

We need to be able to read created files by the record stream and be able to assert some checks.

### Solution

Extend test clients to support the following assertions: 
- [x] Record file is created
- [x] Record file has the correct block number
- [x] Record file contains a correct list of transactions and transaction records
- [x] Some transaction or transaction record is in the record file
- [ ] Sidecar records related to the same period are externalized in sidecar files

**Comment by Kalina-Todorova** [comment]
Done.
