### ISSUE TITLE
Test CongestionPricing-NDReconnect-1-16m failed because CustomSpecAssert

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#3491]
### Description

Slack report URL

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1654162808626339
https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1654159462996929

```
2022-06-02 09:38:46.689 WARN   217  HapiSpecOperation - 'ValidateCongestionPricing' - CustomSpecAssert failed ~10x multiplier should be in affect! ==> expected: <10.0> but was: <1.0>!


```

### Steps to reproduce

Nightly regression circle ci job GCP-ND-Reconnect-Correctness-6N-1C

### Hedera network

other

### Version

latest master branch

### Operating system

Linux

**Comment by JeffreyDallas** [comment]
The failure seems caused by PR #3234 

I experimented with the earlier commit #a9e94f4ab3.  multiple times, and the test passed.

**Comment by IvanKavaldzhiev** [comment]
@statop It seems also other E2E specs are failing (e.g. EthereumSuite)

**Comment by statop** [comment]
the problem is that genesis is now throttle exempt at both hapi and consesus levels, as it should be.

So the contractCall ops the test is making to cause congestion are not actually causing congestion. 

I will make the same changes I made to CongestionPricingSuite.

**Comment by statop** [comment]
@JeffreyDallas  please retry with latest long-term-scheduled-transactions-cleanup branch

**Comment by statop** [comment]
@IvanKavaldzhiev  it looks like EthereumSuite was failing before my pr, I checked out https://github.com/hashgraph/hedera-services/commit/a9e94f4ab39832845cff5ded94c2e7ead9386daf (the commit before mine) and it still failes.

**Comment by statop** [comment]
@JeffreyDallas  Got it to pass - https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1654281482540279

Although I am worried this tests has never actually tested what it wants to test. 

The reconnect always takes longer than it takes congestion pricing to end. 

The transactions after the reconnect are just re-triggering congestion after reconnect.
