### ISSUE TITLE
Avoid polling pattern to reduce CPU idle spinning 

### ISSUE THREAD

**Issue by rjuang** [hashgraph/hedera-services#3509]
### Problem

Noticed while profiling that we have patterns like:

```
while (someVariable) {
    final var task = queue.poll();
    if (task != null) {
       task.run();
    }
}
```

which show up in the profiler as occupying a substantial amount of invocation counts.

### Solution

Avoid unnecessarily polling queues and switch to a block and wait pattern if possible. This should free up CPU resources and make things slightly more efficient.

**Comment by rjuang** [comment]
Without PR #3510,
```
Benchmark                                  Mode  Cnt      Score       Error  Units
NonBlockingHandoffBench.simpleProcessing  thrpt   10  30188.031 ± 15698.228  ops/s
```

With PR #3510,
```
Benchmark                                  Mode  Cnt       Score      Error  Units
NonBlockingHandoffBench.simpleProcessing  thrpt   10  176629.733 ± 2314.701  ops/s
```

**Comment by tinker-michaelj** [comment]
Done.
