### ISSUE TITLE
Remove SwirldState.noMoreTransactions()

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#3511]
[This platform PR](https://github.com/swirlds/swirlds-platform/pull/5512) removes the `SwirldState.noMoreTransactions()` method, so it must be removed from the `SwirldState` implementation in hedera-services.

The method informed the state when it would never receive a transaction again, but it is not used by any current service. If a service does need to cleanup resources in the future, it can be done when the state is fully released per the `Releasable` interface. If the `SwirldState` extends one of the partial merkle implementations (e.g. `PartialMerkleLeaf` or `PartialNaryMerkleInternal`) then it can put that cleanup in the `onDestroy()` method, which is called when the object becomes fully released.

**Comment by tinker-michaelj** [comment]
Done.
