### ISSUE TITLE
HTS Tokens emit events with wrong emitter `address`

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hedera-services#3530]
### Description

HTS has the nice feature to intercept `ERC20` and `ERC721` like interactions and call the HTS Precompile `0x167` contract. This enables developers to use HTS tokens as if they are `ERC20`s. 

`ERC20` tokens have a set of events that are emitted during various interactions. 

When events are emitted, developers **expect** the emitter to be the `HTS` token they are interacting with. F.e if they "expect" `transfer` event to be emitted when they do:
```Solidity
htsToken.transfer(receiver, amount);
```
they are expecting that the log emitted is:
```json
[
  {
    "address": "EVM_ADDRES_OF_HTS_TOKEN",
    "index": 1,
    "data": "0x000000000000000000000000000000000000000000001226942c7170b1e10000",
    "topics": [
      "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
      "0x000000000000000000000000a1c012016b7d7e40cc04abdd5c90f5923065b3aa",
      "0x0000000000000000000000005bb6ad79eac48cb590a2085ea5da8e88553a4f9e"
    ]
  }
]
```
Currently the emitter of the event is the `0x167` precompile:

```json
{
    "address": "0x0000000000000000000000000000000000000167",
    "bloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000001000008002000000000000000000000000000000000000000000000000000008000000000000000000000004000000000000010000400000000000000000000000000000000000000000000000000000000000000000000000000020400000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "contract_id": "0.0.359",
    "data": "0x000000000000000000000000000000000000000000000000000000174876e800",
    "index": 1,
    "topics": [
        "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
        "0x0000000000000000000000000000000000000000000000000000000001c42505",
        "0x0000000000000000000000000000000000000000000000000000000002bd51ff"
    ]
}
```

Additionally, when events contain addresses like `from` and `to` of a transfer, we should write the aliased value of the address instead of the mirror-node equivalent.

In ERCTransferPrecompile#getLogForFungibleTransfer, when loading the addresses for `sender` and `receiver`, check whether they're aliased, e.g. instead of doing `asTypedEvmAddress(fungibleTransfer.sender())`, try doing `super.ledgers.canonicalAddress(asTypedEvmAddress(fungibleTransfer.sender()));`

### Steps to reproduce

1. Create and deploy a smart contract that does `IERC20(HTS_TOKEN).transfer`
2. Get the transaction record and see the `address` property of the `log`

### Hedera network

mainnet, testnet, previewnet

### Version

v0.26.2

### Operating system

macOS

**Comment by stoqnkpL** [comment]
Reopening this, since there's still an issue if the event is emitted on Approval. It is however fixed for Transfers.

**Comment by Nana-EC** [comment]
Please confirm if there are any-other precompile functions that should have events emitted and aren't
