### ISSUE TITLE
ServicesStateTest flakiness

### ISSUE THREAD

**Issue by rjuang** [hashgraph/hedera-services#3540]
### Description

Occasionally, PRs fail the build check with an exception:
```
Error:    ServicesStateTest.setUp:188->setAllChildren:873 » IllegalArgument File system ...
```

The section of code pointer failing is here:
```
	private void setAllChildren() {
		try {
			FileUtils.cleanDirectory(new File("database"));
		} catch (Exception ignore) { }
		subject.createGenesisChildren(addressBook, 0);
	}
```

### Steps to reproduce

1. Create a PR.
2. Wait for build check to come back. Maybe 1 / 10 runs hit this flakiness.

### Hedera network

other

### Version

n/a

### Operating system

Other

**Comment by tinker-michaelj** [comment]
Believed resolved by moving the `ServicesStateE2E` tests into `ServicesStateTest`.
