### ISSUE TITLE
Find out platform stats sudden jump for transaction rcv and sub stats

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#355]
**Summary of the defect**
During JRS's performance testing, observed a strange behavoir for HCS submitMessage requests, when in high TPS scenarios, there are jumps of submitMessageRcv/sec and submitMessageSub/sec in the stats graph. 

Similar behaviors are also observed in Crypto transfer requests.

This may indicate some issue in hedera service stats handling or other functional areas. Or at least to provide reasonable explanation of such behavior.

**How to reproduce (if possible)**
Needs to run performance tests using JRS framework to show the behavior. Please refer to the attached recorded stats graphing files for details. 

[cryptoTransferTest.pdf](https://github.com/hashgraph/hedera-services/files/4972898/cryptoTransferTest.pdf)
[HCS-submitMessageCase.pdf](https://github.com/hashgraph/hedera-services/files/4972899/HCS-submitMessageCase.pdf)

**Service logs (if applicable)**
```
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by tinker-michaelj** [comment]
Stats are now known to have some timing artifacts, not a material issue however.
