### ISSUE TITLE
Provide `EvmSigsVerifier` interface + default implementation using bytes

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#3569]
### Problem

Currently in order to validate sender keys in precompiles we use `JKey` representation of the keys. In order the `hedera-evm` library to be reusable and more dynamic we would need an interface that works directly on the key bytes representation instead of the `JKey` abstraction. `mirror-node` save key data in the form of bytes in the PostgreSQL DB, so we should adapt key validation logic to work on bytes level.

`hedera-node` would need to extend the implementation and provide logic for extracting the bytes from a given `JKey`.

### Solution

Define `EvmSigsVerifier` interface that works directly on key bytes and a default implementation that validates this bytes representation.

**Comment by IvanKavaldzhiev** [comment]
Won't be needed since the EVM library won't support signature verification logic.
