### ISSUE TITLE
Add `TransactionContext` interface for fetching transaction metadata

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#3571]
### Problem

In order to access different transaction related metadata (e.g. `activePayer`, `rationalizedPkToCryptoSigFn`, etc.) we need to introduce a special interface.

### Solution

Define `TransactionContext` interface that will provide needed metadata for a given transaction. It would have specific implementation on `hedera-node` and `mirror-node` side.

**Comment by IvanKavaldzhiev** [comment]
Won't be needed.
