### ISSUE TITLE
Add `ActivationTest` interface for signature verification + default implementation

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#3574]
### Problem

In order to be able to verify signatures we would need a special `ActivationTest` interface that provides test method for verification. It should be adapted to work directly on key bytes representation instead of `JKey` abstraction. We would also need default implementation that proofs the validity of those key bytes.

### Solution

Provide definition of `ActivationTest` interface that works directly on key bytes.
Provide default implementation that validates key bytes.

**Comment by IvanKavaldzhiev** [comment]
Won't be needed since the EVM library won't support signature verification logic.
