### ISSUE TITLE
Fix Fee calculation for FileUpdate

### ISSUE THREAD

**Issue by mohsin-hedera** [hashgraph/hedera-services#3600]
### Description

The Fee calculator report $0.05 for FileUpdate transaction instead of $0.0005
![image](https://user-images.githubusercontent.com/92186249/176029290-80624edb-92d5-4c93-a88e-06d7b95a358f.png)

### Steps to reproduce

View FeeUpdate transaction. 
![image](https://user-images.githubusercontent.com/92186249/176029490-46bf48e2-d996-49cf-96e2-11012fad5936.png)

### Hedera network

other

### Version

0.27

### Operating system

Other

**Comment by Neeharika-Sompalli** [comment]
@mohsin-hedera  The fees for file update is $0.05 as mentioned [here](https://docs.hedera.com/guides/mainnet/fees).  Is the clip for fees posted an old one ?

**Comment by mohsin-hedera** [comment]
It turns out the 'bug' was in the documentation. The docs were subsequently updated.
