### ISSUE TITLE
(Placeholder) Support transaction-based `AddressBook` updates

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#3611]
### Problem

We need to design and implement a transaction-driven mechanism for `AddressBook` updates.

### Solution

TBD

**Comment by steven-sheehy** [comment]
The address book is just the storage of the list of nodes. Suggestion is to use the concept of a node as a new entity type and transactions oriented around that. `NodeCreateTransaction`, `NodeUpdateTransaction`, etc.

**Comment by lbaird** [comment]
A node won’t be an entity type (with an address like 0.0.123).  But it’s
fine to use the word “Node” as if it were a service name, as in
NodeUpdateTransaction.

**Comment by Neeharika-Sompalli** [comment]
This will be done by Dynamic Address Book Phase 2
