### ISSUE TITLE
Nodes should decline `COST_ANSWER` queries if not active

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#3626]
### Description

A reconnecting node did not immediately reject a `COST_ANSWER` version of a `ContractCallLocal`; instead it tried to compute the cost (which requires a valid signed state), and failed with `FAIL_INVALID`.

### Steps to reproduce

Submit `ContractCallLocal` queries to a reconnecting node.

### Hedera network

other

### Version

v0.27.2

**Comment by netopyr** [comment]
This has been fixed with modularization.
