### ISSUE TITLE
Unable to create a contract with max_automatic_token_associations

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-services#3630]
### Description

Creating a contract with the create parameters having a nonzero max_automatic_token_associations fails.

### Steps to reproduce

Create a contract with max_automatic_token_associations greater than zero in the create parameters
query the info for the contract

expected the max_automatic_token_associations to be the value that was set in the create parameters, instead it is zero.

### Additional context

Prob. related to #3629

### Hedera network

previewnet

### Version

Current PREVIEWNET

### Operating system

Windows

**Comment by tinker-michaelj** [comment]
Hi @bugbytesinc! We're still finalizing the details of charging rent for contracts; until that is done, it's unclear how to support `max_automatic_associations` for contracts.

But excellent point...will post here as I know more.

**Comment by Neeharika-Sompalli** [comment]
Yes we should fail on `ContractCreate` that includes `max_automatic_token_associations`. Because don't support that. Will validate if that works in modular code

**Comment by Neeharika-Sompalli** [comment]
In mod service this fails with `NOT_SUPPORTED` as expected. The test validating this scenario is in [this](https://github.com/hashgraph/hedera-services/pull/12696) PR
