### ISSUE TITLE
Add a limit to contract creates with internal transacitons

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#3696]
### Description

There is a property limiting the max allowed following child records for a transaction. However, there is no limit on the internal contract creations and this leads to catastrophic failures on the consensus node.

### Steps to reproduce

Call a contract that creates 50+ contracts internally.

### Hedera network

other

### Version

latest

**Comment by Kalina-Todorova** [comment]
Handled with https://github.com/hashgraph/hedera-services/pull/3753
