### ISSUE TITLE
`ExpandHandleSpan.accessorCache` may become a bottleneck

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#3705]
### Description

As described in [#5704](https://github.com/swirlds/swirlds-platform/issues/5704), `ExpandHandleSpan.accessorCache` may become a bottleneck under heavy load after a short delay (1.5 second) in the platform `event-intake` thread. Severe contention between only two threads, `event-intake` and `thread-cons`, happens due to the former calling `accessorCache.put()` during `explandSignatures()` and the latter calling `accessorCache.getIfPresent()` during `handleTransaction()`. In a particular case, the high contention period was ~16 seconds, which deteriorated event intake even more. 
Most of the time in both threads was spent on `expireEntries()` in `LocalCache.Segment.`. The `event-intake` thread was also seen blocked on the `LocalCache.Segment` lock before entering `put()`.
It took ~12 minutes for the platform to fully recover from the condition manifested by long C2C (~65 sec) and high negative `syncGenDiff` (-5800).

### Steps to reproduce

10K crypto transfer perf test 

### Hedera network

other

### Version

v0.28.0

### Operating system

Linux

**Comment by netopyr** [comment]
Obsolete. Does not apply to modular code base.
