### ISSUE TITLE
ContractCreateTransaction() and ContractUpdateTransaction() not able to stake to account ID

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-services#3707]
### Description

- AccountCreateTransaction() and AccountUpdateTransaction() stake to _nodes_ and _accounts_ successfully

- ContractCreateTransaction() and ContractUpdateTransaction() stake to _nodes_ successfully

- **ContractCreateTransaction() and ContractUpdateTransaction() CANNOT stake to _accounts_** 

### Steps to reproduce

See and run the index.js in this codesandbox.
https://codesandbox.io/s/hedera-example-staking-contract-ir258c?file=/index.js

Enter testnet credentials in .env
After creation the contract should stake to the Operator account.
After update the contract should stake to Alice's account

Double checking in mirror nodes shows that the contract account is staked to node 0. 
Here's the view for a contract account on HashScan: https://hashscan.io/#/testnet/account/0.0.47722830

@tinker-michaelj  @Neeharika-Sompalli 
Please let me know if I'm missing something or if there's an issue in services.

### Hedera network

testnet

### Version

v27.4

### Operating system

Windows

**Comment by tinker-michaelj** [comment]
Hey @ed-marquez, it looks like you are setting both the node id and staked account id in these cases
![Screen Shot 2022-07-21 at 7 34 48 PM](https://user-images.githubusercontent.com/52669800/180337238-16deeccf-fa95-4c95-b6ab-2d1c1f282582.png)
:

**Comment by ed-marquez** [comment]
That's correct, but having both methods present and only setting 1 "works" in some cases. 
I updated the code in index2.js in the code sandbox to include the scenarios to test (commented out).

To not set one of the methods, the arguments I pass to ContractCreate and ContractUpdate are **null** for the accountId and **[]** for the nodeId. For that code, with **both methods present** but only setting one, here's what I'm finding:
1)
- **Creating** contractX with `.setStakedAccountId(operatorId)` and `.setStakedNodeId([])` fails to stake to the operator's account 
- **updating** contractX with `.setStakedAccountId(aliceId)` and `.setStakedNodeId([])` fails to stake to alice's account 
- so after both operations the output for the contract staking info is: stakedAccountId: null  and stakedNodeId: 0
![Untitled](https://user-images.githubusercontent.com/72571340/180343625-07fa05fe-cd23-4386-9bb8-e00ba21bf595.png)


2)
-  **Creating** contractX with `.setStakedAccountId(null)` and `.setStakedNodeId(2)` **stakes** to node2, 
- **updating** contractX with `.setStakedAccountId(null)` and `.setStakedNodeId(4)` **stakes** to node4 
- so after both operations the output for the contract staking info is: (stakedAccountId: null  and stakedNodeId: 2==>4)
![Untitled](https://user-images.githubusercontent.com/72571340/180343381-73de0429-f3c8-41d2-a230-2d30f1c647a5.png)


@SimiHunjan @tinker-michaelj 
I guess what I'm trying to report is that if it's working for one scenario, it should work for all others. 
Or, if the expectation is that it should fail for all scenarios where both methods are present, then the one that is working shouldn't go through. 
Happy to chat through slack or zoom if that's easier. Thanks for looking into this.

**Comment by bugbytesinc** [comment]
I can confirm thru the .NET that creates and updates work as documented in the protobuf.  The .net sdk throws an error if you try to set both scenarios at the same time.  Perhaps the other SDKS would consider doing the same.
