### ISSUE TITLE
Update HIP-514 with additional functions

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#3721]
As per discussion: https://github.com/hashgraph/hedera-improvement-proposal/discussions/516#discussioncomment-3183896
we want to add two new functions as part of HIP-514:
- `isToken(address _token) returns (uint64 statusCode, bool isToken)`
- `getTokenType(address _token) returns (uint64 statusCode, int32 tokenType)`

**Comment by Nana-EC** [comment]
Done. See [HIP 514](https://hips.hedera.com/hip/hip-514-missing-hts-precompile-functions)
