### ISSUE TITLE
HIP 514: Add token management functions for token check

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#3722]
### Problem

The precompile flow is missing support for validating whether an address is a valid token address and the token is not deleted.

### Solution

Add support for the token verifications:

- `isToken(address _token) returns (uint64 statusCode, bool isToken)`
- `getTokenType(address _token) returns (uint64 statusCode, int32 tokenType)`

**Comment by se7enarianelabs** [comment]
That's exactly what I need
