### ISSUE TITLE
Create sidecar records for failing transactions

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#3723]
### Problem

There are some scenarios, e.g. when a ContractCreateTransaction fails, in which we don't create `ContractAction`, `ContractStateChange`, and `ContractBytecode` sidecar records. 
Users of the smart contract service may expect the sidecar records to exist in order to more easily debug the failures.
`ContractBytecode` sidecars can be created only for:
- all non-reverted creates
- a failing top-level create transaction, in which case we only need to populate the init bytecode and not the runtime bytecode

### Solution

Create the sidecar records for failing transactions

**Comment by steven-sheehy** [comment]
The mirror node needs a contract ID to exist to associate with the state changes, actions and bytecode in the db and to query via the API. What would be the contract ID if a create fails and is not assigned a contract ID?
