### ISSUE TITLE
HTS Precompile crypto transfer not using approval transfers

### ISSUE THREAD

**Issue by se7enarianelabs** [hashgraph/hedera-services#3758]
### Description

I gave a smart contract the approval to manage all my HTS tokens(setApprovalForAll),
then I created a smart contract that makes a precompiled `cryptoTransfer` with a swap(HTS NFT for HBar) to support custom royalty fees inside a smart contract.
When I call the smart contract I get `INVALID_SIGNATURE` so it seems to me, that the  `cryptoTransfer` does not use the approval transfers.

My smart contract function:
```
    function transferNewWay(address payable from, address token, int64 serial) public payable returns(int responseCode) { 
        IHederaTokenService.TokenTransferList[] memory transfers = new IHederaTokenService.TokenTransferList[](2);
        transfers[0].token = token;
        transfers[0].nftTransfers = new IHederaTokenService.NftTransfer[](1);

        IHederaTokenService.NftTransfer memory nftTransfer;
        nftTransfer.senderAccountID = from;
        nftTransfer.receiverAccountID = msg.sender;
        nftTransfer.serialNumber = serial;
        transfers[0].nftTransfers[0] = nftTransfer;

        transfers[1].transfers = new IHederaTokenService.AccountAmount[](2);
        IHederaTokenService.AccountAmount memory sendAccountAmount;
        sendAccountAmount.accountID = msg.sender;
        sendAccountAmount.amount = int64(int256(msg.value) * -1);
        transfers[1].transfers[0] = sendAccountAmount;

        IHederaTokenService.AccountAmount memory recieveAccountAmount;
        recieveAccountAmount.accountID = from;
        recieveAccountAmount.amount = int64(int256(msg.value));
        transfers[1].transfers[1] = recieveAccountAmount;
        return cryptoTransfer(transfers);
    }
   ```
   EDIT:
   I've tried also swapping two NFTs from the same collection:
   ```
       function transferHTSForHTS(address payable from, address token, int64 serial, int64 serial2) public returns(int responseCode) { 
        IHederaTokenService.TokenTransferList[] memory transfers = new IHederaTokenService.TokenTransferList[](2);
        transfers[0].token = token;
        transfers[0].nftTransfers = new IHederaTokenService.NftTransfer[](2);

        IHederaTokenService.NftTransfer memory nftTransfer1;
        nftTransfer1.senderAccountID = from;
        nftTransfer1.receiverAccountID = msg.sender;
        nftTransfer1.serialNumber = serial;
        transfers[0].nftTransfers[0] = nftTransfer1;

        IHederaTokenService.NftTransfer memory nftTransfer2;
        nftTransfer2.senderAccountID = msg.sender;
        nftTransfer2.receiverAccountID = from;
        nftTransfer2.serialNumber = serial2;
        transfers[0].nftTransfers[1] = nftTransfer2;

        return cryptoTransfer(transfers);
    }
   ```
   I've got the response code 200: `int32 internal constant EMPTY_TOKEN_TRANSFER_ACCOUNT_AMOUNTS = 200; // TokenTransfersTransactionBody has a TokenTransferList with no AccountAmounts`
   
   I also tried to swap FT for HTS:
   ```
       function transferNewWayHTSForHTS(address payable from, address token, int64 serial, address fungible, int64 amount) public returns(int responseCode) { 
        IHederaTokenService.TokenTransferList[] memory transfers = new IHederaTokenService.TokenTransferList[](2);
        transfers[0].token = token;
        transfers[0].nftTransfers = new IHederaTokenService.NftTransfer[](1);

        IHederaTokenService.NftTransfer memory nftTransfer;
        nftTransfer.senderAccountID = from;
        nftTransfer.receiverAccountID = msg.sender;
        nftTransfer.serialNumber = serial;
        transfers[0].nftTransfers[0] = nftTransfer;

        transfers[1].transfers = new IHederaTokenService.AccountAmount[](2);
        transfers[1].token = fungible;
        IHederaTokenService.AccountAmount memory sendAccountAmount;
        sendAccountAmount.accountID = msg.sender;
        sendAccountAmount.amount = amount * -1;
        transfers[1].transfers[0] = sendAccountAmount;

        IHederaTokenService.AccountAmount memory recieveAccountAmount;
        recieveAccountAmount.accountID = from;
        recieveAccountAmount.amount = amount;
        transfers[1].transfers[1] = recieveAccountAmount;
        return cryptoTransfer(transfers);
    }
```
    I've got again INVALID_SIGNATURE
    https://hashscan.io/#/testnet/transaction/0.0.48095722-1661793036-859810898?t=1661793047.965884501

### Steps to reproduce
HTS for HBAR
1. Deploy a smart contract with the `transferNewWay` function
2. Mint an NFT to account A.
3. Set `approveTokenNftAllowanceAllSerials` as account A and give the approval to the smart contract
4. Call the function as account B

HTS NFT for HTS NFT 
1. Deploy a smart contract with the `transferHTSForHTS` function
2. Mint an NFT to account A.
3. Set `approveTokenNftAllowanceAllSerials` as account A and give the approval to the smart contract
4. Set `approveTokenNftAllowanceAllSerials` as account B and give the approval to the smart contract
5. Call the function as account B

HTS NFT for HTS FT 
1. Deploy a smart contract with the `transferNewWayHTSForHTS` function
2. Mint an NFT to account A.
3. Mint fungible tokens to Account B
3. Set `approveTokenNftAllowanceAllSerials` as account A and give the approval to the smart contract
4. Set `approveTokenAllowance` as account B and give the approval to the smart contract
5. Call the function as account B

### Hedera network

testnet

### Version

0.1.0

**Comment by gregscullard** [comment]
Hi, it looks as though the precompile `accountAmount` doesn't support `is_approval` which is a boolean (default to false) which needs to be set to true when setting up a transfer which comes from approved tokens.
The low level API (protobuf) has this additional boolean.

**Comment by se7enarianelabs** [comment]
> Hi, it looks as though the precompile `accountAmount` doesn't support `is_approval` which is a boolean (default to false) which needs to be set to true when setting up a transfer which comes from approved tokens. The low level API (protobuf) has this additional boolean.

Hey, thanks for the answer, will you add the support of `is_approval` to the precompile?

**Comment by Nana-EC** [comment]
We're investigating.

**Comment by stoqnkpL** [comment]
There are a couple of problems with the setup:

1. The HTS precompiled contract function `cryptoTransfer(TokenTransferList[] memory tokenTransfers)` does not support transfers using allowances, it was never designed to. Currently, the only way to make a transfer using allowances through the precompile is to use the redirect functions `transferFrom`:
`IERC20(token).transferFrom(sender, recipient, amount);`
`IERC721(token).transferFrom(from, to, tokenId);`

I'm not sure why the transferFrom functions were not exposed to HTS precompile top-level like the other functions from ERC20 and ERC721 were with [PR3638](https://github.com/hashgraph/hedera-services/pull/3638). In any case, the cryptoTransfer function will not work with allowances.

2. Transfers of HBars via `cryptoTransfer` is also not supported, only transfers of Fungible tokens and NFTs.

**Comment by Ashe-Oro** [comment]
1. Without cryptoTransfer supporting allowances, we will not be able to respect/enforce native HTS royalties and only fallback fees would be enforced. 

2. Without cryptoTransfer supporting HBAR, we won't be able to respect/enforce native HTS royalties since hbar will be one of the primary FTs used for settlement.

**Comment by Nana-EC** [comment]
Notably atomic transactions can be obtained through single contract functions in the mean time.
We'll be adding allowance support through `transferFrom()` to unblock.
We'll be looking into contract HBAR transfers

**Comment by Ashe-Oro** [comment]
we're only blocked for native HTS royalty fees. All trades can already settle, but without CryptoTransfer supporting both 1) spending approval and 2) hbar allowances, then we are unable to have the protocol enforce royalty fees.

**Comment by Burstall** [comment]
Glad I found this thread as I thought I was going mad. Given the proliferation of royalties in the Hedera NFT space, this situation brings a couple of projects I am working on to a halt until there is a path forward.

cryptoTransfer() to use allowances and heterogeneous tokens in a single transaction [allowing the SC to do NFT for fungible token swaps would get me going faster - although adding support for hbar in cryptoTransfer() would be great too].

**Comment by Nana-EC** [comment]
@Ashe-Oro [precompile atomic transfers](https://github.com/hashgraph/hedera-services/blob/master/docs/design/crypto-transfer.md) dictates the approach we would take.
No promise on timeline but if there's any design input from the team they can review that doc

**Comment by Ashe-Oro** [comment]
> @Ashe-Oro [precompile atomic transfers](https://github.com/hashgraph/hedera-services/blob/master/docs/design/crypto-transfer.md) dictates the approach we would take. No promise on timeline but if there's any design input from the team they can review that doc

hey @Nana-EC seems that link is 404'd? Are you referring to [Batch Transactions](https://github.com/hashgraph/hedera-improvement-proposal/pull/551/files#diff-b146b9f2d53bdce951980539225a0bcf35b6111012cec9b5de2534bea361dc8f)?

**Comment by Ashe-Oro** [comment]
ahhhh @Nana-EC you are referring to this https://github.com/hashgraph/hedera-services/issues/4084  

...ok we will review it and provide feedback.

**Comment by Nana-EC** [comment]
> Member
@Ashe-Oro File got moved it's here https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/docs/design/services/token-service/crypto-transfer.md

**Comment by SSE7EN** [comment]
@Nana-EC will the cryptoTransfer(NFT <-> HBAR) trigger the HTS royalty/fixed fees?

**Comment by Nana-EC** [comment]
> @Nana-EC will the cryptoTransfer(NFT <-> HBAR) trigger the HTS royalty/fixed fees?

Hi @SSE7EN.
Please note this `cryptoTransfer` is not yet released and does not have a release milestone planned.
To answer your question if the token being transferred has royalty/fixed fees configurations then yes it should trigger those just like it would a normal HAPI transaction for such a token

**Comment by SSE7EN** [comment]
@Nana-EC thank you

**Comment by Nana-EC** [comment]
Should have been resoled with HIP 206 atomic transfers but let's confirm

**Comment by lukelee-sl** [comment]
This HAPI test shows that a transfer involving hbar, ft, and nfts
https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AtomicCryptoTransferHTSSuite.java#L641

other tests show that allowances to the contract are respected for `CryptoTransfer`.
