### ISSUE TITLE
Add support for EIP-3670: EOF - Code Validation

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#3806]
### Problem

Our current EVM model does not utilize the upcoming Shanghai details of [EIP-3670: EOF - Code Validation](https://eips.ethereum.org/EIPS/eip-3670)

### Solution

Add support for EIP-3670: EOF - Code Validation

- [ ] Fill out details of solution
- [ ] Add a design doc if it's not a simple fix
- [ ] Link an implementing PR

**Comment by Nana-EC** [comment]
Team to verify inclusion

**Comment by lukelee-sl** [comment]
Addressed in this pr in the Besu repo https://github.com/hyperledger/besu/pull/4644
