### ISSUE TITLE
Add support for EIP-3860: Limit and meter initcode

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#3808]
### Problem

Our current EVM model does not utilize the upcoming Shanghai details of [EIP-3860: Limit and meter initcode](https://eips.ethereum.org/EIPS/eip-3860)

### Solution

Add support for EIP-3860: Limit and meter initcode

- [ ] Besu contribution
- [ ] Fill out details of solution
- [ ] Add a design doc if it's not a simple fix
- [ ] Link an implementing PR

**Comment by shemnon** [comment]
This code will be partly within hedera and partly int he EVM code.

For the EVM code we already have our own Hedera Create Operations to handle creates, we can check max sizes there.

For root level transactions we can check in the `ContractCreateTansactionLogic` and check the code size.

It is recommended that we implement these via dynamic property.  Hence we can ship this in advance of Ethereum Mainnet deployments by setting the init code limit to an absurdly high value, like 8 quintillion.

**Comment by Kalina-Todorova** [comment]
Done.
