### ISSUE TITLE
Аdditional record file validations enhancements

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#3823]
### Problem

We want to have additional validations for record files in place. They are listed below. 

### Solution

- Verify signature file hash signed by node's public key
- Verify signature metadata hash signed by node's public key
- Verify running hash chain unbroken
- Verify record file hash matches signature hash
- Verify record file metadata hash matches signature metadata hash
- Verify sidecar hash matches corresponding sidecar hash in record file
- Verify balances (hbar, token, nft) before plus transfers in record file matches balances after
- Verify expected transactions and records within record file
- Verify entity IDs created in the record file are unique

**Comment by netopyr** [comment]
Will become obsolete with block streams
