### ISSUE TITLE
Allow EET clients to be run in IntelliJ with default configuration

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#383]
**Summary**
At present, if in an IntelliJ project imported from the root _pom.xml_, developers must update their IntelliJ configuration to have _test-clients/_ as the working directory before running an EET spec. It would be nice if the default configuration (with the project root as working directory) "just worked".

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
