### ISSUE TITLE
Copy out and retrieve hgcaa.log and swirlds.log for integration test reports

### ISSUE THREAD

**Issue by rjuang** [hashgraph/hedera-services#3834]
### Problem

One issue I ran into is seeing test failures in SequentialIntegrationTests (or any of the other e2e tests). The outputs provided are only limited to the client side and nothing from services side. One thing that would be incredibly helpful is if hgcaa.log and swirlds.log were copied out and made available as part of the error reporting. That would immediately make finding bugs easier without needing to figure out how to manually run the tests and hoping that a repro case occurred.

### Solution

Copy out hgcaa.log and swirlds.log as part of the error reporting when an error happens.

**Comment by netopyr** [comment]
Obsolete. The test framework was replaced during the modularization project
