### ISSUE TITLE
0 unit token mint/burn/transfers return success in smart contract precompiles

### ISSUE THREAD

**Issue by littletarzan** [hashgraph/hedera-services#3840]
### Problem

Integer rounding will naturally lead to DeFi contracts sometimes minting or transferring 0 units of a token. But the network rejects 0 units in these operations, forcing contract developers to include special cases that would not be necessary on most networks. See the following ERC20 mint token snippet:
```
function mint(uint amount) external {
        balanceOf[msg.sender] += amount;
        totalSupply += amount;
        emit Transfer(address(0), msg.sender, amount);
    }
``` 

### Solution

We propose to allow token transfers, mints, and burns to succeed as no-ops when given 0 units of a token. This will align with developer expectations of an ERC-20 contract.

**Comment by mohsin-hedera** [comment]
@littletarzan after discussing internally, it seems that the implementation to disallow 0 units was as per the HIP. For this new change, we will need to propose a new HIP and communicate the change to the community. It can't be undertaken as simply an enhancement request w/o a HIP.

**Comment by littletarzan** [comment]
> @littletarzan after discussing internally, it seems that the implementation to disallow 0 units was as per the HIP. For this new change, we will need to propose a new HIP and communicate the change to the community. It can't be undertaken as simply an enhancement request w/o a HIP.

@mohsin-hedera we submitted the following PR to the HIP repo: https://github.com/hashgraph/hedera-improvement-proposal/pull/564. Thank you.

**Comment by Kalina-Todorova** [comment]
Fixed by https://github.com/hashgraph/hedera-services/pull/3989
