### ISSUE TITLE
Avoid unnecessary disk I/O during record stream files creation

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#3849]
### Problem

In the current implementation, the RecordStreamFileWriter calls both
```
stream.getChannel().force(true);
stream.getFD().sync();
```
on new record and sidecar file creation. However, as @steven-sheehy pointed [here](https://github.com/hashgraph/hedera-services/pull/3789#discussion_r951474122), both of these calls seem to call `fsync` internally, which makes one of them unnecessary.

### Solution

Make only one of those calls.

**Comment by Kalina-Todorova** [comment]
Depends on: https://github.com/hashgraph/hedera-services/issues/3823

**Comment by netopyr** [comment]
Obsolete. Does not apply to modular code base.
