### ISSUE TITLE
Create docker image from gradle

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#3853]
### Problem

`./gradlew clean eet` fails to execute because the docker image has not been generated. It has to be created using a separate build script, `compose-build.sh`.

### Solution

Eliminate `compose-build.sh` and use Gradle to build the docker image. Update the github workflows accordingly. Make sure docker image build is done before `eet`.

**Comment by netopyr** [comment]
Obsolete. Does not apply to modular code base.
