### ISSUE TITLE
Convert the repository to a GitFlow branching model

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/hedera-services#3878]
### Problem

In order to prepare for the inclusion of the Platform SDK in the repository and the standardization of the Action workflows, we need to convert this to use a GitFlow branching model. 

### Solution

- [ ] Issue an announcement for Hedera Services & Limechain

  - Goal: Changing Hedera Services to use GitFlow branching
  - Goal: Creation of the `develop` branch
  - Goal: Creation of the `main` branch
  - Goal: Summarize the process to switch to the new `develop` branch
  - Goal: Summarize the expectations and cover the fact that `develop` may be rebased once the new `main` is rebuilt
  - Goal: Summarize the process and expectations around the new `main` branch 
  - Goal: Summarize the impacts (partial history rewriting, etc)
  
- [ ] Meeting with Michael, Patrick, Neeha, Albert, & Matt
- [ ] Build a new `develop` branch beginning with commit `233ec8069cc02f003fa8badabaef24899e9e9af5` by incrementally applying the release branch and intermediate commits (where applicable).
  - `origin/release/0.30`
- [ ] Issue an announcement for all new features/work to branch off of the new `develop` branch and closing of outdated PRs
- [ ] Close outdated and abandoned PRs
- [ ] Change remaining PRs to use the new `develop` branch as their base
- [ ] Rebase outstanding PR branches to be off of the new `develop` branch
- [ ] Build a new `main` branch beginning with commit `127dc17766b2159a91d15af55f85efb9acb4d691` by incrementally applying the release branches and intermediate commits.
  - `origin/release/0.6`
  - `origin/release/0.7`
  - `origin/release/0.8`
  - .....
  - `origin/release/0.29`
- [ ] Announcement (TBD)
- [ ] Rebase the `develop` off of the new `main` branch
- [ ] Rebase any outstanding release branches to be off of `develop`/`main` as appropriate
  

### Alternatives

None

**Comment by tinker-michaelj** [comment]
Done.
