### ISSUE TITLE
Atomic precompile transfers of both NFT and FTs are failing

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#3884]
### Problem

Based on #3758 it seems precompile.cryptoTransfer() in which the `TokenTransferList` contains both an NFT and FT fails.
It seems [checkTokenTransfersList](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/ledger/PureTransferSemanticChecks.java#L136) has logic that may prevent this balancing

**More details**
user is doing the following precompile `cryptoTransfer()` - all with the approval/allowance filter on top of it

Scenario 1 - INVALID_SIGNATURE
```
transfers[0] - NFT debit
transfers[1][0] - HBAR debit
transfers[1][1] - HBAR credit
```

Scenario 2 - `EMPTY_TOKEN_TRANSFER_ACCOUNT_AMOUNTS`
```
transfers[0][0] - NFT debit
transfers[0][1] - NFT credit
```

Scenario 3 - `INVALID_SIGNATURE` https://hashscan.io/#/testnet/transaction/0.0.48095722-1661793036-859810898?t=1661793047.965884501
```
transfers[0] - NFT debit
transfers[1][0] - FT debit
transfers[1][1] - FT credit
```

### Solution

Update the balancing check to allow this atomic swapping where the individual types balance out to 0

**Comment by Nana-EC** [comment]
See @lukelee-sl findings in testing here https://github.com/hashgraph/hedera-json-rpc-relay/pull/485

**Comment by tinker-michaelj** [comment]
Hey Nana, if I understand, this is not a bug---it **is** impossible in the current system for a single token type to have both NFTs and fungible units.

**Comment by Nana-EC** [comment]
Correct.
The issue was muddled by the approval details but Luke was also able to confirm if the `TokenTransferList` array is correctly populated you should be able to atomically swap.
This issue was to track investigation on what is by design, a bug and any gaps

**Comment by Nana-EC** [comment]
So this issue seems to be mostly around formatting of array.
We added some E2E scenario on the relay showing that when well formatted you can swamp both FT and NFTs in one transaction
https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/server/tests/acceptance/htsPrecompile.spec.ts#L675
