### ISSUE TITLE
HIP-584: EVM Module HIP design

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#3887]
### Problem

We need an EVM based library to support execution of REST APIs, which are compliant with Ethereum RPC standard. The execution of APIs would trigger a simulation of a transaction inside this EVM library and the output result would be used to populate the return value for the REST API that is invoked. In order to avoid code duplication between the EVM library and hedera-node logic, the EVM library would be also used inside hedera-node for actual execution of transactions.

### Solution

Create a design for a HIP that describes and document the needed changes.

**Comment by Nana-EC** [comment]
@IvanKavaldzhiev in follow up to the HIP we should have a more detailed documentation added in repo.
Both
- design doc under `docs/design` 
  - the interfaces provided and their roles
  - how the interfaces connect
- README under the EVM module.
  - how the evm utilizes and exposes besu components
  - how the evm module operators in term of how transaction process logic  advances. Diagrams encouraged
  - how users of the module would utilize it

**Comment by Nana-EC** [comment]
@IvanKavaldzhiev I believe we can close this right?
Can you point to the checked in design doc.

if not we should create an MD file with the final design version for reference.

**Comment by IvanKavaldzhiev** [comment]
Hey @Nana-EC I believe we can close this issue, the reason being `hedera-evm` library itself would be deprecated. We haven't prepared a special md doc, since we aligned on using a new library from the modularized services code. This makes having a design doc for an eventually deprecated library obsolete. Instead, we should focus on preparing a design doc for the new library, so that `mirror node` developers know what to expect from it when it's started being consumed there.
