### ISSUE TITLE
Switch record stream files compression to consensus node side

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#3891]
With 0.30.0-alpha.1 image of the consensus node it is now possible to enable the compression of record stream files and sidecar record stream files on the consensus node side by configuring the following property: hedera.recordStream.compressFilesOnCreation=true.
Then we can disable the compression on the copier/uploader tool side - for record files and sidecar record files.
Account balance files should still be compressed by the copier/uploader tool.

This change will improve the performance of consensus nodes. There should be no impact on the mirror node.

**Comment by Nana-EC** [comment]
Depends on https://github.com/hashgraph/hedera-services/pull/3952 @tannerjfco  FYI
