### ISSUE TITLE
Nightly regression slack report's platform stats doesn't cover full test duration

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#392]
**Summary of the defect**
Notice in the 'hedera-regression' channel, hedera services master branch's nightly regression slack report doesn't cover full testing duration. 

**How to reproduce (if possible)**

https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1596641771303200

**Service logs (if applicable)**
```
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by JeffreyDallas** [comment]
Close obsolete issue
