### ISSUE TITLE
Update long term schedule transactions feature

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-services#3994]
### Problem

- [x] Revert PR: https://github.com/hashgraph/hedera-services/pull/3581
- [x] Maintain a long-lived branch with LTST unconditionally enabled
- [x] https://github.com/hashgraph/hedera-services/issues/4154
- [ ] Complete canonical performance testing
- Add `CryptoApproveAllowance`
- Add mixed type tests
- [ ] Pre-build 100M schedule transactions for longevity and reconnect tests
- [ ] Complete reconnect and longevity tests
- Add `CryptoApproveAllowance`
- Add mixed type tests
- [ ] Canonical performance test with NFTs on Virtual Merkle
- [ ] Longevity and reconnect tests with NFTs on Virtual Merkle

### Solution

See above

**Comment by Neeharika-Sompalli** [comment]
Enabling `LongTermScheduleTransactions` on `VirtualMap` was added in[ this PR](https://github.com/hashgraph/hedera-services/pull/4013), but due to modularization effort, that PR was closed as it became stale. 

Based on the priority of this feature, needs re-work to re-open the PR.
