### ISSUE TITLE
Improve traceability migration logic

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#4010]
### Problem

Though possible it was preferred to have more light weight operations with cleaner separations.
Traceability migration was turned off and reverted for 0.30 and [in current 0.31](https://github.com/hashgraph/hedera-services/pull/4008).
A more light weight operation with cleaner separations and checks was preferred.

### Solution

Improve the traceability migration logic by
- utilize an explicitly static property to enable migration `hedera.recordStream.enableTraceabilityMigration`
- carry out state migration across multiple handleTransactions to reduce the size of side cars for a given timestamp
- ensure migration occurs only once on upgrade and not a 2nd time on restart. Potentially utilize version comparisons to ensure only 0.30 -> 0.31 migration is applicable

**Comment by steven-sheehy** [comment]
I think spread across multiple record files would also be desirable. That would reduce the size of the sidecars the uploaders would have to upload and mirror node would have to download. Uploaders are taking upwards of 1.5 minutes to compress and upload the 5 sidecars for testnet state. This causes a backlog in the processing of other record files.
