### ISSUE TITLE
Generalize expiry work as a `SystemTask` facility

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4011]
### Problem

We have various types of work with the general profile that they,
 - Need the opportunity to run for, possibly, every entity in state; and,
 - Must happen deterministically, because they create records/change state; and,
 - Can have their performance impact measured in terms of `MerkleMap`/`VirtualMap` operations; and,
 - May either finish at some point, or run continuously.

### Solution

Generalize the facility used for expiration work to perform any implementation of a `SystemTask`.

**Comment by Neeharika-Sompalli** [comment]
Done in `master`.
