### ISSUE TITLE
JRS `StreamDetailValidator` can't consume `RecordStreamFileWriter` output

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4012]
### Description

After making the record stream V6 by default, the `StreamDetailValidator` has started failing with,
```
com.swirlds.common.io.exceptions.ClassNotFoundException: No class with id=0(0x00000000) found
    at com.swirlds.common.io.streams.SerializableDataInputStream.registryConstructor(SerializableDataInputStream.java:458)
    at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:165)
    at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:89)
```

Apparently it is not enough for `RecordStreamFileWriter` to [implement `LinkedObjectStream`](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/stream/RecordStreamFileWriter.java#L68); there must be some other contract that `com.swirlds.common.stream.internal.TimestampStreamFileWriter` has been fulfilling so that `StreamDetailValidator` will work.

### Steps to reproduce

Run JRS `StreamDetailValidator` with V6 record stream.

### Hedera network

other

### Version

v0.30.2

**Comment by JeffreyDallas** [comment]
Streamvalidator calls functions from swirlds-common library to parse stream files (both event and record). 
it does do not anything  else.

So I think record stream switched from TimestampStreamFileWriter to LinkedObjectStream,
missed something.

**Comment by JeffreyDallas** [comment]
in RecordStreamFileWriter.java, I did not see how record file would be generated differently if version is 5 or 6
Should not there be some logic like  if ( recordFileVersion == xx) { } else ?

**Comment by tinker-michaelj** [comment]
Fixed in develop.
