### ISSUE TITLE
Lay groundwork for all `State` and `Store` implementations

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4025]
### Problem

In parallel with https://github.com/hashgraph/hedera-services/issues/4024, we can begin to implement read-only `*Store`'s that use appropriate `State<K, V>` implementations to read and return the `JKey` for given key of their type. (Note the `AccountStore` will likely need to be able to resolve aliases.)

### Solution

Implement:
- [x] A read-only `StateBase<K, V>` type that supports "read-tracking" (i.e., the ability to return all keys that were read since its creation).
- [x] A read-only `InMemoryStateImpl` subclass of `StateBase`.
- [x] #4165
- [x] A read-only `RebuiltStateImpl` subclass of `StateBase` for the aliases `FCHashMap`.

**Comment by rbair23** [comment]
Can we break this down into sub issues for each of the "A read-only *Store" checkboxes? Rather than one really big long lived branch, could we merge smaller changes incrementally?
