### ISSUE TITLE
Implement `BaseTransactionMetadata` and `SignatureVerifier`

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4026]
### Problem

Though each `PreTransactionHandler` method will ultimately do quite specialized things, from the beginning all will share the need to use a `SignatureVerifier` to accumulate the set of `TransactionSignature`'s that must be valid for their operation to be handled.

We want to avoid duplication by providing a `BaseTransactionMetadata` that supports accumulating `TransactionSignature`'s into a list with de-duplication.

### Solution

- [ ] Define and implement a `SignatureVerifier` interface.
- [ ] Write an abstract `BaseTransactionMetadata` with support for `SignatureVerifier` usage patterns.

**Comment by nickpoorman** [comment]
No longer relevant. Need to create a new issue that's more along the lines of the design.
