### ISSUE TITLE
Implement FilesService's `prehandle()`-methods

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4028]
### Problem

We need preHandle()-methods:
- [ ] FileAppendHandler.preHandle()
- [ ] FileCreateHandler.preHandle()
- [ ] FileDeleteHandler.preHandle()
- [ ] FileUpdateHandler.preHandle()
- [ ] SystemDeleteHandler.preHandle()
- [ ] SystemUndeleteHandler.preHandle()

### Solution

Implement the above.

**Comment by nickpoorman** [comment]
Duplicate of https://github.com/hashgraph/hedera-services/issues/5517
