### ISSUE TITLE
Implement the `TokenService`'s `preHandle()`-methods

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4029]
### Problem

We need preHandle()-methods:

- [x] #4361
- [x] #4994
- [x] #4604
- [x] #4590
- [x] #4377
- [x] #4594
- [x] #4578
- [x] #4631
- [x] #4476
- [x] #4580
- [x] #4609
- [x] #4593
- [x] #4497 
- [x] #4651
- [x] #4605
- [x] #4499

### Solution

Implement the above.

**Comment by nickpoorman** [comment]
Completed.
