### ISSUE TITLE
Implement `ScheduleService`s `preHandle()`-methods

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4031]
### Problem

We need prehandle()-methods:
- [x] #4366
- [x] #4367
- [x] #4368
- [ ] Move the methods to the appropriate handlers

### Solution

Implement the above.

**Comment by nickpoorman** [comment]
Update: Waiting for review on ScheduleDelete.

**Comment by kimbor** [comment]
ScheduleDelete was reviewed and merged

**Comment by kimbor** [comment]
Closing as completed
