### ISSUE TITLE
HIP-584: Enhance `hedera-evm` to support `eth_estimateGas` without precompiles

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#4045]
### Problem

In order to support `eth_estimateGas` functionality in the Mirror Archive Node we should enhance the `hedera-evm` library with more capabilities. That includes:

1. Having a default memory/disk (or both) default state implementation where to write temporary information for nested transactions
2. Perform speculative writes and writing to the special light-weight state
3. Extract modifying op codes into the library
4. Extract the necessary validation logic for basic check that a given transaction is valid
5. Implement `HederaEvmHTSPrecompiledContract` that is a light-weight sibling of `HTSPrecompiledContract`
6. Implement `PricesAndFeeProvider` interface with common default logic containing logic for processing and calculating of fee and gas usage
7. Implement `hedera-services` specific logic for Loader interfaces, which fetch `feeSchedules`/`exchangeRates` information from services state

### Solution

To meet these requirements several subtasks were defined:

- [x] #3949 
- [x] #3565
- [x] #4805
- [x] #4806
- [x] #5024 
- [x] #5068 
- [x] #4645 
- [x] #4591

**Comment by Kalina-Todorova** [comment]
Done.
