### ISSUE TITLE
Create new test methods to cover payer records to state

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#407]
**Summary**
In `0.7.0` each `MerkleAccount` has a new `FCQueue` with the records of all transactions it paid for in the last 3min of consensus time, **including duplicates**. (In particular, these records are used to classify duplicates.)

Existing tests will not cover the system's management of duplicate (or unclassifiable) records.

**Comment by anighanta** [comment]
@tinker-michaelj  you have handled it [here](https://github.com/hashgraph/hedera-services/blob/37eb829cb2b7e821eec51a8b1524bf1460f6151a/test-clients/src/main/java/com/hedera/services/bdd/suites/records/DuplicateManagementTest.java#L70) right ? can we close this ?

**Comment by tinker-michaelj** [comment]
Agreed @anighanta we can use the `UncheckedSubmit` method to create records of any possible resolved status; and then use the `GetTxnRecord` query with `includeDuplicates=true` to confirm they exist.
