### ISSUE TITLE
HIP-573: Blanket exemptions for custom fee collectors demo

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-services#4072]
### Problem

Create a simple demo that demonstrates the feature using the SDKs and any mirror node APIs that support this feature.

### Solution

See above

**Comment by nickpoorman** [comment]
https://github.com/hashgraph/hedera-improvement-proposal/discussions/571

**Comment by mhess-swl** [comment]
I created a private repo with the example code [here](https://github.com/mhess-swl/hip-573-code-example). Need to figure out a way to transfer it to the _@hashgraph/services-team_ team...
