### ISSUE TITLE
Provide DA demo for HIP-564 (zero-unit token operations)

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4079]
### Problem

We need examples to clarify the functional changes from HIP-564, which allows several token operations to behave as no-ops when given zero units.

### Solution

Use a standard SDK with a few introductory slides to give DA's working examples of the HIP-564 functional impact.

**Comment by Neeharika-Sompalli** [comment]
Duplicate of https://github.com/hashgraph/hedera-services/issues/4073
