### ISSUE TITLE
Implement atomic cryptoTransfers and approvals

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#4084]
### Problem

Create support for transferring hbars, fungible and non-fungible tokens in a single cryptoTransfer function call from Solidity.  Also, support the approval mechanism when making such calls.

Related Task: #3758 

Dependency Task
- [x] #4085 
- [x] #4086 
- [x] #4087 
- [x] #4088 
- [x] #4089 

### Solution

Break up the solution into multiple tasks to make them more palatable.  Sub tasks will be tied to this epic

**Comment by Nana-EC** [comment]
@lukelee-sl and @quiet-node to link PRs resolving and close.
Should  be done as part of 0.51

**Comment by lukelee-sl** [comment]
closing epic as all sub issues are finished.
