### ISSUE TITLE
Move `JKey` to `HederaKey`

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#4133]
Currently we have `JKey` which is a legacy key format. Move to use `HederaKey`  in the modularization change.
First move some of the JKey types to HederaKey and then move the rest.

- [ ] HederaEd25519Key
- [ ] HederaKeyList
- [ ] HederaThresholdKey

**Comment by mhess-swl** [comment]
We've discovered that it's possible to add two of the same payer keys to `SigTransactionMetadata`. Once JKey is removed--due to its lack of an `equals()` method--we'd like to also check for duplicates before adding keys in `SigTransactionMetadata`

**Comment by Neeharika-Sompalli** [comment]
Closing in favor of #6089
