### ISSUE TITLE
Expose alias in record for HIP 583

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#4176]
### Problem

HIP 583 logic should have exposed the alias value for CryptoCreate scenarios however, this was left out.

### Solution

Ensure [record.alias](https://github.com/hashgraph/hedera-protobufs/blob/main/services/transaction_record.proto#L124) is set with the ED or EC public key alias when an autocreate is initiated via submitting CryptoCreate setting alias

CryptoCreate where
- alias is set (ED)
- alias is set ( EC)

**Comment by dimitar-dinev** [comment]
Closing this issue, since it was agreed upon that there is no need to expose `alias` in the transaction record if already explicitly set in the transaction body---the mirror node can get the `alias` value from the body.
