### ISSUE TITLE
Implement the transaction handling workflow

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#4211]
Update: Most of the handle workflow has been implemented. There are just a couple of TODOs left:

- [x] #7317
- [x] #7319
- [x] #6746 
- [x] #6765 
- [x] #7257 
- [x] #6702 
- [x] #7294 
- [x] #6701

**Comment by nickpoorman** [comment]
Work is ongoing.

**Comment by nickpoorman** [comment]
Blocked by https://github.com/hashgraph/hedera-services/issues/5618 & https://github.com/hashgraph/hedera-services/pull/4856

**Comment by nickpoorman** [comment]
Design doc for handle requests: https://www.notion.so/swirldslabs/Handle-Design-89035f4f8df449b4b38839203507a373?pvs=4
