### ISSUE TITLE
Add more automatic modules

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#4233]
Some of the dependencies does not have an automatic module description
We need to add automatic module infos for all that dependencies.

Sample: https://github.com/hashgraph/hedera-services/pull/4231/commits/cd8057f4b261f490a7684004a3958cfa28946751

Part of epic https://github.com/hashgraph/hedera-services/issues/4239

**Comment by netopyr** [comment]
duplicate
