### ISSUE TITLE
Only use Spotbugs annotations (for now) in test-clients module

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#4345]
See https://github.com/hashgraph/hedera-services/issues/4334

**Comment by thomas-swirlds-labs** [comment]
May be closed by https://github.com/hashgraph/hedera-services/pull/14535 now

**Comment by netopyr** [comment]
I found at least two remaining instances:

- `ContractServiceComponent`
- `FakePlatformContext`

**Comment by netopyr** [comment]
Closed in favor of new, clean issue: https://github.com/hashgraph/hedera-services/issues/4345
