### ISSUE TITLE
`MerkleTopic#toString()` throws NPE under some circumstances

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#4350]
### Description

While writing some tests using `MerkleTopic`, I found that the constructor for `MerkleTopic` annotates many parameters as `Nullable`. If I pass null in for all of them, then `toString()` throws an NPE. This suggests either the `toString` method has a bug (and isn't tested properly) or some of the parameters shouldn't permit null. I'm not sure which it is.

### Steps to reproduce

```
final var topic1 = new MerkleTopic("Memo 1", null, null, 86400, null, null);
topic1.toString();
```

### Hedera network

other

### Version

v0.33

**Comment by netopyr** [comment]
Applies to Mono code only
