### ISSUE TITLE
Update design doc and test plan for HIP-583

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#4390]
### Problem

Since the initial design doc for HIP-583 was created there have been a few updates to the HIP most notably https://github.com/hashgraph/hedera-improvement-proposal/pull/673 
We want to include all finalized changes in the design doc itself and to update the test plan spec accordingly.

### Solution

Update https://github.com/hashgraph/hedera-services/blob/develop/docs/design/alias-configuration.md

**Comment by stoqnkpL** [comment]
- Solidity value transfer to non-existing evmAddress with .send() or .transfer() -> discussed this on the PL, we won't support them.
- Lazy-created account could end up being a contract!!! Discussed here: https://limechain.slack.com/archives/C0175P3D4QL/p1669896085552459?thread_ts=1669782609.120939&cid=C0175P3D4QL
