### ISSUE TITLE
Implement `TokenService`'s `handle()`-methods

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#4452]
### Problem

We need handle()-methods:

- [ ] TokenWipeAccountHandler.preHandle()
- [ ] TokenAssociateToAccountHandler.preHandle()
- [ ] TokenBurnHandler.preHandle()
- [ ] TokenCreateHandler.preHandle()
- [ ] TokenDeleteHandler.preHandle()
- [ ] TokenDissociateFromAccountHandler.preHandle()
- [ ] TokenFeeScheduleUpdateHandler.preHandle()
- [ ] TokenFreezeAccountHandler.preHandle()
- [ ] TokenGrantKycToAccountHandler.preHandle()
- [ ] TokenMintHandler.preHandle()
- [ ] TokenPauseHandler.preHandle()
- [ ] TokenRevokeKycFromAccountHandler.preHandle()
- [ ] TokenUnfreezeAccountHandler.preHandle()
- [ ] TokenUnpauseHandler.preHandle()
- [ ] TokenUpdateHandler.preHandle()

### Solution

Implement the above.

**Comment by Neeharika-Sompalli** [comment]
Duplicate issue of https://github.com/hashgraph/hedera-services/issues/5771
