### ISSUE TITLE
Implement `FileService`'s `handle()`-methods

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#4455]
### Problem

We need handle()-methods:
- [ ] FileAppendHandler.handle()
- [ ] FileCreateHandler.handle()
- [ ] FileDeleteHandler.handle()
- [ ] FileUpdateHandler.handle()
- [ ] SystemDeleteHandler.handle()
- [ ] SystemUndeleteHandler.handle()

### Solution

Implement the above.

**Comment by nickpoorman** [comment]
Duplicate of https://github.com/hashgraph/hedera-services/issues/5517
