### ISSUE TITLE
PR blocked based on Spotless issue

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#4487]
I have an issue with the build of PR https://github.com/hashgraph/hedera-services/pull/4422

Since the gradle build and therefore the GithubActions will not execute successful if the `spotlessCheck` task fails the `spotlessApply` task needs to be called after changes have been done. Sadly the `spotlessApply` task does not work for files that are not already commited to git. Therefore you need to do a git commit every time when you want to check if a full build is working. While this is already a general big problem in the workflow for the given branch it is not working. While I have commited everything the `spotlessApply` task fails with an git based error:

```
hendrikebbers@admins-MBP-2 hedera-services % git status
On branch 04328-D-moving-token-classes
Your branch is up to date with 'origin/04328-D-moving-token-classes'.
nothing to commit, working tree clean


hendrikebbers@admins-MBP-2 hedera-services % ./gradlew :hedera-node:hedera-token-service-impl:spotlessJava
...
> Task :hedera-node:hedera-token-service-impl:spotlessJava FAILED
Step 'com.diffplug.spotless.generic.LicenseHeaderStep' found problem in 'src/main/java/com/hedera/node/app/service/token/impl/util/AliasUtils.java':
Unable to parse date from command 'git log --follow --find-renames=40% --reverse -- /Users/hendrikebbers/git/hedera-services/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/AliasUtils.java':

java.lang.IllegalArgumentException: Unable to parse date from command 'git log --follow --find-renames=40% --reverse -- /Users/hendrikebbers/git/hedera-services/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/AliasUtils.java':
```

**Comment by nathanklick** [comment]
Setting the following `gradle.properties` file value should resolve the issue:
```
spotlessSetLicenseHeaderYearsFromGitHistory=false
```
