### ISSUE TITLE
Add more `RecordStreamValidator` implementations

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4529]
### Problem

The https://github.com/hashgraph/hedera-services/pull/4528 PR only includes one record stream validator for comparing the hbar balance adjustments with the results of `getAccountBalance` queries.

We would also like validators to assert that,
- [x] #4912
 - [x] #4655
 - [x] #4656
 - [x] #4657
 - [x] #4658
 - [x] #4659
 - [x] #4660
 - [x] #4661
 - [x] #4662
 - [x] #4663
 - [x] #4795 
 - [x] https://github.com/hashgraph/hedera-services/issues/4913
 - [x] #4929
 - [ ] https://github.com/hashgraph/hedera-services/issues/6345
 - [ ] https://github.com/hashgraph/hedera-services/issues/8175

### Solution

Add `RecordStreamValidator` implementations for the above.

Update CI defaults to use default entity lifetime of <30 seconds and enable auto-renew/expiration at start of run.

**Comment by Neeharika-Sompalli** [comment]
No more relevant, since all the validation will be on block streams
