### ISSUE TITLE
No websocket endpoint provied

### ISSUE THREAD

**Issue by wdcs-amitkumar** [hashgraph/hedera-services#4543]
### Description

I am not able to find stable WSS endpoint to Hedera hashgraph Testnet.
Please help me where I can find **premium** or **free one**.

### Steps to reproduce

NA

### Additional context

NA

### Hedera network

testnet

### Version

20.04

### Operating system

Linux

**Comment by tinker-michaelj** [comment]
Hi @wdcs-amit-kumar, what led you to expect a WSS endpoint?

**Comment by netopyr** [comment]
Closed due to inactivity
