### ISSUE TITLE
Update configured stream directory paths to match paths used in production

### ISSUE THREAD

**Issue by tannerjfco** [hashgraph/hedera-services#455]
After the 0.7.0 release, DevOps will move to directly use the configurations provided in the configuration/nextRelease directory rather than maintaining separate copies in our deployment scripts. To help facilitate this, and to match services testing to the same configuration, the output directory paths should be changed to the following:

settings.txt:
```
eventsLogDir, /opt/hgcapp/eventsStreams
```

application.properties
```
recordLogDir=/opt/hgcapp/recordStreams
accountBalanceExportDir=/opt/hgcapp/accountBalances/
```

**Comment by anighanta** [comment]
`settings.txt` requires no change https://github.com/hashgraph/hedera-services/blob/dae18b17f5ab18bd17ca7ee3c9e96f7965dbce9a/hedera-node/configuration/nextRelease/settings.txt#L6

**Comment by tannerjfco** [comment]
I believe these paths have been made consistent and we can close this out. If we find any similar inconsistencies down the road we'll open a new issue
