### ISSUE TITLE
HIP 631

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#4566]
### Problem

We need design and test documents for HIP 631 in order to specify the work that needs to be completed.

### Solution

Create a document that specifies the functional and non-functional requirements and technical design for HIP 631. Include required tests cases for acceptance.

**Comment by Nana-EC** [comment]
[Stretch goal] See impacts from HIP 583 update

**Comment by lukelee-sl** [comment]
No plans for this in the near future
