### ISSUE TITLE
Use Testcontainers to start containers for integration tests automatically

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#4587]
Today you need to start the docker based infrastructure for integration tests by hand. This has several drawbacks:

- You need to do (manual) work before starting an integration test
- You can not define if an integration tests needs a fresh / new container or can reuse the same container as other tests

By using testcontainers (https://www.testcontainers.org) we could automate the container creation for tests. Sadly testcontainers does not provide all functionality that we need today. I created the following issue at the testcontainers repo: https://github.com/testcontainers/testcontainers-java/issues/6401

**Comment by kiview** [comment]
I can also look into more specific questions regarding Testcontainers usage best-practices when you start with this effort 🙂

**Comment by netopyr** [comment]
Our integration tests do not rely on Docker anymore
