### ISSUE TITLE
yahcli prefix hash calculation is mysteriously slower

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4598]
### Description

When `--restart-from-failure` is added to a `sysfiles upload upgrade-zip`, yahcli:
  1. Uses a `getFileInfo(0.0.150)` query to check the hash of the file currently on the network.
  2. Computes the SHA-384 hashes of each `(n * 4)kb` prefix of the _softwareUpgrade.zip_ file on disk.

If any of the prefix hashes match the file on the network, yahcli will just "pick up where it left off", choosing the next 4kb chunk to upload **after** the matching prefix.

This step of prefix hash calculation has been observed to take 10+ minutes with a 50MB file, which seems like a major aberration from initial results. 🤔 

### Steps to reproduce

Try uploading a 50MB _softwareUpdate.zip_ file locally (can be any contents, doesn't matter except size).

### Hedera network

other

### Version

yahcli v0.3.5

### Operating system

None

**Comment by povolev15** [comment]
--restart-from-failure will only be useful when the upload fails early. Otherwise it is faster to restart from the beginning
