### ISSUE TITLE
Release Actions & Automation

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#461]
**Summary**
Release Actions & Automation
Complete the following release actions for v0.7.0-rc1 Release
Manually
- [x] Full set of release notes
https://github.com/hashgraph/hedera-services/releases/tag/v0.7.0-rc1
- [x] Push HAPI proto to repo and Maven Central
https://search.maven.org/artifact/com.hedera.hashgraph/hedera-protobuf-java-api/0.7.0-rc1/jar
- [x] Push Docker image of release to docker repo
https://console.cloud.google.com/gcr/images/hedera-registry/GLOBAL/services-node@sha256:80b9c73afbb6a6c2b9761e4b0b7243a5e4d049ceb3eb10bbcb3b8b4d3905ad53/details?tab=info

- [x] Generate & commit hapi-proto/HAPI.html

- [x] Automate release actions.

**Comment by tinker-michaelj** [comment]
Closed by #668
