### ISSUE TITLE
Create Hedera Account Service precompile class

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#4621]
### Problem

Epic: #4619 

There is no class which implements the Hedera Account Service precompile logic in Hedera services.

### Solution

Create and unit test HASPrecompileContract class to handle calls for handling precompile function calls for the Hedera Account Service.  The structure of this class will be similar to HTSPrecompileContract.  This contract will be deploy at address `0x16a`

**Comment by Nana-EC** [comment]
Complete in 0.51 as part of HIP 906 work
