### ISSUE TITLE
[HIP 632][HIP 631] Create class to handle address translation functionality for Hedera Account Service

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#4622]
### Problem

Epic: #4619 

There is no implementation of a class to handle address translation functionality for the Hedera Account Service.

### Solution

Create and unit test a new class - `AddressTranslatePrecompile` to handle the following calls to the Hedera Account Service.

| hash | signature | return                       | description |
| --- | --- |------------------------------| --- |
|e9482d42| getVirtualAddresses(address) | address[]                    | returns an array of virtual addresses for a given Hedera Account ID  |
|a4e310ba| getHederaAddress(address) | (responseCode, address) | returns the top level Hedera Account ID if applicable |
|d501235a| isVirtualAddress(address) | bool                         | true if valid virtual address, false if long-zero or non existing account |

Create additional wrapper classes and utility functionality as needed to be consistent with the implementation of precompile contract handlers in the rest of the system

**Comment by david-bakin-sl** [comment]
Method signatures here may change with HIP-632 update.

**Comment by david-bakin-sl** [comment]
Per _draft_ [HIP-632 revision](https://github.com/hashgraph/hedera-improvement-proposal/pull/1011) (but agreed upon) methods look like this:

| hash | signature | return | description |
| --- | --- | --- | --- |
| `0xdea3d081` | getEvmAddressAlias(address) | address | given a Hedera Account ID (account num alias) returns the EVM address alias, if present |
| `0xbbf12d2e` | getHederaAccountNumAlias(address) | address | given an alias returns the top level Hedera Account ID (as account num alias), if applicable |
| `0x308ef301` | isValidAlias(address) | bool | true if an account num alias or evm address alias), false if non existing account |

**Comment by david-bakin-sl** [comment]
and per discussion with Luke just now:  `getEvmAddressAlias` and `getHederaAccountNumAlias` will return `(responseCode,address)` (`isValidAddress` will still return `(bool)`) and I'll edit the draft HIP to match.
