### ISSUE TITLE
Create class to handle determining signature authorization functionality for Hedera Account Service

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#4623]
### Problem

Epic: #4619 

There exists no class to handle signature authorization functionality for Hedera Account Service.

### Solution

Add a new class `AddressAuthorizedPrecompile` to handle the following function calls to the Hedera Account Service:
| hash | signature | return                       | description |
| --- | --- |------------------------------| --- |
|b2526367| isAuthorized(address, messageHash, signatureBlob) | bool                         | true if account is authorized to carry out transaction execution on account. Accepts protobuf key signature blobs. May be used for ECDSA, ED25519 and complex key flows |
|d501235a| isAuthorizedRaw(address, messageHash, signatureBlob) | bool                         | true if account is authorized to carry out transaction execution on account. Accepts single key raw signature blobs (ECDSA and ED25519). This provides similar logic to ECRECOVER. |

**Comment by david-bakin-sl** [comment]
Resolved by services team.
