### ISSUE TITLE
Update Feature: Special fileID and file handling process for update feature

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#463]
**Summary**
A special file (ID 0.0.150) will be used for the update feature.
At startup if this  file entity does not exist it will be created. (should execute at genesis or restart)
This file ID will be treated as a special case, and  will always be written to local disk instead of blob.
The file itself will not be part of state. (will be added to state in a subsequent features / issue)
The file info should be part of state. Query should return properly formed FileGetInfoResponse.FileInfo
The freeze+update transaction may ONLY use  file id 0.0.150 to update node software.
New FileHash field added to the freeze+update transaction. 
When handling the freeze transaction the existence of the file and its hash match must be validated. (If a node has corrupted its file its payer record will be different from all the other nodes and it will encounter an ISS). A missing file or mismatch of the hash should also be logged as an Exception. If the file is corrupted on all the nodes the exception will be logged on all the nodes with an ISS occurring. 
Each node will keep the file location name and FileHash in memory (to be added to state in a subsequent issue).
When executing the freeze and restart transaction the file and its hash must again be verified. 
If the file or its hash do not match then the freeze must be initiated but the update must NOT be initiated on that node.

Mirror Node - this system file (0.0.150) will come into existence at the restart with this feature.
@jsindy DevOps - this file (path) should be added to our regular node backups.

**Comment by JeffreyDallas** [comment]
The file 0.0.150 is actually a binary zipped file.
The zip file might has a list of file names to be deleted.
The zip file might has some new jar files and libraries need to be copied and/or overwritten existing ones
The zip file contains the script that should be executed during update stage.

**Comment by jsindy** [comment]
@JeffreyDallas can you provide more information on which folder needs to be added to the backups?

**Comment by JeffreyDallas** [comment]
Normally HapApp2.0 is a symbolic link to a folder named as HapApp2.0_2020_09-20_xxxxx.
During the jar file update a new one 2020_09-20_yyyyy will be created.
The old one 2020_09-20_xxxxx can be backed up, or if DevOps already backed it up with normal maintenance,
then we don't need to backup.

**Comment by JeffreyDallas** [comment]
@noshmody Currently,  java logic inside freeze function unzip new jar files first (overwrite existing ones) than
run the script.

With the new requirements, the order order will be changed
1)Java process unzip jar files BUT not overwrite old ones
2) Run script
3) script creates new directory, copying everything from current working directory to new one
4) script copies new jar files to overwrite old jar files
5) script starts new java process
