### ISSUE TITLE
A well-known sequence of specs "match" a "snapshot" record stream.

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4657]
Suppose we run a sequence of HapiSpecs. Then the minimal "snapshot" of that run might just be the ordered list of HederaFunctionality's from the record stream:

CryptoCreate,CryptoTransfer,CryptoTransfer,TokenCreate,...

When we re-run the sequence, we'd want to assert the record stream has the same list.

Being able to take and match just this snapshot would probably not be very valuable itself but it would give a basis for doing more interesting things later.

**Comment by kimbor** [comment]
Closing as low benefit until staking tests are added.
