### ISSUE TITLE
All successful `*Create` transaction have a corresponding entity.

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4660]
Each `*Create` HAPI transaction, if successful, sets the `ID` of its created entity in the `TransactionRecord`'s [receipt message](https://github.com/hashgraph/hedera-protobufs/blob/main/services/transaction_receipt.proto#L47). 

Note that https://github.com/hashgraph/hedera-services/issues/4649 provides 3 steps for giving test clients access to state.

We can then look at all `TransactionReceipt`'s in the record stream with an `*ID` set; and validate the appropriate `MerkleMap` or `VirtualMap` in state contains an entity with that ID.

**Comment by nickpoorman** [comment]
Blocked due to test failures.

**Comment by nickpoorman** [comment]
Could not load the state resulting from the freeze transaction. Was also happening locally. Need to dig into it further.

**Comment by nickpoorman** [comment]
Blocked by: https://github.com/hashgraph/hedera-services/issues/6345
