### ISSUE TITLE
🔥 Consensus timestamps are strictly increasing (and always set).

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4663]
We need to validate:
- [ ] Every `TransactionRecord` in the stream should have a consensus timestamp set.
 - [ ] This timestamp must be strictly increasing.
 - [ ] For records that have the same "parent" `TransactionID`, the increase must be exactly 1 nanosecond. 

(Here "same parent" means that two `TransactionID`'s agree on:
 1. Payer `accountID`
 2. `TransactionValidStart`
 3. `scheduled` flag
 
but _differ_ in their `nonce`.)

**Comment by netopyr** [comment]
@tinker-michaelj What exactly is requested? This was implemented and there are unit tests. Is this issue about adding validations in our e2e-tests?

**Comment by mhess-swl** [comment]
@netopyr yes, this is for adding an e2e test for that functionality
