### ISSUE TITLE
EVM compatibility for `send`, `transfer` & `call` Solidity operations

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#4672]
Smart contracts can send Hbars to EOAs or other smart contracts. There are three solidity instructions that can be used for that, and not all are behaving in Hedera as they would in Ethereum:

1. `receivingAddress.transfer(100);`
    
    Ethereum: if the payment fails, it **reverts.**
    
    Hedera: If the payment fails, it **reverts** ✅.
    
2. `receivingAddress.send(100);`
    
    Ethereum: if the payment fails, it **returns false**.
    
    Hedera: If the payment fails, it **reverts** ❌.
    
3. `receivingAddress.call{value: 100}("")`
    Ethereum: if the payment fails, it **returns false**.
    
    Hedera: If the payment fails, it **reverts** ❌.
    

Note: it is recommended to use `call` and avoid `send` and `transfer` in Ethereum.
Note: any potential changes introduced to Hedera's EVM would need to be released under a new version. 

Action items:

- [x] create a contract and an EET showcasing the different flows
- [ ] research what should be changed in Hedera's EVM implementation in order to achieve EVM-compatibility

**Comment by mshakeg** [comment]
Hi @stoqnkpL , it's been about 2 months since this issue was created and more than 3 months since I created [hedera-json-rpc-relay#805](https://github.com/hashgraph/hedera-json-rpc-relay/issues/805) and there doesn't seem to be much progress, could you provide an estimate for when this will be worked on?

**Comment by stoqnkpL** [comment]
Hi @mshakeg, I'm not in a position to provide an estimate, I hope we will pick this item from our backlog soon.

**Comment by mshakeg** [comment]
@stoqnkpL ok, thanks for the reply.
