### ISSUE TITLE
Hollow account creation fee charging strategy

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#4673]
Currently, when creating a hollow account in the EVM, we charge the hollow account creation fee by subtracting it from the gas limit provided in the call. Users on the Ethereum blockchain are used to only pay the intrinsic gas cost (21K gas) for transfer transactions, even if transferring to a currently non-existing account.

The current Hedera behavior has a couple of drawbacks compared to Ethereum:

1. We’re not able to support hollow account creations via `send` and `transfer` solidity instructions, since they only forward 2300 GAS.
2. External wallets and client software assume the 21K GAS cost for simple transfers.

Solution: in order to address this issue, we would need to not charge the crypto creation fee if the account is created via `EthereumTransaction` or internal EVM operation `call`, `transfer`, or `send` - this would bring us closest to EVM compatibility.

**Comment by Kalina-Todorova** [comment]
Not needed.

**Comment by stoqnkpL** [comment]
> > Not needed.
> 
> Can there be a summary of _why_ it is not needed?

We changed the charging strategy after several discussions. Instead of not charging the account creation fee from the gas limit provided, we will continue to do so, returning a meaningful gas estimate from the relay side, so the user experience will not deteriorate.
