### ISSUE TITLE
Add metrics for sidecar creation (in order to find/eliminate bottlenecks for this feature)

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#4682]
Metrics to include (and possibly others that can be suggested):

- Duration of each sidecar file creation
- Counts of #entries/sidecar file
- Size of entries in each sidecar file

In order to figure out:
- Goal: Figure out how much time is spent on main thread building each sidecar file
- Goal: Identify those events which cause excessive time spent creating a sidecar file
  
Notes:
- Per each sidecar file _kind_
- Possibly logging should be substituted for some of/all of these proposed metrics

**Comment by Nana-EC** [comment]
@david-bakin-sl to update and close.

**Comment by david-bakin-sl** [comment]
Abandoning this work for now.  Performance issues that showed up at the time turned out to not be related to sidecars.  Can revisit later, if desirable, in modularized services.
