### ISSUE TITLE
MerkleHederaState - Use new merkle tree in hedera-app, adapt mono-repo

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#4691]
Before handling this issue, we must solve:
- [x] #4793

**Comment by rbair23** [comment]
NOTE: We may not do this. @tinker-michaelj has another proposal where we invert the direction -- use the new merkle tree in `hedera-app`, but adapt `mono-repo` to use it transparently.

**Comment by nickpoorman** [comment]
https://github.com/hashgraph/hedera-services/pull/4800

**Comment by nickpoorman** [comment]
Out of date. Using new merkle states for persistence.
