### ISSUE TITLE
Update to use PBJ generated classes

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#4712]
Update `hedera-app`, `hedera-app-spi`, and all modular service implementations and APIs to use PBJ entities (generated classes and records based on the HAPI protobuf schemas) instead of the Google generated entities. `mono-service` will continue to use the Google entities. Where a transaction handler in a modular service impl is delegating to the `mono-service`, it will translate from PBJ to Google Protobuf object (which could be done generically by serializing to bytes and deserializing -- slow and hacky but simple -- or manually by using builders).

1. Waiting until @jsync-swirlds fixes the merge conflicts.
2. Merge these changes into the branch on https://github.com/hashgraph/hedera-services/pull/4856

- [x] #5426
- [x] #5427
- [x] #5428
- [x] #5429
- [x] #5430
- [x] #5431
- [x] #5432
- [x] #5433
- [x] #5434
- [x] #5435
- [x] #5436
- [x] https://github.com/hashgraph/hedera-services/issues/5425
- [ ] #5614

## step by step guide

All work should be done based on the `04712-use-pbj` branch. To get this branch compiled the following steps are needed:

- checkout the `04712-use-pbj` branch of `hedera-services`.
- clone https://github.com/hashgraph/pbj and switch to `add-codec` branch.
- call `./gradlew` build and `./gradlew publishMavenPublicationToMavenLocal` from the `obj-core` folder.
- The `pbj-version` in the `settings.gradle.kts` file in `hedera-services` needs to be updated to `0.3.3.11`
- Now `hedera-services` can be build.

**Comment by jasperpotts** [comment]
As people start using the new PBJ API, let me know if there are things that are painful to use. As the API is 100% ours we can tweak it to make it nice. The aim is to make it nice to use 😀

**Comment by rbair23** [comment]
I will be working in `hedera-app`

**Comment by tinker-michaelj** [comment]
I will start with `hedera-consensus-service`.

**Comment by Neeharika-Sompalli** [comment]
I will be working on `hedera-token-service`

**Comment by mhess-swl** [comment]
See also issue #5615 for more pbj updates

**Comment by nickpoorman** [comment]
Depends on https://github.com/hashgraph/hedera-services/issues/5616
