### ISSUE TITLE
Crypto transfer to the deleted SmartContract should fail

### ISSUE THREAD

**Issue by mohsin-hedera** [hashgraph/hedera-services#4716]
### Problem

Once an expired smart-contract is pass it grace period and is deleted, the transfer to the account associated with this smart-contract should revert back. 
Deleted SmartContract: https://hashscan.io/testnet/contract/0.0.47884456?p=1&k=1673620100.026005004
Crypto Transfer to SC: https://hashscan.io/testnet/transaction/1674236833.479075604?tid=0.0.48310124-1674236821-065140157

The sent balance was credited to the account of a deleted-smart contract. 

### Solution

see above.

**Comment by netopyr** [comment]
Fixed
