### ISSUE TITLE
State Facility - Implement `stores` for each module

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#4725]
Implement Readable and Writable `stores` for each module that abstracts current mono-repo merkle data structures.
ReadableStores are implemented as part of pre-handle. WritableStores need to be implemented.

- [x] ReadableAccountStore
- [x] ReadableTokenStore
- [x] ReadableScheduleStore
- [x] #4052

- [x] WritableAccountStore
- [x] WritableTokenStore
- [x] WritableScheduleStore
- [x] #4923

**Comment by Neeharika-Sompalli** [comment]
Done
