### ISSUE TITLE
State Facility - Implement other methods needed in ReadableStores

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#4755]
Add other methods needed in 

- [x] ReadableAccountStore
- [x] ReadableTokenStore
- [x] ReadableScheduleStore

**Comment by netopyr** [comment]
@Neeharika-Sompalli Can we close this issue?

**Comment by Neeharika-Sompalli** [comment]
> @Neeharika-Sompalli Can we close this issue?

yes @netopyr
