### ISSUE TITLE
Implement handle() method in transaction handlers in Contracts module

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#4768]
- [ ] ContractCallHandler
- [ ] ContractCreateHandler
- [ ] ContractDeleteHandler
- [ ] ContractSystemDeleteHandler
- [ ] ContractSystemUndeleteHandler
- [ ] ContractUpdateHandler
- [ ] EtherumTransactionHandler

**Comment by nickpoorman** [comment]
Duplicate of https://github.com/hashgraph/hedera-services/issues/5520
