### ISSUE TITLE
Gradle must use the module path when executing the run task

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#4802]
When executing `ServicesMain` directly the module path will be used. Based on that https://github.com/hashgraph/hedera-services/pull/4799#pullrequestreview-1274648843 has been created since new info needs to be added to the `module-info` (the platform API access some classes from services by using reflections). Looks like the error only happens when executing `ServicesMain` directly in IntelliJ. By using the `gradle run` task the error does not happen. 

We need to check the `run` task. Maybe he is adding all jars to the class path instead of using the module path or he adds `opens-module `statements to the java execution. The `run` task must execute the app by adding all jars to the module path and do not open any of them.

**Comment by nickpoorman** [comment]
Added to the Grade Build Improvements list.
