### ISSUE TITLE
Integrate throttle accumulator in ingest workflow

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#4829]
The API of `ThrottleAccumulator.shouldThrottle()` needs to be double checked. If it is not sufficient, the ingest workflow has to be adjusted accordingly.

**Comment by Neeharika-Sompalli** [comment]
@netopyr Is this API completed. If so, can we close this issue ?

**Comment by netopyr** [comment]
Looks like it is complete.
