### ISSUE TITLE
stream files nanos is not padded which can cause chronological sorting by filename as string to fail

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-services#483]
**Summary of the defect**
Stream files are named with time roughly following ISO-8601 format, which, does not have ending zeros in the nanos field. For example, `2020-02-09T18_30_20.007996Z.rcd`. If stream files are cut in sub second interval, for example, the next record file may be named `2020-02-09T18_30_20.0079969Z.rcd`, when sorted as string, this file will be before the previous file, though the expected result is the opposite. 

Padding the nanos to full 9 digits will solve the problem.

**How to reproduce (if possible)**

**Service logs (if applicable)**
```
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by steven-sheehy** [comment]
Example was for rcd but not that it applies similarly to all stream types.

**Comment by tinker-michaelj** [comment]
Done.
