### ISSUE TITLE
Implementation of solvency precheck in query workflow

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#4832]
We need to decide, if solvency pre-check is a facility of its own, a part of another facility/service or if its functionality should be implemented as part of the workflows. Once, there is a decision, it needs to be integrated in the query workflow (`QueryChecker.validateAccountBalance()`)

**Comment by nickpoorman** [comment]
TODO still in the code. Need to throw an adapter in there.

**Comment by nickpoorman** [comment]
There is an adapter in there now, will need to remove in a future iteration.

**Comment by nickpoorman** [comment]
We will probably rework fee calculation. Closing for now.
