### ISSUE TITLE
Add Contract autoRenew end to end tests

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#4838]
We need to validate the following scenarios are tested before enabling Contract autoRenewal.

https://github.com/hashgraph/hedera-services/blob/develop/docs/autorenew-feature.md

- [x] #4840
- [x] #4841
- [x] #4842
- [x] #4843
- [x] #4844
- [x] #4845
- [x] #4846
- [x] #4847
- [x] #4848
- [x] #4849
- [ ] #4663

**Comment by nickpoorman** [comment]
https://github.com/hashgraph/hedera-services/issues/4663

**Comment by nickpoorman** [comment]
Need to architect archival.
