### ISSUE TITLE
Also verify if the treasury has "receiver signature required" is bypassed in the case of expiry when deleted at the end of the grace period

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#4845]

**Comment by lbaird** [comment]
Yes.  Though it isn’t when it expires, it’s when it’s deleted at the end of
the grace period.

**Comment by mhess-swl** [comment]
Further clarification: 

The "treasury" in this case is the account that minted the tokens. So if a contract is holding some tokens and we are going to delete it (after the grace period), then those tokens should be returned to the treasury account that minted them

**Comment by mhess-swl** [comment]
Committed to the `4838-D-contract-expiry-specs` branch
