### ISSUE TITLE
Make sure it shows that an account balance does not go negative and then we delete an account. It should all show up in the record stream the right way. -- With and without royalties the right stuff should show up in the record stream.

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#4846]
- [x] There shouldn't be royalties and fees when the balance goes back to the treasury.
- [x] We should also show the correct order of operations when tokens are transferred out or account is renewed in the record stream so that it can be displayed properly in mirror node and hashscan.

**Comment by Neeharika-Sompalli** [comment]
Added `ExpiryRecordsValidator` to validate the amounts in records
