### ISSUE TITLE
Verify that it won't start charging storage rent until there is a 100m key-value pairs

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#4848]
- [x] Verify that it won't start charging storage rent  until there is a 100m key-value pairs . For easier testing override this property `contract.storageSlotPriceTiers=0til20`

**Comment by Neeharika-Sompalli** [comment]
Validated with `storageRentChargedOnlyAfterInitialFreePeriodIsComplete` and existing test `storageExpiryWorksAtTheExpectedInterval`.
