### ISSUE TITLE
Verify auto-renew behavior

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#4849]
Per: https://github.com/hashgraph/hedera-services/issues/4843#issuecomment-1412547035

Autorenew should have this behavior:

- [x] If a contract reaches the expiration date, and doesn’t have enough to

renew for the minimum period (3 months), it “expires” but isn’t deleted. It
is in a grace period.

- [x] During the grace period, if the background thread reaches it, and it has

enough hbars to pay for the whole grace period plus 3 months, then
autorenew. Otherwise, do nothing.

- [x] After the grace period, the first time the background thread reaches it,

it will try to autorenew. If it has enough to pay for the grace period plus
a little more (less than 3 months), then go ahead and use the available
hbars to autorenew for as long as possible, bringing the HBAR balance to
zero. If it can renew for the grace period plus the full 3 months, then do
that. If it doesn’t have enough to pay for the entire grace period, then
charge for what it could pay (which will bring the balance to zero hbars),
and then delete the smart contract and its associated account.

**Comment by Neeharika-Sompalli** [comment]
Validated with `autoRenewInGracePeriodIfEnoughBalance` and `autoRenewWorksAsExpected`
