### ISSUE TITLE
Implement MerkleHederaState#getAddressBookCopy() to return the AddressBook

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#4861]
https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java#L223

https://github.com/hashgraph/hedera-services/issues/4200

**Comment by Neeharika-Sompalli** [comment]
This method no more exists in MerkleHederaState.
