### ISSUE TITLE
Unable to Update Hollow Account when Transaction Payer is not ECDSA key for corresponding public eth_address

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-services#4863]
### Description

When creating a hollow account (Ethereum Address) via a transfer the hollow account gets created as expected.

the relevant hip states:

> As an illustration, a wallet or exchange could create and fund a new Hedera account based on the public-address alone. Once the transaction goes through the owner of the public-address user may use a wallet of their choice to submit a signed transaction (e.g. CryptoTransfer, ContractCreate, ContractCall, EthereumTransaction or TokenAssociation) to claim ownership of the account and carry out the desired transaction. The ownership claim and account completion will be seamless and transparent to the user.

However, this appears to only work if the PAYER happens to be the address of the hollow account, this does not work when there is a third party transaction payer.

### Steps to reproduce

1. Create a Hollow Account

2. Execute a transfer or associate transaction (haven't tested others) that is signed by the ECDSA key, but the Payer is another account (that also signed the transaction) with the prefix lenghts set to produce full public key values

Expected behavior: Transaction would complete as normal, & cause the appropriate CryptoUpdate behind the sceenes.

Actual behavior: Transaction fails with invalid signature

### Hedera network

previewnet

### Version

Current PREVIEWNET

### Operating system

Windows

**Comment by Nana-EC** [comment]
Thanks @bugbytesinc nice find.
We'll look into this and circle back if we need more information.

**Comment by stoqnkpL** [comment]
@bugbytesinc @Nana-EC 
Due to performance and resource limitation (# of preceding child records) considerations, it was agreed only to finalize (Update with the admin key) a hollow account if it is the `payer` of a given transaction. 
This is described in the [design doc](https://github.com/hashgraph/hedera-services/pull/4818/files#diff-6163ac1ce9d08acc07c2c34ec58a9a3be74d1b15ed66362f07f5e7259f373b43R129) for HIP-583.

**Comment by bugbytesinc** [comment]
So, you're saying that a system can send an NFT to create a hollow account, and that hollow account will not have the funds to convert itself to a real account?

**Comment by stoqnkpL** [comment]
Hey @bugbytesinc, 

in the final design for the hollow accounts feature, a hollow account can be finalized by looking at all the _required_ signatures for the transaction, and if a signature that matches the EVM address of a hollow account is present, we use the public key that signed to finalise the hollow account. A transaction can have one payer and multiple _required_ signatures, for example all the accounts that are originators of transfers must sign the transaction. So now not only the payer account can be finalized.
The payment for the hollow account finalization is processed at the moment of the hollow account creation, so step 2 of the process - the finalization - should not require additional hbar payment. 

Please share if this is inline with your expectation and use cases.
I'm closing this bug now as it is resolved but feel free to reopen it if you experience further issues.
