### ISSUE TITLE
Remove dependency on DbManager and Pipelines

### ISSUE THREAD

**Issue by cesaragv** [hashgraph/hedera-services#487]
**Summary**
As a Hedera Services client, we won't have access to Swirlds' `DbManager` class as well as its corresponding pipelines. We need to remove unit tests and any code that depends on these classes.

**Possible resolution**

Delete the class `LegacyMerkleOptionalBlobTest`

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
