### ISSUE TITLE
Rearrange Services directories to make way for Platform directories

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#4889]
Everything in Services needs to be moved under `hedera-node`.

**Comment by nathanklick** [comment]
The following files are exceptions and should remain in the root of the repository:

- `.gitignore`
- `codecov.yml`
- `LICENSE`
- `README.md`

**Comment by nathanklick** [comment]
The following related issues already take care of part of this request:

- [ ] #4884 
- [ ] #4517

**Comment by netopyr** [comment]
@nathanklick Can we close this issue?

**Comment by Neeharika-Sompalli** [comment]
This is completed.
