### ISSUE TITLE
Have `getTopicInfo` query working as first goal

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#4891]
Success criterion is that we can:

1️⃣ Create a `MerkleHederaState` with a topic `0.0.T` via `mono-service` workflows,
   - Start locally with `hedera.states.enabled=true` but `hedera.workflows.enabled=false`, and create a topic `0.0.T` via `mono-service` gRPC endpoints.
  - Submit a freeze transaction.

2️⃣ Restart from this state and get the topic info via `hedera-app` query flow,
 - Restart with above state using both `hedera.states.enabled=true` and `hedera.workflows.enabled=true`.
 - Have an EET pass that does **nothing** except `getTopicInfo(0.0.T)` (in particular, does not download fee schedules but uses a fixed fee).

This will establish basic happy path for `QueryWorkflow` and correctness of the `States` schema for the `ReadableKVState<EntityNum, MerkleTopic>` used by `ConsensusGetTopicInfoHandler`.

Steps required:
- [x] Merge #4800 , https://github.com/hashgraph/hedera-services/pull/5019
- [x] Merge #4918 
- [x] #5028

**Comment by Neeharika-Sompalli** [comment]
Sub issues merged
