### ISSUE TITLE
Simplification of config sources

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#4905]
## Current situation
Today the configuration of the services is splitter in 3 layers:
- **Boostrap Properties**
- **Node Properties**
- **Dynamic Properties**

While the **Boostrap Properties** and **Node Properties** are immutable and loaded at start time of the service app the **Dynamic Properties** are mutable and can change at runtime. This happens by a RPC Call that contains updates for config properties.

The **Boostrap Properties** are extracted from 2 different files (`bootstrap.properties` and `data/config/bootstrap.properties`) that are defined in an internal hierarchy. 

The **Node Properties** are extracted from 2 different files (`data/config/node.properties` and `data/config/application.properties`) that are defined in an internal hierarchy. 

## Future

We should discuss if we can make the config workflow more easy. Here is my current idea:

- We define default values for (all) properties directly in code
- We define a `node.properties` file as the basic config file. Configuration properties from this file can overwrite the default values
- We define a `app.properties` file as the application specific config file. Configuration properties from this file can overwrite the default values and the values from the `node.properties` file. We should discuss if this file is really needed. Maybe 1 config file is already enough
- We add support for environment variables that can overwrite any mentioned property source.

Next to this we exclude the **Dynamic Properties** from the config API and provide an individual API to access all properties that are dynamic.

**Comment by mhess-swl** [comment]
It'd be nice if properties loading can be simplified, as long as we aren't missing any use cases that necessitate all the existing config levels
