### ISSUE TITLE
Instrument RAM and on disk usage of elements

### ISSUE THREAD

**Issue by povolev15** [hashgraph/hedera-services#4915]
Implement in memory and on disk counter in order to be able to see when added or remove element from the merkle tree.

**Comment by povolev15** [comment]
@rbair23 I want to add the metrics to merkle tree but I see that `MerkleHederaState` has just `createReadableKVState`
 and I cannot find `createWritableKVState` in order to provide the metrics counter to `OnDiskWritableState` and `InMemoryWritableKVState` constructors. please advice.

` @Override
        @NonNull
        protected WritableKVState<?, ?> createReadableKVState(
                @NonNull final StateMetadata md, @NonNull final VirtualMap v) {
            return new OnDiskWritableKVState<>(md, v);
        }

        @Override
        @NonNull
        protected WritableKVState<?, ?> createReadableKVState(
                @NonNull final StateMetadata md, @NonNull final MerkleMap m) {
            return new InMemoryWritableKVState<>(md, m);
        }`

**Comment by rbair23** [comment]
`WritableKVState` is a subclass of `ReadableKVState`, and internally the code is structured to take advantage of that. This method could be renamed `createKVState` instead of `createReadableKVState`, but otherwise the structure should work. See `MerkleWritableStates` in `MerkleHederaState`.

**Comment by netopyr** [comment]
@rbair23 , @nickpoorman : Is it sufficient to sample the data every three seconds or do we need the maximum (or average) during the sample intervals?

**Comment by povolev15** [comment]
As we discussed with @nickpoorman.
We have all these metrics already in `UsageLimits` and `EntityUtilGauges`.
I added the gauge values and not as percentage as it exist currently,
