### ISSUE TITLE
ContractCallQuery occasionally return TIMEOUT

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#4930]
### Description

ContractCallQuery HAPI submissions are occasionally returning TIMEOUT (17) errors.
It's intermittent and the same call fails and then subsequently passes 

### Steps to reproduce

1. Create a [ContractCallQuery](https://github.com/hashgraph/hedera-protobufs/blob/main/services/contract_call_local.proto#L178) transaction. Setting contractId, gas, functionParameters, senderAccountId and paymentTransactionId (optional)
2. Submit call to the network

Usually a SUCCESS response is returned but occasionally we're seeing TIMEOUT

### Hedera network

mainnet

### Version

v0.34.1

### Operating system

None

**Comment by tinker-michaelj** [comment]
Hi @Nana-EC, how reproducible is this, and in what environments? If we can reproduce in a non-prod environment, I think we should try changing these,
```
netty.prod.keepAliveTime=10
netty.prod.keepAliveTimeout=3
```
For `keepAliveTime`, we are using 10 seconds while gRPC's [default](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L115) is 5 **minutes**(!). For `keepAliveTimeout`, we are using 3 seconds while gRPC's [default](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/GrpcUtil.java#L237) is 20 seconds.

Imo it's very likely what you're seeing boils down to these configurations.

**Comment by Nana-EC** [comment]
Hey @tinker-michaelj, users of HashIO are seeing this occasionally.
Let me take a look, to your point the relay might need to optimize keepAliveTime using the SDK.
Will circle back and potentially close this and replace with a ticket on the relay side
Thanks

**Comment by Nana-EC** [comment]
@ebadiere your changes on the relay side regarding timeouts should address this.
Can close this once those have gone in

**Comment by ebadiere** [comment]
893 Added support to configure SDK requestTimeOut. #920 has been merged and should address this.

**Comment by Nana-EC** [comment]
relay has updated timeout settings to manage this case but there may still be some further config needed

**Comment by nickpoorman** [comment]
@tinker-michaelj did we ever change these netty settings? I think we're still seeing the timeouts.

**Comment by nickpoorman** [comment]
We have some very conservative overrides currently. Maybe we need @nathanklick to chime in?

**Comment by nickpoorman** [comment]
Once these changes go out in 0.39, we need to verify we are no longer seeing these timeouts.

**Comment by Nana-EC** [comment]
@m-swirldslabs missed the ping, if we can confirm it no longer repros then we can close it. I'd say just set up a test  using any of the SDKs, deploy a contract and make a series of calls to query the contract in testnet.
