### ISSUE TITLE
Identify minimal `mono-service` API needed needed to verify payer signature; provide adapter.

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4949]
- [ ] Identify `mono-service` API needed
- [ ] Implement passthrough adapter (with tests)

**Comment by mhess-swl** [comment]
I imagine this ticket would be good to meet about as a team (or subset)

**Comment by nickpoorman** [comment]
Not sure if the current API is sufficient. Need to discuss.
