### ISSUE TITLE
CircleCi custom-migration nightly regression test fails in regression-target-testnet step

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#495]
**Summary of the defect**
It can't get the test network to start up. 

**How to reproduce (if possible)**
https://app.circleci.com/pipelines/github/hashgraph/hedera-services/2921/workflows/e4869b3c-4c47-477a-96ab-5d2117e2afb5

**Service logs (if applicable)**
```
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
This regression uses the pre-provisioned test network for previous CircleCi master nightly regression, which is now turned off. Hence we could either disable this test or change the config for this regression to run on other testnet.

**Comment by ljianghedera** [comment]
Since we don't have the pre-provisioned net-new-regression ready for this test, I am changing this test to use test network created on the fly.

**Comment by anighanta** [comment]
Disabling this workflow for now and will be moving it to JRS based regression workflow.
