### ISSUE TITLE
Design enablement of traceability actions side car in mainnet

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#4951]
### Problem

Currently the traceability side cars are disabled on mainnet and exposed only in previewnet and testnet

### Solution

Enable traceability side cars and migration in mainnet 

- [x] Design discussions around storage and perf impacts
- [x] Design for cross contract and precompile involved  contracts
- ~[ ] Create work item tickets~

**Comment by david-bakin-sl** [comment]
Resolved: all issues resolved (perf issues vanished, mirror node is ready to ingest, action sidecar necessary because even if mirror node can (eventually) use evm inside itself to compute actions _other_ software wanting to track the hashgraph state will still need them).

**Comment by Nana-EC** [comment]
Closing as completed or N/A per David's note
