### ISSUE TITLE
Epic: Gradle refactoring to minimize the compile dependencies & add Java modules

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#4965]
Our goal is to have clean dependency hierarchy with
- no version conflicts
- only full java modules (no automatic modules)
- only needed dependencies (at compile time / at runtime / at test compile time / at test runtime)

Tasks:

- [x] #4966
- [x] #4967
- [x] #4968
- [x] #4969
- [x] #4970
- [x] #4971
- [x] #4972

**Comment by netopyr** [comment]
@hendrikebbers @nathanklick Have these issues become obsolete?
