### ISSUE TITLE
Add a PCLI sub-command to sign stream files

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#4995]
### Problem
NMT needs a way to sign the "gold" stream files during disaster recovery. These include record, account balance, and sidecar files. Without signatures, mirror node will not recognize them as the correct and valid files, leaving a gap.

### Solution
Create a PCLI sub-command (depend on [this ticket](https://github.com/swirlds/swirlds-platform/issues/6712)) that signs stream files. There is an existing class called `FileSignTool` in the platform that has some of this logic in it, but it needs to be cleaned up and updated to support the current formats.

**Comment by JeffreyDallas** [comment]
> @poulok There is also a [FileSIgnTool](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/FileSignTool.java) @JeffreyDallas added for services

The one on service report only supports new v6 version record stream files,
which are not based on LinkedObjectStream as event stream files.

**Comment by nickpoorman** [comment]
@poulok @JeffreyDallas - So what is the specific ask here? It sounds like we need a PCLI sub-command. However, based on this discussion, it's not clear to me what the gaps are. Are we saying that it needs to support all the various versions of record stream files?

**Comment by cody-littley** [comment]
# PCLI vs YAHCLI

In the long term I'd like to unify the functionality of these tools. In the short term, I think it is unimportant where this feature ends up, as long as we are capable of using it during disaster recovery. I'd suggest putting it into yahcli if that ends up being easier.

# Different file versions

We don't need this tool to support different file versions, just supporting the current version is sufficient. If we ever use our disaster recovery protocol, we will only be rebuilding very recent record stream files.

# FileSignTool

If this utility is capable of signing record stream files, side cars, etc, then it may already suit our needs. In that case, we wouldn't even need yahcli integration (if we don't already have it).

We need the ability for a human (or a simple script) to sign a small collection of files manually. Perhaps you can provide us with a short description of the capabilities of the file signing tool, and we can decide if that meets this need.

**Comment by JeffreyDallas** [comment]
@cody-littley Currently FileSignTool on Hedera repo was built for regression validation purpose,
only supported the latest v6 record stream file, and
- only read uncompressed record stream file
- no support of side cars

Users can use FileSignTool to sign a single record file or to sign a directory of record files in batch.

**Comment by Neeharika-Sompalli** [comment]
@JeffreyDallas Do you know the steps that are missing in FileSIgnTool for signing the compressed record files?

**Comment by nickpoorman** [comment]
@povolev15 is that clear?

**Comment by povolev15** [comment]
Yes @nickpoorman. opened a PR for it.
[#5100](https://github.com/hashgraph/hedera-services/pull/5100)
