### ISSUE TITLE
Review Validations and Error / Exceptions

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#5012]
### Problem

We are handling some things as errors and some things as exceptions. We need to go through the list https://www.notion.so/swirldslabs/Validations-748eef6054594a469059c0b03162665a

Cross-check with protobuf response codes
https://www.notion.so/swirldslabs/Validations-response-codes-vs-protobufs-response-codes-530c196654e44f9d9287feb01899dcba?pvs=4

### Solution

For example, `OnsetChecker#checkTransactionBody` both throws `PreCheckException` and returns a `ResponseCodeEnum`. Under some circumstances, it throws the exception; in others, it returns the error code. For example, it will throw `INVALID_TRANSACTION_ID` but return `DUPLICATE_TRANSACTION` or `INSUFFICIENT_TX_FEE`.

**Comment by nickpoorman** [comment]
The error handling needs to be redone to implement the changes in the notion doc.

**Comment by nickpoorman** [comment]
I believe we have done this but we need to double check as part of final testing.

**Comment by ElijahLynn** [comment]
I'm crosslinking https://github.com/hashgraph/hedera-services/issues/304 as it is relevant with `DUPLICATE_TRANSACTION`.
