### ISSUE TITLE
Payer account being charged more than stipulated maxFee

### ISSUE THREAD

**Issue by paulmadsenhed** [hashgraph/hedera-services#502]
**Summary of the defect**

For a CryptoTransfer tx, the client stipulated a maxFee of 220191 tinybars but paid 220200

https://app.dragonglass.me/hedera/transactions/00459471598876959327000000

**How to reproduce (if possible)**

Establish the fee for a CryptoTransfer tx and then incrementally lower the maxFee closer and closer on successive repeated attempts. The tx should fail when maxFee < calculated fee

**Service logs (if applicable)**
```
...
```
**Environment:**
mainnet

**Additional Context**
Some speculation that this might be related to threshold records and/or rounding error

**Comment by tinker-michaelj** [comment]
This happen because the transaction payer is [unconditionally charged](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/records/FeeChargingRecordsHistorian.java#L192) for caching the 3-minute `TransactionRecord` in memory.
