### ISSUE TITLE
Fix `StateLifecyclesTest#testLoadingMHState()`

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#5040]
### Problem

When loading `MerkleHederaState` from a saved state, deserialization of `JasperDbBuilder` throws a `ClassNotFoundException` (c.f. [this unit test](https://github.com/hashgraph/hedera-services/blob/mhs-adapter/hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/StateLifecyclesTest.java#L96)).

### Solution

Fix the exception.

**Comment by iwsimon** [comment]
As I demoed in our Services Modularization meeting, this exception will throw because of the default constructor was called.
