### ISSUE TITLE
HIP-584: Enhance `hedera-evm` to support `eth_estimateGas` with precompiles

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#5064]
### Problem

In order to support `eth_estimateGas` with precompiles functionality in the Mirror Archive Node we should enhance the hedera-evm library with more capabilities.

### Solution

To meet these requirements several subtasks were defined:

- [x] #4648  
- [x] #5066

**Comment by IvanKavaldzhiev** [comment]
Duplicated in mirror-node. Not needed any more.
