### ISSUE TITLE
What needs to be done by services to have ability to set Fully-Qualified Domain Name in the address book

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#5075]
Need to research.

Is there anything that needs to be done from HAPI or Services? What about updating the file for the address book? Do we need to be able to include the field?

**Comment by nathanklick** [comment]
@nickpoorman @mhess-swl Are you referring to the System Files `0.0.101` and `0.0.102` address books used by clients or the `config.txt` used by the Platform SDK?

**Comment by mhess-swl** [comment]
@nathanklick not sure, I'll find out
