### ISSUE TITLE
Skip writing empty MerkleDb files, if no data items are updated since the last flush

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/hedera-services#5084]
### Problem

When data is added to / updated in / removed from a virtual map, this change isn't immediately written to disk. Instead, it's kept in the virtual node cache for a while, and periodically flushed to disk. Sometimes there are no changes in a map since the last flush, yet in the current implementation a new data file on disk is still written. Such empty files will be garbage collected (aka compacted) later, but it would be great to avoid creating them to reduce load on the compaction thread.

### Solution

It can be done at one of the following levels:
* virtual node cache: check if there are no changes and don't call virtual data source to flush data
* virtual data source

It may require some changes in the contract between node cache and data source. Today the updates are sent as a stream, which isn't very easy to check for emptiness.

**Comment by poulok** [comment]
Will not be needed if https://github.com/hashgraph/hedera-services/issues/5319 is completed first.

**Comment by artemananiev** [comment]
Not an issue any longer, given that flushes are now size based.
