### ISSUE TITLE
Preconsensus event file consolidation

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#5099]
The preconsensus event stream files contain a minimum and a maximum generation in their file names. This min/max does not represent the actual events in the file, it defines the legal bounds of the file. It is possible that the legal bounds far exceed the actual data contained within the file.

From a correctness point of view, there is no problem with this. From a performance point of view, it is better for the min/max generation in a file to be as tight as possible.

After we close a file, we could atomically rename the file so that the bounds better reflect the actual data in the file. **The atomicity of this operation is important. If we can't do this atomically, we can't do it at all.**

There is an additional benefit to this strategy. If we ever start writing consensus metadata into this file (this seems likely), we could use this atomic rename to also include the first round number in the file name. This would allow us to efficiently figure out where to start reading stream files if we want to extract consensus data starting at a particular round.

**Comment by poulok** [comment]
done already
