### ISSUE TITLE
Identify which interfaces/classes in hedera-evm module are part of its SPI

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#5115]
### Problem

It is hard to identify which interfaces and classes in the hedera-evm module - which can be used outside this repo (for example, in the mirror node repo) - are the SPI (Service Provider Interface) - that is: which interfaces/classes are _extension points_ and can be _implemented_/_extended_ by users outside of this module.

### Solution

Use package naming to declare the SPI, by grouping all SPI interfaces/classes together.

### Alternatives

Add an annotation to mark such interfaces/classes until such refactoring/renaming is performed.

**Comment by nathanklick** [comment]
The Java and typical industry standard is the SPI is either grouped into a package which separates them, such as `*.spi.*` or they are broken into a separate Jar/Gradle/Maven module, such as `*-spi`.

**Comment by nathanklick** [comment]
A good example of the package approach is the Java NIO SPI: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/channels/spi/package-summary.html

**Comment by david-bakin-sl** [comment]
> The Java and typical industry standard is the SPI is either grouped into a package which separates them, such as `*.spi.*` or they are broken into a separate Jar/Gradle/Maven module, such as `*-spi`.

You are quite correct and that's what I had in mind for the long run.  But I had a short-term solution in mind - a marker annotation - and incorrectly wrote the issue with that.  Fixed (by editing the issue).

**Comment by lukelee-sl** [comment]
no longer applies
