### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#512]
Some items to automate the release process:
- [x] A hook to check license existence in any Java and proto file
- [x] A hook to check if HAPI.html is up-to-date with hapi-proto
- [x] A script/maven option to bump version (minor, major, alpha, rc...)
- [x] A script/maven option to release hapi-proto directly to maven central repo, not going through https://github.com/hashgraph/hedera-protobuf any more
- [x] Manually build and push Docker image to Docker repo - 
- [x] A script to generate release notes for a milestone (using https://github.com/spring-io/github-release-notes-generator)

**Comment by Neeharika-Sompalli** [comment]
Related to #461

**Comment by anighanta** [comment]
Verified that GCR has the latest docker image with tag v0.10.0. Closing the issue.
