### ISSUE TITLE
Update staking logic to include the weight of community nodes according to HIP-406

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#5125]
Under https://hips.hedera.com/hip/hip-406
> Initially, council nodes will have twice the maximum stake as community nodes. minStake will be set to half of maxStake. The sum of all maxStake will equal 50 billion. In the future, these settings may change, as defined by the council.

The current `buidStakingInfoMap` needs to be update to take into consideration the weight of community nodes.  https://github.com/hashgraph/hedera-services/blob/4c7937e541d1699b743908e93da40347f5b06a4d/hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java#L287

The current code assumes the weight of all nodes is equal, which will be incorrect once community nodes are added.

```
private void buildStakingInfoMap(
        final AddressBook addressBook,
        final BootstrapProperties bootstrapProperties,
        final WritableKVState<EntityNum, MerkleStakingInfo> stakingInfos) {
    final var numberOfNodes = addressBook.getSize();
    long maxStakePerNode = bootstrapProperties.getLongProperty(LEDGER_TOTAL_TINY_BAR_FLOAT) / numberOfNodes;
    long minStakePerNode = maxStakePerNode / 2;
    for (int i = 0; i < numberOfNodes; i++) {
        final var nodeNum = EntityNum.fromLong(addressBook.getAddress(i).getId());
        final var info = new MerkleStakingInfo(bootstrapProperties);
        info.setMinStake(minStakePerNode);
        info.setMaxStake(maxStakePerNode);
        stakingInfos.put(nodeNum, info);
    }
}
```

**Comment by Neeharika-Sompalli** [comment]
Needs https://github.com/hashgraph/hedera-improvement-proposal/blob/main/HIP/hip-690.md implemented

**Comment by Neeharika-Sompalli** [comment]
Done in https://github.com/hashgraph/hedera-services/pull/6231
