### ISSUE TITLE
Rename classes with "Swirlds" in their name

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#5151]
- `SwirldsPlatform` --> `PlatformImpl`
- `SwirldMain` --> `AppMain`
- `SwirldState` --> `LedgerState`
- TODO search for more classes needing to be renamed

It may be preferable to create many smaller PRs for this, as opposed to renaming everything all in one go.

We also should rename packages.

**Comment by lpetrovic05** [comment]
outdated
