### ISSUE TITLE
Protobuf Comments for token create freezeKey and wipeKey appear to be misleading.

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-services#525]
Is the purpose of wipeKey is to protect the action of removing all tokens from an an account and supplyKey is to protect the action of minting new tokens?

https://github.com/hashgraph/hedera-services/blob/9fffb6df6fc0d517b22a21c3b3d238c629f86a66/hapi-proto/src/main/proto/TokenCreate.proto#L40-L41

**Comment by bugbytesinc** [comment]
Also, divisibility is really decimal places, right?

**Comment by donaldthibeau** [comment]
Fixed in upcoming PR.
