### ISSUE TITLE
Create another SmartContract performance test config for JRS regression

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#526]
**Summary**
Right now, JRS has the SmartContract performance regression with simpleStorage.bin test case. Need to create another SmartContract performance regression to use BigArray.bin or LargeStorage.bin with large storage footage. 

**Possible resolution**
Need to create a new test case using one or more of these Smart Contract files.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
