### ISSUE TITLE
Token Create Parameters represent float as UInt64 while implementation uses Java long, a signed 64 int.

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-services#527]
Looking at the protobuf definition for create token:

https://github.com/hashgraph/hedera-services/blob/9fffb6df6fc0d517b22a21c3b3d238c629f86a66/hapi-proto/src/main/proto/TokenCreate.proto#L34

it has:

```java
message TokenCreation {
    uint64 float = 1; // The total number of tokens to put into circulation
```

while the implementation references float as a java long, a signed 64 integer.  Will this inconsistency not be a potential source of problems for SDK implementors?

**Comment by donaldthibeau** [comment]
Fixed in upcoming merge.
