### ISSUE TITLE
Create Token Does not allow "numeric" of "alphanumeric"

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-services#533]
The HAPI Protobuf states that a symbol can be alphanumeric:

https://github.com/hashgraph/hedera-services/blob/8519b36fdf9f06a9f508f95f070c8f2fc6baa676/hapi-proto/src/main/proto/TokenCreate.proto#L44

However, the implementation only accepts capitalized alpha characters, not numbers.

**Comment by lbaird** [comment]
In this case, the documentation is wrong and the code is right. The documentation should be fixed.

________________________________

**Comment by donaldthibeau** [comment]
Fixed in upcoming merge.
