### ISSUE TITLE
Remove deprecated body and sigs fields from Transaction proto

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#539]
Remove deprecated `body` and `sigs` fields from Transaction proto (line 40 and line 43)
https://github.com/hashgraph/hedera-services/blob/b440672250924901f9645649d442fa65d9592a20/hapi-proto/src/main/proto/Transaction.proto#L38-L45

**Comment by Neeharika-Sompalli** [comment]
Deprecated body and sigs fields are removed from Transaction proto and `signedTransactionBytes` field is added.

**_New  Transaction.proto_**
https://github.com/hashgraph/hedera-services/blob/c54ef642674348a5230aa9f217fdb540fd143530/hapi-proto/src/main/proto/Transaction.proto#L38-L42

The addition of signedTransactionBytes field to the Transaction protobuf message is designed to ensure that the hash of the transaction as calculated by the client and the network is guaranteed to be identical.
The network nodes will calculate the hash of the transaction using the signedTransactionBytes if it is present. This will ensure that the hash of the transaction as calculated by the client and network is guaranteed to match regardless of any differences in protobuf serialization across versions or languages.

This change is backwards compatible, so clients that currently use the `bodyBytes` & `sigMap` to submit transactions can continue to do so, with the node parsing and hashing the transaction as it currently does.

A transaction can only contain `signedTransactionBytes` or `bodyBytes & sigMap`. A transaction what contains any other combination of fields will be rejected with an INVALID_TRANSACTION response code.
