### ISSUE TITLE
`hedera-app-spi` to use PBJ entities

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#5427]

**Comment by mhess-swl** [comment]
As of commit `922b3fd32` and pbj version ``, all classes compile with the new pbj dependency and all 247 tests pass successfully. 

There is one class that has a couple of instances of an old protobuf object (`com.hederahashgraph.api.proto.java`), but the methods are required so as to avoid a duplicate dependency. See `com.hedera.node.app.spi.KeyOrLookupFailureReason`)
