### ISSUE TITLE
Allow zero weight nodes to accept transactions and create events

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#5476]
We currently have logic that changes the behavior of zero weight nodes. For example, zero weight nodes will not currently create events or accept transactions.

Since we don't currently use this feature and have less than ideal test coverage, we should disable this special behavior, and have zero stake nodes act the same as a non-zero stake node w.r.t. event creation and transaction submission.

**Comment by poulok** [comment]
We do test zero stake nodes. Please see [this](https://github.com/hashgraph/hedera-services/issues/5477#issuecomment-1460211699) comment.
