### ISSUE TITLE
Test zero stake nodes

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#5477]
Once we complete https://github.com/hashgraph/hedera-services/issues/5476, we should ensure that some of our nightly tests have nodes with zero stake. We should validate that the addition of zero stake nodes to a network does not cause unexpected behavior.

The work for this ticket is to compare the graphs from the zero-weight panels prior to [this](5476) change and after the change.

**Comment by poulok** [comment]
We already test for zero stake nodes. Please look at the `GCP-Daily-ZeroStake-4N.json` test panel and see if there is a case you think we are missing.

**Comment by poulok** [comment]
Existing zero-stake node panels are passing after the change to zero-stake node behavior.
