### ISSUE TITLE
hapi-fees comments needed

### ISSUE THREAD

**Issue by kimbor** [hashgraph/hedera-services#5491]
- [ ] fee category abbreviations (sb, tb, rb, etc) are used throughout this package. Need an explanation written up for what each of these mean, maybe in the package-level javadoc. Explanation should be linked with @see in each method that uses these fee categories
- [ ]  3 methods in FeeSchedules with no comments [https://github.com/hashgraph/hedera-services/blob/2931f954f04e7a5eb8a9cea752f3b72e08566261/hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/pricing/FeeSchedules.java#L66](https://github.com/hashgraph/hedera-services/blob/2931f954f04e7a5eb8a9cea752f3b72e08566261/hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/pricing/FeeSchedules.java#L66)
- [ ]  where does this magic number come from? [https://github.com/hashgraph/hedera-services/blob/2931f954f04e7a5eb8a9cea752f3b72e08566261/hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/pricing/ResourceProvider.java#L65](https://github.com/hashgraph/hedera-services/blob/2931f954f04e7a5eb8a9cea752f3b72e08566261/hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/pricing/ResourceProvider.java#L65)
- [ ]  what does Tfs mean in this method name? [https://github.com/hashgraph/hedera-services/blob/2931f954f04e7a5eb8a9cea752f3b72e08566261/hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/pricing/ScheduleGenerator.java#L92](https://github.com/hashgraph/hedera-services/blob/2931f954f04e7a5eb8a9cea752f3b72e08566261/hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/pricing/ScheduleGenerator.java#L92)
- [ ] what does Rbs mean in this method name? https://github.com/hashgraph/hedera-services/blob/cdcfb8885cef3dc43d3a919b2ef120807ae400ee/hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/usage/SingletonEstimatorUtils.java#L36
- [ ] 3 methods need descriptors https://github.com/hashgraph/hedera-services/blob/cdcfb8885cef3dc43d3a919b2ef120807ae400ee/hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/usage/SingletonUsageProperties.java#L26
- [ ] what do Bpt and RecordRb mean in these method names? https://github.com/hashgraph/hedera-services/blob/cdcfb8885cef3dc43d3a919b2ef120807ae400ee/hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/usage/TxnUsage.java#L44
- [ ] add javadoc class descriptors for all public classes and interfaces

**Comment by Neeharika-Sompalli** [comment]
Duplicate issue
