### ISSUE TITLE
Modularize hedera-util-service

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#5522]
TODO: Fill in details in a similar way to "Modularized HCS implementation" was done. 

https://hips.hedera.com/hip/hip-351

https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/util/UtilPrngTransitionLogic.java

**Comment by Neeharika-Sompalli** [comment]
Duplicate of https://github.com/hashgraph/hedera-services/issues/5724
