### ISSUE TITLE
Epic: Modularize hedera-staking-service

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#5523]
Under token service https://github.com/hashgraph/hedera-services/issues/5767

### Tasks
- [x] #7186
- [x] #7187
- [x] #7188
- [x] #7189
- [x] #7580
- [x] #7510
- [x] Add staking rewards payment for each cryptoTransfer in finalize method

**Comment by Neeharika-Sompalli** [comment]
Completed
