### ISSUE TITLE
Reconnect functionality in Hedera

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#554]
**Summary**
Implement reconnect functionality in Hedera
Platform notifies services of a successful Reconnect 

Hedera must rebuild in-memory data structures that are not  of state (also cached in memory) from latest state before accepting and handling transactions. These include

1. Address Books // not needed this moment because it is not used
2. Dedup & Expiration data structures
3. Fees 
4. Exchange Rates
5. Application properties
6. API permissions
7. Record Stream Hash: https://github.com/hashgraph/hedera-services/issues/608
8. Split `init` into `init` and `genesisInit`  https://github.com/hashgraph/hedera-services/issues/649
9. Implement a validator for 2-6: https://github.com/hashgraph/hedera-services/issues/650

**Comment by cesaragv** [comment]
@noshmody `ServicesState` already implements the method `public void initialize(MerkleInternal previous)` at line 131. Wouldn't adding the line `ctx.recordsHistorian().reviewExistingRecords();` at the end, rebuild the expiration data structures?

**Comment by cesaragv** [comment]
do not accept accepttransactions before steps 1 through 6 are complete

**Comment by tinker-michaelj** [comment]
> @noshmody `ServicesState` already implements the method `public void initialize(MerkleInternal previous)` at line 131. Wouldn't adding the line `ctx.recordsHistorian().reviewExistingRecords();` at the end, rebuild the expiration data structures?

Looks right to me! Seems that method assumes the `ctx.txnHistories()` map is empty; so we may need to precede it with `ctx.txnHistories().clear()`,

**Comment by tinker-michaelj** [comment]
For (3)-(5), we would use,
```
ctx.systemFilesManager().loadExchangeRates();
ctx.systemFilesManager().loadFeeSchedules();
ctx.systemFilesManager().loadApiPermissions();
ctx.systemFilesManager().loadApplicationProperties();
```
