### ISSUE TITLE
The State Validation Tool github actions should collate the individual jsons into a combined HTML report

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5541]
- [x] Collect json report from all the nodes state validation runs
- [x] Render a standalone HTML using this json
- [x] Generate real json data from the state validator

**Comment by deepak-swirlds** [comment]
closed by https://github.com/hashgraph/hedera-state-validator/pull/7
The final generated HTML needs to be enhanced, but the entire flow of generating reporting and collecting it works
