### ISSUE TITLE
Track and Test Critical Platform Thread Performance

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#5546]
Prior to adding new major features into the platform (such as BLS), it is important to understand how the threads critical to platform performance interact with the system and perform. We must be able to measure the performance impact of new features.

```[tasklist]
### Tasks
- [x] #5529
- [x] #5488
- [ ] #5575
- [ ] #5574
- [ ] #5585
- [ ] https://github.com/hashgraph/hedera-services/issues/8129
- [ ] #8108
- [ ] #8130
```

**Comment by poulok** [comment]
replaced by https://github.com/hashgraph/hedera-services/issues/9801
