### ISSUE TITLE
Create a Grafana Data Dashboard to view all existing relevant data metrics

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5552]
The aim here is to create one but probably multiple dashboards to visualize platform metrics with three goals in mind:

1. Keeping an eye on how the database is running and making sure everything is running properly
2. Understanding database usage and how that effects future design decisions such as compaction schedule
3. Diagnosing issues when they happen. Having a dashboard ready to go to start tracking down issues can be a huge help and stress reduction.

There are many dimensions to the data which makes it hard to put on dashboards. We have dimensions of:

- 1 to N nodes
- 2+ databases/tables 
- 2+ file collections per database/table, for example Internal hashes, leaves, HalfDiskHashMap buckets

So we are going to want some high level dashboards to see at a glance general operation is in shape. One good thing to do here is charts plotting all nodes as lines, this makes it easy to spot 1 or a few nodes that are behaving differently to the majority of the rest which can be a good indicator of a issue.

We also are going to want dashboards where you pick one node and/or one database/table to drill into the details in that one area.

**Comment by artemananiev** [comment]
A sample dashboard for benchmark runs will be provided as a part of https://github.com/hashgraph/hedera-services/pull/6224. This ticket is used to track production grafana dashboards, which can be created only after the new metrics (introduced by the same PR) are reported for testnet and mainnet.
