### ISSUE TITLE
Determine what new metrics are needed for the Grafana Data Dashboard

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5553]
Get with @jasperpotts to understand what is already done for this. Document the list of new metrics required in #5956

**Comment by jasperpotts** [comment]
I think there are 2 areas for metrics that would be useful:

- **Database internals that we do not have visibility into**
  - For each database/table - eg. SmartContractKV, FileStore etc.
    - **Total disk space is used for this DB** 
    - **Percentage of disk space wasted pending compaction**, ie. how big is total database files in MB / actual data stored in MB. The aim here is to measure compaction effectiveness, every time data changes we write a new copy to a new file. Then later we compact and delete old copies. At any point in time there is a bunch of old data waiting to be compacted and deleted. The question to answer his is what percentage of total data set size is this.
    - For each database/table that uses HalfDiskHashMap
      - What is the distribution of keys in buckets, ideally we would plot a histogram, no idea if that is possible. If not we can plot
        - How many(%) buckets are empty
        - How many(%) buckets are 25% full
        - How many(%) buckets are 50% full
        - How many(%) buckets are 75% full
        - How many(%) buckets are overflowing into second bucket, hopefully close to 0 or 0
        - How many(%) buckets are overflowing into third bucket, really hope 0
      - How many keys fit in a bucket on average
    - How many new files since last saved state?
    - What percentage of data is new since last saved state? 
 - **Stored Data Metrics**
   - How many X objects are stored in each database
   - As we move all other state over to DB then we will have a lot more interesting data we could collect. Like:
     - Most active accounts
     - Accounts with highest value
     - Accounts that have approvals
     - Contracts that have approvals
     - many others

Some of these will already be available in platform metrics and others will need to be added for validation tool

**Comment by artemananiev** [comment]
HalfDiskHashMap buckets work slightly differently than described above. There is no bucket size limits, and therefore no overflows. Each bucket contains as many keys as needed according to keys' hash value. Underlying bucket buffer is resized automatically.

Given this, I see the only HalfDiskHashMap specific metric:
* average number of keys / bucket (total number of keys is known after each flush, total number of buckets is fixed)

Besides that, there will be generic metrics also applicable to HalfDiskHashMaps:
* key reads / s
* files count
* total file size
* writes Mb/s during flushes
* reads/writes Mb/s during compactions
* etc.
