### ISSUE TITLE
Use thread measurement metrics to measure critical threads

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5585]
Use the new metric(s) created in #5574 for performance critical threads (event-intake, pr-consensus handling thread, consensus handling thread) and evaluate their usefulness. Look at JRS tests (use some nightly panels) to make any changes needed.

This ticket should not be merged until we are confident the implemented metrics are the ones we want.

- [ ] Incorporate new metrics into threads
- [ ] Look at JRS test graphs and determine changes needed
- [ ] Implement any changes

**Comment by lpetrovic05** [comment]
[VMerkleSC-Perform-7k-40m.pdf](https://github.com/hashgraph/hedera-services/files/11109551/VMerkleSC-Perform-7k-40m.pdf)

**Comment by lpetrovic05** [comment]
[VMerkle-SBReconnect-1k-15m.pdf](https://github.com/hashgraph/hedera-services/files/11110964/VMerkle-SBReconnect-1k-15m.pdf)
