### ISSUE TITLE
Propose how to integrate pre-consensus event stream startup sequence

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5586]
The logic of platform start up is complex. We need to integrate the pre-consensus event stream playback on startup and doing so with the current logic is undesirable. Come up with a proposal for the startup sequence such that integrating the pre-consensus event stream playback is easy and elegant.

# Proposal

This proposal is currently a WIP.

- when the platform is first started, do not start the gossip network right away
- until enabled, do not permit the following operations
     - writing events in the event intake to the preconsensus event stream
     - accepting app transactions
     - creation of any system transactions
     - the creation of new events
- set platform status to `REPLAYING_EVENTS`
- iterate over preconsensus event stream, and put events into event intake
- wait until all events have been replayed and fully ingested
- enable the following operations
     - writing events in the event intake to the preconsensus event stream
     - accepting app transactions
     - creation of any system transactions
     - the creation of new events
- set platform status to `ACTIVE`
- start gossiping

## Prerequisites

- encapsulate gossip inside of a component and remove as much implementation detail from SwirldsPlatform as possible
- gossip should be fully constructed, but not yet started, inside of the platform constructor
- figure out the requirements for the post-consensus event stream after a restart
- the ability to flush the event intake pipeline
- the ability to disable and enable the following features on the fly:
     - writing events in the event intake to the preconsensus event stream
     - accepting app transactions
     - creation of any system transactions
     - the creation of new events (if currently possible without gossip being started)
- move genesis state construction out of the platform (simplifies workflow, we don't need to support a special genesis workflow)
- final platform variables (nice to have, but perhaps not a strict requirement)

**Comment by lpetrovic05** [comment]
Documenting the ticket for this so far:
- #5639
- #5678
- #5397

**Comment by poulok** [comment]
Re-openning. We need a more detailed plan for integration. For example, when does gossip start?

**Comment by poulok** [comment]
I have added tickets to capture the new prerequisites in the epic (#5682)
