### ISSUE TITLE
Identify serialization requirements (which objects, how often used, etc...)

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-services#5590]

**Comment by artemananiev** [comment]
Closing as completed as MerkleDb PBJ branch is merged to develop now.

Long story short about (de)serialization:
* Reading from files: the existing `FileChannel` based approach is still used. The channel is used to read into byte buffers, which are then wrapped into `BufferedData`, which provides all necessary APIs to work with protobuf types.
* Writing to files: the existing approach is used for writing, too. On writing, a 16Mb chunk of file being written is mapped to memory as a `MappedByteBuffer` Java object. This byte buffer is then wrapped into `BufferedData`
