### ISSUE TITLE
Migrate each object type

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-services#5593]
- [ ] Repeat the following for each object type in Platform Data
  * Select an object type
  * Modify serialization for that object to use PBJ
  * Extend DataIO if needed for this object
  * Ensure proper data migration for that object from existing to PBJ
  * Test and verify correct operation and no performance regression

**Comment by artemananiev** [comment]
This is implemented as a part of #5592. No explicit data migration at node startup is needed. MerkleDb can read old (JDB) files, while new files (flushes, compactions) are always in the protobuf format. Eventually all entities will end up in PBJ files, and all JDB files will go away.

For every existing entity type, both in mono and modularized code bases, serializer classes were enhanced to provide method to serialize and deserialize entities to and from protobuf.
