### ISSUE TITLE
Extend DataIO as necessary to replace streams with DataIO

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-services#5596]

**Comment by artemananiev** [comment]
A number of bugs / enhancements have been filed against PBJ Data I/O library:

https://github.com/hashgraph/pbj/issues/73
https://github.com/hashgraph/pbj/issues/74
https://github.com/hashgraph/pbj/issues/75
https://github.com/hashgraph/pbj/issues/76
https://github.com/hashgraph/pbj/issues/77
https://github.com/hashgraph/pbj/issues/78
https://github.com/hashgraph/pbj/issues/79
