### ISSUE TITLE
Modify DataIO, if necessary, to match/incorporate the recent Memory Mapped IO work

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-services#5598]

**Comment by artemananiev** [comment]
I don't think we need explicit mapped byte buffer support in PBJ yet. `MappedByteBuffer` is still a byte buffer, so it can be wrapped into `BufferedData` as any other (heap or direct) byte buffer. This is how PBJ is used in MerkleDb to write new files, and it works just fine.
