### ISSUE TITLE
Identify data migration requirements

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-services#5601]
Include network restart performance impact, possible interaction impacts, and potential failure modes.

**Comment by artemananiev** [comment]
A few requirements that came to my mind:
* Support legacy (JDB) data file format for reading data files
* Support legacy (JDB) data file format for merging data files

For testing:
* Support legacy (JDB) data file format for writing data files

Questionable:
* A flag to write new (flushed or merged) files in legacy (JDB) format. Current implementation is new files are always PBJ, except in data migration tests, where files in the old format are generated first and then loaded back from disk. If such a flag is introduced, should it be true (use PBJ) or false (use JDB) by default?

**Comment by artemananiev** [comment]
In PR #7545 a new MerkleDb config option is introduced: `usePbj`. It indicates whether to use PBJ for new (flushed) and compacted data files. By default, set to false. In tests, it can be overridden by explicitly requesting data file collection to use PBJ or JDB. This is used in tests for data migration.
