### ISSUE TITLE
Run thorough functional and performance testing of the data migration

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-services#5603]
- [ ] Verify migration performance is sufficient to enable a timely network upgrade
- [ ] Document expected time impact during network upgrade for node operators

**Comment by artemananiev** [comment]
PBJ support in MerkleDb is implemented in such a way that no migration is needed. All entities will be eventually migrated from old JDB files to new PBJ files automatically in background, as long as they are updated (or old files are compacted). No migration performance to check.
