### ISSUE TITLE
Unashed virtual map in pipeline

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#5609]
This error has been around for ages. We should fix it.

```
 ERROR EXCEPTION        <<adv crypto: merkle hash #23>> VirtualPipeline: "unhashed" virtual map copy has a hash!
```

**Comment by artemananiev** [comment]
This has been already fixed, check [swirlds/swirlds-platform #6054](https://github.com/swirlds/swirlds-platform/issues/6054) for details.
