### ISSUE TITLE
Update-Freeze-1-5m test has errors of "Saved state not loaded" in HederaNodeValidator step

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#561]
**Summary of the defect**
The test is still tagged as "SUCCEEDED". 

Maybe we should change the errors to warnings if we think this test is successful.

**How to reproduce (if possible)**
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1600177626334800

**Service logs (if applicable)**
```
...
---- HederaNodeValidator SUCCEEDED validation ----
<<ERROR>>
Node 0 has exception:- Saved state not loaded:
Node 1 has exception:- Saved state not loaded:
Node 2 has exception:- Saved state not loaded:
Node 3 has exception:- Saved state not loaded:

```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by Neeharika-Sompalli** [comment]
The issue has been resolved. Test is passing in todays regression https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1602049685393500 .

It will be reopened if the issue is seen again
