### ISSUE TITLE
Proposal: Stale Transaction Resubmitter

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#5628]
## Required Reviewers
@lpetrovic05 
@cody-littley 

## Optional Reviewers
@edward-swirldslabs 
@poulok 

### Background

A utility is needed for BLS to be able to resubmit transactions that were put into events that become stale

This feature will be useful in other contexts in the future (e.g. StateSignatureTransactions)

### Proposal

- A new object, named `TransactionResubmitter`, implements `StaleEventObserver`
- Upon receiving a stale event, if it's an own event, the included transactions with `abortTime` after now are resubmitted
- An `abortTime` of `null` will mean the transaction is resubmitted forever
    
![EventTransactionPoolOld](https://user-images.githubusercontent.com/102969658/227237194-4637e076-f232-4606-80ba-76d60650e8bc.jpg)

**Comment by lpetrovic05** [comment]
Response to questions:
- There are lots of unit tests that verify that events will either become consensus or stale, so we can rely on this. But all of this goes out the window when there is a reconnect, for this scenario, we will have to figure something out.
- I would say don't worry about the "retry forever" feature for now, if there is no immediate use for it

My questions:
- Is the proposal to add these new fields to all transactions? That would add a lot of overhead.
- On a reconnect, the transaction pool is cleared, how do we handle this scenario?

**Comment by alittley** [comment]
> Is the proposal to add these new fields to all transactions? That would add a lot of overhead.

As Kelly noted, these fields would only be added to `SystemTransaction`s. Also, these fields would only be set for own transactions that want to be resubmitted. In fact, we could add these fields _only_ to specific types of system transactions which require resubmission. We could make an interface `ResubmittableTransaction`, and any transaction that doesn't implement it could be ignored by `handleStaleEvent`

> How will any of BLS work with reconnect?

I've created a [proposal](https://github.com/hashgraph/hedera-services/issues/5733) for BLS reconnect. With this proposal, it doesn't matter if a crash causes a stale event to be missed, and included transactions not resubmitted. Whenever the node comes back online, it simply looks at the transcript of what actually reached consensus, and does its best to recover.

> I would say don't worry about the "retry forever" feature for now, if there is no immediate use for it

In the case of signature transactions, would we want to retry sending forever until it's successful? If we don't want that, at what point in time would we declare defeat and stop trying to get a signature transaction to reach consensus?

> can we add the abort time as an Instant rather than a long

Yes, I will update the proposal to reflect this

>  We can also inject an instance of `Time` to the `TransactionResubmitter` to compare to wall clock time

Actually, I don't think abort should be defined with wall clock time, but rather consensus time. In the case of BLS, protocol rounds are defined by consensus time, and those are the boundaries where we would declare "defeat", if we couldn't get our message to reach consensus

**Comment by poulok** [comment]
> Actually, I don't think abort should be defined with wall clock time, but rather consensus time.

Ah, yes of course.

**Comment by lpetrovic05** [comment]
I don't like the idea of arbitrary lambdas being executed when something happens. Why would we go with a lambda instead of passing the failed transaction to some listener to decide what it wants to do?

**Comment by poulok** [comment]
What is the specific use case for the `transmissionFailedCallback`? Can `abortTime` be replaced with a boolean indicating that the transaction should be resubmitted if it becomes stale?

**Comment by alittley** [comment]
The idea behind `transmissionFailedCallback` was to provide a convenient hook to notify the BLS protocol that it can no longer continue. It isn't strictly necessary, and can be removed. Assuming that's removed, the queue thread is also no longer necessary

I don't think `abortTime` can be replaced with a boolean. There needs to be an end time when we stop resubmitting, unless we just wanted to submit a single time (which I don't think is the case)

**Comment by lpetrovic05** [comment]
Are we still going ahead with this if BLS is on hold?

**Comment by poulok** [comment]
The proposal looks good to me.

**My Answers to the Open Questions:**

> How confident are we in the ShadowGraph to rely on it notifying us of stale events without fail?

After the pre-consensus event stream, the only situation i can think of where it would not notify of stale events is after a reconnect. But then, it shouldn't matter anyways.

> Should we have a "retry forever" feature?

Can't hurt. An `abortTime` of `null` can be retry forever.

**Comment by poulok** [comment]
This proposal is adopted
![gavel](https://user-images.githubusercontent.com/82919061/230932711-6da74859-6f73-47c7-ac73-c4d26d501f39.png)
