### ISSUE TITLE
Separate platform construction from startup

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#5643]
Platform construction is very intertwined with the starting of threads, these should be separated out. Tasks:
- The following PR must merge. Not strictly related, but blocks other needed PRs https://github.com/hashgraph/hedera-services/pull/5633
- https://github.com/hashgraph/hedera-services/issues/5786
- https://github.com/hashgraph/hedera-services/issues/5809
- https://github.com/hashgraph/hedera-services/issues/5800 (requires design sign off)
- https://github.com/hashgraph/hedera-services/issues/5787 (i.e. implement the design described in the proposal above)
- https://github.com/hashgraph/hedera-services/issues/5788
- https://github.com/hashgraph/hedera-services/issues/5853

**Comment by cody-littley** [comment]
Merging this epic into https://github.com/hashgraph/hedera-services/issues/5682
