### ISSUE TITLE
Proposal: Clean up platform Transaction class hierarchy

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#5650]
The existing transaction class hierarchy looks like this:

![TransactionClasses](https://user-images.githubusercontent.com/102969658/225113508-429b63cc-31b4-4a07-9a96-6f248390543e.jpg)

- [ ] Create a proposal to improve this, and come to internal consensus on path forward
- [ ] Implement cleanup proposal

**Comment by alittley** [comment]
@poulok I believe `Transaction`, `ReachedConsensus`, and `ConsensusTransaction` could be collapsed. My understanding is that `SwirldTransaction` is the only type directly involved with the API services uses, and the constructor is just a byte array.

That said, I haven't yet put the work in to be sure (since, as you mention, this would be a big change, and isn't urgent). 

This issue was intended as a seed, so the task could be picked up later if someone is ever looking for a tech-debt task. If you'd prefer not to have issues like this, it's fine to be closed.

**Comment by poulok** [comment]
The current structure is described here, or at least it is pretty close: https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/docs/core/transaction-handling/transaction-handling.md

**Comment by alittley** [comment]
stale
