### ISSUE TITLE
Define non-automatic module for Spotbugs

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#5680]
# Goal
Create a proper non-automatic module for Spotbugs and make it transitively required. 

# Context
We currently wrap Spotbugs with an automatic module. We reference the module statically so as not to include Spotbugs in the final delivered code, but the tradeoff is that there are warnings generated at compile time. We could include Spotbugs transitively, but doing so would add the entire module graph instead of only Spotbugs, and this could hide higher-risk module access issues. 

Here is an example of the warnings generated at compile time:
```
warning: unknown enum constant When.ALWAYS
  reason: class file for javax.annotation.meta.When not found
```

The solution we've discussed is to create a non-automatic module for Spotbugs, and then transitively require Spotbugs in our module-info files.

**Comment by mhess-swl** [comment]
Blocked by #5681

**Comment by jsync-swirlds** [comment]
The Gradle Improvement Project (May 2023) will be reworking much of the modularization, including addressing this concern.  We will reevaluate this issue once that is complete.
