### ISSUE TITLE
Modularization: Create non-automatic modules to eliminate transitive dependency issues

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#5681]
There are a number of wrapped automatic modules in the platform sdk. According to @hendrikebbers, we want to convert these wrapped modules into proper (non-automatic) modules, which will get rid of many transitive dependency issues. 

List of modules to convert:
- [ ] Module 1
- [ ] Module 2
- [ ] ...

**Comment by jjohannes** [comment]
This is done. All we only use "real" Modules now. If a Jar is not a real module, we add a `module-info.class` in the patching process done by Gradle. If someone introduces a new dependency which is not a real module (and has not patching configured) the build fails.
