### ISSUE TITLE
Evaluate and possibly remove unused code

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#5697]
As far as I can tell the method `shouldCreateEvent` and the variable `inFreeze` in `EventTransactionPool` are not used anywhere. We should evaluate if this code is needed or not and remove it if its not.
@cody-littley I know there was some kind of freeze issue in JRS, could this be related?

**Comment by cody-littley** [comment]
@lpetrovic05 Unrelated. It looks like the freeze problem is a symptom of a state leak and not a problem all by itself.

**Comment by lpetrovic05** [comment]
> @lpetrovic05 Unrelated. It looks like the freeze problem is a symptom of a state leak and not a problem all by itself.

So then it looks like we should remove this unused code
