### ISSUE TITLE
Add a PCLI sub command to sign services stream files

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5710]
After #5757 is complete, create a sub command that signs all necessary stream files generated by services. This command will be used by NMT during disaster recovery to sign the gold stream files.

**Comment by alittley** [comment]
@nathanklick Is the functionality that currently exists in `FileSignTool::generateSigFileOldVersion` something that needs to be accessible in this new feature to be used by NMT for disaster recovery?

**Comment by cody-littley** [comment]
Given the current difficulties imposed by platform and services not being integrated at build time, it's currently a bit of a hassle writing services PCLI sub-commands. As a short term solution, I am ok if this functionality ends up in YAHCLI.
