### ISSUE TITLE
Proposal: BLS Reconnect Behavior

### ISSUE THREAD

**Issue by litt3** [hashgraph/hedera-services#5733]
How should BLS behave with reconnect?

### Required Reviewers
@cody-littley 
@lpetrovic05 

### Optional Reviewers
@edward-swirldslabs 
@poulok 

### Proposal

- First, check the system state to see what the current protocol round is, and which own BLS messages have reached consensus
    - If it's determined that we _have_ failed to send a required message, abort the protocol. There is no way to recover, and we'll have to wait until the next rekeying
    
- ![BlsReconnectUnuccessful](https://user-images.githubusercontent.com/102969658/226649088-73ffe737-8fab-4339-887a-1be481309b46.jpg)

    - If it's determined that we _haven't_ failed to send a required message, rebuild the local BLS state from the transcript of all BLS messages that have been sent thus far
        - This local state rebuild involves computing various cryptographic aggregates, which exist locally and aren't put into the system state. It hasn't been measured yet how much work this is... if it's a burdensome amount of work, we could create a system that caches these local aggregates. The necessity of this can be determined at a later date
    - Once the node has finished recomputing the local state, send the required message to complete the current round (if it isn't too late)
    - At this point, the node is fully caught up and can complete the protocol as normal
    - ![BlsReconnectSuccessful](https://user-images.githubusercontent.com/102969658/226649516-54152d8e-6b20-42d1-b3ff-c68be751b597.jpg)

### Questions

- Currently, there are some "message-optional" protocol rounds, where a message is only sent if a node has something to complain about
    - This causes the problem that a reconnecting node that comes online during (or immediately following) one of these "message-optional" rounds won't know whether it simply died too soon to send a complaint, or if it finished computations and found nothing to complain about.
    - To err on the side of safety, a node would need to assume it crashed before finishing calculations, and re-do the entire round.
    - If instead of allowing nodes to skip sending a message, we required them to send an empty complaints message, then we would be able to avoid this ambiguity.
    - We need to measure if there is a meaningful difference in work required between re-doing the entire round, and simply rebuilding the local state. This is only applicable for the edge case of "we finished a 'message-optional' protocol round, found nothing to complain about, and then crashed"

**Comment by edward-swirldslabs** [comment]
Is "rekeying" sounds very fundamental and catastrophic.  Is rekeying something that can be automated as a recovery procedure?  Or is this as fundamental in severity as an ISS?

**Comment by edward-swirldslabs** [comment]
In the case of sending an empty complaint message and then a node crashes.   When it comes back from having crashed, how does it learn that it has sent an empty complaint message?

**Comment by alittley** [comment]
BLS is not happening anymore
