### ISSUE TITLE
Improve transaction storage for receipts

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5743]
Transactions are currently stored in a MerkleMap and FCQueue. The last 3 minutes are kept around in order to provide transaction receipts. The map is used for fast querying and the FCQueue is used for expiry. The performance of add/remove is a bottleneck. Hashing of the MerkleMap is also an overhead.

First thing to try is to use the virtual map but all in memory. Depends on #5824

**Comment by OlegMazurov** [comment]
Currently, when `accounts.storeOnDisk` is enabled, we create a new child in `ServicesState`, `PAYER_RECORDS`, as a `MerkleMap`.Adding or removing records from the map is done via `payerRecords.getForModify(payerNum)`, which is a performance bottleneck at high TPS.

An alternative solution has been proposed to make the `PAYER_RECORDS` node an `FCQueue` and maintain a separate `Map<EntityNum,ExpirableTxnRecord>` outside the state.
When adding a new record, we update the state via the `FCQueue` node and also add the record to the map.
When looking up records for an account, we do it using the map.
When expiring a record, we update the state by removing the record from the `FCQueue` node as well as from the map.
As only the `FCQueue` node will be saved/restored with the state, we need to reconstruct the map from the queue upon state restoring.

**Comment by rbair23** [comment]
I can take this one and deal with it in the modular implementation
