### ISSUE TITLE
Investigate failing freeze test performance

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5745]
A freeze test recently started failing because the application could not keep up with the transaction load. This test has been around for a long time but recently started failing to keep up.

[Regression Ticket](https://github.com/swirlds/swirlds-platform-regression/issues/3282#issuecomment-1476884381)

**Comment by artemananiev** [comment]
@imalygin and I have just looked through all VM related metrics (VM size, flush latency, merge latency, flush backlog,  for `VMerkleSC-Restart-200-17m` for a failed run (Mar 21st) and for a successful run (Mar 13th). VM flushes grow slightly faster for the failed run in the very end of the test than for the successful run, but it doesn't look critical. Flush latency is higher for the successful run, though.

Some transaction related metrics are different. For example, `trans/sec` is about 2 times lower for the failed run, and it's observed through the whole run time, not just in the beginning or in the end.

**Comment by artemananiev** [comment]
Log inspection for the failed runs didn't reveal any exceptions, either.

**Comment by poulok** [comment]
kicked back to the hashgraph team #5684
