### ISSUE TITLE
Proposal: incremental serialization improvements

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#5746]
Currently, the number one biggest roadblock to getting rid of static access patterns are the serialization APIs. These APIs currently provide no ways for injecting node resources (e.g. configuration, metrics, etc).

# The Current Plans for Serialization

We have grand plans for how we will overhaul the entire serialization framework, and do things like introspect on constructors and pass all of the needed resources at object construction time.

The problem is that this is a very nontrivial change, and it's hard to justify putting the cycles into this in the short term.

# Proposal 1: Augment the serialization API with a PlatformContext

Since it will take a long time to get to the final goal, I propose an intermediate solution that will allow us to stop using static access patterns much sooner. This solution requires low developer effort.

Add the following method to the `SelfSerializable.java` interface:

```
    default void deserialize(
            @NonNull final PlatformContext platformContext,
            @NonNull final SerializableDataInputStream in,
            final int version)
            throws IOException {
        deserialize(in, version);
    }
```

And provide a default implementation for the existing deserialization method:

```
    default void deserialize(final @NonNull SerializableDataInputStream in, final int version) throws IOException {
        // No need to override this method if the deserialization method with a context is implemented
        // This method is never called directly by the serialization framework.
        throw new UnsupportedEncodingException("deserialize() is not implemented");
    }
```

(Note: use the same pattern on the `ExternalSelfSerializable` interface.)

## Downstream impact

This will not effect down stream users who have implementations of serializable objects using the old serialization API, since we will still support that workflow. I suggest we leave the old workflow in place until the build pipeline for platform and services are unified (this will allow a platform engineer to migrate the code without burdening the services team).

# Proposal 2a: Add core utilities to the Platform Context

There are a few platform utilities that are needed by serializable classes. I propose that they be added to the `PlatformContext`.

- ThreadManager
- TemporaryFileBuilder
- LogManager (this one requires more discussion, and we don't need to do this right away -- there are mixed opinions on this)
- SwirldMain (this seems horrible at first... but there are data structures like VirtualMap that need access to a node-scoped merkle DB... I don't know of a better way to do this)
- others?

# Propsal 2b: just add a bunch of extra arguments

If we can't agree to add the things listed in `PlatformContext`, then one alternative may be to add extra arguments to the deserialize method.

**Comment by lpetrovic05** [comment]
This has a few drawbacks I think:
- Adding a dependency on the context for all deserialization, which will probably add dependencies to all sorts of places
- It might bloat the PlatformContext with stuff that some deserializers need and doesn't belong in the context

If this is a simple short term solution, then it makes sense, but I doubt it will be short term. Here is another option:

### Proposal 3
Add specialized deserializers as an option. Classes that need additional dependencies (whatever the dependencies are), can have a deserializer that has them. We can make the construction of deserializers automatic if constructed from PlatformContext. 
The benefits of this approach are:
- It can work with any possible dependencies, not just the platform context
- It will allow us to turn `SelfSerializable` objects into records (see `ConstructableRecord` used in a unit test)

**Comment by lpetrovic05** [comment]
> @lpetrovic05
> 
> My main concern about proposal 3 is that it requires some nontrivial implementation work. Proposal 3 is the ideal solution, but the reason why we haven't implemented it up until now is because it requires a lot of work.
> 
> IMO, it's better to implement a less than ideal solution that we have time to do if it allows us to make forward progress. The change I propose won't make it any harder to implement specialized constructors when we get around to it, and it will allow us to continue our cleanup work with respect to static stateful objects.

Makes sense, I guess this is something @poulok must decide 😄

**Comment by poulok** [comment]
Closing, since we will switch to PBJ.
