### ISSUE TITLE
We need to be validating JRS metrics

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#5763]
Right now, we basically ignore metrics output for the nightly JRS tests.

- We need a metrics validator that can be configured on a test by test basis.
- We need to be able to specify boundaries for certain metrics that will fail the test if they are exceeded
- We should be capable of ignoring very short bursts above a threshold (if configured)
- We should add sanity checks for important metrics, e.g. if it takes more than 1 second to copy a state we should fail a test

**Comment by poulok** [comment]
@cody-littley, should we close this ticket since the plan is to eventually replace all JRS tests with other forms of tests?
