### ISSUE TITLE
Find out why UmbrellaRedux only send out ~50% of required operations for HCS requests

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#578]
**Summary of the defect**
While doing perf test, UmbrellaRedux seems to only send out 50% of configured requests rate.

**How to reproduce (if possible)**

Check out the nightly JRS regression HCS perf test config.

**Service logs (if applicable)**
```
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
None

**Comment by Neeharika-Sompalli** [comment]
Observation : This issue does not happen in file and smart contract tests . In file test expected rate is 28 TPs and it gives the same https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1602012257372500
