### ISSUE TITLE
Improve the ThreadManager

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#5787]
Our current thread manager is more of a placeholder than anything.

In order for the thread manager to do what we need it to do, we need the following features:

- we should be able to create threads before the thread manager is started
- if we try to start a thread before the thread manager is started then we should throw
- we should be able to directly instantiate thread pools from the thread manager
- we should be able to create thread pools before the thread manager is started
- if we attempt to enqueue work on a thread pool before the thread manager is started then we should throw

[Design Proposal](https://github.com/hashgraph/hedera-services/issues/5800)

**Comment by david-bakin-sl** [comment]
should be able to limit #threads - e.g., to 1 - for use during unit tests.
