### ISSUE TITLE
Integrate new ThreadManager

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#5788]
Once we add the new features to the `ThreadManager`, we need to switch from the adhoc implementation that permits creation of threads any time to the more restricted version.

This is likely to cause some breakages (i.e. any place where we try to do work on threads before the system is constructed). Do any necessary refactoring necessary to get the system functional under the new threading model.

**Comment by poulok** [comment]
Platform implemented a new framework that may make these resource manager tickets moot. If we need something like this in the future, we will create new tickets.
