### ISSUE TITLE
Add PCLI command to sign account balance files

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#5820]
- Some functionality exists in the platform `FileSignTool` that purports to do this, but it's possible the format has changed
- After implementing this feature, `FileSignTool` can be removed, since all the functionality will have been moved

**Comment by cody-littley** [comment]
Given the current difficulties imposed by platform and services not being integrated at build time, it's currently a bit of a hassle writing services PCLI sub-commands. As a short term solution, I am ok if this functionality ends up in YAHCLI.
