### ISSUE TITLE
Revive HCS EET's on PBJ branch

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#5842]
### Problem

We want to make sure the HCS EET's are still passing with `workflows.enabled` before merging `04712-use-pbj` to `develop`.

### Solution

- [x] #5851
- [x] #5843
- [x] #5860
- [x] #5852

**Comment by mhess-swl** [comment]
We'll also need to get the docker image created via `./gradlew createDocker` working again. Right now the platform never comes online (active).
