### ISSUE TITLE
State Proofs V1

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#5850]
# State Proofs Version 1

- decide if we want state proofs before BLS
- decide if we want state proofs that support nary trees
- decide if we want to support state proofs with multiple leaves (i.e. a state proof tree)
- design the serialization protocol for state proofs (probably a protobuf)
- create the protobuf definitions for state proofs
- create a design spec for state proofs intended for public consumption (perhaps by a standards body)
- design the platform/merkle APIs for constructing state proofs
- implement state proofs

# Future tasks (not required for V1)

- state proofs with BLS
- design API for public to request state proofs
- implement API for public to request state proofs
- support state proofs with different SDKs
- write solidity library for interacting with state proofs
- public state proof spec (perhaps to standards bodies)
- use state proofs for cryptographic validation of event/record streams (needed for scalability)
- use state proofs for more robust fallen-behind detection

**Comment by poulok** [comment]
Completed
