### ISSUE TITLE
Fully remove support for settings in config.txt

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#5865]
We currently support a small handful of settings in `config.txt`, but nobody uses this feature. Remove support for this workflow.

When this refactor is completed, the only things remaining in `config.txt` will be the app definition, the address book, and the "swirld" name.

**Comment by poulok** [comment]
@timo0 can this ticket be closed?

**Comment by mxtartaglia-sl** [comment]
After talking with @cody-littley , I am closing this issue as duplicated from https://github.com/hashgraph/hedera-services/issues/8877. After services modularization we can create a follow-up ticket to remove the remaining properties on the file.
