### ISSUE TITLE
change preHandles to throw a PreCheckException instead of setting context status

### ISSUE THREAD

**Issue by kimbor** [hashgraph/hedera-services#5880]
### Problem

In existing preHandle methods, when invalid arguments are encountered, we currently set the context.status to the relevant ResponseCodeEnum and then return. Instead it would be better to throw a PreCheckException with the ResponseCodeEnum.

Also there is an implicit undocumented assumption that every implementation of TransactionHandler should have preHandle and handle methods. Methods should check payer key before doing other work.

### Solution

Update existing preHandle methods to throw the exception. Also update javadoc in TransactionHandler class to document this assumption.

**Comment by rbair23** [comment]
This change had a lot of follow on effects. I thought it would be a straightforward exercise in adding "throws PreCheckException" in a few places, but it was not.

In the existing code, on methods like `getKey(AccountID)` we return not a `Key`, but a `KeyLookupOrFailure` object, which is a tuple of `Key` and `ResponseCodeEnum`. But `getKey` on `AccountAccess` or `ReadableAccountStore` really aren't the right place to be doing verification or raising exceptions. So I removed `KeyLookupOrFailure` and all the logic in those methods so they could be dead simple -- return null or non-null depending on whether you found the object or not. And then the pre handlers had to be updated to compensate. And a huge pile of tests. A huge, huge pile of tests.
