### ISSUE TITLE
Enforce metric name rules

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5967]
There are currently no restrictions on what characters can be used in metric names. Some characters cause problems for systems like Prometheus and Elastic to ingest. There are currently scripts that modify metric names to make them compatible with other systems.

Metric names should be validated at the time of creation. There are at least two options for this:

1. Throw an exception when a metric is created with an invalid name
2. Modify the name of the metric to conform to the standards when publishing to externals 

**Elastic converter:** https://github.com/swirlds/infrastructure/blob/master/hedera-utils/PipelineGenerator.py
**Prometheus converter:** `com.swirlds.common.metrics.platform.prometheus.NameConverter`

**Comment by mxtartaglia-sl** [comment]
Noting here to discuss with @tannerjfco: 
1. Elastic Converter: it is not there anymore; where should I look for it? What are the constraints for the converter?
2. A suggestion is to throw an exception during Metric creation, but should that be accompanied by some change other than the hedera-services codebase?
3. How can I get Prometheus access?

**Comment by mxtartaglia-sl** [comment]
List of decisions made after discussing with @hendrikebbers 
  | Throw exception | Log Error
-- | -- | --
Design |   | ✓
  | Not Required | Required for Metrics Supporting Units
Unit | ✓ |  
  | suffix of the name | Prometheus handle
Unit |   | ✓
  | Fixed values | Free values
Unit |   | ✓
  | Create and assert naming conventions | Free values
Naming Style |   | ✓
  | Validate In Metrics Framework | Validate in Prometheus adapter
Design |   | ✓
  | Extension | Performance
Design |   | ✓

- We should perform the validations as close to the Prometheus client as we can, given that we want to maintain independence between the framework and the tool used to report.
- metric units will not be mandatory. 
1.  To make them mandatory introduces some challenges,  such as having to replicate some logic Prometheus implements to identify the type of metrics that cannot have a unit; 
2. Unit field might not be enough context for all the public consuming the metric, some would need a description to understand what the metric is measuring, we cannot make all fields mandatory. What we actually need is a way to make graphana, prometheus and our framework to share metadata that can better describe the information the metric is representing.
