### ISSUE TITLE
Setup alerts based on data integrity failures and out of bounds metrics

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5983]
Setup alerts that tie into PagerDuty (this can be directly from the state validation tool or based on a metric that is pushed to grafana, whichever is easier).

**High Urgency Alerts**
1. A rehash produces the wrong hash
2. If any table has zero files, except the filestore

**Low Urgency Alerts**
1. A state cannot be downloaded from any node for 1 hour
2. A state cannot be downloaded from a particular node for 2 hours

**Comment by ElijahLynn** [comment]
Please let me know if you need assistance on the PagerDuty side setting up the low and high urgency alerts. We can set them up so that low urgency just pages during business hours.

**Comment by imalygin** [comment]
let's call the variable `PAGER_DUTY_TOKEN`

**Comment by ElijahLynn** [comment]
Looks like I don't have that level of access. I've created a ticket for our team to provide support in https://github.com/swirlds/infrastructure/issues/4971. cc @dalvizu @tannerjfco

**Comment by imalygin** [comment]
PD integration for failed `Rehash` and `TotalSupply` validation added with this task https://github.com/hashgraph/hedera-services/issues/6023

**Comment by ElijahLynn** [comment]
Do we still need a task to move from a testing PD integration token/service to a non-testing one? We will need an existing service and escalation policy or a new one created.

**Comment by imalygin** [comment]
@ElijahLynn yes, we need a real PD integration token.

**Comment by ElijahLynn** [comment]
Internal Slack conversation here https://swirldslabs.slack.com/archives/C03DN7L1T1A/p1698104334241009. And @tannerjfco and @poulok chatted and worked out what is needed for PagerDuty.
