### ISSUE TITLE
Enhance PCLI to print event stream reports for many streams

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#6008]
When analyzing an event stream using `pcli event-stream info`, it would be nice to be able to supply many directories, or a directory with many sub directories, each containing a different event stream, and print out a report for each in a single command. A summary report should also be reported, listing the directory with the highest number of events and the directory with the latest event in consensus time.

### Use Case

There are 3 nodes that have event stream files for the same time period. Each node has a directory which contains one or more subdirectories of event streams. Each node directory is in the same parent directory:

```
parentDir/node0/evt1/<event_stream_files>
parentDir/node0/evt2/<event_stream_files>
parentDir/node1/evt1/<event_stream_files>
parentDir/node1/evt2/<event_stream_files>
parentDir/node2/evt1/<event_stream_files>
parentDir/node2/evt2/<event_stream_files>
parentDir/node2/evt3/<event_stream_files>
```

I want to be able to provide the `parentDir` to PCLI (and some new flag) that causes the tool to print out a separate event stream report for each node, and a summary report telling me the node with the highest number of events and the node with the latest event in consensus time:

```
parentDir/node0/<report_file>
parentDir/node1/<report_file>
parentDir/node2/<report_file>
parentDir/<summary_report_file>
```

**Comment by alittley** [comment]
@poulok

Proposed implementation:
- Allow user to specify multiple path arguments
- Add a flag `--split-report`, which when set, causes a separate report to be generated for each specified directory (and any subdirectories found inside), plus a summary report as described
    - Not setting `--split-report` will result in behavior exactly matching current behavior

Questions:
1. How should nested directories be handled with the `--split-report` flag set to `true`?
    - E.g. If a `parentDirectory` contains stream files, and a `childDirectory` also contains stream files, should the report for the `parentDirectory` encompass the stream files inside of `childDirectory`? Or should a given report only encompass stream files *directly* inside that directory?
2. Would there be any benefit in allowing the user to choose not to generate separate reports for child directories?
    - E.g. "Here are directories `X`, `Y`, and `Z`, which contain nested directories with stream files. Generate a separate report for `X`, `Y`, and `Z`, recursively including all contained stream files, **but** ignoring precise directory hierarchy"
3. Would there be any benefit in adding a flag to ignore child directories entirely?

**Comment by alittley** [comment]
We settled on the following strategy:

The new flag will simply push the level of the report down one directory.

- Current behavior: "generate a single report for directory X, which encompasses all contained stream files, recursively
- New behavior: "generate a single report for every immediate child directory contained in directory X, and additionally create a summary of these individual reports"

The current behavior will be exactly maintained if the new flag isn't used
