### ISSUE TITLE
Setup a PagerDuty alert when the State Validation Tool fails on a production environment

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#6023]
Setup a PagerDuty alert when the state validation tool fails on a production environment.

**Comment by imalygin** [comment]
Related issue - https://github.com/swirlds/infrastructure/issues/4971

**Comment by imalygin** [comment]
PagerDuty key is added as `secrets.PD_INTEGRATION_KEY` to https://github.com/hashgraph/hedera-state-validator/

**Comment by imalygin** [comment]
PagerDuty is integrated with the State Validation Tool. If `Rehash` or `TotalSupply` validations fail, it triggers a critical alert

**Comment by imalygin** [comment]
https://github.com/hashgraph/hedera-state-validator/pull/67

**Comment by ElijahLynn** [comment]
Do we still need a task to send it to a non-test service/integration key? Or did you already do that?
