### ISSUE TITLE
Post 0.35.2 new contracts unexpectedly fail to associate or dissociate other accounts

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#6029]
### Description

Prior to 0.35.2, contracts could utilize `HederaTokenService.associateToken()` and `HederaTokenService.dissociateToken()` in their logic to modify an accounts assocaition with a token.

However, this logic relied on the application of top level HAPI signatures being applied to EVM contract execution logic. This was insecure and could have allowed unauthorized association without the accounts intent.

In the [0.35.2 security model changes](https://github.com/hashgraph/hedera-services/releases/tag/v0.35.2) this issue was addressed to ensure user and network security.
As a result new contracts deployed assuming the previous model worked are encountering `CONTRACT_REVERT_EXECUTED ` `INVALID_FULL_PREFIX_SIGNATURE_FOR_PRECOMPILE`.
This implies that the operation did not have the appropriate authorization for the action.

As a result DApps and developers will encounter issues for new contracts since they may assume previously model operation. Submitting a `TokenAssociate`/`TokenDissociate` via HAPI using the SDK is the only workaround solution at this time.
Additionally, if a smart contract doesn't differentiate between `TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT` and other errors it may result in further undesired UX issues.

### Steps to reproduce

1. Deploy a smart contract that calls `HederaTokenService.associateToken()` or `HederaTokenService.dissociateToken()` where the account to be associated is not the contract in question e.g. the EOA or another contract
2. Execute a smart contract call to call the function to run the association
3. Observe the error

### Additional context

The urgency and the side effect here is undesirable.
However, designs are already in exploration to address this e.g. https://github.com/hashgraph/hedera-services/pull/5986 

Accounts should operate on themselves when it comes to modifying state/properties

### Hedera network

testnet

### Version

0.36.1

### Operating system

None

**Comment by mshakeg** [comment]
Hi @Nana-EC will the solution enable developers to associate & dissociate an account from a token as hashgraph/hedera-services/issues/4126 would've enabled.

For example, an `account` could submit a transaction to `address(0x167)` with `data=encode(associateToken(account,token))` to associate with a `token`.

As this issue describes it's no longer possible to have an intermediary contract call the HTS precompile to associate/dissociate an EOA with a token, so as far as I can tell it's not currently possible for an ECDSA(Ethereum) account to associate/dissociate with tokens.
