### ISSUE TITLE
Configure `VirtualMapFactory#MAX_IN_MEMORY_HASHES` properly 

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#6043]
### Problem

The current value of `VirtualMapFactory#MAX_IN_MEMORY_HASHES` is zero, and all data sources configured by `VirtualMapFactory` use this value. This means that the usage of the in-memory hash store is effectively disabled, and it seems like the current configuration is missing out on a potential performance improvement.

### Solution

Run a series of experiments to find the proper balance between hash lookup performance and acceptable memory consumption by tuning `VirtualMapFactory#MAX_IN_MEMORY_HASHES`.

**Comment by artemananiev** [comment]
This is fixed long time ago. First, custom hash RAM to disk threshold settings in `VirtualMapFactory` are removed now. Default mechanism to set the threshold is used: `MerkleDbConfig`. Second, the default value in the config is set to what's used in mainnet, `8388608`, and is not overridden in HS settings.
