### ISSUE TITLE
Verify and add missing EET test coverage for smart contract legacy tests

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#605]
1. Find out what new EET test suite(s) covers these test cases. If any test scenario missed, add them;

Refer to #604 for more details.

- [x] **Smart contract service tests** 
  - [x] legacy.regression.SmartContractCRUD
                 - Already handled [here](https://github.com/hashgraph/hedera-services/blob/9cc54f3b83028a82f9e93015f463fc2cfd2d3885/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ContractCallSuite.java#L109)

  - [x] legacy.regression.SmartContractPay
        - Already handled [here](https://github.com/hashgraph/hedera-services/blob/9cc54f3b83028a82f9e93015f463fc2cfd2d3885/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ContractCallSuite.java#L225)
  - [x] legacy.regression.SmartContractCreateContract
  - [x] legacy.regression.SmartContractBitcarbon
         - added to `SmartContractAggregatedTests` and will be converted to EET later
  - [x] legacy.regression.SmartContractCallLocal
            - Already handled [here](https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ContractCallLocalSuite.java)
  - [x] legacy.regression.SmartContractDeletePayable
         - Add tests to `ContractCallSuite` that sends some balance to a contract and validate what happens to that balance when we delete that contract.
  - [x] legacy.regression.SmartContractInlineAssembly
  - [x] legacy.regression.SmartContractNegativeCalls
          - [x] Add negative test - `insufficientGas` to `ContractCallSuite` 
  - [x] legacy.regression.SmartContractNegativeCreates
          - handled negative SC creates [here](https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ContractCreateSuite.java)
  - [x] legacy.regression.SmartContractPayReceivable
         - very similar to `SmartContractPay` add a test to `ContractCallSuite` that does multiple transfers to a contract and validate the balance.
  - [x] legacy.regression.SmartContractPayReceivableAmount
         - Do multiple transfers to the contract and validate the TransferList each time
         - This and other several smart contract pay/fund transfer test cases are converted to EET SmartContractPaySpec suite
  - [x] legacy.regression.SmartContractSimpleStorage
         - handled SC create, set and get [here](https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ChildStorageSpec.java) Couldn't find solidity to compare with.
  - [x] legacy.regression.SmartContractSimpleStorageLinked
         - handled SC create, set and get [here](https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ChildStorageSpec.java) -- Actual Child Storage 
  - [x] legacy.regression.SmartContractSimpleStorageWithEvents
         - handled SC create, set and get [here](https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ChildStorageSpec.java) Couldn't find solidity to compare with.
  - [x] legacy.smartcontract.BigArray
  - [x] legacy.smartcontract.OCTokenIT
  - [x] legacy.CI.SmartContractFailFirst 
  - [x] legacy.CI.SmartContractSelfDestruct

**Comment by anighanta** [comment]
fixed with https://github.com/hashgraph/hedera-services/pull/643
