### ISSUE TITLE
Design Task: Platform detection of a missed upgrade

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#6052]
The platform should detect if it has missed an upgrade and write an indicator file for NMT so it can initiate node upgrade.

The platform already detects if it is attempting to gossip with a node that is at a different software version than itself. If self is told that it is behind by a super majority of peers by consensus weight, it should write a marker file with the version of software the super majority is on.

The location of this file must be coordinated with the NMT team since they are the consumers of this file.

UPDATE:
This approach has problems. Come up with and document a better approach.

**Comment by poulok** [comment]
Can we make the threshold a strong minority instead of a super majority? If so, this should be compatible with the address book initialization logic as long as a node doesn't miss more than 1 upgrade.

**Comment by poulok** [comment]
Problems:

1. Nodes must have the latest state (through the freeze time) in order to arrive at the proper consensus weights after upgrade.
2. Nodes must be in a fully connected network in order to detect a strong minority of peers' versions.

**Comment by Reccetech** [comment]
@poulok Regarding "If self is told that it is behind by a super majority of peers by consensus weight, it should write a marker file with the version of software the super majority is on."

Why do we need to reply upon consensus to tell a node if its on the wrong software. We could certainly use this method as a backup, for could we not also have nodes run more traditional checks on a service like Github upon startup to check and see if they are on latest version of software? like a github action version check?

Thanks!
