### ISSUE TITLE
Need access to metrics configuration from services

### ISSUE THREAD

**Issue by kimbor** [hashgraph/hedera-services#6062]
### Problem

While attempting to integrate Platform v0.38 into Services (PR #[6054](https://github.com/hashgraph/hedera-services/pull/6054)), we ran into an issue. AppTestBase and TestUtils classes need access to TestConfigBuilder from the platform code but this class is not accessible. 

As a temporary workaround we copy-pasted TestConfigBuilder into the services project test folder.

### Solution

Update platform to expose TestConfigBuilder so we can import it properly.

**Comment by timo0** [comment]
I am unable to replicate the issue you mentioned. When I remove your copy from `hedera-node/hedera-app/src/test/java/com/hedera/node/app`, everything compiles and the tests run without any problems. 

Therefore, it seems that the copy you added does not affect the code, which continues to use the original class from the platform. Could you please describe the issue you encountered before adding the copy?

**Comment by kimbor** [comment]
Were you looking at the branch in PR #6054 ? The class is not needed until we bump the platform version in use (as is done in the PR I mentioned). Once we bump the platform version, the DefaultMetrics constructor requires an additional argument of type MetricsConfig. TestConfigBuilder is needed in order to create a stub instance of MetricsConfig for testing in AppTestBase and TestUtils.
