### ISSUE TITLE
change updateStake to updateWeight

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#6065]
In order to disambiguate the concept of consensus weight from per node from the concept of stake per node, the fields and methods that reference `stake` in the address book should be changed to `weight`.   
* SwirldState.updateStake()
* AddressBook.updateStake()
* AddressBook.getTotalStake()
* Address.getStake()
* Address.copySetStake()

**Comment by poulok** [comment]
How about `weight` instead of `consensusWeight` for the method names? It is also used for state signing so i think that is more accurate. Plus, it's shorter.
