### ISSUE TITLE
Remove `ownHost` from Address

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#6094]
`Address` objects currently have a field called `ownHost`, which is true iff that address corresponds to a local address.

I suggest we remove that field from `Address`, and create a new micro-component that looks something like this:

```
public class OwnHostTracker {

    boolean isOwnHost(@NonNull final Address address);

}
```

This class should only be passed into the components that currently need this information.

**Comment by edward-swirldslabs** [comment]
fixed by: https://github.com/hashgraph/hedera-services/pull/6973
