### ISSUE TITLE
Create special test workflow to validate ISS logging/FCM dumps

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#61]
When an ISS happens, Platform will call the `InvalidSignedStateListener` that Services [registers](https://github.com/swirlds/services-hedera/blob/dev/hedera-node/src/main/java/com/hedera/services/ServicesMain.java#L327) in `ServicesMain`.

For up to the next 5 rounds (assuming the ISS persists), Services is now designed to [dump](https://github.com/swirlds/services-hedera/blob/dev/hedera-node/src/main/java/com/hedera/services/ServicesMain.java#L362) the `accounts`, `storage`, and `topics` FCMs to disk. 

We do not have any automated validation that these dumps happen. 

But it would be fairly straightforward to build a CircleCI workflow that:
1. Starts a 4-node network from spot nodes.
2. Runs some transactions.
3. Runs a `sudo postgres` on one of the nodes to delete a row from the `fcfs` table.
4. Scans that all the nodes have the expected _*.fcm_ dumps and log statements.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
