### ISSUE TITLE
Create ERC-1155 replay test assets for modularized `ContractService`

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#6115]
### Problem

The first step in modularizing `ContractService` is, naturally, to ensure the Hedera-agnostic parts of the service operate as expected.

Standard ERC-1155 contracts are a good starting point for such testing, as they exercise a wide variety of contract state changes and internal function calls; but do not bring in external calls (and clearly not Hedera-specific system contracts).

But we do not have an appropriate EET client creating and exercising standard ERC-1155 contracts; nor appropriate "recording" versions of every facility used by the `ContractService`. (So far `replay-develop` only includes recording facilities needed for the `ConsensusService`.)

Furthermore, `replay-develop` does not automatically assert the correctness of contract state at the end of a replay test.

### Solution

- [x] #6118
- [x] #6119
- [x] #6120

**Comment by netopyr** [comment]
Outdated
