### ISSUE TITLE
replace use of 0.38 deprecated methods

### ISSUE THREAD

**Issue by kimbor** [hashgraph/hedera-services#6130]
Platform v0.38 marked a number of methods as deprecated. Need to update services to no longer use those methods.

**Comment by kimbor** [comment]
To see list of places that deprecated methods are used in IntelliJ:
Code -> Analyze Code -> Run Inspection by Name
Search for 'Deprecated API Usage'

626 found!

**Comment by jsync-swirlds** [comment]
Note, this is not "fix all 626" deprecated items, it is only to replace the methods from platform that are properly deprecated and have alternatives documented.
