### ISSUE TITLE
It is preferred to use Objects.requireNonNull to for null checks. 

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#6139]
`CommonUtils.throwArgNull` and `ArgumentUtils.throwArgBlank` both do the same activity as `Objects.requireNonNull`.   From recent conversations the coding standard has converged on using `Objects.requireNonNull` as the preferred method for performing null checks to back the `@NonNull` attribute. 

[conversation 1](https://swirldslabs.slack.com/archives/C04RFBCCP8B/p1681139457284359)
[conversation 2](https://swirldslabs.slack.com/archives/C03DU0QGE2G/p1681242564890119)
[Decision/Outcome](https://www.notion.so/swirldslabs/007-Java-Code-Style-a0130a7059b044f68447b9ca3a5242b3?pvs=4#fadddb0f9c974f06a8fecccff951eb96)

`CommonUtils.throwArgNull` and `ArgumentUtils.throwArgBlank` should be deprecated and direct people to use `Objects.requireNonNull`.

**Comment by hendrikebbers** [comment]
Let's double check if `CommonUtils.throwArgNull` and `ArgumentUtils.throwArgBlank` is not used anymore and is removed. In that case the issue can be closed

**Comment by mxtartaglia-sl** [comment]
In https://github.com/hashgraph/hedera-services/pull/10433 we removed all uses of `CommonUtils.throwArgNull`  and removed the method.  
All uses of `CommonUtils.throwArgBlank` were changed to `ArgumentUtils.throwArgBlank`, and `CommonUtils.throwArgBlank` was removed.
There are still 12 classes in the codebase that use `ArgumentUtils.throwArgBlank`; changing those for `Objects.requireNonNull` would change the validation functionality as we would be removing the check for blank values.

I can't find in the attached discussions where this specific change is discussed.
I imagine that the functionality change is expected but could you please confirm @edward-swirldslabs.
Thanks!

**Comment by edward-swirldslabs** [comment]
I'm not sure why I thought `throwArgBlank` could be replaced by `Objects.requireNonNull`.    The check that a string is not all white space is not something that a check for nonNull can cover.    At this point I would have to relax my request and just standardize the null check on Objects.RequireNonNull.     There doesn't seem to be a standard library function that throws an exception if a `string.isBlank()` is true.

**Comment by mxtartaglia-sl** [comment]
Fixed with: https://github.com/hashgraph/hedera-services/pull/10433
