### ISSUE TITLE
HTS name and symbol field should not be unique

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-services#614]
**Summary of the defect**
Current requirement stipulates that name and symbol for a token type entity must be unique from all other entities. This is to track change of requirement for discussion to no longer require uniqueness.

Reasoning:
- Consistency with other token issuance standards (ERC)
- Exclusivity could cause land grab of token names and symbols
- Entity ID can still be used for uniqueness, and would be consistent with other services.

**Comment by Daniel-K-Ivanov** [comment]
The issue should be resolved by the #620 PR
