### ISSUE TITLE
Make stores of other services available via PreHandleContext

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#6178]
- Add `ReadableStores` that allows to create any kind of store. (First version will be hard-coded.)
- Integrate `ReadableStores` in `PreHandleContext` and `QueryContext`.
- Make `TransactionHandler.preHandle()` expect only the context.

**Comment by nickpoorman** [comment]
@netopyr Will this allow one service to call another service? For example, [Freeze Service - freezeUpgrade](https://github.com/hashgraph/hedera-services/issues/6197) needs to be able to call [Network Service - getFileContent](https://github.com/hashgraph/hedera-services/issues/6154) to get the upgrade file.

**Comment by netopyr** [comment]
This issues will build the base and integrate it with the pre-handle and query workflow only. We are just starting to re-design the handle workflow, therefore it is too early to do any modifications right now.
