### ISSUE TITLE
uncheckedSubmit - NetworkAdminService

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#6186]

**Comment by povolev15** [comment]
Question: I'm not sure how we are supposed to implement uncheckedSubmit as I understand all behaviour needs to be implemented in handle workflow to handle unchecked/pre-checked transactions

**Comment by nickpoorman** [comment]
We have decided to remove this and not have it in the modularized code paths.

**Comment by nickpoorman** [comment]
@povolev15 I will leave it up to you to close this once you have done so and addressed the failing tests as a result of removing it.
