### ISSUE TITLE
Freeze Service - telemetryUpgrade

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#6198]
Extract upgrade file. To do this we need to get the file from specialFileStore in File Service callable from Freeze Service. Depends on: https://github.com/hashgraph/hedera-services/issues/6178
 
- [x] Implement zip file extract
- [x] Write tests

Implemented in #6225

**Comment by kimbor** [comment]
Implemented in PR #6225, but implementation will need modification once PR #6178 is merged.
