### ISSUE TITLE
Verify behaviour of code producing preceding child records

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#6203]
For the case of hollow account finalization:
- We create successful preceding child records even if the top-level transaction fails
- The created preceding child records have empty `parent_consensus_timestamp` and non-zero `nonce` field

Verify that we have the same behaviour for the other cases in which we produce preceding child records, namely for:
- Migrations
- Staking calculations (done every day at 12:00 UTC)

**Comment by agadzhalov** [comment]
Detailed explanation of the verification can be found [here](https://limechain.notion.site/Verify-behaviour-of-code-producing-preceding-child-records-248a12ec1a194834bfea2fc37dff29ab)
