### ISSUE TITLE
Use staking info from UTC Midnight

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#6204]
For better predictability, it is preferable for the consensus weight specified at upgrade time (via `SwirldState.updateWeight()`) to be set using the staking information UTC midnight, as opposed to staking information in the freeze round.

Every UTC at midnight, using the snapshot of stake for rewards, compute the node weights and log what the address book would look like with the computed weights.   The logged midnight address book would be useful for debug and sanity check prior to upgrade to see what the node weights will be ahead of time.

This issue is taking over for #5487, and should include normalization of stake to appropriate proportionate weight values on the nodes. 

Export the weight updated to mirror node using `NodeStakeUpdate` synthetic transaction, using `NodeStake.stake` field

To calculate weights the following algorithm is followed:
If the stake of the node is below minimum stake, then its weight is zero.
If the stake is equals or greater than minimum stake, then its weight is computed as 
```
Math.max(Math.floor((# of whole hbars staked by A) * 500 / (total # of whole hbars staked)), 1)
```

**Comment by Neeharika-Sompalli** [comment]
As per the latest update from @steven-sheehy and @nickpoorman , the stake values exported to mirror node will be scaled up  from the consensus weight. 

We use the following method to scale up the values. Where
1. final int weight = weight calculated from teh stake value.
2. final long minStake = min stake set on the node  
3. final long maxStakeOfAllNodes = maximum stake of all nodes
4.  final long totalStakeOfAllNodes = total stake of all nodes

```
long scaleUpWeightToStake(
            final int weight, final long minStake, final long maxStakeOfAllNodes, final long totalStakeOfAllNodes) {
        final var zeroStake = 0;
        final var newMin = minStake;
        final var newMax = maxStakeOfAllNodes;
        // If zero stake return zero
        if (weight == zeroStake) {
            return zeroStake;
        } else {
            // This should never happen, but if it does, return zero
            if (totalStakeOfAllNodes == 0) {
                return 0;
            }
            final var oldMinWeight = 1;
            // Since we are calculating weights based on the real stake values, we need to consider
            // the real max Stake and not theoretical max stake of nodes.
            // Otherwise, on a one node network with a stake < maxStake where we assign a weight of 500,
            // the scaled stake value will be greater than its real stake.
            final var oldMaxWeight = BigInteger.valueOf(maxStakeOfAllNodes)
                    .multiply(BigInteger.valueOf(500))
                    .divide(BigInteger.valueOf(totalStakeOfAllNodes))
                    .longValue();
            // Otherwise compute the interpolation of the weight in the range [minStake, maxStake]
            return BigInteger.valueOf(newMax)
                    .subtract(BigInteger.valueOf(newMin))
                    .multiply(BigInteger.valueOf(weight - oldMinWeight))
                    .divide(BigInteger.valueOf(oldMaxWeight - oldMinWeight))
                    .add(BigInteger.valueOf(newMin))
                    .longValue();
```
