### ISSUE TITLE
Add node weights to record stream for mirror node. 

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#6218]
This was removed from #6204 since it would require a HIP to complete. 

It would be beneficial node weights were made available in the record stream, so that eventually it can be reflected in the mirror node. 

Node stake is translated to node weight for use in consensus.  Making the node weights available provides transparency about how consensus is affected when nodes are down.

**Comment by Neeharika-Sompalli** [comment]
The weight will be updated in the `NodeStake.stake` field that already exists. So, no HIP will be needed for this change.
