### ISSUE TITLE
Constant `AutoCreationLogic.THREE_MONTHS_IN_SECONDS` should be moved to `GlobalDynamicProperties` and given a proper name

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#6261]
`com.hedera.node.app.service.mono.txns.crypto.AutoCreationLogic.THREE_MONTHS_IN_SECONDS` is a constant - with the obvious value - that is imported from here into a couple of locations.  It should be given a proper name that reflects the Hedera _semantics_ of its _uses_ (e.g., "default auto renew period") and moved to `GlobalDynamicProperties` (or some other appropriate place).

**Comment by david-bakin-sl** [comment]
a) Should probably be called `NINETY_DAYS_IN_SECONDS` as `THREE_MONTHS_IN_SECONDS` could be 90 or 91 days.
b) Now appears in 5 separate locations.

**Comment by tinker-michaelj** [comment]
Obsolete.
