### ISSUE TITLE
Reduce fee for token allowances

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-services#6276]
### Problem

[v0.36.0](https://github.com/hashgraph/hedera-services/releases/tag/v0.36.0) requires all contracts to be approved before they can spend from an EOA.

This will make token allowance transactions far more frequent. The current price of a token allowance transaction is about $0.05, whereas a token transfer costs about 50x less at $0.001.

On Ethereum, the gas cost for an ERC20 transfer is about equal to that of an ERC20 approval. Therefore for relative consistency in pricing with Ethereum the token allowance transaction should be priced similarly to the token transfer transaction. I suggest an allowance transaction should cost no more than 5x the cost of a token transfer.

### Solution

Investigate why the cost of an allowance transaction is so much more than that of a transfer transaction and determine a feasible reduction in price.

**Comment by netopyr** [comment]
Fee costs are outside the scope of this project, as they are determined by the governing council.
