### ISSUE TITLE
Clean up SignedState methods

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#6282]
There are a bunch of "convenience" methods in `SignedState.java` that clutter things up. For example,

```
    /**
     * Get the timestamp of the last transaction added to this state.
     *
     * @return the timestamp of the last transaction added to this state
     */
    public @NonNull Instant getLastTransactionTimestamp() {
        return state.getPlatformState().getPlatformData().getLastTransactionTimestamp();
    }
```

Most of these convenience methods only have one or two uses across the entire code base. IMO, it's better to just call into the data structure directly than to try and maintain these sorts of getter methods.

**Comment by poulok** [comment]
I'm not sure I agree with this. Long chained calls should be hidden from callers outside of the class. A `SignedState` should be able to answer the question, "What is your last transaction timestamp?" without requiring the caller to know the details of how that data is stored.
