### ISSUE TITLE
High latency and inconsistent interval between record stream files

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-services#631]
**Summary of the defect**
Running tests in perfnet at a high TPS with a system account exhibits increased latency and inconsistent interval between record files. Inconsistent interval meaning if the file is set to write every 2s we may actually not see it for much higher periods of time. This usually occurs after longer duration of time though can occur quicker if ever higher TPS.

A test in testnet also reproduced the problem:
![Screen Shot 2020-09-28 at 15 11 56](https://user-images.githubusercontent.com/17552371/94621184-7c9c9d80-0275-11eb-96cc-456da3785abd.png)

**How to reproduce (if possible)**
Run a performance test at 2500+ TPS and 256B HCS messages for 30 minutes.

**Service logs (if applicable)**

**Environment:**
- OS: MacOS
- Java: OpenJDK 11
- Hedera Services Version: 0.8.0
- HAPI Version: 0.8.0

**Additional Context**

**Comment by noshmody** [comment]
Hi @steven-sheehy, would you mind closing this issue, having been resolved in 0.8.1?

I also posted a response for the [record stream interval variations in slack](https://hedera-hashgraph.slack.com/archives/GKKFCDCE5/p1602088076055500)....

The explanation for separation in the record stream files…
@Steven Sheehy, when the network is running at or very near capacity the following sequence occurs…
HandleTransactions takes longer than the 100micro sec budget
Various queues (specifically q2) get max’ed out
In the platform the back-pressure mechanism stops accepting transactions and stops creating events…
When handling transaction catches up and queues get less full - events start getting created
This results in a gap the consensus timestamp of events (and transactions)
This then results in a gap in the record stream….
The  solutions are is to run  below capacity
where platform back-pressure (queues no longer full) does not engage OR
reduce time in handle transaction (which is something we are working on)

**Comment by steven-sheehy** [comment]
Confirm this is fixed in 0.8.1
