### ISSUE TITLE
Create a `RoundMetadata` singleton to let ingest and query workflows avoid `getLatestSignedState()`

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#6350]
### Problem

There are several places we call `Platform.getLatestImmutableState()`:
 1. In `StructuralPrecheck` [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/submission/StructuralPrecheck.java#L101) (indirectly via [`SignedStateViewFactory.latestSignedStateView()`](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/primitives/SignedStateViewFactory.java#L84)).
 2. In [`StaticBlockMetaProvider.getSource()`](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/StaticBlockMetaProvider.java#L34), which is called twice while answering a `ContractCallLocal` query.
 3. In [`SpanMapManager.expandEthereumSpan()`](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/span/SpanMapManager.java#L151) during pre-handle of an `EthereumTransaction`.

But of these, only (3) has a legitimate need for the entire state, since it does need access to an arbitrary calldata file. (1) and (2), on the other hand, only need the consensus time and block number from the state (one `Instant` and one `long`).

### Solution

- [ ] Add a `RoundMetadata` in `@Singleton` scope that, at first, amounts to an `AtomicReference<Pair<Instant, Long>>` with last-handled consensus time and current block number.
- [ ] At the end of `handleConsensusRound()`, set these two values atomically based on the mutable `MerkleNetworkContext` resulting from handling the round.
- [ ] Update (1) and (2) to get the needed information from `RoundMetadata` instead of `Platform.getLatestImmutableState()`.

**Comment by nickpoorman** [comment]
Probably about a days worth of work for one engineer.

**Comment by netopyr** [comment]
@tinker-michaelj Can we close this issue?
