### ISSUE TITLE
Add `pureChecks` and `validateSemantics` methods for TokenAssociateToAccountHandler

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#6353]
- [ ] Add `pureChecks` method in `pre-handle` containing checks from `TokenAssociateTransitionLogic`  that validates `TransactionBody` without involving dynamic properties or State. 
- [ ] Add `validateSemantics` method as first step in `handle` containing checks from `TokenAssociateTransitionLogic`  that validates `TransactionBody` involving dynamic properties or State.

**Comment by mhess-swl** [comment]
Implemented with #6388

**Comment by mhess-swl** [comment]
Finished in #6388
