### ISSUE TITLE
Add `pureChecks` and `validateSemantics` implementations for TokenBurnHandler

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#6354]
- [ ] Add `pureChecks` method in `pre-handle` containing checks from `TokenBurnTransitionLogic`  that validates `TransactionBody` without involving dynamic properties or State. 
- [ ] Add `validateSemantics` method as first step in `handle` containing checks from `TokenBurnTransitionLogic`  that validates `TransactionBody` involving dynamic properties or State.

**Comment by mhess-swl** [comment]
Closed with PR #7058
