### ISSUE TITLE
Add `pureChecks` and `validateSemantics` implementations  for TokenDeleteHandler

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#6356]
- [ ] Add `pureChecks` method in `pre-handle` containing checks from `TokenDeleteTransitionLogic`  that validates `TransactionBody` without involving dynamic properties or State. 
- [ ] Add `validateSemantics` method as first step in `handle` containing checks from `TokenDeleteTransitionLogic`  that validates `TransactionBody`  involving dynamic properties or State.

**Comment by mhess-swl** [comment]
Finished with #6979
