### ISSUE TITLE
Add `pureChecks` and `validateSemantics` implementations  for TokenFreezeAccountHandler

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#6359]
- [ ] Add `pureChecks` method in `pre-handle` containing checks from `TokenFreezeTransitionLogic`  that validates `TransactionBody` without involving dynamic properties or State. 
- [ ] Add `validateSemantics` method as first step in `handle` containing checks from `TokenFreezeTransitionLogic`  that validates `TransactionBody` without involving dynamic properties or State.

**Comment by mhess-swl** [comment]
Implemented in #6116
