### ISSUE TITLE
Add `pureChecks` and `validateSemantics` implementations for TokenGrantKycToAccountHandler

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#6360]
- [ ] Add `pureChecks` method in `pre-handle` containing checks from `TokenGrantKycTransitionLogic`  that validates `TransactionBody` without involving dynamic properties or State. 
- [ ] Add `validateSemantics` method as first step in `handle` containing checks from `TokenGrantKycTransitionLogic`  that validates `TransactionBody`  involving dynamic properties or State.

**Comment by mhess-swl** [comment]
Done with #5905
