### ISSUE TITLE
Add `pureChecks` and `validateSemantics` implementations for TokenUnfreezeAccountHandler

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#6364]
- [ ] Add `pureChecks` method in `pre-handle` containing checks from `TokenUnfreezeTransitionLogic`  that validates `TransactionBody` without involving dynamic properties or State. 
- [ ] Add `validateSemantics` method as first step in `handle` containing checks from `TokenUnfreezeTransitionLogic`  that validates `TransactionBody` without involving dynamic properties or State.

**Comment by mhess-swl** [comment]
Implemented with #6117
