### ISSUE TITLE
Need to know if Token Relationship exists for a Contract

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-services#646]
**Summary**
As a Hedera Services client, I need to know if a contract is associated with a token so that I can associate a token with the contract if I need to.

**Possible resolution**

Add Token Relationships (such as seen CryptoGetInfo)

https://github.com/hashgraph/hedera-services/blob/ab15b18bb8a5e447cde3ef079415740491986782/hapi-proto/src/main/proto/CryptoGetInfo.proto#L61

to the Crypto Get Info Response:

https://github.com/hashgraph/hedera-services/blob/ab15b18bb8a5e447cde3ef079415740491986782/hapi-proto/src/main/proto/ContractGetInfo.proto#L41

**Comment by tinker-michaelj** [comment]
Based on the logic in #699, smart contracts will no longer be allowed to form token relationships.
