### ISSUE TITLE
Run NFT / Crypto transfer end-to-end benchmarks against a network with simulated node reconnects

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/hedera-services#6488]
We use a number of end-to-end benchmarks to simulate client requests and check performance numbers. The benchmarks work very well, but usually the results are reported, when the backend (a single node or, more interesting, a network) is stable. This task is to run the benchmarks against a network, where nodes periodically fall behind and need to reconnect. It would let estimate reconnect impact on TPS and stability.

There may be additional changes needed to benchmark code to handle backend issues. For example, be ready for nodes to be inaccessible for some periods because of reconnects. Once benchmarks are changed to handle these cases, they should be scheduled to run periodically as a part of release process, but it can be tracked in a different ticket.

**Comment by poulok** [comment]
Consider testing this using a 7 node performance network.

**Comment by OlegMazurov** [comment]
Further analysis and development is covered by #9426
