### ISSUE TITLE
Extend software version to include a settings version

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#6503]
Settings should have an alphanumeric version number. The services SoftwareVersion should be extended to include the settings version number. When printed, the settings version should come at the end of the software version string to preserve alphanumeric ordering. 

**Rationale:**
* In order to adopt AddressBook value changes in config.txt, we need to bump the software version number.   In order to not create a new software deliverable (jars/containers) for config only changes, we should introduce an alphanumeric version number set in the settings file and extend the SoftwareVersion used by services with the settings version. This would allow a config-only update to the software version to trigger the adoption of the AddressBook in config.txt.   NOTE: This will cause the platform to query the Hedera App for consensus weights.

**Comment by Neeharika-Sompalli** [comment]
@edward-swirldslabs Could you please elaborate, what do you mean by settings version? Is it the protobuf version ?
Also, why do we need the settings version and not rely only on version based on the tag?

**Comment by edward-swirldslabs** [comment]
The settings.txt file should have a new version field for giving an alpha numeric label to the settings that are being used.  This should contribute to `SoftwareVersion` that `Hedera.java` returns.  Looking through the code, taking a guess, I think the `SemanticVersion` and `SerializableSemVers` would need to be extended to handle the added configuration version in the settings.txt file.  

The addition of this is to allow DevOps to bump the software version and trigger a config.txt update to the AddressBook through the `AddressBookInitializer`
