### ISSUE TITLE
Broken legacy configuraiton

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#6528]
This PR removed a bunch of legacy configuration values: https://github.com/hashgraph/hedera-services/pull/6110

At least one of these values is still being used: `genesisFreezeTime`

```
final long genesisFreezeTime = configuration.getValue("genesisFreezeTime", Long.class, 0L);
```

☝️ This is actually a horrible little line of code! I'm guessing the dependency on this old setting was not noticed because we were using a magic string (as opposed to using a configuration record).

This is causing an issue in some of our restart tests: https://github.com/swirlds/swirlds-platform-regression/issues/3410

My suggestion to fix this would be to

1) add a new entry to `BasicConfig.java`
2) refactor the code so that it uses the configuration record instead of using a magic string
3) run this restart test and validate that it passes

**Comment by poulok** [comment]
@timo0, reminder to add some points to this ticket
