### ISSUE TITLE
EVM version update and optimizations

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#6560]
### Problem

This epic will track the effort of updating the EVM interaction with Hedera System Accounts.

### Solution

The following must be achived:

- [ ] blocking transfers to 0.0.1 → 0.0.750 through the HTS precompile
- [ ] Refactor the newly created (v0.38) classes
- [ ] Create a test plan

**Comment by Kalina-Todorova** [comment]
Part 1 - blocking transfers to 0.0.1 → 0.0.750 through the HTS precompile: https://github.com/hashgraph/hedera-services/pull/6985

**Comment by stoqnkpL** [comment]
Michael is working on refactoring the newly created classes here: https://github.com/hashgraph/hedera-services/pull/7000
