### ISSUE TITLE
EventStreamPathIterator potentially remove boundcheck for base case in search

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#6572]
There may be a boundary error here.  The `firstEvent` is from the first file.  If the bound is a round that is not 1, is it possible that the files prior to this file, which do not exist, may contain events from the same round?    Is the proper behavior to error with not finding the round?    

One valid case is searching for round 1 and the files start with round 1.   Removing this check will cause failure to find round 1.  

```
        if (bound == UNBOUNDED || bound.compareTo(firstEvent) == 0) {
            // We are attempting to get events from the beginning of the event stream.
            iterator = eventStreamFiles.iterator();
        } else {
```

This issue came out of a [lengthy discussion](https://github.com/hashgraph/hedera-services/pull/6346#discussion_r1191610094) on this PR: https://github.com/hashgraph/hedera-services/pull/6346

**Comment by poulok** [comment]
Consensus event stream is stable and will be replaced in the future.

**Comment by edward-swirldslabs** [comment]
The world hasn't ended in the last 6 months.  Perhaps this issue / concern wasn't relevant.  Since I created the issue, I'm going to proactively close it.
