### ISSUE TITLE
Resolve performance issues with Sync as Protocol

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#6596]

**Comment by alittley** [comment]
Seemingly related to https://github.com/hashgraph/hedera-services/pull/6626 and https://github.com/hashgraph/hedera-services/issues/6627

**Comment by alittley** [comment]
Network health appears good with the above issues fixed.

**Comment by alittley** [comment]
The issues linked above fixed the issue that was being observed, but it is still unclear whether all performance issues have been resolved

**Comment by alittley** [comment]
I'm not aware of any remaining issues.
