### ISSUE TITLE
Fix failed EET with INSUFFICIENT_TX_FEE expectation

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#66]
Genesis (account 2) was changed to be free of charge on any transactions/queries. We need to switch to using another account (by creating one) to pay for those requests.

**Comment by qnswirlds** [comment]
We did many changes and refactoring to the EET framework. We also added a lot more EET. We are now monitoring our product via CI for functionalities and via a Slack channel/dashboard for regressions. Closing this issue.
