### ISSUE TITLE
Add/create EET scenarios to test KEY_PREFIX_MISMATCH and INVALID_SIGNATURE_COUNT_MISMATCHING_KEY errors

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#661]
This may need to enhance EET framework to force test clients to generate those key/signature combinations that are not correct. 

This is a follow up issue for #604

**Comment by qnswirlds** [comment]
These are for both crypto and files.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
