### ISSUE TITLE
Fix a `catch` of `Exception` when handling precompile inputs to be more specific

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#6621]
See [this location where `Exception` is caught](https://github.com/hashgraph/hedera-services/blob/19ab4e1fb2b8915c7b21839613e330ccdd8b4b83/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java#L839) and then fails the contract (ultimately).  Failing the contract is correct, but catching `Exception` is broad and may be masking some other error that we'd like to know about (and fix).

```java
    void decodeInput(final Bytes input, final UnaryOperator<byte[]> aliasResolver) {
        this.transactionBody = TransactionBody.newBuilder();
        try {
            this.transactionBody = this.precompile.body(input, aliasResolver);
        } catch (final Exception e) {
            transactionBody = null;
        }
    }
```

Should be replaced by a more specific catch against the input decoding failures we actually expect, and then log something (as some low level) if not.

**Comment by lukelee-sl** [comment]
mono service. no longer applies
