### ISSUE TITLE
Automate the Platform version update and verify the service build is compiling.

### ISSUE THREAD

**Issue by povolev15** [hashgraph/hedera-services#6664]
Issue:  Most of the time when the platform creates a new version for their build and we update it manually in our kts file it is breaking some of the code.

Suggestion: automate it

1. Generate a new platform build.
2. Update the version in the service kts file
3. run ./gradlew clean build
4. if everything is passing commit it if not send an email with a file that includes a stack trace.

**Comment by nathanklick** [comment]
This is unnecessary and will be handled by the merging of the gradle builds which @jjohannes is actively working on.

**Comment by nathanklick** [comment]
Additionally, these version changes should be made and submitted as a PR which automatically builds the code and reports a failure to the author by email (if they have notifications enabled). 

I do not see why yet another automated process is required.

**Comment by nickpoorman** [comment]
That's wonderful news @nathanklick! Thanks for the update.

**Comment by povolev15** [comment]
Thank you @nathanklick

**Comment by mhess-swl** [comment]
Done via unification of the platform and services repo
