### ISSUE TITLE
Use the injected ledger ID to implement the `ConsensusGetTopicInfo` query

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#6749]
This depends on implementing `queryContext.getConfiguration()` from @hendrikebbers (#6750, #6642)

**Comment by mhess-swl** [comment]
Use `preHandleContext.getConfiguration().getConfigData(LedgerConfig.class)`

**Comment by mhess-swl** [comment]
Use `queryContext.getConfiguration().getConfigData(LedgerConfig.class)`

**Comment by mhess-swl** [comment]
@iwsimon is PR #6643 what was needed for the byte configuration?

**Comment by iwsimon** [comment]
> @iwsimon is PR #6643 what was needed for the byte configuration?

yes @mhess-swl

**Comment by nickpoorman** [comment]
Is this still blocked? @mhess-swl @iwsimon

**Comment by iwsimon** [comment]
> Is this still blocked? @mhess-swl @iwsimon

No block.
