### ISSUE TITLE
Implement `QueryContext.getConfiguration()` and convert to byte array

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#6750]
We need an implementation of the `QueryContext.getConfiguration()` call in order to implement the `ConsensusTopicGetInfo` query as discussed in our modularization call circa 22 May 2023.

Other queries also depend on this implementation.

**Comment by netopyr** [comment]
@mhess-swl Can we close this issue?

**Comment by mhess-swl** [comment]
It looks like `QueryContext.configuration()` is implemented in `QueryContextImpl`. It seems we can close this
