### ISSUE TITLE
busyTimeMetricTest() flake

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#6792]
I observed the following test flake on a branch of mine:

```
     ✘ busyTimeMetricTest() Test

      org.opentest4j.AssertionFailedError: 
      expected: 0.5
       but was: 1.0
          at app//com.swirlds.common.test.threading.QueueThreadTests.busyTimeMetricTest(QueueThreadTests.java:927)
```

https://github.com/hashgraph/hedera-services/actions/runs/5080743539/jobs/9128131550?pr=6705

**Comment by lpetrovic05** [comment]
It seems that the only way to ensure the timing of this test is to create a custom queue. That way we can control what the thread is doing
