### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#681]
- Add child module `hapi-fees`
- Add `Troubleshooting/FAQ` section:
-- Show how to build the whole project or build each child module individually
-- Show how to do a complete rebuild by cleaning up `hedera-node/data/lib/*`, `test-clients/target/extLib/*`, or even `~/.m2`

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
