### ISSUE TITLE
Don't save states during PCES replay

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#6874]
If we cross a state saving boundary during PCES replay, don't bother saving the state.

A node replaying from the PCES is quite likely to be under high load, and quite likely in danger of falling behind and needing to reconnect. If the node crashes again, it can always replay from the stream again, and so we are in no danger of losing data by not saving the state snapshot.

**Comment by poulok** [comment]
@cody-littley can this be closed?
