### ISSUE TITLE
When test net has more than 7 nodes, the hedera services can't start correctly from saved state

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#691]
**Summary of the defect**
When there are more than 7 nodes in the test network, hedera services can't come to ACTIVE status on all nodes.

**How to reproduce (if possible)**
Please refer to this: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1603243074302600
and this: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1603242220302100

**Service logs (if applicable)**

 Please refer to above slack links.

**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
The test config file needs to start from saved state. Please refer to the following test config files:

AWS-Services-Weekly-Perf-StartFromState-15N-15C.json

and: 
CryptoTransfer-Perf-FromState-10k-240m.json

```
{
	"name": "CryptoTransfer-Perf-FromState-10k-240m.json",
	"description": "CryptoTransferLoadTest-Performance-StartFromState-JRS",
	"duration": 14420,
	"settings": [
		{
			"name": "showInternalStats",
			"value": "1"
		},
		{
			"name": "csvFileName",
			"value": "ServicesStats"
		},
		{
			"name": "csvAppend",
			"value": "true"
		},
		{
			"name": "maxOutgoingSyncs",
			"value": "2"
		},
		{
			"name": "freezeSettings.active",
			"value": "0"
		},
		{
			"name": "maxEventQueueForCons",
			"value": "10000"
		}
	],
	"hederaServicesConfig": {
		"ciPropsMap" : "tps=23,mins=240,threads=30",
		"testSuites": [
			"CryptoTransferLoadTest"
		]
	},
	"defaultFilesConfig": {
		"appType": "SERVICES"
	},
	"runConfig":{
		"type": "HEDERA_SERVICE"
	},
	"memoryLeakCheckConfig": {
		"nodeGroupIdentifier": "FIRST"
	},
    // NOTE: when there are more than 7 nodes in the network, hedera services can't start from saved state.

	"startSavedState": {
		//s3 bucket is in platform AWS account
	    "location": "s3://services-regression-jrs-files/StartFromSavedState/11842097-v0.8.0-rc-1-With-Eng-TreasuryKey/11846140/",
		"mainClass": "com.hedera.services.ServicesMain",
		"swirldName": "123",
	    "round": 11846140,
		"restoreDb": true,
		"nodeIdentifier": "ALL"
	},
	"app": {
		"jar": "HederaNode.jar"
	},
	"resultFiles": [
		"swirlds.log"
	],
	"validator": [
		"STATS",
		"HEDERA_NODE",
		"HAPI_CLIENT",
		"HGCAA"
	]
}


```

**Comment by Neeharika-Sompalli** [comment]
@ljianghedera The problem happened to me once. In my case it was because of network issue. When the test is re-ran it worked.
But @JeffreyDallas  faced this issue once when there was `AddressBook` size mismatch

**Comment by ljianghedera** [comment]
Closed by https://github.com/hashgraph/hedera-services/pull/713. 
Essentially, we need to have a saved state file from a 15-node network to make this work.
