### ISSUE TITLE
Preconsensus event stream recovery

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#6947]
We currently have the capability of replaying transactions from the consensus event stream. It would be nice if we had the option of also replaying transactions from the preconsensus event stream.

If there is a special setting set to true, then do the following workflow

1) construct the platform like normal
2) replay the preconsensus event stream
3) when finished writing the preconsensus event stream, save the latest state to disk and block until complete
4) exit the JVM

The effort required to support this workflow is small.

**Comment by poulok** [comment]
This has been completed
