### ISSUE TITLE
ContractFunctionParameter uint256 not taking input of decimal more than 20

### ISSUE THREAD

**Issue by 0xAnon0602** [hashgraph/hedera-services#6975]
### Description

I am using hedera SDK to write a function of already deployed Contract function which takes two uint256 parameter as input .

When I am calling the function using below code 
![image](https://github.com/hashgraph/hedera-services/assets/71931823/1ff4c91d-bf71-46e5-800b-987219cce198)

I am getting this error 
![image](https://github.com/hashgraph/hedera-services/assets/71931823/c6e4c4d5-40f5-400b-a943-e17ad4f16259)
![image](https://github.com/hashgraph/hedera-services/assets/71931823/05188284-98a7-4745-906b-af420462aa3e)

It works fine if the contract parameter input is limited till 20 decimal but it doesn't work for more than 20.

### Steps to reproduce

To produce this error you can call any contract function using hedera-sdk which takes input as uint256 and give it value more than 20 decimal places 

### Hedera network

mainnet, testnet, previewnet

### Version

2.18.1

### Operating system

macOS

**Comment by tinker-michaelj** [comment]
Hi @0xAnon0602, thanks for the issue. I believe the [JavaScript SDK ](https://github.com/hashgraph/hedera-sdk-js) repo is the best place to get this addressed.

Would you mind opening our issue there and closing this one?

**Comment by 0xAnon0602** [comment]
Done thanks 

https://github.com/hashgraph/hedera-sdk-js/issues/1640
