### ISSUE TITLE
StdoutValidator should not treat NO_ERROR as an error

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/hedera-services#6983]
After recent changes to `System.exit()` calls, the following messages can be found in stdout/stderr:

```
Exiting System (NO_ERROR)
java exit code 0\n
```

They seem to make `StdoutValidator` fail, and the whole JRS run is reported as failed. The validator should be improved to ignore these kinds of messages and not treat them as errors.

**Comment by JeffreyDallas** [comment]
Already resolved in regression validator
