### ISSUE TITLE
Owner Account Unable to Remove Allowance after Spender Account Deleted

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-services#7018]
### Description

If **Owner** account creates an allowance for **Spender** account for a fungible token and then the **Spender** account is deleted the **Owner** account cannot remove the **Spender**'s allowance.  The attempt returns INVALID_ALLOWANCE_SPENDER_ID.

### Steps to reproduce

1. **Owner** account creates an allowance for **Spender**
2. **Spender** account is deleted. (Note: this does not delete the allowance)
3. **Owner** account attempts to remove allowance by setting amount to 0
4. The attempt fails and the network returns `INVALID_ALLOWANCE_SPENDER_ID`

The _Expected_ behavior would be one of two things:

1. The allowance that was designated by **Owner** would be removed when **Spender** account was deleted (preferred)
2. The **Owner** account would be able to remove the **Spender** allowance without error.

### Hedera network

testnet, previewnet

### Version

.net SDK 10.0.0 beta 7

### Operating system

Windows

**Comment by nickpoorman** [comment]
That's for filing this @bugbytesinc. I'm looking into it.
