### ISSUE TITLE
Subsume TokenTransfer into CryptoTransfer

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#703]
**Summary of the defect**
There is no reason to add a new operation for token transfers.

We should simply extend the existing `CryptoTransfer` operation with `TokenTransferList` fields.

```
message CryptoTransferTransactionBody {
    TransferList transfers = 1; 
    repeated TokenTransferList tokenTransfers = 2;
}
```

**Comment by gregscullard** [comment]
Looks good to me.
