### ISSUE TITLE
Reconnect with update testing scenarios

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#709]
Alice, Bob, Carol, Dave, etc are nodes in the network.

### Scenario A 
> Network is at v0.X.0 
> Update file 0.0.150 with zip for v0.Y.0.
> Alice disconnects from the network 
> Alice Reconnects (File 0.0.150 SHOULD NOT need to be sync'd)
> Alice participates in network
> Send Freeze Txn with 0.0.150
> Network (including Alice) should restart at v0.Y.0 
> 

### Scenario B
> Network is at v0.X.0 
> Alice disconnects from the network 
> Update file 0.0.150 with zip for v0.Y.0.
> Alice Reconnects (File 0.0.150 SHOULD need to be sync'd)
> Alice participates in network
> Send Freeze Txn with 0.0.150
> Network (including Alice) should restart at v0.Y.0 
> 

### Scenario C
> Network is at v0.X.0 
> Alice disconnects from the network 
> Update file 0.0.150 with zip for v0.Y.0.
> Send Freeze Txn with 0.0.150
> Network (NOT including Alice) should restart at v0.Y.0 
> Alice attempts to reconnect - **Reconnect should fail with version mismatch error** 
> Manually deploy software for v0.Y.0
> Manually deploy recent v0.Y.0 state from Bob or Carol
> Restart Alice
> Alice should reconnect successfully
> Alice participates in network

**Comment by JeffreyDallas** [comment]
In scenario A, if Alice disconnected after getting 0.0.150 new updated, why it need to sync it again after reconnect ?

**Comment by qnswirlds** [comment]
This issue is currently blocked by https://github.com/swirlds/swirlds-platform-regression/issues/709

**Comment by tinker-michaelj** [comment]
Done.
