### ISSUE TITLE
Create new docker images to capture all needed software components for services   

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#710]
**Summary**
We need to come up with a list of software components that are needed in services' AMI image to avoid installation on the fly during deployment. 

These list hopefully will be combined with platform's requirement and we will have a common core AMI image for all out needs.

**Possible resolution**
1. Go through services modules/packages/tests to gather all required components and their versions, if n to have a list for services' side needs.

**Services side software components/tools**
0. Ubuntu 18.04
1. Postgres: 10.9 
2. unzip
3. wget
4. zip
5. haveged
6. vim
7. python-psycopg2
8. libpq5
9. postgresql-client-10
10. postgresql-client-common
11. ssl-cert
12. Python: 3.7

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
