### ISSUE TITLE
Use TransactionID everywhere a Transaction is referenced in PBJ/Proto definition or State

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-services#7105]
EntityNum and Long/int64 are insufficient to correctly reference a Transaction because the bare number does not reference realm or shard, and this will prevent enabling sharding if not corrected.

**Comment by povolev15** [comment]
@jsync-swirlds @tinker-michaelj 
Can you raise it during the modularization call? I'm unsure if it exists. 
Do we need to covert it at all? or we can close this ticket
