### ISSUE TITLE
Update HIP's design doc

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#7126]

**Comment by Nana-EC** [comment]
@MiroslavGatsanoga which HIP was this for 729?

**Comment by MiroslavGatsanoga** [comment]
@Nana-EC It's for 729, we had [a PR open](https://github.com/hashgraph/hedera-services/pull/7331) (it was not linked to the issue, fixed now) but I think it got pushed down due to other tasks with higher priority.
