### ISSUE TITLE
(Startup code to) Create Entities below 0.0.1000 for system use - Files: 101 - 200, SmartContract: 201-300, HCS Topics: 401-500

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#72]
(Startup code to) Create Entities below for system use (if the entity does not exist)
- [ ] Files: 101 - 200 (Leaving existing system files unchanged)
- [ ] SmartContract: 201-300
- [ ] HCS Topics: 401-500

Use public keys currently applied to account 50

Reference #2043

**Comment by JeffreyDallas** [comment]
Close obsolete issue
