### ISSUE TITLE
Clean up `settings.txt` sync settings

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#7279]
Once `sync-as-protocol` feature has gone live and no problems are observed, the `settings.txt` files for *all environments* should be cleaned up in the following ways:

- remove the `maxOutgoingSyncs` values, since they aren't relevant with `sync-as-protocol` enabled
- remove the explicit setting of `sync.syncAsProtocolEnabled` to true, since it's true by default

**Comment by poulok** [comment]
This has been completed
