### ISSUE TITLE
Enhance Hedera services Circleci CI framework to use normal AWS instances if necessasry

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#73]
Right now hedera services' Circleci framework is implemented as the CI workflow only works on AWS spot instances. This can be an issue since spot instances are not guaranteed to be fulfilled. In the event of the COVID-19, we have couple days the spot resources are not available on different regions. This causes lots of slow down of our development work.

The goal is to enhance the framework to be easily switched to normal AWS instances if required.

**Comment by ljianghedera** [comment]
It's not necessary for GCP clouds any more. (Plus, this was done long time back for AWS).
