### ISSUE TITLE
Determine appropriate timeout for ingest signature verification

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#7301]
**Problem**

PR #7274 introduced a timeout during `IngestWorkflow` in the `IngestChecker#verifyPayerSignature` method. It is currently hardcoded to 1 second. This number is probably OK, normally, but maybe is too low. It doesn't make sense for the timeout to be longer than whatever the configured request timeout is, unless it would be interrupted by the grpc server once the timeout was exceeded (which I don't believe it is).

**Solution**

We should have a configuration value for this, or reuse the correct configuration value if it already exists.

**Comment by aramosIEU** [comment]
I'm looking into this issue

**Comment by aramosIEU** [comment]
`IngestChecker#verifyPayerSignature` method is already using a DefaultKeyVerifier which sets the timeout to the value specified by in "workflow.verificationTimeoutMS" config property defined in `HederaConfig.java`

**Comment by poulok** [comment]
@netopyr can this ticket be closed?

Thank you @aramosIEU for looking into this!
