### ISSUE TITLE
Integrate DualState in workflows

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#7349]
Make `ReadableFreezeStore` and `WritableFreezeStore` available in the factories. The current `dualState` needs to be passed to the factories for this.

**Comment by kimbor** [comment]
From Richard via Slack: 

> Maybe there is a simpler way. What if we deal with the freeze state exactly like we handle special files. The FreezeServiceImpl will manage the freeze state, like normal, separate from dual state. Then in the same way the HandleWorkflow (and genesis startup) have special handling for special files, HandleWorkflow (and startup) would copy values from dual state into the Freeze's writable store, or out of the Freeze's readable store into dual state, keeping them in sync.

> Fundamentally, having a shared "scribble space" in dual state is kind of an awkward design, because we have a ton of different threads roaming around, and having, essentially, static variables that we're storing values into is a little error prone. Ideally we wouldn't have dual state at all, and instead there would be a concrete API that the platform would call asking for freeze info, and the app would handle all the other details, and we wouldn't use dual state at all.

> I'm just worried with the current implementation strategy how it will behave if the transaction fails and rolls back or anything else.
