### ISSUE TITLE
Profile Smart Contract Performance for storage sizes (4k -32k) 

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#736]
**Summary**
Profile Smart Contract Performance for storage sizes (4k -32k) 

Create Smart Contract with 2 Methods
1. Update Storage content with value provided to the length provide.
2. Read & return storage - CallLocalMethod 

Profile for TPS

**Comment by anighanta** [comment]
With a Single Client which is doing 1000 Contract Calls and 1000 contractCallLocals, im getting **4 TPS** over a period of 10 minutes for contract sizes ranging from 4k - 32k. 

Sample Run [here](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1605156651009300)

**Comment by noshmody** [comment]
Working on improvement of FC Blob (file / smart contract) performance.
Will close out this issue for now.
