### ISSUE TITLE
Fix StatsValidator failure in UpdateNode Test

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#739]
In the UpdateNode test where we add a new config.txt during update which has one extra node added to network.
After the network restarts with new node, the csv stats file has two extra columns created because of the newly added node `bytes/sec_sent_04`, `ping_ms_04`.  Because of this half of the CSV file has different number of columns that will make StatsValidator to fail. 

The possible solution is to add a script that removes these two columns from the csv before validation.

Related to : https://github.com/hashgraph/hedera-services/issues/725

**Comment by JeffreyDallas** [comment]
@Neeharika-Sompalli 
Maybe we should not removes the two column, instead we should append new column (with 0 or empty data) to preexisting one.

**Comment by Neeharika-Sompalli** [comment]
Yes agreed @JeffreyDallas  !

**Comment by Neeharika-Sompalli** [comment]
Based on discussion with Nosh, 

- [ ]  Move the csv file to HapiApp2.0 during update and delete the file after update in remoteExperiment. This will create a new csv file

- [ ]  While analyzing StatsValidator need to validate both the csv's

- [ ] Also graph both the csvs and post to slack channel

**Comment by Neeharika-Sompalli** [comment]
This should be fixed by one of the PR's from @JeffreyDallas !
