### ISSUE TITLE
Identify platform status state machine edges that are not reliably reproduced in JRS tests

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#7390]
Create a list of status transitions that cannot be reliably reproduced (e.g. RECONNECT_COMPLETE -> FREEZING).

Once we have this list, determine if the risk profile is acceptable, and determine a plan to test any that are not acceptable.

**Comment by alittley** [comment]
State machine edges that *currently* aren't reliably reproduced:
- `REPLAYING_EVENTS` -> `FREEZE_COMPLETE`
    - reproducible by coordinating a node restart with a scheduled freeze
- `RECONNECT_COMPLETE` -> `FREEZING`
    - reproducible by coordinating a node falling behind with a scheduled freeze
- `OBSERVING` -> `FREEZING`
    - reproducible by configuring a long delay to transition from `OBSERVING` to `CHECKING`, waiting for all nodes to become active, and then restarting a node shortly before a scheduled freeze, such that it is in `OBSERVING` when the freeze threshold is crossed
- `CHECKING` -> `FREEZING`
    - I can't think of a reliable way to reproduce this
