### ISSUE TITLE
Add a modification timestamp to all Entities - update timestamp EVERY time the entity is modified

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#741]
**Summary**
Add a last changed timestamp to all Entities - Set the timestamp to consensus time EVERY time the entity is modified.

getInfo for all entities will now include this field.

Use Case: State proof can claim that the account hadn’t changed between the last modification time and when the state proof was created.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
