### ISSUE TITLE
Yellow flag: Different timeouts and validations

### ISSUE THREAD

**Issue by enolte-hash** [hashgraph/hedera-services#743]
# Yellow flag: Different timeouts and validations
## Impact
Different timeout definitions and validations across the codebase can degrade the maintainability.
## Situation
In hedera-services:
•	There are different timeouts used throughout the codebase (see below).
•	It’s unclear how the timeouts were chosen based on the code.
•	It’s hard to tell if any of them are correct due to these points.

### List of existing operations and their corresponding validations:
CryptoCreate:
•	Pre-consensus validation: autoRenewPeriod >= <min_auto> and <= <max_auto>

(ContextOptionValidator.isValidAutoRenewPeriod)
•	Validation before execution: autoRenewPeriod >= <min_auto> and <= <max_auto> 
(ContextOptionValidator.isValidAutoRenewPeriod, repeated call to pre-consesus check)

CryptoUpdate:
•	Pre-consensus validation:
*	autoRenewPeriod >= <min_auto> and <= <max_auto> (see ContextOptionValidator.isValidAutoRenewPeriod)
*	expiry > consensus (see ContextOptionValidator.isValidExpiry)
*	expiry >= prev.expiry (see SmartContractRequestHandler.updateContract)
•	Validation before execution:
*	autoRenewPeriod >= <min_auto> and <= <max_auto> (see ContextOptionValidator.isValidAutoRenewPeriod, repeated call to pre-consesus check)
*	expiry > consensus (see ContextOptionValidator.isValidExpiry, repeated call of pre-consensus check)

ContractCreate:
•	Pre-consensus validation: autoRenewPeriod is >= <min_auto> and <= <max_auto> (see TransactionValidationUtils.validateDuration)
•	Validation before execution:
*	autoRenewPeriod is >= <min_auto> and <= <max_auto> (see TransactionValidationUtils.validateDuration, repeated call to pre-consensus check)
*	autoRenewPeriod is >= <min_auto> and <= <max_auto> (see TransactionHandler.durationCheck)

CryptoUpdate:
•	Pre-consensus validation: not checked
•	Validation before execution: expiry >= prev.expiry (see SmartContractRequestHandler.updateContract)

ConsensusCreateTopic:
•	Pre-consensus validation: not checked
•	Validation before execution: autoRenewPeriod >= <min_auto> and <= <max_auto> (see ContextOptionValidator.isValidAutoRenewPeriod)
ConsensusUpdateTopic:
•	Pre-consensus validation: not checked
•	Validation before execution:
*	autoRenewPeriod >= <min_auto> and <= <max_auto> (see ContextOptionValidator.isValidAutoRenewPeriod)
*	expiry > consensus (see ContextOptionValidator.isValidExpiry)

FileCreate:
•	Pre-consensus validation: expiry - start is >= <min_auto> and <= <max_auto> (see TransactionValidationUtils.validateDuration)
•	Validation before execution: expiry - start is >= <min_auto> and <= <max_auto> (see FileServiceImpl.createFile)

FileUpdate:
•	Pre-consensus validation: expiry - start is >= <min_auto> and <= <max_auto> (see TransactionValidationUtils.validateDuration)
•	Validation before execution: expiry - start is >= <min_auto> and <= <max_auto> (see FileServiceImpl.updateFile)

## Recommendation
•	Ideally these timeouts should be configurable somewhere centralized.
•	Creating an abstraction for timeouts would make both issues explicit.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
