### ISSUE TITLE
Yellow flag: Build configuration ignores warnings

### ISSUE THREAD

**Issue by enolte-hash** [hashgraph/hedera-services#744]
# Yellow flag: Build configuration ignores warnings
## Reproducible in commits:
•	fccbbe7ed911628d73ff8ab07981246fac5639cf
## Impact
No direct impact.
## Issue
The current build process does not emit any warnings. For example, configuring the compiler with the following compilerArgs in the respective root pom.xml results in 180 warnings for hedera-services and 325 warnings for swirlds-platform, which might point to existing vulnerabilities or show usages of deprecated code. These warnings include deprecations, which are covered in the issue Deprecated code.
```
<configuration>
    <compilerArgs>
        <arg>-Xlint</arg>
    </compilerArgs>
</configuration>
```
## Suggestion
The optional compiler argument -Xlint should be used to enable a relevant set of warning types throughout the build process.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
