### ISSUE TITLE
Yellow flag: Shellcheck

### ISSUE THREAD

**Issue by enolte-hash** [hashgraph/hedera-services#745]
# Yellow flag: Shellcheck
Reproducible in commits:

•	fccbbe7ed911628d73ff8ab07981246fac5639cf
## Impact
No direct impact. Numerous shell scripts do not follow best practices, which may cause incorrect behaviour.
## Situation
As part of the audit, the tool shellcheck was run to spot shortcomings in the shell scripts of the services-hedera and swirlds-platform repositories. shellcheck provides a code for each finding of the form SCXXXX, which we are using in this issue as well. This issue outlines found issues with error-severity.
## Issue
The following analysis was generated with the tool shellcheck and its invocation: shellcheck -S error $(find . -name '*.sh'). For completeness, the findings include occurrences of code that is out of scope, e.g. the /sdk directory.
hedera-services:
11 issues with error-severity were found, which fall into five distinct error codes:
SC1128: The shebang must be on the first line. Delete blanks and move comments.
SC2068: Double quote array expansions to avoid re-splitting elements.
SC2096: On most OS, shebangs can only specify a single parameter.
SC2145: Argument mixes string and array. Use * or separate argument.
SC2148: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.
SC2199: Arrays implicitly concatenate in [[ ]]. Use a loop (or explicit * instead of @).
The full shellcheck output can be found in the attached asset shellcheck-services.txt.
swirlds-platform: [shellcheck-services[1].txt](https://github.com/hashgraph/hedera-services/files/5503153/shellcheck-services.1.txt)
In the incremental audit, a few issue with error-severity were found in commit 35a1a036470d8beba435968f3f611b6b14f5a255. A full list of the shellcheck output of directories that are in scope of this audit can be found in the attached asset shellcheck-platform.txt.
## Recommendation
Since the above reports are already filtered by error-severity, we suggest fixing all of these. Furthermore, our recommendation is to integrate shellchecks into CI workflows so that dangerous scripting practices can be spotted and addressed consistently (and as early as possible).

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
