### ISSUE TITLE
[Design] Explore HIP 632 isAuthorized support with H.A.S

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#7459]
### Problem

HIP 632 suggests an approach to support the ability to verify an account is authorized to carry out a certain acton by examining a signature 

### Solution

Explore the design and necessary implementation steps to support this and update the relay.
Create sub epic tasklist to capture the necessary work

**Comment by Nana-EC** [comment]
@lukelee-sl please open a new Epic with tasks based on design doc needed for modularized service implementation.
Note ticket here and then you can close this

**Comment by lukelee-sl** [comment]
Created epic #8086 to track
