### ISSUE TITLE
Yellow flag: Test coverage in hedera-services

### ISSUE THREAD

**Issue by enolte-hash** [hashgraph/hedera-services#746]
# Yellow flag: Test coverage in hedera-services
Reproducible in commit: fccbbe7ed911628d73ff8ab07981246fac5639cf
## Impact
No direct impact.
## Situation
Compared to the last audit of commit 7d2ba0624aeaee997d2aa2a38506088de97c7ad7, we found that the tests in the repository hedera-services have been improved significantly. Our first investigation showed that the ratio of lines of tests to the lines of code quadrupled.
Running mvn test shows that the test suite is passing. A few tests are skipped. We observed a reasonable test run time of ~5 minutes.
Tests run: 2523, Failures: 0, Errors: 0, Skipped: 49
Furthermore, one test coverage report was generated through jacoco for tests in /hedera-node, and is attached as the asset test-report-hedera-node.png. /hapi-proto does not contain tests. The test reports can be found locally under /hedera-node/target/site/jacoco/index.html once the tests are run.
## Issue
Regarding /hedera-node:
A discrepancy of the test coverage between different packages was discovered:
•	com.hedera.services.legacy.* packages: combined test coverage of <50% (approx.)
•	The rest of the packages: combined test coverage of >90% (approx.)
A lacking test-coverage percentage appears in the case of the com.hedera.sevices.legacy.* packages, which are currently being used by the project. A larger amount of test coverage would contribute to more confidence in these packages.
Regarding (previously considered) /evm-adapter:
This directory was removed from the hedera-services repo.
## Recommendation
Increase the test coverage for com.hedera.services.legacy.* packages.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
