### ISSUE TITLE
[Design] Explore HIP 755 support

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#7460]
### Problem

HIP 755 presents an approach to utilize smart contract to schedule the execution of a transaction that requires multiple entity signatures.

### Solution

Explore the design and necessary implementation steps to support this and update the relay.
Create sub epic tasklist to capture the necessary work

**Comment by Nana-EC** [comment]
FYI @lukelee-sl

**Comment by lukelee-sl** [comment]
Design doc in #10730 and epic to implement is #16519.  closing this issue as a duplicate
