### ISSUE TITLE
[Design] Explore HIP 756 support

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#7461]
### Problem

HIP 756 presents an opportunity to utilize smart contract enabled scheduled transaction to create tokens that require signatures from other entities.

### Solution

Explore the design and necessary implementation steps to support this and update the relay.
Create sub epic tasklist to capture the necessary work

**Comment by Nana-EC** [comment]
Design work was approached and HIP 756 was updated and will be send for council approval.
@lukelee-sl please create an Epic with tasks needed for high level implementation based on design doc and note there.
Then you can close this issue.

**Comment by lukelee-sl** [comment]
Added issue #8085 to capture the work necessary
