### ISSUE TITLE
[Design] Explore HIP 719 isAssociated support

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#7463]
### Problem

HIP 729 provided the ability for EOA's to securely  associate and dissociate via smart contracts without having to deploy a contract.
It also called out the ability for accounts to check if they are associated or not with a token in a similar manner

### Solution

Explore the design and necessary implementation steps to support this and update the relay.
Create sub epic tasklist to capture the necessary work

**Comment by Nana-EC** [comment]
@lukelee-sl please create a separate Epic with sub tasks that would be needed to carry out the work based on the design. Include one task for a design doc migration from Notion to github md file.
Then you can close this

**Comment by lukelee-sl** [comment]
Here is the epic for this task #8082
