### ISSUE TITLE
[Design] Explore smart contract state migration tests (smoke tests)

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#7467]
### Problem

We'd benefit from tests that focus on viewing smart contract state across version upgrades

### Solution

Explore the design and necessary implementation steps to support this and update the relay.
Create sub epic tasklist to capture the necessary work

**Comment by Nana-EC** [comment]
@david-bakin-sl can you open a new Epic with a few tasks highlighting at a high level the components that need to be explored.
Just enough to capture your current design and we can come back to this post modularization.
At minimum the Seed, Census and Validate tasks. These seem large enough to be Epics themselves.

Once done you can close this task

**Comment by david-bakin-sl** [comment]
I forgot about this.  But now it turns out that my work on the mono- to modular- state migration, and the way it is incorporated into the contract state dumper, will do much of this work.  Will update with more information.

**Comment by Nana-EC** [comment]
@quiet-node do we need this or is it covered by a ticket in smart contracts repo covering the tests we set up?

**Comment by quiet-node** [comment]
@Nana-EC I believe this PR here https://github.com/hashgraph/hedera-smart-contracts/pull/731 cover this topic. I would need to update the PR though.

**Comment by Nana-EC** [comment]
> @Nana-EC I believe this PR here https://github.com/hashgraph/hedera-smart-contracts/pull/731 cover this topic. I would need to update the PR though.

Okay.
Please do

**Comment by david-bakin-sl** [comment]
There's a "smoke test" document in the internal Notions that discusses this at a high level, from the POV of all state (not just contracts) but it has diagrams and stuff and might be useful to review.

**Comment by quiet-node** [comment]
https://github.com/hashgraph/hedera-smart-contracts/pull/731 is merged.
