### ISSUE TITLE
[Design] Explore smart contract feature gates

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#7468]
### Problem

Are additional features gates required for smart contract features

### Solution

Explore the design and necessary implementation steps to support this and update the relay.
Create sub epic tasklist to capture the necessary work

**Comment by Nana-EC** [comment]
@lukelee-sl please open a ticket for modularization to ensure feature gates that are no longer needed get removed at some point.
Then close this as done

**Comment by lukelee-sl** [comment]
Here is the related issue #8081
