### ISSUE TITLE
Yellow flag: Round trip and other issues in TopicSerde

### ISSUE THREAD

**Issue by enolte-hash** [hashgraph/hedera-services#747]
# Yellow flag: Round trip and other issues in TopicSerde
Reproducible in commit: fccbbe7ed911628d73ff8ab07981246fac5639cf
## Impact
No immediate impact (but could be an issue in the future).
## Situation
TopicSerde.java has two methods named deserializeV1 and serialize to perform deserialization and serialization of the data.
We wrote a test to check the round trip property (the property where serialization and deserialization on a data gives you the original data back) of the above methods:
```
@Test
public void topicSerdeRoundTripTest() throws IOException {
        long autoRenewSecs = 1_234_567L;
        long seqNo = 7_654_321L;
        String memo = "Anything";
        JKey[] adminKeys = new JKey[] {
            null,
            new JEd25519Key("abcdefghijklmnopqrstuvwxyz012345".getBytes()),
            new JKeyList(List.of(new JEd25519Key("ABCDEFGHIJKLMNOPQRSTUVWXYZ543210".getBytes())))
        };
        JKey[] submitKeys = new JKey[] {
            null,
            new JEd25519Key("aBcDeFgHiJkLmNoPqRsTuVwXyZ012345".getBytes()),
            new JKeyList(List.of(new JEd25519Key("AbCdEfGhIjKlMnOpQrStUvWxYz012345".getBytes())))
        };
        EntityId ent = new EntityId(0, 666, 888);
        RichInstant ri = new RichInstant(123L, 456);
        MerkleTopic mt = new MerkleTopic(memo, adminKeys[0], submitKeys[0], autoRenewSecs, ent, ri);

        TopicSerde ts = new TopicSerde();
        var out = new SerializableDataOutputStream(new FileOutputStream("/home/sibi/output.txt"));
        ts.serialize(mt, out);

        var in = new SerializableDataInputStream(new FileInputStream("/home/sibi/output.txt"));
        MerkleTopic mtDes = new MerkleTopic();
        ts.deserializeV1(in, mtDes);
        assertEquals(memo, mtDes.getMemo());
}
```
Executing the above test results in the following error:
```
[ERROR] Errors:
[ERROR]   The input stream provided a length of 1097759092 for the list/array which exceeds the maxLength of 4096
```
The above error arises from the deserializeV1 method. The issue is happening because of using writeBytes in serialization:
`out.writeBytes(merkleTopic.getMemo());`
whereas during deserialization it uses byte array (with array length included):
`var bytes = in.readByteArray(MAX_MEMO_BYTES);`
## Issue
There are couple of issues here:
•	Round trip property of serialization is failing because the serialization code uses writeBytes instead of writing a byte array.
•	memo is being written using the writeBytes function. Since the writeBytes method will discard its higher eight bits - it won’t work for non ASCII characters.
•	Different values of MAX_MEMO_BYTES:
*	4096 in TopicSerde
*	1024 in MerkeTopic
## Suggestion
We suggest fixing the serialization and adding tests to check the round trip property. Also, if the two definitions of the constant MAX_MEMO_BYTES are supposed to be the same, deduplicating it would improve the codebase. Otherwise, an explanation of the difference should be given in the comments.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
