### ISSUE TITLE
Override SerializableDet#getMinimumSupportedVersion to return (<CURRENT_VERSION> - 1)

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#748]
**Summary of the defect**
The default implementation of `SerializableDet#getMinimumSupportedVersion` returns `1`; we currently accept this default, which is inappropriate since we do **NOT** actually intend release `N` to support migration from any version earlier than `N - 1`.

**Suggested resolution**
In all `SerializableDet` implementations, override `getMinimumSupportedVersion` to return 1 less than the previous version.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
