### ISSUE TITLE
Add TokenServiceApi to change the balance

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#7493]
The smart contract service needs a lightweight possibility for changing the account balance without creating a record. To enable this, we decided to provide a `TokenServiceApi`. Two entities need to be added an interface `TokenServiceApi` and an implementation `TokenServiceApiImpl`.

The interface `TokenServiceApi` needs to be defined in the module `token-service` in a special package that will only be available to the smart contract service and hedera-app. This interface’s method(s) can take only parameters of the specific operation (e.g., `sender`, `receiver`, `amount`). No information regarding the token service's state or configuration should be part of the method(s) as these will be provided by `hedera-app`.

The class `TokenServiceApiImpl` should go into the module `token-service-impl`. It must have a constructor or static factory method that takes a `Configuration` and a `WritableStoreFactory`. (The latter will be turned into an interface and added to `hedera-app-spi` shortly.) This class must be registered in the (yet to be added) `ServiceApiFactory`. Ideally, this class shares as much code with the respective handler as possible.

See also #7492

**Comment by tinker-michaelj** [comment]
It's worth noting the Contract Service needs some unorthodox signature checks for this `transfer(sender, receiver, amount)` method:
 - The method should not do any key-based check to authorize the `sender`, but the `sender` **must** be a contract, not an EOA. (Externally Operated Account.)
 - If the `receiver` is an EOA with `receiverSigRequired=true`, the method _should_ do key-based authorization; but should accept three additional parameters: (1) `activeContractId`, (2) `activeContractAddress`, and (3) `isDelegateCall`.
     * These parameters should be used to activate any matching `Key{contractID}` and `Key{delegatable_contract_id}` simple keys in the `receiver` key structure.

**Comment by netopyr** [comment]
The requirement that the `sender` must be a contract comes from the Smart Contract Service, right? I think the TokenService should only check preconditions based on its business logic. The caller should ensure anything more specific. I.e., the Smart Contract Service makes sure the `sender` is a contract. The TokenService merely checks if the `sender` is valid, has enough balance, etc.

I have not thought about key verification, really. I expected this to be done in the calling code, but that may not be a good idea. Can we follow the pattern in `HandleContext` and add a single parameter, `VerificationAssistant`, instead of the three parameters mentioned above?

**Comment by david-bakin-sl** [comment]
w.r.t.

| The TokenService merely checks if the sender is valid, has enough balance, etc.

What about the myriad fees and fee rules that apply to tokens - that too would be the token service's responsibility? And too the special rules about who pays for fallback fees.
