### ISSUE TITLE
No need to run MerkleDb compactions every second

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/hedera-services#7525]
This ticket is another sub-task of #7501.

MerkleDb compactions are scheduled to run every second:

```java
                mergingFuture = mergingExecutor.scheduleAtFixedRate(
                        this::doMerge, config.mergeActivatePeriod(), config.mergeActivatePeriod(), TimeUnit.SECONDS);
```

In this snippet, merge activation period is 1 second by default. In `doMerge()`, there is a number of checks whether to actually run compactions, what type of compaction is needed, what files are included, etc. In most cases, no compaction is run as a result of `doMerge()`, so the method is completed quickly, but in a second it's run again, and again, and again. It's just a waste of resources, at least CPU.

**Comment by imalygin** [comment]
There are two things that can be done here: 
1. The simplest - just to increase activation period from 1 second to 1 minute. That will significantly reduce number of "empty" runs. 
2. More complicated - we can count number of flushed files in `MerkleDbDataSource#saveRecords`. Once the number of files reaches `minNumberOfFilesInMerge`, it should start the compaction and reset the counter.

**Comment by imalygin** [comment]
Prior to the implementation Artem recommended running a benchmark with 1 sec and 1 min compaction frequency to estimate the overhead introduced by too frequent compaction

**Comment by imalygin** [comment]
This issue becomes obsolete with https://github.com/hashgraph/hedera-services/pull/9060
