### ISSUE TITLE
HTS: Update max symbol length to 100 characters

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-services#757]
Update max symbol length from 32 bytes to 100 characters. This will allow use cases like DID references or SHA384 hash to be referenced in the symbol as well as name.

**Comment by tinker-michaelj** [comment]
@donaldthibeau We also currently restrict the symbol to be uppercase letters.

Should this be relaxed?

**Comment by donaldthibeau** [comment]
Yes, we should support UTF-8, similar to name field.

**Comment by tinker-michaelj** [comment]
> Yes, we should support UTF-8, similar to name field.

Got it, will relax that requirement now.
