### ISSUE TITLE
Shorter renew period and expiration leads to increased transaction cost

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-services#758]
**Summary of the defect**
When setting the `autoRenewPeriod` to `7890` seconds and `expiry` to `now + 7890` seconds in `TokenCreateTransactionBody` 
the cost of the transaction determined by the `TransactionRecord` is ~900 Hbar. However, if instead of using `7890` seconds I use `7890000` seconds the transaction cost decreases to ~1 Hbar. Is this behavior intended? I would assume a shorter renew period and expiration time would lead to a decrease in cost.

**How to reproduce (if possible)**
I used the Java v2 and Go v2 SDK's to test this.

**Environment:**
- OS: Arch Linux
- Java: 14.0.2
- Hedera Services Version: v0.9.1-SNAPSHOT
- HAPI Version: Not sure

**Comment by noshmody** [comment]
@danielakhterov thanks for raising the issue.
We will investigate code and reproduction. A couple of quick questions for clarification.

Which network was this test run against?
What were the response codes for both the TokenCreate transactions?
I believe we currently have a range limit on the value for autoRenewPeriod.   6999999 <   autoRenewPeriod < 8000001
Based on the network and its configuration, 
the first transaction should have failed and the cost should have been in the order of tinyHbars NOT~900 Hbars for sure.
the second transaction should have succeeded and the cost does sound reasonable. We will investigate both.

**Comment by tinker-michaelj** [comment]
@danielakhterov Can you easily capture the underlying gRPC transaction?

I get `SUCCESS` for the below transaction (note my specified max `transactionFee` is only about 0.18ℏ):
```
body=transactionID { transactionValidStart { seconds: 1605108435 nanos: -502 } accountID { accountNum: 1013 } } nodeAccountID { accountNum: 3 } transactionFee: 17910321 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" tokenCreation { name: "primary706172" symbol: "QVMHFUMJ" initialSupply: 10000 treasury { accountNum: 2 } expiry: 1605116382 autoRenewAccount { accountNum: 1012 } autoRenewPeriod: 7890 }; sigs=sigPair { pubKeyPrefix: "\221" ed25519: "\235\265\031\0204x\027=f\361f$\004\3574y\370\356.\021\242\363$+\2546:\3248<\r&\305$\256\v\200\271\354y\3752\357\336\221P\224\3743\342\323\300\334]\3555`!U\263k\342\222\001" } sigPair { pubKeyPrefix: "\n" ed25519: "{G=\257\312|\315\376{\016\021h\334z\316\344\207\363;\205]\t?xf\350c\246K\303\367\372\206#\364\331g\321yA\315\223\267\346\221\372_\265\035y\305\355R||s\253\373/\234J\361j\r" } sigPair { pubKeyPrefix: "\032" ed25519: "\350o\372\277|\376:yy\3579\214\355\204\212\"Ea&\301\t\by\020;J?\277P\243\222\322\276\020r\350\216>#^y1\253\261;8\355\321\r\246\323\376\020\020&M\212\'\"q\001o\033\n" }
```

**Comment by gregscullard** [comment]
May be related: 
Just tried creating a token with no AutoRenewAccount specified and got INSUFFICIENT_TX_FEE (max fee set to 1hBar). 100Hbar was not sufficient.
If an auto renew account is specified, a 1 hBar fee is sufficient to create the token.

**Comment by danielakhterov** [comment]
Sorry for such a late reply.
@noshmody 
> Which network was this test run against?

Previewnet at the time.

> What were the response codes for both the TokenCreate transactions?

`INSUFFICIENT_TX_FEE`

@tinker-michaelj 
> Can you easily capture the underlying gRPC transaction?

```transactionID:{transactionValidStart:{seconds:1604978604 nanos:486156181} accountID:{accountNum:16372}} nodeAccountID:{accountNum:3} transactionFee:100000000000 transactionValidDuration:{seconds:120} tokenCreation:{name:"ffff" symbol:"F" decimals:3 initialSupply:1000000 treasury:{accountNum:16372} adminKey:{ed25519:"\xb4\xaf>\n\xc5\"m\xf1A۷s\x8e\x04G:SQӪ5\xdc!\x12\x1b\xa0\x11\xf63\x1eS\xe7"} kycKey:{ed25519:"\xb4\xaf>\n\xc5\"m\xf1A۷s\x8e\x04G:SQӪ5\xdc!\x12\x1b\xa0\x11\xf63\x1eS\xe7"} freezeKey:{ed25519:"\xb4\xaf>\n\xc5\"m\xf1A۷s\x8e\x04G:SQӪ5\xdc!\x12\x1b\xa0\x11\xf63\x1eS\xe7"} wipeKey:{ed25519:"\xb4\xaf>\n\xc5\"m\xf1A۷s\x8e\x04G:SQӪ5\xdc!\x12\x1b\xa0\x11\xf63\x1eS\xe7"} supplyKey:{ed25519:"\xb4\xaf>\n\xc5\"m\xf1A۷s\x8e\x04G:SQӪ5\xdc!\x12\x1b\xa0\x11\xf63\x1eS\xe7"} expiry:1604986504433941502 autoRenewPeriod:7890}``` 

Note: This was originally tested in Go v2 with the following code:
```	transaction.SetAutoRenewPeriod(7890000 * time.Second)
	transaction.SetExpirationTime(time.Now().Add(7890000 * time.Second))
```
which does
```
transaction.pb.AutoRenewPeriod = uint64(autoRenewPeriod.Seconds())
```
```
transaction.pb.Expiry = uint64(expirationTime.UnixNano())
```
Now that I mention it I see we're using `UnixNano()` for some reason. This could also be the cause for this issue. Will test using `Unix()` instead with `7890` seconds again, and get back you with that.
