### ISSUE TITLE
Need a link for node logs in CI runs

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#7662]
Currently there is no link provided in CI run for node logs. 
It will be nice to provide link for those logs like [these](http://35.247.76.217:8095/Neeharika-Sompalli/integrate-0.41.0-adhoc.x0a2709a2/4N/Abbrev/20230724-190523-GCP-PRCheck-Abbrev-4N/) in Summary page for CI run.

**Comment by JeffreyDallas** [comment]
no longer needed
