### ISSUE TITLE
Extend lifecycle of sync to include ingestion

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#7663]
Currently when we sync, we require that a sync permit is held. That permit is released after the sync protocol completes.

This workflow has a flaw. This flaw is that the sync protocol pushes events onto an asynchronous queue, and we don't use those events for gossiping until they travel through the queue. When this queue backs up, the net effect is that we start new syncs without waiting for the old ones to truly finish.

To remedy this, we should treat a sync that still has unprocessed events in the intake queue as if that sync were not yet finished. This means that we should wait until events are ingested until we start another sync with that peer, and before we release the sync permit.

**Comment by poulok** [comment]
This feature should be behind a feature flag
