### ISSUE TITLE
Investigate error "Node 0 has exception:- Error reading '0.0.150' " in HederaNodeValidator for 15-Node performance test

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#768]
**Summary of the defect**
In 15-Node performance regression test, there are error messages "Node 0 has exception:- Error reading '0.0.150' @ data/diskFs/0.0.3/File0.0.150!". 

Need to find out whether this is an real issue or not.

**How to reproduce (if possible)**
Checkout this slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1605086762222700 

**Service logs (if applicable)**
```
---- HederaNodeValidator FAILED validation ----
<<ERROR>>
Node 0 has exception:- Error reading '0.0.150' @ data/diskFs/0.0.3/File0.0.150!
Node 1 has exception:- Error reading '0.0.150' @ data/diskFs/0.0.4/File0.0.150!
Node 2 has exception:- Error reading '0.0.150' @ data/diskFs/0.0.5/File0.0.150!
Node 3 has exception:- Error reading '0.0.150' @ data/diskFs/0.0.6/File0.0.150!
Node 4 has exception:- Error reading '0.0.150' @ data/diskFs/0.0.7/File0.0.150!
Node 5 has exception:- Error reading '0.0.150' @ data/diskFs/0.0.8/File0.0.150!
Node 6 has exception:- Error reading '0.0.150' @ data/diskFs/0.0.9/File0.0.150!
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by JeffreyDallas** [comment]
No log uploaded to AWS, please investigate and resolve the logging issue first.
But since this test involves restart, my guess is the default state.savePeriod is 900, so in the first run, signed state 
has not been saved to disk before app restarted, 
please try use a short savePeriod

**Comment by ljianghedera** [comment]
> No log uploaded to AWS, please investigate and resolve the logging issue first.
The log files location please refer to comments in #767 

> But since this test involves restart, my guess is the default state.savePeriod is 900, so in the first run, signed state
> has not been saved to disk before app restarted,
> please try use a short savePeriod

No, actually this is not restart test. It's actually start from a saved state. We are just following the naming conventions. I think the real issue is when we first launch the services from a saved state (only the SignedState.swh and the PostgresBackup.tar.gz) are restored, we didn't restore the diskFs directory at all. However, in the ServicesState class we still try to restore the update file from 150 regardless it exists or not. If the directory structure is not there, we spit an error message. 

So the question is whether we should treat the diskFs as optional during start up, hence no error if it doesn't exist.

**Comment by anighanta** [comment]
Couldn't observe this anymore. 
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1605723404064400

**Comment by ljianghedera** [comment]
Move it to 0.10.0 and check if this issue still exists. If not, will close it.

**Comment by ljianghedera** [comment]
This issue doesn't appear any more.
