### ISSUE TITLE
JRS Test Reader

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#7739]
Create utility program for reading and collecting JRS test results.

**Comment by cody-littley** [comment]
Additional feature ideas. Features that do not get included in v1 of this tool will be put into issues for later work.

- sortable columns
- a special column that has " " by default, but a "!" if the test is failing but has passed in recent history
- a more human readable summary page (current formatting has slack gunk). Perhaps even use HTML formatting.
- HTML rendered logs (with color formatting)
- link to a log summary, where we only display high priority logs like exceptions and status change messages

**Comment by edward-swirldslabs** [comment]
Is there a way to add and keep active and rendered in between sheets a link for each failure to the github issue for addressing the failure?

**Comment by edward-swirldslabs** [comment]
If we are using this as the new Triage page, a notes column for each test so that people can update the comments on the test when they hand off triage responsibilities to the next person.

**Comment by edward-swirldslabs** [comment]
Need a JRS Test Reader for each release that has active regression tests running.  40, 41, 42, develop ...
