### ISSUE TITLE
Differential testing PBB:  Drive recovery to specific event record by timestamp then save state file

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#7744]
Enhance PBB event recovery tool so that it will stop at a specific event then save a state file at that point.

Also, should be able to incrementally step forward event by event (while looking at things in debugger) and choose a point at which to save the state.

**Comment by Nana-EC** [comment]
@david-bakin-sl moved this to 0.46, if this already complete, in progress or appropriately in backlog?
