### ISSUE TITLE
PCES File Cleanup on Startup

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#7752]
Consider cleaning up PCES files with events that occur after any events that can be replayed on the loaded state.

In testing, we may want to run multiple transaction loads on different runs starting from the same saved state. It would be nice if, on startup, the platform detected if there were PCES files that contain events that both, 1) Cannot be replayed on top of the loaded state, and 2) Have a higher generation than the highest generation in the state. If such files are detected, recycle them.

Adding this feature means that the test runner does not need to remove both the saved state files and the preconsensus files.

[Slack](https://swirldslabs.slack.com/archives/C05D5TLCN1X/p1690704107714619) convo

**Comment by cody-littley** [comment]
Hard to do, let's not do this.
