### ISSUE TITLE
Add a new Load test to test performance of HCS and Crypto with large tree size

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#779]
Currently the load tests we use to test performance create only 12 or 18 accounts and test for 10K TPS.
Add tests whose tree size is 1 million and the do CryptoTransfers/SubmitMessages.

- [x] Modify throttle on the public testnet state to allow 10K TPS or create a new state with 1M accounts and use that state for load tests

**Comment by lbaird** [comment]
That’s useful. But it isn’t a “large” tree. Mainnet already has a tree of that size. So a “large” tree would be 10 million. Or maybe 1 million.

________________________________

**Comment by Neeharika-Sompalli** [comment]
@lbaird  Thank you!! I have modified the description to have tree size of 1 million.
