### ISSUE TITLE
Migrate gdrive docs

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#7810]
Go though the legacy documents in gdrive and either:
- delete any that are obsolete
- migrate relevant ones to the repo

**Comment by poulok** [comment]
@lpetrovic05 was this already done?

**Comment by lpetrovic05** [comment]
> @lpetrovic05 was this already done?

I think I migrated the docs from the old repo, I never got to the gdrive docs. I will take a look today, most of it will probably be deleted
