### ISSUE TITLE
HapiTestEngine does not give correct test results when run TopicCreateSuite

### ISSUE THREAD

**Issue by iwsimon** [hashgraph/hedera-services#7827]
### Description

Running *Suite and running individual method gives different results.

### Steps to reproduce

In 7673-run-consensus-e2e branch, right click TopicCreateSuite, run it. You will see the last three tests failed. Select any of those three tests to run, it's passed, which is the correct result.

### Hedera network

other

### Version

develop

### Operating system

None

**Comment by iwsimon** [comment]
Fixed by Richard's PR 7954.

**Comment by vtronkov** [comment]
> Fixed by Richard's PR 7954.

@iwsimon, do you know exactly what the problem was and what change fixed it? I don't see any changes to the `HapiTestEngine` class so maybe the problem was somewhere else?

**Comment by vtronkov** [comment]
> Fixed by Richard's PR 7954.

Oh, I see: https://limechain.slack.com/archives/C040H9JPQT1/p1691554897554749
