### ISSUE TITLE
HTS invariants of ERC methods return empty values with ContractCallLocal queries

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#7838]
### Description

Currently we have 3 method signatures from `IHederaTokenService` that are invariants of methods from the ERC standard. Those are:

1. `getApproved(address token, int64 serialNumber)`
2. `isApprovedForAll(address token, address owner, address operator)`
3. `allowance(address token, address owner, address spender)`

It seems we don't cover these methods in the `ViewExecutor`, therefore if we perform a `ContractCallLocal` query we don't match a proper case for these methods and they default to return `Bytes.EMPTY`.

### Steps to reproduce

1. Deploy a contract with a method that invokes one of the 3 methods listed from the IHederaTokenService interface
2. Perform a query, calling this method via the SDK or inside a test-clients suite
3. Expect that the returned result is always empty

### Hedera network

testnet

### Version

v.0.40

### Operating system

macOS

**Comment by stoyanov-st** [comment]
Cannot reproduce reported issues.
Confirmed that the reported functions are implemented as view calls in HSCS by running tests.
