### ISSUE TITLE
Find out why master 6-Node JRS HCS perf regression doesn't have traffic

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#787]
**Summary of the defect**
It happens in today's HCS 6-node perf regression.

**How to reproduce (if possible)**
Check out this summary link: 
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1605720248099200

and its detail report link:
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1605720209063300

**Service logs (if applicable)**
```

```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by Neeharika-Sompalli** [comment]
@ljianghedera Is there any error on server side or client side logs?

**Comment by Neeharika-Sompalli** [comment]
This issue is resolved based on yesterday's run https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1605757858319700. It gave 0 TPS as the platform was not ACTIVE.

**Comment by Neeharika-Sompalli** [comment]
This happens when Platform doesn't turn ACTIVE.
