### ISSUE TITLE
FCM-Query-2.5k-110m nightly failed on 2023-08-08

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#7908]
Node 2, after 52.6 minutes of being ACTIVE falls into the CHECKING state for 6 seconds.  With the 10 second threshold, Node 2 was not able to have an event reach consensus for 16 seconds.  

test data: http://35.247.76.217:8095/swirlds-automation/develop/4N/FCM/20230808-053608-GCP-Daily-FCM-4N/FCM-Query-2.5k-110m/

**Relevant Metrics**

`trans/sec` becomes erratic: 
<img width="614" alt="Screenshot 2023-08-08 at 4 04 38 PM" src="https://github.com/hashgraph/hedera-services/assets/123979964/bf705a3f-d3c2-4699-933b-dbbaabb5bb31">

`secTransH` hits 10^(-4) for a while: 
<img width="578" alt="Screenshot 2023-08-08 at 4 09 12 PM" src="https://github.com/hashgraph/hedera-services/assets/123979964/058af037-f555-4661-8571-b89748ae6402">

The consensus thread maxes out a core for a while:
<img width="591" alt="Screenshot 2023-08-08 at 4 10 15 PM" src="https://github.com/hashgraph/hedera-services/assets/123979964/dab7e3fc-3749-4924-8263-00e3f4e706db">

**Comment by JeffreyDallas** [comment]
Multiple reconnects failed because platform status switching back to CHECKING from ACTIVE during middle of test,
which led to some client transactions could not go through .

**Comment by alittley** [comment]
The issue was made for `develop`, but this has happened in release 40

http://35.247.76.217:8095/swirlds-automation/release/0.41/4N/FCM/20230810-093938-GCP-Daily-FCM-4N/FCM-Query-2.5k-110m/

**Comment by JeffreyDallas** [comment]
Even a short, low TPS test has the same issue : switching back to CHECKING after ACTIVE

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1691740525366919

**Comment by JeffreyDallas** [comment]
Any update on the issue ?

Half of service tests are reconnect/restart related and they are failing due to this issue.

The test runner need a reliable way to know when can a test client send
transactions to platform without worry about platform status changing to CHECKING during
the time.
