### ISSUE TITLE
Mismatched msg.sender and NonFungibleTokenInfo.ownerId

### ISSUE THREAD

**Issue by bmino** [hashgraph/hedera-services#7926]
### Description

I have a smart contract that checks if the provided NFT is owned by the sender. It checks `IHTS.getNonFungibleTokenInfo(NFT_ID, NFT_SERIAL_ID)` and successfully returns the struct `IHTS.NonFungibleTokenInfo`

### Steps to reproduce

I am issuing this call using an ECDSA account from portal.hedera.com with an account id of 0.0.156560. Inside the smart contract, msg.sender resolves to the evm address (0x96be143b8e6bcf98996460e8d9be55463155ff07) while the IHTS.NonFungibleTokenInfo.ownerId resolves to the 0-prefixed address (0x0000000000000000000000000000000000026390) and the smart contract's address comparator marks them as not equal

### Additional context

**Simplified Contract**
```solidity
pragma solidity =0.8.15;

import "../hts-precompile/HederaTokenService.sol";
import "../hts-precompile/IHederaTokenService.sol";

// SPDX-License-Identifier: MIT
contract OwnershipCheck is HederaTokenService {
    function isOwner(address token, int64 serialNumber) external view returns (address, address, int256) {
        (int256 responseCode, IHederaTokenService.NonFungibleTokenInfo memory tokenInfo) = HederaTokenService.getNonFungibleTokenInfo(token, serialNumber);

        return (tokenInfo.ownerId, msg.sender, responseCode);
    }
}
```

**Test Script**
```javascript
const tx = await new ContractCallQuery()
    .setContractId('0.0.466415')
    .setGas(300_000)
    .setFunction('isOwner',
        new ContractFunctionParameters()
            .addAddress('0x0000000000000000000000000000000000070dd3') // token
            .addInt64(2) // serialNumber
    )
    .execute(client);
const owner = tx.getAddress(0);
const sender = tx.getAddress(1);
console.log(`HTS Owner: 0x${owner}`);
console.log(`Sender:    0x${sender}`);
```

**Test Output**
```
HTS Owner: 0x0000000000000000000000000000000000026390
Sender:    0x96be143b8e6bcf98996460e8d9be55463155ff07
```

### Hedera network

testnet

### Version

latest

### Operating system

Windows

**Comment by tinker-michaelj** [comment]
Great catch @bmino, thanks for reporting this.

**Comment by stoqnkpL** [comment]
Fixed and tested on previewnet.
