### ISSUE TITLE
FCMFCQ-Basic-3k-120m has poor performance in release 0.41

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#7953]
FCMFCQ-Basic-3k-120m

http://35.247.76.217:8095/swirlds-automation/release/0.41/4N/FCMFCQ/20230809-094024-GCP-Daily-FCMFCQ-4N/FCMFCQ-Basic-3k-120m

Node 0 maxes out its consensus thread and spikes in secC2C

<img width="562" alt="Screenshot 2023-08-10 at 2 53 42 PM" src="https://github.com/hashgraph/hedera-services/assets/123979964/4a7c1e70-8ce3-4cb7-add7-c676c0d620e1">

<img width="614" alt="Screenshot 2023-08-10 at 2 47 06 PM" src="https://github.com/hashgraph/hedera-services/assets/123979964/e343f195-7f9b-4a53-9298-f5b81b7c3946">

<img width="588" alt="Screenshot 2023-08-10 at 2 52 37 PM" src="https://github.com/hashgraph/hedera-services/assets/123979964/282b12d7-5a51-45e1-8884-ba3c8f74bbf1">

**Comment by edward-swirldslabs** [comment]
this test has consistently failed the last three runs. 

What a good run looks like: 
http://35.247.76.217:8095/swirlds-automation/release/0.41/4N/FCMFCQ/20230804-093938-GCP-Daily-FCMFCQ-4N/FCMFCQ-Basic-3k-120m/

**Comment by edward-swirldslabs** [comment]
There is some though that turning off the expectedMap might improve performance.   Logs have this feature: `SAVE_EXPECTED_MAP`

**Comment by poulok** [comment]
no reproduction in 3 weeks, closing
