### ISSUE TITLE
Implement frontend throttle

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#7961]
Implement frontend ingestion workflow throttling by reusing/delegating to existing mono-service implementation (annotated with `@HapiThrottle`)

**Comment by vtronkov** [comment]
For now, the FE throttling seems to be working. The tests are failing due to modularization issues. I am blocking it since it might need to be changed when https://github.com/hashgraph/hedera-services/issues/7960 is done
