### ISSUE TITLE
Services Modularization Does not honor setting grpc.port=50300

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/hedera-services#7967]
### Description

Pre modularization putting `grpc.port=50300` in `data/config/node.properties` changed the GRPC port.

### Steps to reproduce

put `grpc.port=50300` in `data/config/node.properties` and see if server starts listening on port 50300 not 50211

### Hedera network

other

### Version

0.40

### Operating system

None

**Comment by tinker-michaelj** [comment]
By default mod-service does not use _data/config/node.properties_ at all.

If `HEDERA_APP_PROPERTIES_PATH` was overridden to _data/config/node.properties_, this property could be set there and it would work.
