### ISSUE TITLE
(Perf) Improve TransitionLogic classes to avoid triggering exceptions in HederaLedger methods

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#797]
**Summary**
If an account is deleted, e.g. the `CryptoTransferTransitionLogic` should avoid calling any `HederaLedger` method involving that account; such a call will throw an `AccountDeletedException`. 

Even though the exception is handled correctly, the overhead is high compared to simply short-circuiting to an `ACCOUNT_DELETED` status.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
