### ISSUE TITLE
Setting up a simple Loki sample for Java with Docker-Compose for devs

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#7988]
Links:

- https://grafana.com/docs/loki/latest/clients/
- https://github.com/tkowalcz/tjahzi
- https://grafana.com/docs/loki/latest/installation/docker/
- https://grafana.com/go/webinar/getting-started-with-logging-and-grafana-loki/?src=ggl-s&mdm=cpc&camp=nb-loki-exact&cnt=124221004773&trm=promtail&device=c&gclid=Cj0KCQjwoeemBhCfARIsADR2QCvppx8RSYoy5gY-SGiJAK5_4KPYmJWkNGznpW20qHLs0jsg-DbjmeAaAn_uEALw_wcB

**Comment by mxtartaglia-sl** [comment]
Added the necessary configuration + docker compose files in:
https://github.com/hashgraph/hedera-services/pull/11408
