### ISSUE TITLE
SmartContractOps-NIReconnect-14-21m failed due to merkledb error

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8013]
### Description

Slack report URL

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1692087479320529

```
ERROR EXCEPTION        <<merkledb: Merging #0>> DataFileCommon: accountStore_internalhashes has references to files [-2] that don't exists in the index. Latest new files = [10]
```

### Steps to reproduce

Nightly regression panel `GCP-Daily-Comp-Reconnect-6N-1C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by poulok** [comment]
This has been fixed
