### ISSUE TITLE
Implement correct gas calculation for prng system contract

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#8094]
### Problem

Currently the gas calculations for prng system contract always returns 0.

### Solution

Once the fee calculator utility for system contracts is available, update the logic to return the correct gas charge.

**Comment by Nana-EC** [comment]
Team to verify

**Comment by lukelee-sl** [comment]
fixed with this pr https://github.com/hashgraph/hedera-services/pull/12309
