### ISSUE TITLE
ISS on TransactionHistory-Reconnect-1-12m test while running nightly

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#811]
While running `TransactionHistory-Reconnect-1-12m` ISS occurred in nightly. But when I ran it locally ,ISS did not occur https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1606243422108400. 
This could be intermittent and needs to be investigated. 
Logs can be found at https://app.circleci.com/pipelines/github/hashgraph/hedera-services/7249/workflows/96bf16c6-285e-4b4f-9eee-81ffabbfb762/jobs/43356/artifacts

Failed tests : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1606296401111000

**Comment by cesaragv** [comment]
Duplicated by #815 and fixed by [689](https://github.com/swirlds/swirlds-platform-regression/pull/689)
