### ISSUE TITLE
Release 0.41: Unexpected reconnect after uprade

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8192]
### Description

Slack report URL

https://swirldslabs.slack.com/archives/C05MHKR9BJ7/p1692793363375479

Node 0 became fall behind after upgrade restart, although all nodes started from
the same round `13343`

```
---- ReconnectValidator FAILED validation ----
<<ERROR>>
Node 0 was not expected to reconnect. (reconnect count: 1)
<<INFO>>
minimumTimeBetweenReconnects is PT9M
```

### Steps to reproduce

Run nightly test panel `GCP-Daily-Update-Reconnect-4N-2C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by poulok** [comment]
This looks like a test failure. Node 0 did not start until about 45 seconds after the other 3 nodes.

**Comment by JeffreyDallas** [comment]
Agree with Kelly's observation, seem GCP infrastructure: although all nodes were launched at the same time,
node 0 was started much late then others.
