### ISSUE TITLE
Reconnect - node does not reconnect after being shut down

### ISSUE THREAD

**Issue by tannerjfco** [hashgraph/hedera-services#821]
**Summary of the defect**
A node shut down by GCE Preemption does not reconnect after it is started back up. The other nodes in the network log new connections to the node when it is started. The node reports changing status from "STARTING_UP" to "BEHIND", but does not change from this status after. The rest of the network continues to accept and process transactions

**How to reproduce (if possible)**
- power down node
- run transactions on the network with remaining nodes
- power up downed node hours later

**Service logs (if applicable)**

[node00 logs](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T16%3A57%3A59/logs/node00-logs.tar.gz?x-goog-signature=7e8e6ea4182d008aecf64dd86857b613d1b7ec51b626f18896c039b4493ead7b6e90ec0c799a71f703e215c584d2ee3d23a694a7feaa2b871a7e38d18590daa71b6206f3404598f9ebbd1018254a877fbb57dcab07629c9c3554926c53ed558866df1108854859acdb025048a5de3dc03d1499bf99ddc00257d78750933ed668d6ddd1923fe079711409c276b3618f341ed866cc5a0ac41394483820172ffafadec94482b397eefa6358877b56b4be34e8cbcaf148aa69bb40fccad05e58f6193e16fc84d20f5841f861712e4ab57c1bf27885917018bfc1338e540159b23a2addeae3a778cb1b35a770c672672b99d48acd330eb0cb09a583ed84e9d64ed7e8&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T165908Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node01 logs](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T16%3A57%3A59/logs/node01-logs.tar.gz?x-goog-signature=12bfb52bfab5b04609590820925b7c9754cce6c46f8e80a70109049b5e9e5a07aa93804443828b14f5cf886b50e4b8fdec1adaeb90dc68e2b9a02f723228eab08b127496d9fb6e2bde715c92a1608faa3c384e5225c63938d6d043e7ecb4becf810a56aa981b30ecf529b7d5eb4c4114c4a8a4cc4d5d5f07302784c2b5d73ce3f591034549f5d35439b1924eb0e9a60d9dfe3faca81bd4a32e4ab6db1a2e2b3665930d4d1253d173808beebddc9ebbd69d2018eaa46080dd326c30ca2f7bbe2322f48aa5e49f696a5a6061e70d3a83d443c0fa64a3663e898f6d8823916be0154e52084c2b381ba9a477ab19580dbb4b7963bbfadc0d8bfafca5c70105df7990&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T165910Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node02 logs](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T16%3A57%3A59/logs/node02-logs.tar.gz?x-goog-signature=31969f12ea212580a3ff0d23615d3b249adcd2b8d14077079fe5f347be7673c60f1c3647dac674f0dc29a45c2151549eb0cd6806bc67658149fe70491cdeebad3f5476020d5b2fd844315dde2ab2783afb863ad8ac8b638b7184cf66aa70480033e6feddc4c933659f7fb750d3a6f18db307f9fd34843bff7427a6a4e036747731cc1b2f1a6225b3b185b17387716155f9f10ce6d7b591fbf7b9d49003bb6ed82cea903b303d426bbe8d6ad57761f27acaa329953797bb95f8ae7f7a11b282ee23519c4c284e559c3362a5cce9cf2622f9161d24c47faf302f42b35e28227c044e2ff27b43471763d74c697cd5a990bd58a7b780a0be3bd025b3543d6b32dc1a&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T165912Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node03 logs](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T16%3A57%3A59/logs/node03-logs.tar.gz?x-goog-signature=aa25a6d300a7eafa53ee2f4f6e4b0e9992a898621f66d6e2c9d585f368e09fa9b942e6d8d341d706523f515e707d38883a730100598910ff80a181ecef9c4b322eb8f86f7f983c7f0a1ee446fd9e444f162ee6645d2e09aca871b3c015111cbc3ebc665cc5d82d0ecd06eabc63dc03061f2853e10e893803c685ba9b724ec1be80ea801053c457e565cb70ab076472cf99e944eb8524a498a8e414350c2d7491b2efe2c886390c5df7356a45e780cbefc95fe037fee7e983324d2d6f5b43e414c3ef49ca2e4b95b0ee6a7cda39e8ad95019cbb2699746163d621be756bec2f70b5a32a0f754f952bb5839319fb78daeefb8e8d80378d3a6d57647cde3a53c06d&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T165914Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node04 logs](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T16%3A57%3A59/logs/node04-logs.tar.gz?x-goog-signature=a60449c2a9a7c0a315377efa8e497fc29a6d9bd09228e820b183738b05f747a790f81580e2541d941eb74d6d00e3b5310db68f6681c05bd30a5f73f8344919e39a873681fb85d1aa81e4cab68b8875f27b5078a6a9993c447566abf53c1dfff8120180905b9bdeae968371e8846e1f9da416c92a99d18c7bc57373068c2a1c917f3f487d30ad7ff615971f92010d9b5a4b1f8a46c2be10957f7bee107799a999454755624b4a3866256ed67ce087573b972b0eca004eca9615564b6e86db028f75bc38a5db84439794b8ecc8e1e37186a4f26ab337a6f397e8f320a7c89898c29c81bb370e0dbe9f58f24254dfc9cdcb62f6faa92504ffeb6fafff260ade9659&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T165915Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node05 logs](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T16%3A57%3A59/logs/node05-logs.tar.gz?x-goog-signature=36da2effb25c8948ec6fef501c6ce8ff5298999753f86d9fee743071214491d0ae6c7660fd7e95dee8f52e162455ae197d59e732e21e78fe65d8c7aa21c0595f9f48bfe500b2e3d19377fe80ec7c2a7c0d6a06ec155d5778ef153d0ea097971c1bf29fdc48e860b4978d8424edc52bed6fb0ff3a8939f61cbfcc968901ef53c88e53e5e847dfa221b68ae5c930934ea0ee70f5858357c817146c2b0394bcbd238dd62a10b1fd2e54c4d0aab1d61f66ea7e6148741e076ac9920d36033a5c6fbb20503fe833e075034fb7f96fac75642713973a49db465fc599897f030df0aa3642e1b67af798e1f95ee43c2b55005f09059eac99faa5b651f4cbf4a27ec5b809&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T165917Z&x-goog-expires=604800&x-goog-signedheaders=host)

[node00 data](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T16%3A57%3A59/data/node00-data.tar.gz?x-goog-signature=be1a32e6b601969628b853ae4506ef561390f0e4fe9c851016e8b99654a1ce255028292c9fa3e36d4ba486c442f8092fea69d29d0cd3079186ae84a18833218d6aa5c4ad35607bcfc05b23bdde2c74d6d794e891f4d9da3f28bd1ae7625267ad4d63b31bf10bedd2d3e7a194db1270880b6f906563a4c72ba1c4d01754a5a969bae5d348a14d4bac1710f02d30d942123f72f4903d0c0e648bf1928648708920c574fde3083530fb89187b338ead3cd07a97a319d34a08e603c17b2b3915308a1b57477768c260fdccaba16f19cc3399b59cfa4c95d4da47e7c10e6acb38d1d249226ef59adaea8834b9c789724f72aa55021c625a8fd43ba9284c37a9465268&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T170058Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node01 data](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T16%3A57%3A59/data/node01-data.tar.gz?x-goog-signature=40058faf25efa56f288776c150dd88e327223f5edc484c3c2419c8b5f088581cd4c119141db143995f0c610a9de9e0a29950056571d0865386dcd99d4027ce3465f06935f4b9442ee819f8a6c506f78d763486365f25b15c4c0bfd9d1070c11bae7aa9c92b0cc90310982488eab8484af1820ca526352c82422554758d11b1d325babb19c8001c5391135f2ff580ce15dd5760b062d6015df8d85bb8370eb413a1c132bf7b996b34e752da4cdc32a6d3d87aa5bbcb277d1e1bff474c99579e6bb81c87d416e53bc9eb9adf5471d14164f8ecf0b7dcf9bbe2a4c4b9f46538c99f986d1c864511085ab7b64f3efa5e93ab82c4ba0c042fe724629ddccf3dd852fe&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T170100Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node02 data](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T16%3A57%3A59/data/node02-data.tar.gz?x-goog-signature=053908c1e2e4bb1aa820e3085540d6bb2b04ef1b5d10c4ef55a108504edb168046f8787dd094b89a0c5308fcc14854c367888ddee99123782b02e15e74f7d7986c7e2737943697487a27f4e2233c07a5b335a34103ae7e9342f2c0b58e0e668b233beb68da338ad7fcc77bf7daa3659ed532f7d65030ab312676904e159df3bfa0fc49dbf81cd43ea67cd513e846a93c183025a888ad76c67cb3447273f2465e99f9b7317bc4250f55462b48d1a5f6f2b55d722f223b869e45e209ed4655941841a4780526b6097ea40d8e99c27586b4f6185d1e3cf4dc873fa7b658320f9bff3631358e800a21fb1c317ec12622a0277ce0bf5229e245ed9ba8a552110dab37&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T170102Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node03 data](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T16%3A57%3A59/data/node03-data.tar.gz?x-goog-signature=45f098d71dccaa50b8629bef41c1c1982534f47958a59c6ae7bca7cd895d56d22d4ed61d5262f2687c7864d8ef6628942835e8b20b3dda1715757772282fe0cc46b3172e5869449b72ed21ef9c50088a5029a6f14a07906925d8d86ae2272bc875df10a65a0a81a65d898232916609e2e386f598603c800de324783817478d6c88a4214a533d3403e6780bc0df4a5467d4c1d83da965ae90b3dc79dd3dd46a69e1a3d410ce68a8f449ab8cb5bfcb0fd93dcea5bb538ce8352cef76d07b66d349bf1a13215092d5a7dce488a38225845dec32fbec5e787ae256c484d7d88126ea32e8361b71c6137a9241d14068f0219fd1d497c751bd6c7f6bffaed5fc64d987&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T170104Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node04 data](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T16%3A57%3A59/data/node04-data.tar.gz?x-goog-signature=2811f6a80e5fcea109114005096dbbe525e00cbc3671934ee62b4072ca4803933a833b0186ce4a7d48467243a61000679df2620e084f07ddf440b077caeb62fb99f2a0cadd45c70f6d9284269750782d8623cabef292afdc888606e03e96ff8d305a847833a5c1f7f9ca96820e62c51e74d5e19a48c2d61569f1245d6196b2117a49867c32d73de81ba6239b4fb6584ade2b3d2987e10a835ee365d78a5b036998b4473ac677c4c8398bf26e856b8659d69da2cd47b3ef0b8893ca1adf53f3e468beb405a910946e7eebeb126e9b01a9c19f7a4876727f6342c6dda5bdd4a4e76c3974be340b92aed78ba1b8befa60ba9fccbb19de42275330bc795e8a552fe1&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T170105Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node05 data](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T16%3A57%3A59/data/node05-data.tar.gz?x-goog-signature=c9ff11580fa36742466cc27d657b684e659c24ccc24a229eb7171b4ccf5e2b6a9314c8c7289689a31f478859fe579f5f0ac18b8df1ac88a39e924585f55cff6760a56cf57c5d03c70ed2570a42e34dbc909eda754afd3d50cd0ec0b902c3ea8963c8f738d9b7aa758dcc3d39e6e9989988ec9675eda9fcf60d8b4bb19a10bdd2c55a35a0def520040caab2d06e32b92bdc2ddb9249016c260e873f063b47af89f9a048e8f758d182d6395da61889846a5abafefba76a0598a8ac7ab1ab0b55349ce755ba7899f1d78531228eafe3fc8243954d1f4eb3c28f26280085653f961e9765f0691a6194d8f1325505bd0a932852c8b46b99b8fd61cc2da250b5798cfd&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T170107Z&x-goog-expires=604800&x-goog-signedheaders=host)

**Environment:**
- Network topology:
  - 6 node network
  - 1 of the 6 nodes is zero-stake node
  - 4 Ubuntu nodes
  - 2 Centos nodes, one of which is the zero-stake node
  - GCP Nodes in US: us-east1, us-east4, us-central1, us-west1, us-west2, us-west3
- OS: Ubuntu 18.04 and Centos7
- Java: openjdk 12.0.1
- Hedera Services Version: Built from master commit https://github.com/hashgraph/hedera-services/commit/0f58f2a286d095c275c96e1f5496c916103368dc Devops build `build-v0.9.0-rc.2-193-g0f58f2a2`

**Additional Context**
Network is configured to have reconnect enabled with `reconnect.active, 1` in settings.txt and `ledger.keepRecordsInState=true` in bootstrap.properties

**Comment by cesaragv** [comment]
@tannerjfco which node is the one that reconnect? i.e., which node is the one that changes its status from `ACTIVE` to `BEHIND`?

**Comment by tannerjfco** [comment]
@cesaragv node03 is the node that disconnected and goes into/stays in BEHIND status

**Comment by cesaragv** [comment]
@tannerjfco We are going to need a little bit more info from the logs. Please, in your `log4j2.xml` configuration, add

```
    <MarkerFilter marker="RECONNECT"              onMatch="ACCEPT"   onMismatch="NEUTRAL"/>
```

in the `<Filters>` section.

Also, add

```
    <RollingRandomAccessFile name="SwirldsPrimaryJsonLog" fileName="swirlds.json" filePattern="swirlds.%i.json">
      <JsonLayout>
        <!-- ensure there is a newline after each entry -->
        <eventEol>true</eventEol>
        <!-- don't add whitespace in the middle of an entry -->
        <compact>true</compact>
        <!-- stack traces are SUPER long in json format, don't include them -->
        <includeStacktrace>false</includeStacktrace>
      </JsonLayout>
      <Policies>
        <SizeBasedTriggeringPolicy size="500 MB"/>
      </Policies>
      <DefaultRolloverStrategy max="1"/>
    </RollingRandomAccessFile>
```

in the `<Appenders>` section.

Finally, add

```
        <MarkerFilter marker="RECONNECT"              onMatch="ACCEPT"   onMismatch="NEUTRAL"/>
```

in `<Loggers> -> <Root> -> <Filters>`

I will open a ticket to enable this logs by default.

**Comment by tannerjfco** [comment]
Here are updated log sets with the updated log4j2.xml in place. Nodes 1 and 3 were preempted again since the last set of logs, and I restarted the hgcapp service on node 3 so there may be multiple start up events for these nodes contained in the logs

[node00 logs](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T23%3A48%3A59/logs/node00-logs.tar.gz?x-goog-signature=1c3df8563b836f3613836c165b4557a10fd4f6596e29c23928c01c28fd366dc28d46812d2142ce5830505cfb12e29e6650ef95eea2aa4223e6815f3bb18eb4dc357fefc6189669b202ba4aec6adf30c41d74db467f28d83f0e92347ffb54be1b0c74ef02236c3c87a9baf421ea366ea67c0c90a878d3932e21b8e0d8bc4232d9dfe5d417a970c31150959df7a76b50b2d7fa0e195f5ef8c1165750c571267c7c0685168f14b8a8d4fe5fce40a85f5667b2ab3a2f001903feffb98674972608e1e297db2386a3c6baad7d576c7cff4bda1d72aeadc03625f3d3d837edc549895bf9f39f6f44a6c8fdfafe3208c2cd56769d0b66fcc3251a7b28e8bd59e8a5d8d6&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T235009Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node01 logs](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T23%3A48%3A59/logs/node01-logs.tar.gz?x-goog-signature=cb23fc1004d606d511ae528181902d812a38a14efbd32e3e3f6797521d0581daed83db4111ce9c43549388fa53e638d59f02c72a432053da934614a6d8ac0cb459c4c9ae472718b1376423a435f2b9e4b9598ee35b072b5fd6c7e4bc58af70575a9152e46613e445d65cdf1749cf7a423cdac8e08b75e53be9afc0bbcc8397747d98f40a05c49f57da0c6b8024354165e16ff2fcfbb821f4f27c6f9652dabb6b3f21798d868b8476d17e795e54006dcfb77863d9d70bcfdeb29582f314950e9b194051d6019dfe1df72a095bc104b598fb3042ead01749862e6132d82886cd31a2fb9d1f199360c1028eed907df2a27d22091e08dec661a051abbcce50c54303&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T235011Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node02 logs](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T23%3A48%3A59/logs/node02-logs.tar.gz?x-goog-signature=8d27aa890ec45e5e03ea460a3aeef02278a4fbf6dbffe647b97e62cc9a91dee4d25d4741ef303e6401cb3c50cd1992829f320acd9ce13ecce5bfcb4a70251a4b46468f772c57744a4e2a92e6242cbfb9fb2d5a0131c6af1419afd3e0efe8ea812e2a7fe849250f0adaae347bad489343d688a39eb12cce5af7455ea42452215bb95237593bcf0b727f0b4f93039af8cf2c8b7650e14b2d5ff1fbb5f245fdcccfef2fa8808681355a0cf99e57b910fa1962b15a1ec7acbc8f5f632938078417cc232c34a6be44efd5fec93247323e2010706dc31a787328053a6c0e7675a1df1991bfede16b14c121b53a316e3f51293bebba4a0218d8e3e382fc07645a7b2c68&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T235013Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node03 logs](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T23%3A48%3A59/logs/node03-logs.tar.gz?x-goog-signature=025d30d1f6c5639a5fad25cc71d1fc844a08d3ec13c625df2193cff27f4150bd0919170876eeb4a0b8bf5fa79afd977049c64adf3cb00a0812eb33553f177f0634a88efa6213b3a48e0497f61b3d8f15f1378ef0e0c2007925957e06b4fa270e5930953d9d9bf257c0882b8101fc4f2fcf09ff17501450e00efc5ce46e739dda17a36d7202c95bddb59497e3f7cf68ea4d144d79d1bccb4781d792370df604e97d67ea00364da99cda47242bf5ee81356943285bff7ff4c732b8e8ff487f0737061d65cd5dc76debdde903035206c8699076745941fefa2b16e174877d630a796d6a0db1e7bd34cb6d323080635a2b45a1fb0e63128ab7b6fa0ed7e4c51abb2f&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T235014Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node04 logs](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T23%3A48%3A59/logs/node04-logs.tar.gz?x-goog-signature=0f8b779d552536fcc0fb3e5ea30e5a27ff05b225cb6bb9e6a0eaeed65c331af09f558041661f655adc0c6f495575d936e4ea24351001ea0b8f3f4c08c206090cb8e9701a1b62a5952c8cdae9cba676d85b0f1a229632ef338c2f7d471b9f7a930db0140f4e82db60e5d2267e51509544c423f05273c4434f6570ab2c232cfddba358f676f6be5990d69c110f53a743a1c176f4b4dc69c975d50269b4c92d915b351310a26ced1ddc9d086359803fe4b43d36fd1b1d8295d0c9712463da3b70c8fe042a9587b3f720cac5ebcb35686794577162cd1ce3e475894854024237566eedcb42ce80ed2600974ef8c0ec6bd3f3c90f770851baa341f03e3025ce5705fe&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T235016Z&x-goog-expires=604800&x-goog-signedheaders=host)
[node05 logs](https://storage.googleapis.com/hedera_node_logs/dev/2020-12-01T23%3A48%3A59/logs/node05-logs.tar.gz?x-goog-signature=2856a39f46b09caabdc154713f0e991bb9066b2c40cd06d2b17bc97ddf68bec68322ab77d5c1751c4cdcf4f91f64d7d71396ab42737a44570717ec14a5abeb8f84bc7e03accd18730db3280902379cc3ef1f65583b03c801e346e2d66dd51a4c26abbd72044f7d81fa17e1090468a719d71ae2fe7e9ca064b65e93764843befb5e2d5bd1d33ad1940c92e4faaec61c260e699ed3278aa97beb5d0b8113100041b617b8d87c8f793fbd3482048254ba2f985696f1a5775cc12865bad41d71602c58b206b9d20688a2251e90eecba7d99af2269bc621eb9b37049d39be80960d0d296021bfd8852ceee4ee57418e748ac2c18a5eac52fc150baaa7d0439ff66c6d&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=235822363393-compute%40developer.gserviceaccount.com%2F20201201%2Fus%2Fstorage%2Fgoog4_request&x-goog-date=20201201T235018Z&x-goog-expires=604800&x-goog-signedheaders=host)

**Comment by cesaragv** [comment]
@tannerjfco are you using blobs? and if so, how big are they?

**Comment by cesaragv** [comment]
It looks like the receiver hangs at

```
2020-12-01 23:39:33.720 INFO  362  SyncCaller - 3 has fallen behind, will try to reconnect with [5, 2, 4]
2020-12-01 23:39:33.725 INFO  433  SyncCaller - Starting reconnect in role of the receiver. {"receiving":true,"nodeId":3,"otherNodeId":5,"round":37644} [com.swirlds.logging.payloads.ReconnectStartPayload]
2020-12-01 23:39:33.726 INFO  133  ReconnectReceiver - 3 sent commStateRequest to 5
2020-12-01 23:39:33.727 DEBUG 365  SyncUtils - 3 received commEventDiscarded from 5 
2020-12-01 23:39:33.762 INFO  138  ReconnectReceiver - 3 got commStateAck from 5
2020-12-01 23:39:33.764 INFO  152  ReconnectReceiver - Starting synchronization in the role of the receiver.
```

and the sender has the exception:

```
2020-12-01 23:39:33.557 ERROR 257  SyncServer - 5 got new connection from 3, disconnecting old one
2020-12-01 23:39:44.003 ERROR 176  SyncListener - ! SyncListener.sync Exception (so incrementing interruptedRecSyncsPerSecond) while 5 listening for 3:
com.swirlds.common.merkle.synchronization.MerkleSynchronizationException: Synchronization failed with exceptions
	at com.swirlds.common.merkle.synchronization.SendingSynchronizer.synchronize(SendingSynchronizer.java:141) ~[swirlds-common-0.7.5.jar:?]
	at com.swirlds.platform.reconnect.ReconnectSender.reconnect(ReconnectSender.java:118) ~[swirlds-platform-core-0.7.5.jar:?]
	at com.swirlds.platform.reconnect.ReconnectSender.execute(ReconnectSender.java:86) ~[swirlds-platform-core-0.7.5.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsgOrException(SyncListener.java:304) ~[swirlds-platform-core-0.7.5.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsg(SyncListener.java:152) [swirlds-platform-core-0.7.5.jar:?]
	at com.swirlds.platform.SyncListener.run(SyncListener.java:104) [swirlds-platform-core-0.7.5.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Comment by qnswirlds** [comment]
@tannerjfco, could you please provide us the details of the following step?

> - run transactions on the network with remaining nodes`

What test suite(s) did you use?

**Comment by tannerjfco** [comment]
We are using the [validation scenarios](https://github.com/hashgraph/hedera-services/tree/master/test-clients/devops-utils/validation-scenarios) suite to perform test transactions on the network

**Comment by tannerjfco** [comment]
I don't know the exact PRs but I am fairly confident several fixes were made to address this issue. We have not reproduced this issue in quite some time, so I am going to close it
