### ISSUE TITLE
Some tests failed with jvmPauseDetectorThread detected JVM paused

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8218]
### Description

Some tests have error in their logs

https://swirldslabs.slack.com/archives/C05MHKR9BJ7/p1692964348025799
https://swirldslabs.slack.com/archives/C05MHKR9BJ7/p1692970196199609

```
2023-08-25 11:23:02.250 132612   WARN  EXCEPTION        <jvm-pause-detector-thread> Browser: jvmPauseDetectorThread detected JVM paused for 1265 ms, allocation pause 990 ms
```

### Steps to reproduce

Run service nightly regression panel `GCP-Daily-Comp-3NReconnect-15N-4C`
This is an intermittent issue, may not be easy to reproduce

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by poulok** [comment]
@JeffreyDallas does this test have the garbage collector flag specified in this ticket? https://github.com/hashgraph/hedera-services/issues/4413

**Comment by JeffreyDallas** [comment]
Did not find the flab being used, I will add it to JRS

**Comment by JeffreyDallas** [comment]
DevOp team has updated JVM option
https://github.com/swirlds/swirlds-docker/issues/779
