### ISSUE TITLE
Unexpected node reconnect 

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8220]
### Description

Slack report URL

https://swirldslabs.slack.com/archives/C05MHKR9BJ7/p1692970196199609

Node 0 fall behind unexpectedly. The purple line in the below charts

```
---- ReconnectValidator FAILED validation ----
<<ERROR>>
Node 4 was not expected to reconnect. (reconnect count: 5)
<<INFO>>
minimumTimeBetweenReconnects is PT-1M
```

![image](https://github.com/hashgraph/hedera-services/assets/39912573/dfb74101-3fcf-4f0c-93a7-cb6fa63abdcd)

### Steps to reproduce

Nightly regression panel of release 0.41 `GCP-Daily-Reconnect-6K-6N-4C`

Intermittent issue hard to reproduce

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by poulok** [comment]
@JeffreyDallas This test is configured with `consensus.roundsExpired = 100`, making it easier for nodes to fall behind. Combined with the very high rounds per second, the node falling behind after being a teacher is not a shock. Was the value changed from 500 to 100 recently?

**Comment by JeffreyDallas** [comment]
No network latency added for release 0.41 tests

![image](https://github.com/hashgraph/hedera-services/assets/39912573/eb0aa8ba-81b9-4aeb-b7d7-b0951875fe13)

**Comment by JeffreyDallas** [comment]
Closing since not happening in the last few weeks
