### ISSUE TITLE
ISS-recoverable-1k-5m: unexpected double ISS

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#8257]
what I see the node was supposed to recover but got an ISS in the same round again
http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20230829-062217-GCP-Daily-ISS-4N/ISS-recoverable-1k-5m/

**Comment by cody-littley** [comment]
- an ISS is intentionally scheduled on node 3 for time T
- before we get to time T,  node 3 saves state X to disk
- when we get to time T, node 3 has an ISS and dies
- when node 3 starts up again, it loads state X
    - this happens fast enough that node 3 does not need to reconnect
- node 3 gets events through gossip and reaches time T a second time
- node 3 intentionally provokes the ISS a second time

To fix this problem, we either need to keep node 3 offline for longer or make the ISS testing tool not ISS after the node is rebooted.

**Comment by lpetrovic05** [comment]
this appears to be the same issue in a different test:
http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20230831-062133-GCP-Daily-ISS-4N/ISS-emergency-recovery-1k-10m/

**Comment by edward-swirldslabs** [comment]
Node 0 has 17 ISS's http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20230904-062051-GCP-Daily-ISS-4N/ISS-emergency-recovery-1k-10m/

**Comment by edward-swirldslabs** [comment]
http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20230906-062255-GCP-Daily-ISS-4N/ISS-recoverable-1k-5m/

Failed after a sea of green.

**Comment by alittley** [comment]
Another failure

http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20230919-062233-GCP-Daily-ISS-4N/ISS-recoverable-1k-5m/
