### ISSUE TITLE
Enable reconnect logs by default

### ISSUE THREAD

**Issue by cesaragv** [hashgraph/hedera-services#831]
**Summary**
Given that reconnect is an operation that is expected to be executed on a non-regular basis, it would be ideal to have the platform logs enable for the `RECONNECT` marker. In the case, an issue arises with reconnect, we would be able to take a look at the logs and validate that it is executing as expecting, or if there is an issue on the platform, or in services, instead of asking to rerun the test with logs enable as in #821 

**Possible resolution**
In `log4j2.xml` and `log4j2.xml` we need to do the following changes:

Add

```
    <MarkerFilter marker="RECONNECT"              onMatch="ACCEPT"   onMismatch="NEUTRAL"/>
```

in the `<Filters>` section.

Also, add

```
    <RollingRandomAccessFile name="SwirldsPrimaryJsonLog" fileName="swirlds.json" filePattern="swirlds.%i.json">
      <JsonLayout>
        <!-- ensure there is a newline after each entry -->
        <eventEol>true</eventEol>
        <!-- don't add whitespace in the middle of an entry -->
        <compact>true</compact>
        <!-- stack traces are SUPER long in json format, don't include them -->
        <includeStacktrace>false</includeStacktrace>
      </JsonLayout>
      <Policies>
        <SizeBasedTriggeringPolicy size="500 MB"/>
      </Policies>
      <DefaultRolloverStrategy max="1"/>
    </RollingRandomAccessFile>
```

in the `<Appenders>` section.

Finally, add

```
        <MarkerFilter marker="RECONNECT"              onMatch="ACCEPT"   onMismatch="NEUTRAL"/>
```

in `<Loggers> -> <Root> -> <Filters>`

These changes were applied on commit [8986a](https://github.com/swirlds/swirlds-platform-regression/commit/8986a2a5306d17134a4d0b98fd8dd62e3b428580) in `regression` to enable the reconnect logs.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
