### ISSUE TITLE
Create and use a withUnavailableNode UtilOp

### ISSUE THREAD

**Issue by cesaragv** [hashgraph/hedera-services#832]
**Summary**
Currently, several reconnect tests wait for a fix amount of time for a node to become unavailable, and then we check its availability as in:

```
sleepFor(Duration.ofSeconds(25).toMillis()),
						getAccountBalance(GENESIS)
								.setNode("0.0.6")
								.unavailableNode()
```

But the 25 seconds is just an approximation of how long we think we need to wait for a node to become unavailable. This hard-coded value has resulted in some test to fail randomly and then pass at the next run, which causes engineering hours to be wasted while trying to troubleshoot the issue.

**Possible resolution**
Just as with [`withLiveNode`](https://github.com/hashgraph/hedera-services/blob/905977d598e4a4fa8c8e482c033da0341bd05729/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java#L113) which uses [`NodeLivenessTimeout`,](https://github.com/hashgraph/hedera-services/blob/905977d598e4a4fa8c8e482c033da0341bd05729/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/pauses/NodeLivenessTimeout.java#L33) we should create a class called `NodeUnavailableTimeout` and its verb `withNodeUnavailable`, to wait for a node to become unavailable, as

```
withNodeUnavailable("0.0.6")
				.within(180, TimeUnit.SECONDS)
				.loggingAvailabilityEvery(30)
				.sleepingBetweenRetriesFor(10),
```

and

```
	public static NodeUnavailableTimeout withNodeUnavailable(String node) {
		return new NodeUnavailableTimeout(node);
	}
```

The idea behind `NodeUnavailableTimeout` is similar to

```
getAccountBalance(GENESIS)
			.setNode("0.0.6")
			.unavailableNode(),
```

where we are using the `unavailableNode()` option. 

Notice that we need to consider the case in which the node is only unavailable for a couple of seconds, and then is active again. This might return assuming the node is down when it really isn't, so we might have to check a couple more times before validating that the node is down. Usually, these parameters are configurable, with certain defaults.

**Comment by tinker-michaelj** [comment]
Done.
