### ISSUE TITLE
Improve NodeLivenessTimeout to support small moments of liveness

### ISSUE THREAD

**Issue by cesaragv** [hashgraph/hedera-services#833]
**Summary**
For our reconnect tests, we execute certain operations while the node to be reconnected is down, and then wait for the node to become available again to start validating. We use `withLiveNode` which returns an object of time `NodeLivenessTimeout` to wait until a node is up again. 
Unfortunately, we have found cases in which the node goes through these states:

1. ACTIVE
2. DISCONNECTED
3. ACTIVE
4. BEHIND
5. ACTIVE

From the step 3 to 4, it might not take long, but `NodeLivenessTimeout` might validated the node to be available at that moment, and then we proceed to query the reconnected node and we get failure.

A workaround that we have for this issue is:

```
withLiveNode("0.0.6")
		.within(60, TimeUnit.SECONDS)
		.loggingAvailabilityEvery(10)
		.sleepingBetweenRetriesFor(5),
UtilVerbs.sleepFor(30 * 1000),
withLiveNode("0.0.6")
		.within(60, TimeUnit.SECONDS)
		.loggingAvailabilityEvery(10)
		.sleepingBetweenRetriesFor(5),
```

That is, we validate the node is available, we sleep for a while, and then validate the node is still available. 

**Possible resolution**
Even though the above solution works, it adds boiler-plate code to our tests that make it harder to read/understand. This logic should be embedded in `NodeLivenessTimeout` with certain parameters to validate a node is actually available.

**Comment by qnswirlds** [comment]
@cesaragv, I think we had discussed this issue and added the workaround solution in our test. I agree that this workaround is hard to read/understand. But I remember pointing out that the correct solution should be from the platform side where we shouldn't have a transition from `DISCONNECTED` to `ACTIVE`. When a node becomes back to `CONNECTED` to the network (which we don't have this kind of status), it should determine whether it is really `ACTIVE` or it is `BEHIND`. @lpetrovic05 , @cody-l, what do you guys think?

**Comment by lpetrovic05** [comment]
I agree, once we the nodes establish connections, we should wait for a successful sync before we switch the status to active. That way we will make sure we are not behind.

**Comment by lbaird** [comment]
It should sync with nodes that (together with itself) have a supermajority of stake, before it sets status to active.

That should happen for both reconnect and restart. In both cases, we want to make sure we know all the latest events before we start creating new events.

________________________________

**Comment by lbaird** [comment]
To be clear, it shouldn’t even create new events until after syncing with the more-than-two-thirds-stake nodes (including itself).

________________________________

**Comment by qnswirlds** [comment]
I created an issue in the platform repo https://github.com/swirlds/swirlds-platform/issues/2780. Please continue our discussion over there. I am closing this issue. Thanks!
