### ISSUE TITLE
Move light TPS JRS regression test flow to pure CircleCi test workflow.

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#836]
**Summary**
Right, we have lots of test workflows in JRS framework. Some of them are just basic functional tests and have very low TPS rate. Running these regression tests in JRS regression is probably not the best use of these resources and also waste of money. 

So it would be better to run the light TPS tests in CircleCi controlled workflow with spot instances.

**Possible resolution**
1. Identify these regressions first. Right now, the AWS-Daily-Services-Comp-Basic-4N-1C's **Misc-Basic-1-11M** is one of them;
2. Either create new worklfows in CircleCi or merge them into existing CircleCi workflow;

**Comment by ljianghedera** [comment]
We can also remove any redundant JRS tests with this issue.

**Comment by Neeharika-Sompalli** [comment]
On a side note, Instead of removing them can we use m4.2xLarge or smaller machines for this test, so it has less cost? If we remove them we won't have correctness tests in regression.

**Comment by ljianghedera** [comment]
Yeah, I thought about that. But there might be something more in there. Spot instances types are different than others, I guess.

**Comment by qnswirlds** [comment]
I tend to agree with @Neeharika-Sompalli. We could use a less expensive type of instances for this kind of test to save cost. In fact, we still have the `continuous-integration` workflow to be used in CircleCI that serves several purposes, including the one described here. Having different JRS suites give developers better options to kick off tests on their own, with or without customization. For CircleCI workflow, they usually have to push a commit to a remote branch to kick off a workflow.

**Comment by ljianghedera** [comment]
Yeah, I agree and also think it's an viable option. Not sure what's the difference of cost between spot instances and the on demand instances. 
I think we can resuscitate this workflow once we have a better overall idea.
