### ISSUE TITLE
Calling non-existing contracts fails and doesn't charge gas

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#8373]
I'm executing the following [test](https://github.com/LimeChain/equivalence-tests/blob/8e6392f3a2d62b2d7bf09c63e45171bcb141f714/test/LowLevelCall.ts#L72), which tries to call a contract that doesn't exist on the target address:
```
  it('should be able to make a top-level CALL to a non-existing contract', async function() {
    const fakeCaller = CallerFactory.attach(invalidAddress);
    const tx = await fakeCaller.testCallFoo(receiverAddress, {gasLimit: 1000000});
    const rc = await tx.wait();
    expect(rc.status).to.be.eq(1);
  });
```

When I execute this test in an Ethereum environment (a local instance of a Besu node), the call succeeds - The EVM loads the code on the target account, which is an empty account with empty code, it zero pads the code string, first opcode is zero -  STOP opcode, so it stops.  Successful execution. 21432 gas is charged and the transaction is successful.

However, when I execute this test in a Hedera environment, the execution reaches [this place in the code](https://github.com/hashgraph/hedera-services/blob/437f16655c5feb2279a61b496e233f56e3ea4f40/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java#L147) and then if fails the transaction and returns status `INVALID_CONTRACT_ID`. No gas is charged and the transaction is not successful. 

This leads to unexpected behavior for smart contract developers who expect such calls to succeed. One example of a broken user flow is described in this issue: https://github.com/hashgraph/hedera-json-rpc-relay/issues/805

**Comment by david-bakin-sl** [comment]
Note the EVM is defined to work this way, see [`evm.codes CALL`](https://www.evm.codes/#f1?fork=shanghai)

**Comment by stoqnkpL** [comment]
Also related to https://github.com/hashgraph/hedera-services/issues/9120 which is for internal calls to non-existing contracts.

**Comment by georgi-l95** [comment]
Fixed already
