### ISSUE TITLE
Upgrade test failed due to could not get hapiVersion

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8381]
### Description

Slack report URL

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1693903863956319

Recent changes in gradle caused the following command could not return correct hapiVersion string value,
which is needed by upgrade test runner

```
./gradlew showHapiVersion --quiet

FAILURE: Build failed with an exception.

* What went wrong:
Task 'showHapiVersion' not found in root project 'hedera-services'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
```

---

Last week, when it still working, it should return hapiVersion string as the following output

```
./gradlew showHapiVersion --quiet
0.40.0-blocks-state-SNAPSHOT
```

### Steps to reproduce

Run nightly regression panel `GCP-Daily-Crypto-Update-Abort-4N-2C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by JeffreyDallas** [comment]
Great. Thanks for the solution

**Comment by jjohannes** [comment]
The best would be

./gradlew :hedera-node:app:showHapiVersion --quiet

Because then you address the task directly. The others only work because Gradle does some fuzzy matching and the task only exists on one project.

**Comment by JeffreyDallas** [comment]
Fixed already in regression repo by updating the logic of querying correct Hapi and Happ version
