### ISSUE TITLE
Intermittent failing unit test Queue Thread Tests -> Queue Max/Min Size Metrics Test - With Thread Start

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#8389]
### Description

The test `Queue Max/Min Size Metrics Test - With Thread Start` failed with a fresh clone while running `./gradlew check`.

### Steps to reproduce

Difficult to reproduce, just chance of hitting it.

### Additional context

```
Queue Thread Tests

    ✔ Single Use Per Config Test
    ✔ Idle Callback Test
    ✘ Queue Max/Min Size Metrics Test - With Thread Start

      java.lang.AssertionError:
      Expecting actual:
        105
      to be less than or equal to:
        100
          at com.swirlds.common.test.threading.QueueThreadTests.testQueueMaxMinSizeMetricsWithThreadStart(QueueThreadTests.java:751)
```

### Hedera network

other

### Version

develop

### Operating system

None

**Comment by lpetrovic05** [comment]
easy to reproduce with `@RepeatedTest(10)`
