### ISSUE TITLE
Balances filename changed from 8.1 to 9.0 

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#842]
The last 8.1 balance was written. 2020-12-03T17_00_00.139802Z
When 9.0 came online it produced. 2020-12-03T19:25:28.087653005Z
This could be considered a bug as it would break windows users from storing that filename format.
This broke at-least one mirrornode implementation that we know of.

(Opened by @jsindy in [swirlds-platform](https://github.com/swirlds/swirlds-platform/issues/2783))

**Comment by tinker-michaelj** [comment]
When updating the exported balances CSV to include token balances, I accidentally stopped substituting `:` characters with `_`. This is a one-line fix.
