### ISSUE TITLE
release 41, reconnect taking a long time. 

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#8433]
http://35.247.76.217:8095/swirlds-automation/release/0.41/4N_2C/UpdateReconnectAbortDisPreUpdate/20230907-104541-GCP-UpdateRecAbort-PreUpdate-4N-2C/Crypto-Update-ND-DisPreUpdate-RecAftFreezeAbort-1.5k-35m/

Node 3 takes 10s to reconnect 100mb. 

previous runs have taken as low as 3s. 
http://35.247.76.217:8095/swirlds-automation/release/0.41/4N_2C/UpdateReconnectAbortDisPreUpdate/20230904-104459-GCP-UpdateRecAbort-PreUpdate-4N-2C/Crypto-Update-ND-DisPreUpdate-RecAftFreezeAbort-1.5k-35m/

**Comment by imalygin** [comment]
This could be fixed with the following PR: 

https://github.com/hashgraph/hedera-services/pull/8434

**Comment by imalygin** [comment]
Once we confirm that the test is passing on `develop`, we can backport it to release/0.42

**Comment by imalygin** [comment]
It is backported to `release/0.42`

https://github.com/hashgraph/hedera-services/pull/8506

**Comment by poulok** [comment]
Great work @imalygin! Can this ticket be closed now?

**Comment by imalygin** [comment]
This test fails and the issue still manifests itself (perhaps, for a different reason). Needs more investigation

**Comment by imalygin** [comment]
I'm closing this issue in favor of https://github.com/hashgraph/hedera-services/issues/8793
