### ISSUE TITLE
Test flake in testFlushCount()

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#8439]
Flake was observed on branch `08392-state-metadata` which does not modify virtual map code in any way.

https://scans.gradle.com/s/vbynihizs2m46/tests/overview?outcome=FAILED#:platform-sdk:swirlds-virtualmap:test-6-com.swirlds.virtualmap.virtualmaptests-515

![Screenshot 2023-09-07 at 1 20 01 PM](https://github.com/hashgraph/hedera-services/assets/56973212/50648d01-0a69-46e3-b78c-ce701d9419b7)

**Comment by imalygin** [comment]
This flake happens because there is a race condition there: 

`com.swirlds.virtualmap.internal.merkle.VirtualRootNode#flush()`:

```
...
        flushLatch.countDown();
        statistics.recordFlush(end - start);
...
```
and in the test:
```
        lastRoot.waitUntilFlushed(); // here we're waiting for it to be flushed
        map1.release();

        // createMap() creates a map labelled "Test"
        Metric metric = metrics.getMetric(VirtualMapStatistics.STAT_CATEGORY, "vmap_lifecycle_flushCount_Test");
        assertNotNull(metric);
        if (!(metric instanceof Counter counterMetric)) {
            throw new AssertionError("flushCount metric is not a counter");
        }
        // and then verify the count
        assertEquals(flushCount, counterMetric.get());
``

Theoretically it is possible to have a case in which the `flushLatch` is already released but the `statistics` is not updated yet.
