### ISSUE TITLE
Test CryptoTransferSuite

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#8466]
- [x] aliasKeysAreValidated
- [x] allowanceTransfersWithComplexTransfersWork
- [x] allowanceTransfersWorkAsExpected
- [x] autoAssociationRequiresOpenSlots
- [x] baseCryptoTransferFeeChargedAsExpected
- [x] cannotTransferFromImmutableAccounts
- [x] dissociatedRoyaltyCollectorsCanUseAutoAssociation
- [x] hapiTransferFromForFungibleTokenWithCustomFeesWithAllowance
- [x] hapiTransferFromForNFTWithCustomFeesWithAllowance
- [x] hbarAndFungibleSelfTransfersRejectedBothInPrecheckAndHandle
- [x] nftSelfTransfersRejectedBothInPrecheckAndHandle
- [x] nftTransfersCannotRepeatSerialNos
- [x] okToRepeatSerialNumbersInBurnList
- [x] okToRepeatSerialNumbersInWipeList
- [x] okToSetInvalidPaymentHeaderForCostAnswer
- [x] royaltyCollectorsCanUseAutoAssociation
- [x] specialAccountsBalanceCheck
- [x] tokenTransferFeesScaleAsExpected
- [x] transferToNonAccountEntitiesReturnsInvalidAccountId
- [x] transferWithMissingAccountGetsInvalidAccountId
- [x] vanillaTransferSucceeds
- [x] https://github.com/hashgraph/hedera-services/issues/9345

**Comment by mhess-swl** [comment]
Some of these tests depend on #9286 (e.g. `complexKeyAcctPaysForOwnTransfer()`)

**Comment by mhess-swl** [comment]
`allowanceTransfersWorkAsExpected` depends on #9321

**Comment by Neeharika-Sompalli** [comment]
Closing this issue . Remaining tests are in this issue https://github.com/hashgraph/hedera-services/issues/9345
