### ISSUE TITLE
Throttles update for perfnet, publictestnet, mainnet

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-services#860]
The public testnet and mainnet will be updated to the following values:

- 2 tps (crypto create)
- 13 tps (contract and file operations) 
- 6,000 tps (crypto operations (excluding crypto create))
- 8,000 tps (consensus submit message and queries)
- 3,000 tps (all consensus operations aside from createTopic and submit message, and all token operations aside from token creations and association)
- 5 tps (createTopic)
- 100 tps (token creations and association)

Receipts will not have a throttle

- [x] Update will first be to perfnet December 11th
- [x] followed by testnet on December 17th
- [x] and Mainnet on January 7th.

**Comment by jsindy** [comment]
@tinker-michaelj can you provide the setting to achieve this? From our conversations yesterday it seemed the only change was to adjust submit message to 8k, correct @donaldthibeau ? I plan to redeploy performance today with the provided changes. Thanks.

**Comment by donaldthibeau** [comment]
Correct

**Comment by donaldthibeau** [comment]
@jsindy ca you confirm we are still on track with these dates and update the issue accordingly?

**Comment by jsindy** [comment]
I will confirm today, and catch us up if we are not.

**Comment by jsindy** [comment]
@donaldthibeau we are now up to date on previewnet and testnet.

**Comment by donaldthibeau** [comment]
@jsindy @atul-hedera updated the crypto create throttle.

**Comment by jsindy** [comment]
@donaldthibeau @SimiHunjan all networks listed above have been updated.

**Comment by SimiHunjan** [comment]
docs updated with new throttle values
