### ISSUE TITLE
[QualityAssurance] Run Smart Contract e2e tests and report failures

### ISSUE THREAD

**Issue by attest08** [hashgraph/hedera-services#8609]
### Problem

his includes the following TestSuites:

- [x]  contract.hapi.ContractCallLocalSuite
- [x]  contract.hapi.ContractCallSuite
- [x]  contract.hapi.ContractCreateSuite
- [x]  contract.hapi.ContractDeleteSuite
- [x]  contract.hapi.ContractGetBytecodeSuite
- [x]  contract.hapi.ContractGetInfoSuite
- [x]  contract.hapi.ContractUpdateSuite
- [x]  contract.opcodes.BalanceOperationSuite
- [x]  contract.opcodes.CallCodeOperationSuite
- [x]  contract.opcodes.CallOperationSuite
- [x]  contract.opcodes.Create2OperationSuite
- [x]  contract.opcodes.CreateOperationSuite
- [x]  contract.opcodes.DelegateCallOperationSuite
- [x]  contract.opcodes.ExtCodeCopyOperationSuite
- [x]  contract.opcodes.ExtCodeHashOperationSuite
- [x]  contract.opcodes.ExtCodeSizeOperationSuite
- [x]  contract.opcodes.GlobalPropertiesSuite
- [x]  contract.opcodes.PrngSeedOperationSuite
- [x]  contract.opcodes.PushZeroOperationSuite
- [x]  contract.opcodes.SStoreSuite
- [x]  contract.opcodes.SelfDestructSuite
- [x]  contract.opcodes.StaticCallOperationSuite
- [x]  contract.openzeppelin.ERC1155ContractInteractions
- [x]  contract.openzeppelin.ERC20ContractInteractions
- [x]  contract.openzeppelin.ERC721ContractInteractions
- [ ]  contract.precompile.ApproveAllowanceSuite
- [x]  contract.precompile.AssociatePrecompileSuite
- [ ]  contract.precompile.AtomicCryptoTransferHTSSuite
- [ ]  contract.precompile.ContractBurnHTSSuite
- [ ]  contract.precompile.ContractHTSSuite
- [ ]  contract.precompile.ContractKeysHTSSuite
- [ ]  contract.precompile.ContractKeysStillWorkAsExpectedSuite
- [ ]  contract.precompile.ContractMintHTSSuite
- [ ]  contract.precompile.CreatePrecompileSuite
- [x]  contract.precompile.CryptoTransferHTSSuite
- [ ]  contract.precompile.DefaultTokenStatusSuite
- [ ]  contract.precompile.DelegatePrecompileSuite
- [ ]  contract.precompile.ERCPrecompileSuite
- [ ]  contract.precompile.FreezeUnfreezeTokenPrecompileSuite
- [ ]  contract.precompile.GrantRevokeKycSuite
- [ ]  contract.precompile.HRCPrecompileSuite
- [ ]  contract.precompile.LazyCreateThroughPrecompileSuite
- [x]  contract.precompile.PauseUnpauseTokenAccountPrecompileSuite
- [ ]  contract.precompile.PrngPrecompileSuite
- [ ]  contract.precompile.RedirectPrecompileSuite
- [ ]  contract.precompile.SigningReqsSuite
- [ ]  contract.precompile.TokenAndTypeCheckSuite
- [ ]  contract.precompile.TokenExpiryInfoSuite
- [ ]  contract.precompile.TokenInfoHTSSuite
- [ ]  contract.precompile.TokenUpdatePrecompileSuite
- [ ]  contract.precompile.TopLevelSigsCanBeToggledByPrecompileTypeSuite
- [ ]  contract.precompile.WipeTokenAccountPrecompileSuite
- [x]  contract.records.LogsSuite
- [x]  contract.records.RecordsSuite
- [x]  contract.traceability.TraceabilitySuite
- [x]  ethereum.EthereumSuite
- [x]  ethereum.HelloWorldEthereumSuite

### Solution

Report the errors found in this Notion report:
https://www.notion.so/limechain/Modularization-Test-Execution-Shared-76aab6e7c85a4fbd82ec68f46dde3125?pvs=4

**Comment by Nana-EC** [comment]
@attest08 did we complete this?
Is the initiative still needed?

**Comment by attest08** [comment]
Resolved
