### ISSUE TITLE
NFT_INFO

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#8641]

**Comment by Nana-EC** [comment]
@IvanKavaldzhiev can you expand the details here, not clear what the task here was and if it's still needed

**Comment by Nana-EC** [comment]
@IvanKavaldzhiev noted that "this task aimed to add a missing precompile for another [ticket 8481](https://github.com/hashgraph/hedera-services/issues/8481). I checked the code and saw that we have NftInfoTranslator for the NftInfo precompile, so the task should be already covered"

Closing as a result
