### ISSUE TITLE
MerkleSynchronizationException during reconnect test

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8652]
### Description

Slack report URL

https://swirldslabs.slack.com/archives/C05R1D74CMC/p1694783007481589

### Steps to reproduce

Nightly regression test panel `GCP-Daily-Comp-3NReconnect-15N-4C`

### Hedera network

other

### Version

release 42 test

### Operating system

None

**Comment by JeffreyDallas** [comment]
The same `MerkleSynchronizationException` incident in latest develop branch

Slack link:

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1701763007295809

GCP result summary:

http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/3NReconnect/20231205-063751-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-Interrupted-2NReconnect-1k-41m/

**Comment by JeffreyDallas** [comment]
This `MerkleSynchronizationException` keeps happening on develop branch since last weekend



![Image](https://github.com/hashgraph/hedera-services/assets/39912573/d19c4197-f9ce-454e-a31d-182d4ad2fb76)

**Comment by alittley** [comment]
Stale
