### ISSUE TITLE
Account balance test failed due to error in client log

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8655]
### Description

Slack report URL

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1694763536105549

```
2023-09-15 07:37:24.517 ERROR  60   CustomSpecAssert - Operation 'HapiGetAccountInfo{node=0.0.3, account=null}' :: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null

```

### Steps to reproduce

Nightly test panel `GCP-Daily-Comp-BalancesValidate-6N-1C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by Neeharika-Sompalli** [comment]
Resolved the error that is posted in #8724 . But now the test fails with [some timing issue](https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1695142438546899). Will post an update after @JeffreyDallas takes a look at it.
