### ISSUE TITLE
Replace CriticalQuorum in sync

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#8664]
The sync protocol currently uses `CriticalQuorum` to decide when it is time to sync with a peer. We should replace this with a much simpler heuristic, as the critical quorum algorithm is no longer relevant when the tipset algorithm is enabled.

**Comment by poulok** [comment]
@cody-littley can this be closed?

**Comment by cody-littley** [comment]
@poulok There's a small PR for this, but there is no need for it to go into the 43 milestone.
