### ISSUE TITLE
DAB Prep: Identify algorithms that need updating

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#8684]
In preparation for an address book that can change daily, several algorithms need to be updated. Make a list of these algorithms in this ticket. These algorithms/sections of the code have been documented in several places, so start with existing documentation. Notion, Github, etc.

**Comment by edward-swirldslabs** [comment]
Durables Classes which hold onto durable references to an AddressBook
* ConsensusRounds 
* CriticalQuorumImpl
* XXXXGossip - All Gossip Classes
