### ISSUE TITLE
Add `isolated` as a boolean option to the `HapiTestSuite` annotation

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#8687]
### Problem

Some tests, such as those related to testing "freeze", leave the network in a state where it cannot be reused for subsequent tests. Yet for efficiency, we create a single network at the start of all test suites, and reuse that same network for all tests.

### Solution

We propose adding an `isolated` boolean to the `HapiTestSuite` annotation. If true, then a new network is created for the duration of that suite and the old one thrown away, and at the end of the suite the network is thrown away and a new fresh one created.

### Alternatives

We could create a new network at the start of each suite, but creating the network takes a lot of time. The network (currently by design) even has a 10second wait at startup. When multiplied by many tests, these startup and teardown operations just take a large amount of time.

We could make such tests manual, but then we don't get as much test coverage since they cannot be run on each PR.

We could add to the test a call to "bounce" the nodes (when that HapiOp is merged) and have it bring the network back into a working state, although that is more of a restart test.

We could remove the freeze test completely and just use the restart tests for it.

**Comment by netopyr** [comment]
What are we going to with suites that require a restart after each test-method? I see three possibilities:

- If the `isolated`-flag is set, we create a new network for each method.
- We add the `isolated`-flag also to the `HapiTest` annotation.
- We split such tests in several suites.
