### ISSUE TITLE
Implement payer account exemption logic

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#8813]
We have `htsOwnershipCheckWorksWithAliasAddress` test from `ContractCallLocalSuite` failing with `INSUFFICIENT_TX_FEE` due to failure in a token mint transaction.
The reason for that seems to be due to transaction fee being set to 0 in `test-clients`. In mono we have[ exemption logic in place for the payer account](https://github.com/hashgraph/hedera-services/blob/f832b996cef64bf557305fd0f07708590c1520c5/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/submission/SolvencyPrecheck.java#L104) for this case to pass, we need the same implemented in modularized.

**Comment by netopyr** [comment]
The payer exempt logic was recently added. The test still fails, but with a different error message: 
```
2023-10-05 10:32:38.798 WARN   262  HapiSpecOperation - 'htsOwnershipCheckWorksWithAliasAddress' - CustomSpecAssert failed - Sender address should match the owner address. ==> expected: <0x7c1E698315a7cAF0c3EFdEF02B7eaE2f2D597c78> but was: <0x0000000000000000000000000000000000000000>!
```

Can you please take another look?

**Comment by MiroslavGatsanoga** [comment]
> The payer exempt logic was recently added. The test still fails, but with a different error message:
> 
> ```
> 2023-10-05 10:32:38.798 WARN   262  HapiSpecOperation - 'htsOwnershipCheckWorksWithAliasAddress' - CustomSpecAssert failed - Sender address should match the owner address. ==> expected: <0x7c1E698315a7cAF0c3EFdEF02B7eaE2f2D597c78> but was: <0x0000000000000000000000000000000000000000>!
> ```
> 
> Can you please take another look?

Alright, I will take a look, thanks.

**Comment by MiroslavGatsanoga** [comment]
It looks like now the test fails [here](https://github.com/hashgraph/hedera-services/blob/fb2c82b5acf55c25ac5904589e3aded6db34e284/hedera-node/test-clients/src/main/resource/contract/contracts/OwnershipCheck/OwnershipCheck.sol#L11), after calling the `getNonFungibleTokenInfo‎` precompile we expect `tokenInfo.ownerId` and `msg.sender` to be equal in the test.
Additionally tried running it against mono and there we also get `responseCode` `SUCCESS(22)` but in modularized we get `UNKNOWN(21)`.

I see https://github.com/hashgraph/hedera-services/issues/8645 is not done yet, so probably after it's completed we can circle back to this one.

cc @netopyr @lukelee-sl
