### ISSUE TITLE
Fix `calculateFees` in FileUpdateHandler

### ISSUE THREAD

**Issue by thenswan** [hashgraph/hedera-services#8861]
**The Context**
[This issue](https://github.com/hashgraph/hedera-services/issues/8849) (StaticCallOperationSuite mod) fails with same error as these two ([#8804](https://github.com/hashgraph/hedera-services/issues/8804), [#8848](https://github.com/hashgraph/hedera-services/issues/8848)) on `develop` branch. 
If I try to run it using branch `08722-contract-call-local-suite-fixes` (PR #8812) — I get `ResponseCodeEnum#INSUFFICIENT_PAYER_BALANCE` in `SolvencyPreCheck.checkSolvency`.

**The Problem**
Seems like `FileUpdateHandler#calculateFees` is doing the wrong fee calculation.

**Comment by thenswan** [comment]
Update: `StaticCallOperationSuite` passed. See #8959 

cc @povolev15

**Comment by povolev15** [comment]
@thenswan thanks for the update but I didn't change anything
