### ISSUE TITLE
Reconnect takes a very long time to complete

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#8870]
In the test `VMerkleDual-NDReconnect-500-60m`, a single reconnect attempt required almost 15 minutes to complete. This causes the "old signed state" error to be thrown on the learning node, since it holds a state for a long time while reconnecting.

```
node3 | 31m 1.762s | INFO | Finished  synchronization  {"timeInSeconds":885.958,"hashTimeInSeconds":0.004,"initializationTimeInSeconds":0.002,"totalNodes":46886462,"leafNodes":23443235,"redundantLeafNodes":19,"internalNodes":23443227,"redundantInternalNodes":11}  [com.swirlds.logging.payloads.SynchronizationCompletePayload]
node3 | 31m 1.762s | INFO | Reconnect data usage report {"dataMegabytes":5013.8723430633545} [com.swirlds.logging.payloads.ReconnectDataUsagePayload]
```

http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20230925-053528-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

**Comment by poulok** [comment]
closing as stale.
