### ISSUE TITLE
Standardize UpdateMeta resolver for Topics

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-services#8906]
### Problem

Tokens throw `INVALID_EXPIRATION_TIME`, but for topic it's expected currently to throw `AUTORENEW_DURATION_NOT_IN_RANGE`

### Solution

Standardize UpdateMeta resolver for Topics to match with the rest of the operations.

**Comment by poulok** [comment]
@georgi-l95 is this still valid? If so, will you please provide more details.
