### ISSUE TITLE
Crypto transfer transactions that also transfer tokens should use a dedicated row in the fee schedule

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#895]
**Summary**
Add a row to the fee schedule for token transfers (crypto transfers with tokens).
Use this row with dedicated coefficients for transfers involving tokens.
If the transfer only has involves hbars, use the original crypto transfer row in the fee schedule.

**Comment by paulmadsenhed** [comment]
I created a new feeschedule file with a new row for a `TokenTransfer` pseudo transaction.

**Comment by tinker-michaelj** [comment]
Done.
