### ISSUE TITLE
Daily-Comp-NetError-4N-1C fails with bad account records exception

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#898]
The test is failing on both AWS and GCP
```
---- HAPIClientValidator FAILED validation ----
<<ERROR>>
java.lang.Exception: Bad account records! :: Bad list size! expected:<0> but was:<1>
```

**Comment by anighanta** [comment]
`ledger.keepRecordsInState=true` has to be set `false` for this test to pass.

**Comment by anighanta** [comment]
Issue for fix created in regression Repo [here](https://github.com/swirlds/swirlds-platform-regression/issues/759)
