### ISSUE TITLE
Some nodes upload corrupted indexes

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#8983]
### Description

In some cases Hedera nodes upload either corrupted files or don't upload index files at all. 

1. Missing index files for the [internal hash store](https://console.cloud.google.com/storage/browser/mainnet-1m/HederaNode2/149668565/tables/fileStore-0/internalHashStoreDisk?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)
2. The file is there but it's effectively empty in the [internal hash store](https://console.cloud.google.com/storage/browser/mainnet-1m/ecstatic-bohr-hivelocitydns-com/149668565/tables/fileStore-2/internalHashStoreDisk?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)

### Steps to reproduce

Look at result of the state validation tool results:
1. [This job ](https://github.com/hashgraph/hedera-state-validator/actions/runs/6383750486/job/17325536100)caught a file that is effectively empty 
2. [This job ](https://github.com/hashgraph/hedera-state-validator/actions/runs/6383750486/job/17325537027)caught missing index file 

### Additional context

Here is the list of nodes with corrupted indexes:
- node00 - LG, hgc-teraswitch-spare
- node09 - DLA piper, hgc-dla-hetzner
- node12 - Deutsche Telekom, hgc-hedera-hetzner2-spare
- node16 - Standard Bank, hgc-oraclecloud-standardbank
- node24 - Servicenow, cc6209
- node25 - Ubisoft, hgc-servermania

And these nodes have index files missing:
- node06 - Zain, HederaNode2
- node03 - Wipro Azure, Insohedbchnvm01 
- node10 - Tata, schgcnode01
- node14  - Avery Dennison, appdbdc44
- node18 - EDF, p0019 

### Hedera network

mainnet

### Version

v0.41.0

### Operating system

None

**Comment by imalygin** [comment]
To understand the root cause I need to know if the reason for the missing files is some unfortunate timing/script issues or the fact that those files were never created or created corrupted in the first place. For that we need access directly to the nodes.

**Comment by rustyShacklefurd** [comment]
[GCP link](https://console.cloud.google.com/storage/browser/mainnet-1m/hgc-oraclecloud-standardbank/149848164/tables/fileStore-4/internalHashStoreDisk?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)

![Screen Shot 2023-10-04 at 2 01 57 PM](https://github.com/hashgraph/hedera-services/assets/18269241/e76e5c89-1123-418b-83bb-6d2a93a923bc)
![Screen Shot 2023-10-04 at 1 58 35 PM](https://github.com/hashgraph/hedera-services/assets/18269241/d24c336b-d010-457e-842d-a7116c5aca2c)

Looks like these are being backed up but there's not much in there.

**Comment by rustyShacklefurd** [comment]
![Screen Shot 2023-10-04 at 2 47 09 PM](https://github.com/hashgraph/hedera-services/assets/18269241/40763fbf-8f2e-4cef-ac23-dba6bfa637a4)
![Screen Shot 2023-10-04 at 1 58 35 PM](https://github.com/hashgraph/hedera-services/assets/18269241/6d902a02-99e3-4591-8281-6cccca8c5099)
Looks like the same files but there is not much in there

**Comment by imalygin** [comment]
After the investigation I made an update to the validation tool confirms, and it confirmed state is valid on all the nodes. So, the initial assumption about corrupted index files was incorrect. 

However, there is a caveat to that: we still have two set of nodes - some nodes behaves as if they have `merkleDb.hashesRamToDiskThreshold` setting configured and that results in missing or empty files in `internalHashStoreDisk` directory and presence of `internalHashStoreRam.hl` file, and the other nodes behaves as if `merkleDb.hashesRamToDiskThreshold ` is not configured or configured to have zero value and, therefore, `internalHashStoreRam.hl` file is missing while index files in `internalHashStoreDisk` are present.

Both scenarios are valid, what bothers me is the inconsistency between the nodes. We need to investigate that further.

**Comment by imalygin** [comment]
Here is an examples of both states:
[`node00` ]( https://console.cloud.google.com/storage/browser/mainnet-new/hgc-teraswitch-spare/149919582/tables/fileStore-2?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) has `merkleDb.hashesRamToDiskThreshold` configured

**Comment by imalygin** [comment]
The first set of nodes is cleared - now they have `internalHashStoreRam.hl` and they work fine. However, the following set of nodes: 

node03 - Wipro Azure, Insohedbchnvm01
node06 - Zain, HederaNode2
node10 - Tata, schgcnode01
node14 - Avery Dennison, appdbdc44
node15 - Dentons, rockx-mainnet-hashgraph-node
node18 - EDF, p0019
node20  - Chainlink, hgc-chainlink-labs-liquidweb
node28 - Cofra Holdings, hgc-contabo-spare-cofra

Have missing backups

**Comment by imalygin** [comment]
Upon further investigation it turned out that these nods are slow when it comes to the backup upload. To prevent validation failures I increased the number of retries https://github.com/hashgraph/hedera-state-validator/pull/64
