### ISSUE TITLE
Investigate reason for performance drop on all performance tests

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#905]
From Dec4th , all the performance tests started failing as `secTransH` reached 160 micro secs. 
After testing, it looks like this is caused by setting `ledger.keepRecordsInState=true` in all the tests.

Investigate the reason for increase in the `secTransH` to 160 micro secs from 60 micro secs when this property is set to true.

**Comment by Neeharika-Sompalli** [comment]
Passed all performance tests on master : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609446373400000

**Comment by tinker-michaelj** [comment]
Do we happen to have the amount of time spent in `FCQueue.offer` and `FCQueue.poll`?

It's been a while since I last profiled with records in state, but IIRC we were spending about the same amount of time on `FCMap` and `FCQueue` operations.

**Comment by Neeharika-Sompalli** [comment]
Closing the issue as it is fixed on platform https://github.com/swirlds/swirlds-platform/issues/2831
