### ISSUE TITLE
isFrozen - match mono service behavior

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#9063]
### Problem

Match mono service behavior on incorrect input

### Solution

Match the output for `isFrozen` from [this](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/resource/call-results-snapshot.json) document for 
1. static context
a. incorrect account_id
b. incorrect token_id 
2. non-static context 
a. incorrect account_id
b. incorrect token_id

**Comment by Nana-EC** [comment]
Done as part of https://github.com/hashgraph/hedera-services/issues/9075
