### ISSUE TITLE
Epic - Match mono service behavior for incorrect input for HTS calls

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#9075]
### Problem

Mono service behavior for HTS calls when given incorrect input can be seen in [this](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/resource/call-results-snapshot.json) document.

To support compatibility between modularized service and mono service we need to match the existing behavior for the following calls

- [x] #9063 
- [x] #9064 
- [x] #9065 
- [x] #9066 
- [x] #9067 
- [x] #9068 
- [x] #9069 
- [x] #9070 
- [x] #9071 
- [x] #9072 
- [x] #9073 
- [x] #9074 

### Solution

Implement code to match the results of mono service for each of the calls above.

**Comment by Nana-EC** [comment]
@lukelee-sl is this item completed or is the status valid?

**Comment by lukelee-sl** [comment]
Issue has been addressed previously.
