### ISSUE TITLE
Test Crypto-Restart-Stake-2.5k-10m failed due to did not turn ACTIVE within 300 seconds 

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#9111]
### Description

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1696750957782539
https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1696753151193759
https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1696750957782539

### Steps to reproduce

Nightly regression run `Crypto-Restart-Stake-2.5k-10m`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by JeffreyDallas** [comment]
Failed test

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1696839931118799

The newly added node0004 stuck at BEHIND, could not enter ACTIVE mode

Previously passed tests

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1696580841678729

**Comment by JeffreyDallas** [comment]
Node0004 sent reconnect request to other nodes, but got denied due to 

`Rejecting reconnect request from node 4 because this node isn't ACTIVE`

**Comment by alittley** [comment]
This doesn't appear to be a platform failure to me. Rather, a test configuration problem

The reconnect request is rejected because the 4 original nodes have an ISS while replaying PCES

**Comment by JeffreyDallas** [comment]
Thanks for the update.
Please assign someone from platform team to investigate the new ISS failure.

**Comment by JeffreyDallas** [comment]
Freeze issue resovled

But nonr-restart node still reported invalid signature issue.

http://35.247.76.217:8095/swirlds-automation/develop/5N/UnevenStake/20231014-074034-GCP-RestartWithNewNodes-UnevenStake-5N/Crypto-Restart-Stake-2.5k-10m/

Node0004 log:

```
2023-10-14 07:54:15.739 486      FATAL EXCEPTION        <<platform-core: thread-cons 2>> ConsensusHashManager: Invalid State Signature (ISS): this node has the wrong hash for round 326.

```

**Comment by alittley** [comment]
Stale
