### ISSUE TITLE
Elaborate HTS javadoc

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#912]
**Summary**
Method-by-method, the HTS codebase is generally quite readable, but some class interactions (e.g. the `HederaTokenStore` with the `HederaLedger`) could use more high-level documentation.

**Possible resolution**
Add Javadoc to HTS components with an emphasis on component interaction patterns.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
