### ISSUE TITLE
Making an internal call to a non-existing contract reverts the transaction

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#9120]
When the following scenario is executed in Hedera and in Ethereum:
`EOA` -call→ `Caller` -call→ `Receiver`, where `Receiver` doesn’t exist on the address that's called.

Note that the internal call (`Caller` to `Receiver`) does not forward any value. That would change the scenario to an auto-account creating scenario.

In Ethereum, this internal call executes successfully and returns (bool success, bytes data) -- (1, 0x0).
In Hedera, we have a check on each internal call that validates the target address. If it’s not an existing contract that can be called, the whole transaction is reverted.

This causes unpredictable inequivelent behavior. For example, this causes multicall scenarios to revert unexpectedly (ref https://github.com/hashgraph/hedera-json-rpc-relay/issues/805).
Also related to https://github.com/hashgraph/hedera-services/issues/8373 which is for top-level calls to non-existing contracts.

**Comment by georgi-l95** [comment]
Resolved and checked by https://github.com/hashgraph/hedera-smart-contracts/pull/671
