### ISSUE TITLE
Fix ContractDeleteSuite tests

### ISSUE THREAD

**Issue by vtronkov** [hashgraph/hedera-services#9124]
Two tests in `ContractDeleteSuite` are failing: `cannotSendValueToTokenAccount` and `cannotUseMoreThanChildContractLimit `.
One of them is failing due to **MAX_CHILD_RECORDS_EXCEEDED** not being implemented, and the other is failing due to a fee implementation error.

According to this comment from Michael Thinker https://github.com/hashgraph/hedera-services/pull/8911#pullrequestreview-1663674291 - we still need to figure out how records are managed to be able to implement the MAX_CHILD_RECORDS_EXCEEDED validation.

**Comment by MiroslavGatsanoga** [comment]
Closing this issue, we have https://github.com/hashgraph/hedera-services/issues/8920 which should fix the only `ContractDeleteSuite` test left (i.e. cannotSendValueToTokenAccount).
