### ISSUE TITLE
Restart test failed due to expected freeze payload message was not found in swirlds.log

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#9130]
### Description

Multiple restart test failed

https://swirldslabs.slack.com/archives/C03F23RBDDF/p1696839367713899

Because the validator expecting SetFreezeTimePayload or ApplicationDualStatePayload
after NodeStartPayload

<img width="723" alt="image" src="https://github.com/hashgraph/hedera-services/assets/39912573/5daa13b5-667b-4272-817a-0bb9f255e8a7">

### Steps to reproduce

Nightly regression `GCP-Daily-Restart-4N`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by alittley** [comment]
From what I can tell based on these test logs, your state machine is reaching `DONE` earlier than expected. It's not that there are missing messages, just that they arrive at a different state than expectedc

```
Node 0 unexpected payload com.swirlds.logging.payloads.NodeStartPayload encountered while in state DONE
Node 0 received setFreezeTime after DONE
Node 0 received setLastFrozenTime after DONE
Node 0 froze 1 times, didn't match expected frequency of freeze: 2 
Node 1 unexpected payload com.swirlds.logging.payloads.NodeStartPayload encountered while in state DONE
Node 1 received setFreezeTime after DONE
Node 1 received setLastFrozenTime after DONE
Node 1 froze 1 times, didn't match expected frequency of freeze: 2 
Node 2 unexpected payload com.swirlds.logging.payloads.NodeStartPayload encountered while in state DONE
Node 2 received setFreezeTime after DONE
Node 2 received setLastFrozenTime after DONE
Node 2 froze 1 times, didn't match expected frequency of freeze: 2 
Node 3 unexpected payload com.swirlds.logging.payloads.NodeStartPayload encountered while in state DONE
Node 3 received setFreezeTime after DONE
Node 3 received setLastFrozenTime after DONE
Node 3 froze 1 times, didn't match expected frequency of freeze: 2 
<<INFO>>
```

**Comment by alittley** [comment]
The test failures were the result of 2 distinct problems

- https://github.com/swirlds/swirlds-platform-regression/issues/3785
- https://github.com/swirlds/swirlds-platform-regression/issues/3786
