### ISSUE TITLE
Allow underscore in converters

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#9184]
### Problem

Some of the default values we use in our configuration are high numbers, which are hard to read, e.g.:
```
@ConfigProperty(defaultValue = "25000000000000000") @NetworkProperty long startThreshold
```

### Solution

Allow underscores in numbers, e.g.:
```
@ConfigProperty(defaultValue = "25_000_000_000_000_000") @NetworkProperty long startThreshold
```

**Comment by david-bakin-sl** [comment]
See also #9589 for property files (for mono service).

**Comment by poulok** [comment]
Completed in https://github.com/hashgraph/hedera-services/pull/9682
