### ISSUE TITLE
Serialization/deserialization overhead in MerkleDb during reconnects

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#9225]
### Problem

When a `VirtualMap` is synchronized during reconnects, on the teacher side, leaves and hashes are deserialized when read from disk only to be serialized again, albeit with different methods, before they are sent over the wire.
On the learner side, the received bytes are deserialized in order to be inserted into `VirtualMap` and serialized again, albeit with different methods, for hashing and separately for recording in `MerkleDb`.

### Solution

There are two levels of solution:
* implement a shortcut on the teacher side, so that bytes are sent over the wire in the same form as they are read from disk; the equivalence of different serde methods needs to be verified/established; this solution alone can greatly reduce memory pressure on the teacher side.
* have `VirtualMap`/`MerkleDb` work with immutable `byte[]` arrays for keys/values and move all serde up the stack to consumers.

**Comment by artemananiev** [comment]
This idea happened to be very hard, if possible at all, to implement. See my comment to the PR.

If in the future (after switching to PBJ) we get back to this idea, it will be tracked in a separate ticket.
