### ISSUE TITLE
Use OptionValidator.isValidExpiry for all expiry validation

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#927]
**Summary**
`TokenCreateTransitionLogic` uses an inline check instead of the `OptionValidator.isValidExpiry` method.

**Possible resolution**
Always validate expiries with `OptionValidator.isValidExpiry`.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
