### ISSUE TITLE
Standardize validation of auto-renew durations and expiries between TokenCreate/Update

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#928]
**Summary**
Validation of auto-renew durations and expiries are placed somewhat unpredictably across the syntax check and state transition implementations of `TokenCreate` and `TokenUpdate`.

**Possible resolution**
Move validation of expiry and auto-renew duration to the `TransitionLogic.syntaxCheck` of both `TokenCreate` and `TokenUpdate`.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
