### ISSUE TITLE
Add record and event stream design doc to /docs folder

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-services#932]
Link to doc: https://hederatest.sharepoint.com/:w:/s/Engineering/EZIuSuJ9eSZOkbCfu0HEa6AByPTaV0ixTfSXeDg7153IvQ?e=oonPwj

**Comment by SimiHunjan** [comment]
Instead of having a word document being attached as a file download can we please convert this to markdown format and post in the /docs folder.

**Comment by SimiHunjan** [comment]
The sections in the word document should be separated to docs/streams/eventstream.md for event stream information and docs/streams/recordstream.md for record stream information. Sample files should be included for each.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
