### ISSUE TITLE
Test Coverage Stability Issue

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#94]
This issue is to:

Prioritize the possible improvements; and,
Create a roadmap to complete them in priority order.
Infrastructure reliability

Use dedicated AWS nodes (instead of spot nodes) to run "priority" workflows, e.g. dev CI and nightly regression workflows. This will also require us to enhance our buildscripts to target the appropriate infrastructure based on the branch. :: 8 hrs
Retry Terraform spot node provisioning until successful (current buildscript will fail job) :: 8 hrs
Keep spot node capacity higher by reusing a single testnet per workflow (not per job). :: 12 hrs
Increase all timeouts to accommodate slow network etc. :: 2 hrs
Upon failure of run-umbrella-freeze-restart steps, scan swirlds.log for signs of well-known network issue and exit with return code 0 + a message in Slack @ the last Git commit author to consider retrying the build. :: 12 hrs
Better standards and practices in team AWS VPC creation. :: 2 hrs
Buildscript quality

Improve log scanning to identify legitimate build failures, upload node logs to S3, and send the S3 link to hedera-regression Slack channel. :: 12 hrs
Refactor Terraform and Ansible CLI invocations into Python client library calls. :: 96 hrs
Refactor the numerous helper shell scripts into Python modules. :: 36 hrs
Templatize the Circle.ci's config,yml file to remove the redundancy of the definitions of jobs, workflows, etc.
Test client improvements

Investigate possible UmbrellaTest client issues, such as the management of pubKey -->> privKey map for contracts; fix if client errors are confirmed. :: 24 hrs
Investigate edge cases of record file hash calculation to ensure RecordStreamValidation doesn't fail incorrectly. :: 8 hrs
Redesign and improve memory usage in HapiSpecRegistry so the EET client works for load and longevity testing. :: 12 hrs
Complete the EET UmbrellaTest replacement for all transaction and query types; incorporate into the continuous-integration and regression workflows at appropriate TPS targets. :: 24 hrs

**Comment by qnswirlds** [comment]
Since we moved to JRS, I are not using AWS and Terraform any more. Closing this issue.
