### ISSUE TITLE
Publish next-gen svctools Docker image to GCR 

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#940]
**Summary**
Various Hedera roles are using the [`svctools` Docker image](https://github.com/hashgraph/hedera-services/blob/master/test-clients/devops-utils/sysfiles-update/Dockerfile), but this is only available by direct interaction with Engineering.

**Possible resolution**
Improve usability and documentation of the `svctools` image; publish it to the `gcr.io/hedera-registry` public registry and evolve in a principled way.

**Comment by anighanta** [comment]
Commands implemented
- [ ] Account Balance
- [ ] Base Fee for transactions
- [ ] System File upload / download


- [ ] pushed to gcr.io/hedera-registry

**Comment by anighanta** [comment]
Created a new issue in milestone 0.14.0 https://github.com/hashgraph/hedera-services/issues/1168 got Throttles Update. 
Closing this issue.
