### ISSUE TITLE
Conditional records of hollow account creation via internal value transfer.

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#9423]
Validate the below happy path scenarios:
 - [x] An `EthereumTransaction` sending value to an absent `to` address (outside long-zero range) generates a preceding child with a synthetic `CryptoCreate` and `TransactionRecord` identical that created by mono-service when it resolves to `SUCCESS`: https://github.com/hashgraph/hedera-services/pull/10539
 - [x] A `ContractCreate` with an internal message call to a `MessageFrame` with absent `receiver` address (outside long-zero range) with sufficient gas generates a preceding child with a synthetic `CryptoCreate` and `TransactionRecord` identical that created by mono-service: https://github.com/hashgraph/hedera-services/pull/11163

And validate the below failure scenarios:
 - [x] An `EthereumTransaction` sending value to an absent `to` address (outside long-zero range) generates no preceding child when it resolves to `INSUFFICIENT_GAS`: https://github.com/hashgraph/hedera-services/pull/10539
 - [x] A `ContractCall` with 4 internal message calls to `MessageFrame`s with absent `receiver` addresses (outside long-zero range) with sufficient gas generates no preceding children because the fourth message call reverts with a `MAX_CHILD_RECORDS_EXCEEDED` reason: https://github.com/hashgraph/hedera-services/pull/10631
 - [x] A `ContractCall` that performs a valid lazy creation in a frame at stack depth 2, and then reverts that frame, generates no preceding children even when the frame at stack depth 1 deals with its child's reversion via a `try`-`catch`: https://github.com/hashgraph/hedera-services/pull/11131

**Comment by vtronkov** [comment]
All happy path scenarios are done
