### ISSUE TITLE
Unconditional, enriched, traced records of payable HTS system contract calls.

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#9429]
Validate the below happy path scenarios:
 - [x] For a respectable sampling of (5-6 different) payable system contracts other than `TokenCreate` variants, the synthetic `ContractCallResult`s found on their success records match those from mono-service.
 - [x] The `TokenCreate` variants match their mono-service records upon `SUCCESS`.

And the failure scenarios:
 - [x] For a respectable sampling of (5-6 different) of read-only system contracts, the synthetic `ContractCallResult`s found on their unsuccessful records match those from mono-service.
- [x] The `TokenCreate` variants match their mono-service records on unsuccessful outcomes including: `INSUFFICIENT_GAS`, insufficient non-gas fee payment, and other.

**Comment by thenswan** [comment]
**Validate the below happy path scenarios:**

For a respectable sampling of (5-6 different) payable system contracts other than TokenCreate variants, the synthetic ContractCallResults found on their success records match those from mono-service.
- `ClassicGrantApprovalCall` (PR #9649)
- `setapproval` (PR #9649)
- `mint` (PR #9795)
- `burn` (PR #9795)
- `associations` (PR #9795)
- `ClassicTransfersCall` (PR #9795)
- `Erc20TransfersCall` (PR #9957)

 The TokenCreate variants match their mono-service records upon SUCCESS.
- ...

**And the failure scenarios:**

 For a respectable sampling of (5-6 different) of read-only system contracts, the synthetic ContractCallResults found on their unsuccessful records match those from mono-service.
- ...

 The TokenCreate variants match their mono-service records on unsuccessful outcomes including: INSUFFICIENT_GAS, insufficient non-gas fee payment, and other.
- `createFungibleToken` via `ClassicCreatesCall` (PR #9795 and #9792)
- `createNonFungibleToken` via `ClassicCreatesCall` (PR #9795 and #9792)
