### ISSUE TITLE
Reconnect abort is not thread safe

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#9450]
```
new ReconnectTeacher(
                            threadManager,
                            connection,
                            reconnectSocketTimeout,
                            connection.getSelfId(),
                            connection.getOtherId(),
                            state.get().getRound(),
                            fallenBehindManager::hasFallenBehind,    <-- will abort reconnect if returns true
                            reconnectMetrics,
                            configuration)
```

When a node falls behind while it is teaching, the reconnect protocol attempts to abort. However, this abort operation is asynchronous. The reconnect protocol may still be sending data over the socket by the time that control is returned back to the protocol negotiator. This may cause bytes from both sources to intermingle.

Even if aborting a reconnect is fully synchronous, there are problems. Unless the reconnect-abort procedure is closely coordinated with the learner, it is very unlikely that the connection will be salvageable. Unless the learner knows exactly which bytes should be discarded w.r.t. the failed reconnect, its stream alignment will be wrong, and it won't be able to interpret the bytes sent by the protocol negotiator.

We either need to break the socket when we want to abort a reconnect, or we need to coordinate the operation with all threads on both the teacher and the learner.

**Comment by lpetrovic05** [comment]
@cody-littley 
Why do we abort the reconnect if we fall behind? Removing this feature seems like the simplest option.

**Comment by lpetrovic05** [comment]
The proposed solution to this is:
- Do not abort the sync as a teacher, even if we do fall behind
- Prevent a node from being a learner while its still teaching
