### ISSUE TITLE
AccountDeleteTransaction() Not working (Testnet & Mainnet)

### ISSUE THREAD

**Issue by Topachi** [hashgraph/hedera-services#9458]
### Description

When you try to delete a hedera account ID with a simple AccountDeleteTransaction script (tried with Javascript SDK), the network just returns error `ACCOUNT_ID_DOES_NOT_EXIST` 

### Steps to reproduce

1. Create simple script to delete an account on Hedera (tested with Javascript SDK)
2. Make sure you have an account to be deleted
3. run AccountDeleteTransaction script
4. check outcome

### Hedera network

mainnet, testnet

### Version

latest

### Operating system

macOS

**Comment by gregscullard** [comment]
Confirming Java SDK returns the same error, sounds like it's not an SDK issue.

**Comment by netopyr** [comment]
In such cases, we always return `ACCOUNT_ID_DOES_NOT_EXIST`. 

If the account does not exist, we return `INVALID_ACCOUNT_ID`.
