### ISSUE TITLE
Fix SteadyStateThrottlingCheck

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#9507]
To make this work, the order of the tests has to be enforced. This will be possible once support for `@Order` was added to the test framework (#9437).

**Comment by vtronkov** [comment]
@netopyr After implementing the `@Order` annotation(https://github.com/hashgraph/hedera-services/pull/9510) I tried to run the suite locally:
<img width="445" alt="Screenshot 2023-10-27 at 12 00 47" src="https://github.com/hashgraph/hedera-services/assets/99957253/180832d3-87d8-4487-b31e-d790eaab1c0c">
- 3 of the test are passing
- 2 of the tests are failing
- 4 of the tests are taking around 3 minutes(that's 12 minute added to each build)
- The last test(`checkBalanceQps`) took 40 minutes and it's still executing(this might be a throttle issue and after fixing it it might took less time)

This is just FYI for the person who starts working on that. We should also note that it will increase the build time with at least 12 minutes.

**Comment by netopyr** [comment]
Thanks, good to know. We should tag the suite with `@Tag("TIME_CONSUMING")` and run them in a separate step on CI.

We should also introduce a class with all tags in use.

**Comment by petreze** [comment]
Fixed in the following [PR](https://github.com/hashgraph/hedera-services/pull/10786)
