### ISSUE TITLE
Reconnect validator fails for slow reconnect

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#9528]
```
---- ReconnectPerformanceValidator FAILED validation ----
<<ERROR>>
Reconnect took 20.87 seconds to transmit 87.11782455444336 mb.
```

Test: http://35.247.76.217:8095/swirlds-automation/develop/4N/Genesis/20231026-053742-GCP-Daily-Genesis-4N/FCM-GenesisReconnect-2.5k-15m/

If this is slower than we are willing to tolerate, we should investigate this as a performance regression. If this is not too slow, then we should relax our test thresholds.

**Comment by lpetrovic05** [comment]
This seems to be an issue in another test as well
http://35.247.76.217:8095/swirlds-automation/develop/6N/Migration/20231027-090720-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/

**Comment by cody-littley** [comment]
The change that introduced this slowdown has been disabled.
