### ISSUE TITLE
Unit Test Flake: testCompactionWithNullNullables()

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#9556]
The test failed in a branch of mine with unrelated changes. `com.swirlds.merkledb.MerkleDbCompactionCoordinatorTest.testCompactionWithNullNullables()`

https://scans.gradle.com/s/knuhvm2yhlg5a/tests/overview?outcome=FAILED
https://github.com/hashgraph/hedera-services/actions/runs/6670617402/job/18130886398?pr=9554

**Comment by imalygin** [comment]
There is another ticket related to that - https://github.com/hashgraph/hedera-services/issues/9559 -, and I believe this PR will fix it

https://github.com/hashgraph/hedera-services/pull/9560
