### ISSUE TITLE
Property files should handle `_` as a numeric separator

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#9589]
### Problem

A couple of us lost several hours today because we didn't realize that you couldn't use `_` as a numeric separator in property files.  A PR had added some numeric values that way and lots of HAPI tests failed.

There was a `NumberFormatException` in the logs pointing to one of those values. Took out the `_` and all the tests succeeded. 

_Strange thing is that there were **already** a few values with underscores in the property files_ - they didn't cause any tests to fail.  Don't know why.  Also don't know how that impacted the nodes in production, if it did.  But it's a trap waiting for more victims.

### Solution

Make the property file parsers accept `_` in numeric literals just like Java does.

### Alternatives

Doing nothing.  Would be a solution but not be ideal: Someone else will get bit and learn the hard way that property files don't accept `_`.

**Comment by poulok** [comment]
Completed in https://github.com/hashgraph/hedera-services/pull/9682
