### ISSUE TITLE
Tool to remove GDPR data (file and transaction) Record & Event stream files

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#96]
Tool to remove GDPR data (file and transaction) Record & Event stream files
Tool to remove an offending transaction and file contents from Record & Event stream file sequence
Input - Transaction ID / Transaction Consensus Time, record & file stream files (files covering window of time, preceding and and following transaction consensus time)
Output - Event & Record files with offending transaction & file contents removed (write out 2 distinct files. Both files should be able to support validation of the running  hash on the stream files.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
