### ISSUE TITLE
ISS-recoverable-1k-5m failed to fall behind

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#9613]
http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20231101-062252-GCP-Daily-ISS-4N/ISS-recoverable-1k-5m/

Austin indicated that the validators are expecting the node to fall behind after it comes back up after recovering from the ISS.  The node did not fall behind as expected.  

```
---- PlatformStatusValidator FAILED validation ----
Node 3: Transitioning to CHECKING from OBSERVING is not a valid status for step 7 [StatusProgressionStep{targetStatus=BEHIND, optionalInterimStatuses=[], requiredInterimStatuses=[], observedStatuses=[CHECKING]}]
```
```
---- ReconnectValidator FAILED validation ----
<<ERROR>>
Node 3 was expected to reconnect at least 1 time.  (reconnect count: 0)
<<INFO>>
minimumTimeBetweenReconnects is PT9M
minimumTimeBetweenReconnects is PT9M
minimumTimeBetweenReconnects is PT9M
minimumTimeBetweenReconnects is PT9M
```

**Comment by alittley** [comment]
Additional occurrence: http://35.247.76.217:8095/swirlds-automation/release/0.44/4N/ISS/20231114-103920-GCP-Daily-ISS-4N/ISS-recoverable-1k-5m/

**Comment by edward-swirldslabs** [comment]
I will modify the validator to tolerate not falling behind.
