### ISSUE TITLE
Complete test coverage for hedera services R5 

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#97]
Verify and add the missing EET test coverages for hedera services based on the spreadsheet: 

https://hederatest.sharepoint.com/:x:/r/sites/Engineering/_layouts/15/Doc.aspx?sourcedoc=%7Bc7433ff8-1de9-4201-ad0c-625df409c686%7D&action=edit&activeCell=%27HAPI-Services%20Validations%27!L3&wdInitialSession=edcb6b75-aef5-4fff-9a43-d43b884fba26&wdRldC=1

Here are tips to to fill in the table: 
1. Need both positive and negative test cases for coverage; If only positive or negative available, just put 'positive' or 'negative' for the moment and add the missing test cases;
2. Test scenarios can be vague as there may be lots of corner cases may need more time and effort to come up with complete coverage, minimum requirement is to create basic normal scenarios for both 'positive' and 'negative' side testing before put 'yes' in the cell;

I feel it's better to create a new issue to focus the test coverage per discussion of today's scrum. 

Quan, if you think the scope is too large for one issue, please feel free to create separate issue(s) to track system side functionality EET coverages.

**Comment by qnswirlds** [comment]
We've been adding a lot of EET tests both for functionalities and regressions. Closing this issue. Will open new issues for future EET requirements.
