### ISSUE TITLE
HIP-844 Work Package 1/1: Address account nonce discrepancies

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#9728]
### Abstract / Motivation

Introduce clear rules for when to update an Ethereum transaction signer's nonce and a new field for externalising the nonce update in the record stream. This will help resolve issues where the Consensus nodes and the Mirror nodes are out of sync in regards to what the current value of an account's nonce is.

### Specification

1. The nonce of a signer of an Ethereum transaction should be increased for all transactions that are executed _in the EVM_.
2. Transactions that have reached consensus and are handled by the node but have failed additional validations performed by the node _prior to being executed in the EVM_ should have **no effect** on the Ethereum transaction signer nonce.
3. A new protobuf field in the record stream - `signerNonce` - should be populated by the node with the current value of the signer account nonce _after_ executing the transaction. This value should be used by the Mirror nodes when importing record stream files.

### Protobuf update

Add a new protobuf field to contract_call_local.proto:
```
message ContractFunctionResult {
    
    [...]

    /**
     * If not null this field specifies what the value of the signer account nonce is post transaction execution. 
     * For transactions that don't update the signer nonce, this field should be null.
     */
    Int64Value signer_nonce = 15;
}
```

### Services update

1. Move the signer nonce update to be right before this code block that starts the EVM:
```
while (!messageFrameStack.isEmpty()) {
   process(messageFrameStack.peekFirst(), tracer);
}
```
2. Populate the new protobuf field when externalising the transaction.
3. Fix in mono and mod codebase

### Mirror node update

1. When importing transactions from the record stream, update the value of the signer account's nonce that's persisted on the mirror node side with the value externalised in the new protobuf field.
2. When importing legacy transactions that don't have this field, the Mirror node should consider whether the transaction result is `SUCCESS` or `CONTRACT_REVERT_EXECUTED` and increment the signer nonce in these cases. Some statuses such as `INSUFFICIENT_GAS` can be returned both before and after entering the EVM, there is no way for the Mirror node to know whether the signer nonce should be updated. This was the root cause of multiple issues and the reason for the new protobuf field.

### Testing

Different scenarios should be covered with transactions failing due to 
- precheck validations
- handle validations
- EVM reverts from smart contract logic or insufficient gas, account amounts
- EVM reverts due to Hedera-specific validations like system account validations
- EVM reverts due to Hedera-specific validations like resource validations (e.g. preceding child record slots availability)
And different successful scenarios as well:
- Ethereum transaction with a simple transfer
- Ethereum transaction with a creation
- Ethereum transaction with a call with multiple layers, some reverting internal calls, etc

### Related issues
https://github.com/hashgraph/hedera-services/issues/9149 
https://github.com/hashgraph/hedera-services/issues/9310
https://github.com/hashgraph/hedera-services/issues/9459
https://github.com/hashgraph/hedera-mirror-node/issues/6831
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1803
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1791
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1711

**Comment by stoqnkpL** [comment]
This may not be the desired behavior, will update the ticket after further discussions.

**Comment by Nana-EC** [comment]
> Hey @stoqnkpL I just wanted to confirm if account `0xE1CB04A0fA36DdD16a06ea828007E35e1a3cBC37` will have its nonce reset to 0 or at least its `signerNonce` on both testnet and mainnet.

Hey @mshakeg not an easy answer given the implications as noted in those related issues.
We're pondering on it, thanks.

**Comment by Nana-EC** [comment]
Hey @mshakeg 
Wanted to circle back and highlight advancement towards a resolution.
Please see https://hips.hedera.com/hip/hip-844
This is one component needed to properly resolve and avoid this issue going forward.

We plan to share more details on a resolution that you and other users can use to unblock yourself of similar issues.
It needs to be self service solution as the network itself should not be resetting or modifying an accounts settings

**Comment by mshakeg** [comment]
@Nana-EC thanks, hopefully I can convince the safe global team to resign that tx but with the next nonce i.e. 1

**Comment by Nana-EC** [comment]
> @Nana-EC thanks, hopefully I can convince the safe global team to resign that tx but with the next nonce i.e. 1

Hey @mshakeg 
It might not have been clear, but the resolution isn't complete yet.
We're still working on some items, so I wasn't expecting the safe team to take any action just yet.

Short version is any account should be able to delete their own account and recreate using the appropriate keys assuming no collisions.
This will create a new account with a different account ID but with the desired evm address and a nonce of 0.
This requires a network upgrade and utilization of the SDK prior to reatteping the contract creation.

We'll update this thread once all the necessary components have been designed, implemented and deployed to testnet and mainnet.

**Comment by piyush-chittara** [comment]
I could observe error nonce too low intermittently while using etherjs for hedera contract calls, it starts working sometimes and sometimes fails.

Error: nonce has already been used [ See: https://links.ethers.org/v5-errors-NONCE_EXPIRED ] (error={"name":"ProviderError","_stack":"ProviderError: [Request ID: 39b783cc-2141-4cca-94dd-99959fbbab38] Nonce too low. Provided nonce: 2341, current nonce: 2341\n    at HttpProvider.request (/Users/piyush/Desktop/work/streamNFT/evm/EVM/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at EthersProviderWrapper.send (/Users/piyush/Desktop/work/streamNFT/evm/EVM/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)","code":32001,"_isProviderError":true}, method="sendTransaction", transaction=undefined, code=NONCE_EXPIRED, version=providers/5.7.2)

I have tried passing nonce manually and using transcation count as well. But I get too low for same number and too high for +1

**Comment by stoqnkpL** [comment]
@piyush-chittara thank you for sharing. If the work around with manually increasing the nonce is not working for some reason, we definitely need to investigate further. It may be a problem with a validation on the Relay side. 
If possible, can you share a bit more information, what transactions are you sending, when did they start to fail, even links to hashscan for individual transactions can be useful for our investigation. The part about the transactions _sometimes_ working is especially interesting to me.

**Comment by piyush-chittara** [comment]
@stoqnkpL I am having this problem with most of the keys I have. There was a single which was working with ether.js for me. But two days back, after a I did a contract deployment, I can see nonce error in this too.
Currently in any deployment or contract call that I do using ether.js, I see the error. Although Hbar transfer seems to be working fine via hashpack.
```

    const FacetStream = await ethers.getContractFactory('Stream');
    const facetStream = await FacetStream.deploy({ gasLimit: 500000 });
    await facetStream.deployed();
```
following is the EVM address for which this stopped working now:
0x5052672db37ad6f222b8de61665c6bb76acfefaa

**Comment by piyush-chittara** [comment]
@stoqnkpL any update on this? 
I am stuck with my contract as I can't upgrade to change the admin and it contains valuable test data replicating of our main net hedera NFT loan application

**Comment by stoqnkpL** [comment]
hey @piyush-chittara, a new version ([v0.39.1](https://github.com/hashgraph/hedera-json-rpc-relay/releases/tag/v0.39.1)) of Hashio was released on testnet (https://testnet.hashio.io/api) which removes a validation that is causing some of the nonce issues. Can you try again on testnet to manually increase the transaction nonce value by 1 and resend the transaction? 
Please let me know if this unblocks you.

**Comment by piyush-chittara** [comment]
@stoqnkpL 
Same issue. Execution returned:

`(error={"name":"ProviderError","_stack":"ProviderError: [Request ID: cf8d6ef1-e1ce-4202-9319-0dffdf6ed647] Nonce too low. Provided nonce: 2341, current nonce: 2341\n    at HttpProvider.request`

And increasing nonce returned:
`[Request ID: 081b6416-025e-481b-a774-b8bcb19887c1] Nonce too high. Provided nonce: 2342, current nonce: 2341`

**Comment by stoqnkpL** [comment]
Thank you @piyush-chittara.
We're investigating the issue and possible solutions. Some improvements to the network are coming soon that may resolve the issue and make sure more accounts are not affected.
Meanwhile, for completeness sake, can you please also try to send the same transaction with a nonce decremented by 1 instead of incremented by 1?

**Comment by Nana-EC** [comment]
@piyush-chittara please submit a transaction with nonce set to 2340 using your preferred EVM tool, this should unblock you. This lines up with Stoyans suggestion of try decrement by 1
As noted in the context above there are some edge cases where the mirror node was incorrectly given the signal to incremented the nonce.

I used the [js-sdk](https://github.com/hashgraph/hedera-sdk-js) to query your account info from the consensus node itself to get the current nonce, similar to the call in https://github.com/hashgraph/hedera-sdk-js/blob/develop/examples/get-account-info.js.
I modified the example account as follows
```js
...
        const info = await new AccountInfoQuery()
            .setAccountId('0x5052672db37ad6f222b8de61665c6bb76acfefaa')
            .setQueryPayment(new Hbar(1))
            .executeWithSigner(wallet);

        console.log(`*** info: ***\n${JSON.stringify(info)}`);
...
```

The resolution of this issue should mean you wouldn't have to utilize such workaround but i'd encourage you to check out the js-sdk for increased query and transaction support on Hedera for scenarios beyond the JSON RPC API

**Comment by piyush-chittara** [comment]
@Nana-EC WOW! You are a saviour!!
Thanks a lot, it worked!
Unfortunately the keys I am using right now are imported from metamask and I don't know how to get operator ID and keys for such accounts which are not created via hashportal.

Thanks a lot for the solution!
C.C: @stoqnkpL

**Comment by natanasow** [comment]
@piyush-chittara

If you're using ECDSA keys, the account number can't be derived by a private key, so you have to obtain it manually from the hashscan info and set it as I did in the example below. If you want to do it programmatically, an `AccountInfoQuery`, with a hashpack account as a client, can be executed before initializing your desired ECDSA client with the EVM address (what you see in your metamask) of your ECDSA account.
```typescript
  const operatorPrivateKey = PrivateKey.fromStringECDSA('105d050185ccb907fba04dd92d8de9e32c18305e097ab41dadda21489a211524');
  const operatorAccountId = new AccountId(0, 0, 1012);

  const client = await Client.forNetwork({
    '127.0.0.1:50211': '0.0.3'
  }).setOperator(operatorAccountId, operatorPrivateKey);
```

**Comment by Ivo-Yankov** [comment]
Creating some issues for better tracking of this work package.
- Address account nonce discrepancies in mono repo
- Address account nonce discrepancies in modularization
- Add fuzzy matching to NonceSuite tests

**Comment by georgi-l95** [comment]
Closing as this is done.
