### ISSUE TITLE
Migrate account nonces

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#9729]
Due to some recently discovered issues on the consensus node side, the mirror node can have outdated information in regards to account nonces. 
Migrate all ECDSA account nonces where the `nonce` is not 0.

**Comment by Nana-EC** [comment]
@stoqnkpL is this still applicable or can we close in favour of recent discussions?

**Comment by stoqnkpL** [comment]
After recent discussions with team it was decided a migration is not needed.
