### ISSUE TITLE
Rewrite CustomFractionalFeeAssessor.reclaim() to use safe math operations

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#9730]
The method `CustomFractionalFeeAssessor.reclaim()` contains the following code:
```
for (final var entry : credits.entrySet()) {
    availableToReclaim += entry.getValue();
    validateTrue(availableToReclaim >= 0, CUSTOM_FEE_OUTSIDE_NUMERIC_RANGE);
}
```

I believe this code needs to be fixed. It takes the entries of a `Map`, adds their values, and ensures the intermediate results are not negative. But the iteration can happen in any order and one can easily think of cases where one order fails [-1, 1], while the other one does not [1, -1].

I am not sure what the goal is, but we need to ensure that either the iteration always happens in the same order or the checks are independent of the order.

**Comment by Neeharika-Sompalli** [comment]
That should not be an issue here I think, since we want to know how much amount can be deducted from each credits. 
But agreed, I am using lot of HashMaps in CustomFee logic, will change them to `LinkedHashMaps`

**Comment by netopyr** [comment]
I do not really understand what this check is doing. I would understand if we check each entry by itself (`entry.getValue()`) and if we check the sum of all entries. What I do not understand is why we want to check all intermediate sums.

**Comment by netopyr** [comment]
After further consideration, I think the check is there to prevent overflows. We should rewrite the section to use Math.addExact() instead to make the intent more obvious.

**Comment by netopyr** [comment]
Closing in favor of new, clean issue: https://github.com/hashgraph/hedera-services/issues/15376
