### ISSUE TITLE
Update the description for the TokenCreate proto

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-services#974]
Link: https://github.com/hashgraph/hedera-services/blob/master/hapi-proto/src/main/proto/TokenCreate.proto

**Update the description in the file to the following:**

First, in the paragraph that starts "The supply", add an additional sentence at the start, which says:

The initialSupply is the initial supply of the smallest parts of tokens (like a tinybar, not an hbar).

Then, immediately after that paragraph, add these two paragraphs:

The supply can change over time. If the total supply at some moment is S parts of tokens, and the token is using D decimals, then S must be less than or equal to  2^63-1, which is  9,223,372,036,854,775,807.  The number of whole tokens (not parts) will S / 10^D.

If decimals is 8 or 11, then the number of whole tokens can be at most a few billions or millions, respectively. For example, it could match Bitcoin (21 million whole tokens with 8 decimals) or hbars (50 billion whole tokens with 8 decimals). It could even match Bitcoin with milli-satoshis (21 million whole tokens with 11 decimals). 

cc: @lbaird

**Comment by tinker-michaelj** [comment]
Closed by https://github.com/hashgraph/hedera-protobufs/pull/10
