### ISSUE TITLE
Flaky test: EndToEndTests.schedule()[5][51]

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#9748]
Gradle output: https://github.com/hashgraph/hedera-services/actions/runs/6787373203/job/18450035672?pr=9745
Build scan: https://scans.gradle.com/s/hx2mnddhjnre2/tests/overview?outcome=FAILED

I observed this test failure on a branch off of recent `develop`. This branch only has platform unit test changes in it.

From initial look it appears that either the scheduled transaction did not execute at all, and did not produce a visible error, or the record for the executed "scheduled" transaction was not written.  This _might_ be an incipient bug in monoservice tied to recent platform or monoservice changes and needs proper investigation.
Commit range of interest:
Last possible impacting commit is d308d9503192923a313fac479224bb5117221d3d (PR #9706)
Earliest possible impacting commit is 8815e277a36ce808c2fc07952d3b8cb787758732 (PR #9661)

**Comment by netopyr** [comment]
The test was disabled.
