### ISSUE TITLE
Fix `XTest`'s post merge of dispatch validations

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#9776]
### Description

Almost all `XTest`'s stop working with dispatch validations as implemented [here](https://github.com/hashgraph/hedera-services/pull/9308/files).

The reason could be either the `XTest` setup is incomplete; or the validations are wrong. Or a combination of those. 😁 

### Steps to reproduce

Run `XTest`s.

### Hedera network

other

### Version

`develop`

### Operating system

None

**Comment by stoyanov-st** [comment]
Solved with the changes from https://github.com/hashgraph/hedera-services/pull/9769 and https://github.com/hashgraph/hedera-services/pull/9930
