### ISSUE TITLE
Define the API for passing the consensus roster between platform and services

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#9803]
There are two new interactions required for the consensus roster:

1. When there is a new consensus roster the application wishes the platform to move to, the application must provide the platform with it. This must be provided on the handle thread.
2. When the platform has adopted the new consensus roster, it must communicate this to the application on the handle thread.

**Comment by edward-swirldslabs** [comment]
This issue doesn't seem like an actionable issue as much as setting constraints or invariants for other issues.  

item 1 is covered here:  https://github.com/hashgraph/hedera-services/issues/10415

I've added this ticket to the blue-wire sub-epic for dynamic address book.  It will represent the final step of conveying the dynamic change over of address books to the app.
