### ISSUE TITLE
Let a `HapiSuite` opt-in to record fuzzy-matching in CI 

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#9812]
### Problem

Once a `HapiSuite` is known to fuzzy-match the committed record-snapshot, I want to enable that suite to keep validating the fuzzy-match in CI.

### Solution

Add a `HapiSuite` method
```
public boolean expectsPassingFuzzyMatch() {
    return false;
}
```
that we can override to `true` in suites we want to fuzzy-match in CI.

**Comment by netopyr** [comment]
@tinker-michaelj Is this still needed or is the property `@HapiSuite.fuzzyMatch` sufficient?

**Comment by netopyr** [comment]
The property `fuzzyMatch` in `@HapiSuite` is sufficient.
