### ISSUE TITLE
Re-enable 15-node weekly perf regression for Crypto, HCS, HTS services

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#984]
**Summary**
The 15-node perf regression tests need to be re-enabled for Crypto and HCS services. It should also set up for HTS services.

**Possible resolution**
1. Use the new in-house generated 1M accounts + 1M topics state file for the performance testing;
2. Try to run as long (3+ hrs) as possible;

**Comment by Neeharika-Sompalli** [comment]
Before this is merged , PR for using 1M accounts state should be merged. https://github.com/swirlds/swirlds-platform-regression/pull/792
