### ISSUE TITLE
Follow up: Fix ContractUpdateSuite tests

### ISSUE THREAD

**Issue by vtronkov** [hashgraph/hedera-services#9853]
Two tests are still failing `fridayThe13thSpec` and `canMakeContractImmutableWithEmptyKeyList`.

Both tests are failing due to the _MODIFYING_IMMUTABLE_CONTRACT_ check. The implementation in mono is in `StateChildrenSigMetadataLookup.aliasableContractSigningMetaFor`. From there we call `lookupContractByNumber` and we return **IMMUTABLE_CONTRACT**.
The `aliasableContractSigningMetaFor` is called from `SigRequirements.contractUpdate` and when it returns **IMMUTABLE_CONTRACT** we call `contractFailure`. In it, we throw the `MODIFYING_IMMUTABLE_CONTRACT`.

The problem with this implementation is that it uses the `aliasManager`(that doesn't exist in mod) and other concepts that I'm not sure exactly how they relate to the mod(like `EntityNum`, `LinkedRefs`, `JKey`, `JContractIDKey`)

For this story, we need to implement the mono logic in mod. Hopefully, that will resolve the issues and we will be able to enable the failing tests

Note: all other tests are fixed in https://github.com/hashgraph/hedera-services/pull/9847

**Comment by MiroslavGatsanoga** [comment]
@tinker-michaelj I see that you fix those 2 tests in https://github.com/hashgraph/hedera-services/pull/10312 and you have separate issues for those(https://github.com/hashgraph/hedera-services/issues/10331 and https://github.com/hashgraph/hedera-services/issues/10333), so closing this one as duplicate.
