### ISSUE TITLE
AllProtectedFilesUpdate-Reconnect-1-12m  fails on release/0.11

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#989]
`AllProtectedFilesUpdate-Reconnect-1-12m` test passes on `master` but fails on `release/0.11` branch. 
Failures are in `ReconnectStreamValidator`, `HAPIClientValidator`, `ReconnectValidator`
Investigate the reason for failure and fix them.
Link for failed test : 
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1611130722012400

**Comment by qnswirlds** [comment]
This is instability, not really failing. Rerun would usually pass.

**Comment by Neeharika-Sompalli** [comment]
@qnswirlds  Understood. I re-ran it yesterday in my local. But it failed with the same error. So, I thought its better to have an issue for this.

**Comment by Neeharika-Sompalli** [comment]
As @qnswirlds mentioned , it looks like instability failure. When ran twice it worked.https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611594235032500
