### ISSUE TITLE
Investigate the AWS security group not existing issue

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#99]
In CI build  https://app.circleci.com/jobs/github/swirlds/services-hedera/25411, the build failed in terraform create workspace step with the following error message:

* module.hgc-spot-nodes.aws_spot_instance_request.hgc_nodes_block[2]: 1 error(s) occurred:

* aws_spot_instance_request.hgc_nodes_block.2: Error requesting spot instances: InvalidGroup.NotFound: The security group 'sg-03fe177e7ae336fb2' does not exist in VPC 'vpc-098429d87855e6b4b'
        status code: 400, request id: 2e678435-cdfb-44ee-8712-3383a446225c

Need to find out why the security group couldn't be created.

Also find out why the build didn't stop at this step since it already failed.

**Comment by anighanta** [comment]
Not relevant anymore
