### ISSUE TITLE
Record file hash chain broke in performance net

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-services#991]
**Summary of the defect**
When running mirror node with v5 reocrd file support in performance net environment, the hash chain is found broken between record file `2021-01-14T18_37_17.862730001Z.rcd` and `2021-01-14T18_47_25.239512004Z.rcd`:

- `2021-01-14T18_37_17.862730001Z.rcd` has end object running hash `ccd60bfe3eeb529f108ab729f9d7de6ebf82dd0130809795580d30129cc50cec2b4931d26af83c39000709bd729dac1c`
-  `2021-01-14T18_47_25.239512004Z.rcd` has start running object hash `b1211955a405206f785f8f1447f1b4ee3605ea710e90160a1a7ca236ced0a3f38052c7ae1754741e85d0ab676167f14f`
- all nodes have the same record files 

**How to reproduce (if possible)**

**Service logs (if applicable)**
```
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**

[record_files.zip](https://github.com/hashgraph/hedera-services/files/5845801/record_files.zip)

**Comment by jsindy** [comment]
Issue was related to doing an upgrade on the performance network without initiating a freeze.
