### ISSUE TITLE
Reconnect: ServicesState initialization after reconnect won't scale

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#9967]
### Problem

After a successful reconnect, the platform loads and initializes the obtained state (`SwirldsPlatform.loadReconnectState(SignedState)`).
`ServicesState.init()` calls `deserializedInit()` -> `internalInit()` -> `ServicesInitFlow.runWith()` -> `StoreInitializationFlow.run()`.
The last one makes two calls that invoke `AccountStorageAdapter.forEach()`, which loads every account from disk:
```
        backingAccounts.rebuildFromSources();
        aliasManager.rebuildAliasesMap(...);
```
With larger and larger number of accounts on disk, those steps will take longer and longer to the point of making reconnecting broken.

### Solution

This issue needs to be addressed/revisited by every planned major rework.
Until then, it should remain on the radar screen as a potential performance issue.

**Comment by netopyr** [comment]
Mono code
